with source as (

    select * from {{ source('gdvii_dbo', 'pop30300') }}

),

renamed as (

    select
        workflow_status,
        disavamt,
        ppstaxrt,
        vendname,
        vnddocnm,
        bchsourc,
        taxschid,
        pop_hdr_errors_4,
        bachnumb,
        disavtkn,
        withhamt,
        dscpctam,
        creatddt,
        currnidx,
        originatingprepaymentamt,
        frtamnt,
        ordatkn,
        rcptnote_7,
        orsubtot,
        txrgnnum,
        shipmthd,
        rcptnote_1,
        revaljrnentry,
        total_landed_cost_amount,
        backoutmisctaxamt,
        ormsctax,
        taxinvreqd,
        obtaxamt,
        rcptnote_3,
        poptype,
        ten99amnt,
        rcptnote_6,
        dscdlram,
        refrence,
        posteddt,
        pymtrmid,
        ratetpid,
        frttxamt,
        rcptnote_5,
        trdpctpr,
        xchgrate,
        rcptnote_4,
        user2ent,
        subtotal,
        discdate,
        purchase_freight_taxable,
        distknam,
        time1,
        aplywith,
        miscamnt,
        glpostdt,
        voidstts,
        ordavamt,
        ten99boxnumber,
        ptdusrid,
        purchase_misc_taxable,
        ortdisam,
        backoutfreighttaxamt,
        taxamnt,
        rcptnote_2,
        replacegoods,
        modifdt,
        origbackoutfreighttaxamt,
        rcptnote_8,
        simplifd,
        bcktxamt,
        orfrtamt,
        msctxamt,
        ratecalc,
        prepaymentamount,
        ectrx,
        frtschid,
        orddlrat,
        ordistkn,
        taxinvrecvd,
        pophdr1,
        poplnerr,
        ormiscamt,
        mctrxstt,
        orfrttax,
        ten99type,
        revaltrxsource,
        trxsorce,
        denxrate,
        invoicereceiptdate,
        actlship,
        vchrnmbr,
        trdisamt,
        curncyid,
        ortaxamt,
        cbvat,
        dex_row_id,
        exchdate,
        or1099am,
        bsivcttl,
        exgtblid,
        receiptdate,
        origbackoutmisctaxamt,
        duedate,
        mscschid,
        vadcdtro,
        invoiceexpected,
        pophdr2,
        tax_date,
        _fivetran_deleted,
        _fivetran_synced,
        upper(trim(poprctnm)) as poprctnm,
        upper(trim(vendorid)) as vendorid

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
