with

source as (

    select * from {{ source('gdvii_dbo', 'pm10000') }}

),

renamed as (

    select
        cdocnmbr,
        vendorid,
        txengcld,
        campmtnm,
        bktfrtam,
        invoicereceiptdate,
        taxschid,
        un1099am,
        mscchamt,
        taxinvreqd,
        duedate,
        posted,
        gstdsamt,
        bktpuram,
        ictrx,
        chamcbid,
        aplywith,
        docamnt,
        simplifd,
        curncyid,
        pstgdate,
        vaddcdpr,
        pgramsbj,
        modifdt,
        cntrltyp,
        crcrdamt,
        apdstkam,
        ten99boxnumber,
        bachnumb,
        backouttradedisc,
        pmdstmsg,
        trdisamt,
        camtdate,
        posteddt,
        retnagam,
        distknam,
        curtrxam,
        cheknmbr,
        dex_row_id,
        electronic,
        cashamnt,
        appldamt,
        prchdate,
        cbvat,
        wrofamnt,
        docdate,
        corrctn,
        prctdisc,
        prchamnt,
        pchschid,
        bnkrcamt,
        vchnumwk,
        lngdesc,
        ccampynm,
        pmwrkmsg,
        crcarddt,
        pordnmbr,
        mdfusrid,
        camcbkid,
        dex_row_ts,
        docnumbr,
        ten99amnt,
        disamtav,
        ppstaxrt,
        shipmthd,
        chekbkid,
        workflow_status,
        doctype,
        docprinted,
        tax_date,
        taxamnt,
        vadcdtro,
        bktmscam,
        cardname,
        sourcdoc,
        icdists,
        bchsourc,
        trxdscrn,
        printed,
        pmicmsgs,
        pmwrkms2,
        vchrncor,
        discdate,
        pymtrmid,
        mscschid,
        ppsamded,
        frtschid,
        vchrnmbr,
        chekdate,
        campynbr,
        pstgstus,
        ptdusrid,
        corrnxst,
        chekamnt,
        ectrx,
        ten99type,
        noteindx,
        frtamnt,
        dscdlram,
        chrgamnt,
        ccrctnum,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
