with source as (

    select * from {{ source('culc1_dbo', 'pm20000') }}

),

renamed as (

    select
        pchschid,
        docdate,
        pyenttyp,
        posteddt,
        ttlpymts,
        vndchknm,
        un1099am,
        taxinvreqd,
        vadcdtro,
        workflow_status,
        prchamnt,
        duedate,
        trdisamt,
        dex_row_id,
        ten99type,
        curtrxam,
        modifdt,
        bnkrcamt,
        distknam,
        tax_date,
        docnumbr,
        trxsorce,
        ppsamded,
        bktpuram,
        ictrx,
        mscchamt,
        shipmthd,
        cntrltyp,
        bktmscam,
        discdate,
        pymtrmid,
        pstgdate,
        trxdscrn,
        vendorid,
        prctdisc,
        simplifd,
        hold,
        ten99amnt,
        docprinted,
        disavtkn,
        discamnt,
        ptdusrid,
        prchdate,
        doctype,
        mscschid,
        invoicereceiptdate,
        bachnumb,
        frtschid,
        dscdlram,
        frtamnt,
        cardname,
        vchrnmbr,
        dex_row_ts,
        lngdesc,
        pgramsbj,
        aplywith,
        corrctn,
        retnagam,
        voided,
        disamtav,
        ten99boxnumber,
        noteindx,
        backouttradedisc,
        ppstaxrt,
        ponumber,
        dinvpdof,
        taxamnt,
        bchsourc,
        wrofamnt,
        curncyid,
        cbvat,
        gstdsamt,
        mdfusrid,
        pordnmbr,
        ectrx,
        taxschid,
        chekbkid,
        bktfrtam,
        electronic,
        docamnt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
