with source as (

    select * from {{ source('cfami_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        pmcshidx,
        vendstts,
        ratetpid,
        pmfrtidx,
        txidnmbr,
        taxschid,
        withholdingtype,
        prspayee,
        pmmschix,
        purpvidx,
        pymtrmid,
        duegrper,
        pmdavidx,
        mxiafvnd,
        post_results_to,
        disgrper,
        pmapindx,
        vaddcdpr,
        pmrtngix,
        modifdt,
        kgldsths,
        trddisct,
        dex_row_ts,
        pmwrtidx,
        workflow_priority,
        zipcode,
        vndclsid,
        venddba,
        vadcd1099,
        revalue_vendor,
        shipmthd,
        pmdtkidx,
        phnumbr2,
        address3,
        pmtdscix,
        vadcdtro,
        minpydlr,
        ppstaxrt,
        txrgnnum,
        cbvat,
        declid,
        chekbkid,
        ten99type,
        creatddt,
        rtobutkn,
        phone3,
        vndcntct,
        kptrxhst,
        hold,
        crtcomdt,
        dxvarnum,
        acpuridx,
        maxindlr,
        phnumbr1,
        ptcshacf,
        vendname,
        govindid,
        address2,
        userdef2,
        onepaypervendinv,
        comment2,
        workflow_status,
        pymntpri,
        credtlmt,
        taxinvrecvd,
        withholdingentitytype,
        noteindx,
        kperhist,
        freeonboard,
        taxfilenummode,
        dex_row_id,
        ten99boxnumber,
        faxnumbr,
        crtexpdt,
        vendshnm,
        userdef1,
        vndchknm,
        country,
        minpytyp,
        city,
        upszone,
        userlang,
        docfmtid,
        minpypct,
        address1,
        brthdate,
        workflow_approval_status,
        kpcalhst,
        comment1,
        pmprchix,
        state,
        sbppsded,
        parvenid,
        curncyid,
        crlmtdlr,
        withholdingformtype,
        vadcdpad,
        ccode,
        pmtaxidx,
        xpdtoblg,
        vadcdsfr,
        pmfinidx,
        writeoff,
        acnmvndr,
        mxwofamt,
        minorder,
        laborpmttype,
        govcrpid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
