with source as (

    select * from {{ source('cfami_dbo', 'pop30300') }}

),

renamed as (

    select
        pophdr2,
        posteddt,
        ordistkn,
        denxrate,
        bcktxamt,
        taxschid,
        rcptnote_5,
        backoutfreighttaxamt,
        vadcdtro,
        ppstaxrt,
        workflow_status,
        ten99amnt,
        origbackoutmisctaxamt,
        poptype,
        ormiscamt,
        ten99type,
        receiptdate,
        bchsourc,
        withhamt,
        msctxamt,
        miscamnt,
        rcptnote_8,
        orddlrat,
        currnidx,
        pymtrmid,
        purchase_misc_taxable,
        user2ent,
        discdate,
        frtschid,
        obtaxamt,
        rcptnote_1,
        taxamnt,
        orsubtot,
        pophdr1,
        actlship,
        invoiceexpected,
        trdpctpr,
        shipmthd,
        rcptnote_4,
        dex_row_id,
        exgtblid,
        orfrtamt,
        ratecalc,
        duedate,
        refrence,
        disavamt,
        aplywith,
        orfrttax,
        rcptnote_7,
        mscschid,
        dscpctam,
        mctrxstt,
        voidstts,
        simplifd,
        cbvat,
        dscdlram,
        time1,
        poplnerr,
        purchase_freight_taxable,
        ten99boxnumber,
        xchgrate,
        distknam,
        exchdate,
        ordavamt,
        revaltrxsource,
        total_landed_cost_amount,
        tax_date,
        ormsctax,
        creatddt,
        poprctnm,
        bsivcttl,
        disavtkn,
        ortdisam,
        frtamnt,
        rcptnote_3,
        subtotal,
        frttxamt,
        vendorid,
        modifdt,
        txrgnnum,
        or1099am,
        invoicereceiptdate,
        rcptnote_6,
        replacegoods,
        vnddocnm,
        ptdusrid,
        origbackoutfreighttaxamt,
        pop_hdr_errors_4,
        ordatkn,
        backoutmisctaxamt,
        ortaxamt,
        curncyid,
        vendname,
        originatingprepaymentamt,
        taxinvrecvd,
        trdisamt,
        ratetpid,
        vchrnmbr,
        taxinvreqd,
        revaljrnentry,
        bachnumb,
        prepaymentamount,
        trxsorce,
        glpostdt,
        ectrx,
        rcptnote_2,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
