with source as (

    select * from {{ source('cfami_dbo', 'rm00101') }}

),

renamed as (

    select
        disgrper,
        staddrcd,
        comment2,
        kptrxhst,
        govcrpid,
        rmslsacc,
        fax,
        govindid,
        cprcstnm,
        custnmbr,
        rmsoracc,
        defcacty,
        ratetpid,
        finchdlr,
        declid,
        userlang,
        inactive,
        custclas,
        crcardid,
        address3,
        fnchpcnt,
        crcrdnum,
        taxexmt1,
        state,
        phone2,
        stmtcycl,
        kpcalhst,
        rmwracc,
        shrtname,
        fnchatyp,
        comment1,
        orderfulfilldefault,
        custpriority,
        crlmttyp,
        bankname,
        pymtrmid,
        curncyid,
        integrationid,
        rmovrpymtwrtoffacctidx,
        docfmtid,
        custname,
        ccode,
        rmavacc,
        taxschid,
        userdef2,
        stmtname,
        cntcprsn,
        prstadcd,
        finchid,
        kperhist,
        hold,
        cbvat,
        custdisc,
        address2,
        shipmthd,
        crlmtpam,
        rmcshacc,
        phone1,
        mxwrofam,
        balnctyp,
        bnkbrnch,
        prclevel,
        dex_row_ts,
        integrationsource,
        minpydlr,
        country,
        rmcosacc,
        upszone,
        creatddt,
        includeindp,
        frstindt,
        mxwoftyp,
        city,
        shipcomplete,
        crlmtamt,
        rmfcgacc,
        post_results_to,
        salsterr,
        chekbkid,
        rmaracc,
        txrgnnum,
        userdef1,
        zip,
        rmivacc,
        kpdsthst,
        adrscode,
        rmtakacc,
        dex_row_id,
        minpypct,
        revalue_customer,
        address1,
        send_email_statements,
        modifdt,
        slprsnid,
        duegrper,
        ccrdxpdt,
        minpytyp,
        taxexmt2,
        crlmtper,
        phone3,
        gpsfointegrationid,
        prbtadcd,
        noteindx,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
