with source as (

    select * from {{ source('cfami_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        frtschid,
        voided,
        electronic,
        bktmscam,
        trxdscrn,
        docamnt,
        trxsorce,
        modifdt,
        ten99amnt,
        disamtav,
        tax_date,
        ponumber,
        un1099am,
        ppstaxrt,
        duedate,
        prctdisc,
        workflow_status,
        mscschid,
        noteindx,
        taxinvreqd,
        bktfrtam,
        wrofamnt,
        hold,
        distknam,
        ttlpymts,
        pordnmbr,
        discdate,
        ppsamded,
        ectrx,
        cntrltyp,
        vadcdtro,
        dex_row_id,
        ten99boxnumber,
        corrctn,
        vendorid,
        ictrx,
        taxamnt,
        dex_row_ts,
        frtamnt,
        cbvat,
        aplywith,
        backouttradedisc,
        bchsourc,
        pgramsbj,
        curncyid,
        voidpdate,
        pstgdate,
        pchschid,
        ten99type,
        simplifd,
        invoicereceiptdate,
        discamnt,
        pyenttyp,
        docdate,
        lngdesc,
        docnumbr,
        dinvpdof,
        trdisamt,
        mdfusrid,
        prchdate,
        taxschid,
        bachnumb,
        cardname,
        chekbkid,
        retnagam,
        shipmthd,
        posteddt,
        curtrxam,
        ptdusrid,
        disavtkn,
        docprinted,
        mscchamt,
        dscdlram,
        vndchknm,
        bktpuram,
        pymtrmid,
        prchamnt,
        gstdsamt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
