with source as (

    select * from {{ source('cfami_dbo', 'pm20000') }}

),

renamed as (

    select
        prchdate,
        taxschid,
        ttlpymts,
        ten99boxnumber,
        discdate,
        curtrxam,
        ppsamded,
        ectrx,
        vadcdtro,
        vchrnmbr,
        shipmthd,
        corrctn,
        dex_row_id,
        ptdusrid,
        disavtkn,
        dscdlram,
        bktpuram,
        ictrx,
        dex_row_ts,
        prchamnt,
        gstdsamt,
        frtamnt,
        aplywith,
        frtschid,
        backouttradedisc,
        simplifd,
        pchschid,
        docamnt,
        voided,
        bktmscam,
        trxdscrn,
        pstgdate,
        trxsorce,
        modifdt,
        ten99type,
        invoicereceiptdate,
        ten99amnt,
        discamnt,
        tax_date,
        bnkrcamt,
        pyenttyp,
        docdate,
        lngdesc,
        docnumbr,
        trdisamt,
        chekbkid,
        cardname,
        bachnumb,
        doctype,
        duedate,
        retnagam,
        posteddt,
        docprinted,
        mscchamt,
        vndchknm,
        mscschid,
        hold,
        taxinvreqd,
        wrofamnt,
        bktfrtam,
        pymtrmid,
        distknam,
        pordnmbr,
        electronic,
        cntrltyp,
        disamtav,
        vendorid,
        ponumber,
        taxamnt,
        ppstaxrt,
        cbvat,
        un1099am,
        bchsourc,
        pgramsbj,
        curncyid,
        prctdisc,
        workflow_status,
        noteindx,
        dinvpdof,
        mdfusrid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
