with source as (

    select * from {{ source('cfami_dbo', 'rm20101') }}

),

renamed as (

    select
        cspornbr,
        simplifd,
        pstusrid,
        trdisamt,
        voidstts,
        curtrxam,
        agngbukt,
        pymtrmid,
        bktmscam,
        bachnumb,
        cheknmbr,
        slsamnt,
        cbkidcsh,
        noteindx,
        tax_date,
        saledate,
        dscdlram,
        electronic,
        taxschid,
        aplywith,
        costamnt,
        dscpctam,
        shipmthd,
        discdate,
        cashamnt,
        lstedtdt,
        taxamnt,
        frtamnt,
        duedate,
        voiddate,
        dex_row_ts,
        lstusred,
        curncyid,
        trxdscrn,
        bktfrtam,
        docnumbr,
        cprcstnm,
        miscamnt,
        slprsnid,
        glpostdt,
        eftflag,
        directdebit,
        corrctn,
        disavamt,
        dex_row_id,
        ortrxamt,
        cbkidchk,
        wrofamnt,
        trxsorce,
        docdate,
        ppsamded,
        adrscode,
        postdate,
        bchsourc,
        discrtnd,
        backouttradedisc,
        gstdsamt,
        cshrctyp,
        cbkidcrd,
        comdlram,
        rmdtypal,
        disavtkn,
        factoring,
        mscschid,
        dinvpdof,
        bktslsam,
        distknam,
        ectrx,
        slstercd,
        frtschid,
        delete1,
        slschdid,
        custnmbr,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
