with source as (

    select * from {{ source('cpqln_dbo', 'pm10000') }}

),

renamed as (

    select
        bachnumb,
        bchsourc,
        vchnumwk,
        campmtnm,
        bnkrcamt,
        vendorid,
        invoicereceiptdate,
        taxschid,
        posted,
        txengcld,
        simplifd,
        cdocnmbr,
        retnagam,
        duedate,
        pgramsbj,
        taxinvreqd,
        trdisamt,
        backouttradedisc,
        chamcbid,
        corrnxst,
        electronic,
        ten99boxnumber,
        cntrltyp,
        docamnt,
        chekdate,
        aplywith,
        docdate,
        campynbr,
        ictrx,
        prchdate,
        cbvat,
        icdists,
        corrctn,
        pchschid,
        un1099am,
        vchrncor,
        pstgstus,
        pmwrkmsg,
        mscchamt,
        workflow_status,
        crcrdamt,
        gstdsamt,
        mscschid,
        pymtrmid,
        chekbkid,
        ten99type,
        docprinted,
        prchamnt,
        wrofamnt,
        modifdt,
        vadcdtro,
        appldamt,
        cashamnt,
        crcarddt,
        pordnmbr,
        ccampynm,
        mdfusrid,
        pmwrkms2,
        curtrxam,
        docnumbr,
        pmdstmsg,
        chekamnt,
        ppsamded,
        shipmthd,
        lngdesc,
        dex_row_ts,
        disamtav,
        vchrnmbr,
        taxamnt,
        ptdusrid,
        ectrx,
        doctype,
        dex_row_id,
        apdstkam,
        ppstaxrt,
        distknam,
        camcbkid,
        bktmscam,
        pmicmsgs,
        trxdscrn,
        ccrctnum,
        cardname,
        sourcdoc,
        discdate,
        camtdate,
        printed,
        bktpuram,
        posteddt,
        curncyid,
        cheknmbr,
        frtschid,
        vaddcdpr,
        dscdlram,
        tax_date,
        frtamnt,
        pstgdate,
        ten99amnt,
        chrgamnt,
        noteindx,
        bktfrtam,
        prctdisc,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
