with source as (

    select * from {{ source('cpqln_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        custname,
        zip,
        inactive,
        taxexmt1,
        balnctyp,
        crlmtper,
        integrationsource,
        taxschid,
        country,
        fax,
        defcacty,
        kpcalhst,
        city,
        mxwrofam,
        kptrxhst,
        finchid,
        cbvat,
        rmcshacc,
        declid,
        bankname,
        govcrpid,
        phone1,
        orderfulfilldefault,
        post_results_to,
        cntcprsn,
        address1,
        prstadcd,
        stmtcycl,
        crlmtpam,
        frstindt,
        dex_row_id,
        phone3,
        crcardid,
        includeindp,
        custpriority,
        staddrcd,
        custclas,
        mxwoftyp,
        taxexmt2,
        revalue_customer,
        shipmthd,
        ratetpid,
        rmovrpymtwrtoffacctidx,
        crcrdnum,
        send_email_statements,
        minpypct,
        minpytyp,
        gpsfointegrationid,
        upszone,
        chekbkid,
        finchdlr,
        duegrper,
        noteindx,
        crlmtamt,
        prclevel,
        ccode,
        hold,
        phone2,
        disgrper,
        state,
        bnkbrnch,
        kpdsthst,
        crlmttyp,
        creatddt,
        rmivacc,
        modifdt,
        ccrdxpdt,
        integrationid,
        shipcomplete,
        fnchpcnt,
        fnchatyp,
        comment2,
        salsterr,
        minpydlr,
        cprcstnm,
        kperhist,
        comment1,
        docfmtid,
        userdef1,
        userlang,
        rmcosacc,
        rmfcgacc,
        slprsnid,
        address2,
        rmsoracc,
        govindid,
        pymtrmid,
        rmwracc,
        rmtakacc,
        txrgnnum,
        stmtname,
        rmslsacc,
        address3,
        custdisc,
        rmavacc,
        prbtadcd,
        adrscode,
        shrtname,
        rmaracc,
        userdef2,
        dex_row_ts,
        curncyid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
