with source as (

    select * from {{ source('cpqln_dbo', 'pop30110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        reqdate,
        cmpnynam,
        orextcst,
        ortaxamt,
        prmshpdte,
        zipcode,
        decplqty,
        source_document_line_num,
        flags,
        costcatid,
        unitcost,
        polneary_1,
        odecplcu,
        itemdesc,
        itemnmbr,
        lstrcptdt,
        city,
        addrsource,
        source_document_number,
        product_indicator,
        taxamnt,
        obtaxamt,
        vendorid,
        locncode,
        freeonboard,
        country,
        jobnumbr,
        polneary_6,
        origprmdate,
        qtyorder,
        doctype,
        currnidx,
        dex_row_ts,
        contact,
        phone3,
        qtycance,
        polneary_7,
        purchase_site_tax_schedu,
        purchase_iv_item_taxable,
        landed_cost_group_id,
        costcode,
        noninven,
        phone2,
        address3,
        projnum,
        potype,
        oruntcst,
        shipmthd,
        polnesta,
        phone1,
        reqstdby,
        bcktxamt,
        lineorigin,
        purchase_item_tax_schedu,
        dex_row_id,
        released_date,
        ccode,
        fstrcptdt,
        extdcost,
        address2,
        itmtrkop,
        vctnmthd,
        vnditnum,
        polneary_2,
        costtype,
        polneary_5,
        polneary_8,
        prmdate,
        adrscode,
        umqtyinb,
        release,
        fax,
        polneary_3,
        releasebydate,
        purchsitetxschsrc,
        polneary_9,
        address1,
        print_phone_numbergb,
        invindx,
        decplcur,
        linenumber,
        commntid,
        polneary_4,
        vnditdsc,
        state,
        uofm,
        bsivcttl,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
