with source as (

    select * from {{ source('cpqln_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        backouttradedisc,
        duedate,
        bktmscam,
        bchsourc,
        modifdt,
        docnumbr,
        ten99type,
        corrctn,
        gstdsamt,
        taxamnt,
        shipmthd,
        frtamnt,
        taxschid,
        mscschid,
        cbvat,
        ictrx,
        pordnmbr,
        noteindx,
        voided,
        chekbkid,
        docprinted,
        bktfrtam,
        pgramsbj,
        workflow_status,
        cardname,
        vndchknm,
        dscdlram,
        curtrxam,
        docdate,
        aplywith,
        docamnt,
        ttlpymts,
        mdfusrid,
        dinvpdof,
        posteddt,
        curncyid,
        hold,
        simplifd,
        distknam,
        cntrltyp,
        trxsorce,
        ten99boxnumber,
        ponumber,
        ptdusrid,
        taxinvreqd,
        wrofamnt,
        trdisamt,
        bktpuram,
        dex_row_ts,
        dex_row_id,
        discdate,
        un1099am,
        trxdscrn,
        vendorid,
        bnkrcamt,
        ppsamded,
        frtschid,
        tax_date,
        ppstaxrt,
        pstgdate,
        pchschid,
        retnagam,
        prchamnt,
        lngdesc,
        vadcdtro,
        disamtav,
        bachnumb,
        pyenttyp,
        pymtrmid,
        prchdate,
        prctdisc,
        mscchamt,
        electronic,
        ectrx,
        discamnt,
        ten99amnt,
        invoicereceiptdate,
        disavtkn,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
