with source as (

    select * from {{ source('cpqln_dbo', 'pop10110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        source_document_number,
        curncyid,
        reqstdby,
        vnditdsc,
        source_document_line_num,
        bcktxamt,
        qty_canceled_orig,
        po_line_status_orig,
        projnum,
        itmtrkop,
        qtycmtbase,
        capital_item,
        vnditnum,
        address1,
        polneary_3,
        polneary_9,
        dex_row_ts,
        costtype,
        commntid,
        linenumber,
        polneary_4,
        purchase_item_tax_schedu,
        locncode,
        release,
        plnndspplid,
        reqdate,
        umqtyinb,
        cmpnynam,
        uofm,
        vendorid,
        taxamnt,
        decplqty,
        unitcost,
        qtyuncmtbase,
        costcode,
        address3,
        dex_row_id,
        obtaxamt,
        shipmthd,
        lstrcptdt,
        adrscode,
        polneary_6,
        itemnmbr,
        qtycance,
        extdcost,
        orextcst,
        product_indicator,
        polneary_7,
        freeonboard,
        denxrate,
        xchgrate,
        ccode,
        jobnumbr,
        phone1,
        purchsitetxschsrc,
        address2,
        prmdate,
        lineorigin,
        vctnmthd,
        releasebydate,
        fax,
        fstrcptdt,
        polneary_2,
        polneary_5,
        polneary_8,
        decplcur,
        backouttradedisctax,
        origprmdate,
        invindx,
        polnesta,
        landed_cost_group_id,
        potype,
        purchase_iv_item_taxable,
        oruntcst,
        purchase_site_tax_schedu,
        change_order_flag,
        itemdesc,
        prmshpdte,
        currnidx,
        ratecalc,
        odecplcu,
        released_date,
        print_phone_numbergb,
        city,
        zipcode,
        qtyorder,
        polneary_1,
        contact,
        state,
        ortaxamt,
        noninven,
        origbackouttradedisctax,
        qtycommittedinbaseorig,
        country,
        phone2,
        doctype,
        bsivcttl,
        phone3,
        addrsource,
        opostsub,
        flags,
        costcatid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
