with source as (

    select * from {{ source('cpqln_dbo', 'pop30300') }}

),

renamed as (

    select
        poprctnm,
        obtaxamt,
        tax_date,
        orfrttax,
        trdpctpr,
        shipmthd,
        orfrtamt,
        curncyid,
        total_landed_cost_amount,
        backoutmisctaxamt,
        ormiscamt,
        rcptnote_3,
        modifdt,
        rcptnote_6,
        dscdlram,
        revaljrnentry,
        origbackoutmisctaxamt,
        taxinvrecvd,
        invoicereceiptdate,
        frttxamt,
        pophdr1,
        taxschid,
        taxamnt,
        revaltrxsource,
        trxsorce,
        ten99boxnumber,
        vnddocnm,
        miscamnt,
        bchsourc,
        pophdr2,
        ratetpid,
        denxrate,
        bachnumb,
        xchgrate,
        receiptdate,
        exgtblid,
        ordatkn,
        time1,
        posteddt,
        trdisamt,
        voidstts,
        mscschid,
        taxinvreqd,
        vadcdtro,
        pop_hdr_errors_4,
        dex_row_id,
        rcptnote_7,
        glpostdt,
        aplywith,
        orddlrat,
        originatingprepaymentamt,
        ratecalc,
        ten99type,
        rcptnote_8,
        poplnerr,
        ordistkn,
        mctrxstt,
        orsubtot,
        ectrx,
        vchrnmbr,
        simplifd,
        vendorid,
        replacegoods,
        actlship,
        ortaxamt,
        frtamnt,
        ten99amnt,
        frtschid,
        or1099am,
        dscpctam,
        origbackoutfreighttaxamt,
        rcptnote_4,
        discdate,
        subtotal,
        withhamt,
        purchase_misc_taxable,
        rcptnote_5,
        duedate,
        exchdate,
        distknam,
        poptype,
        disavamt,
        bsivcttl,
        cbvat,
        purchase_freight_taxable,
        workflow_status,
        creatddt,
        bcktxamt,
        user2ent,
        ortdisam,
        currnidx,
        ordavamt,
        ppstaxrt,
        refrence,
        rcptnote_1,
        vendname,
        backoutfreighttaxamt,
        prepaymentamount,
        disavtkn,
        txrgnnum,
        rcptnote_2,
        invoiceexpected,
        ptdusrid,
        ormsctax,
        pymtrmid,
        msctxamt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
