with source as (

    select * from {{ source('cpqln_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        prchamnt,
        lngdesc,
        cardname,
        tax_date,
        invoicereceiptdate,
        ttlpymts,
        ppstaxrt,
        bktfrtam,
        frtschid,
        trxdscrn,
        curtrxam,
        trdisamt,
        ten99boxnumber,
        ponumber,
        bachnumb,
        un1099am,
        pgramsbj,
        aplywith,
        wrofamnt,
        curncyid,
        corrctn,
        dinvpdof,
        ppsamded,
        backouttradedisc,
        voided,
        bchsourc,
        hold,
        vndchknm,
        ictrx,
        workflow_status,
        docprinted,
        docdate,
        mdfusrid,
        gstdsamt,
        taxamnt,
        taxschid,
        pyenttyp,
        posteddt,
        vadcdtro,
        dscdlram,
        pordnmbr,
        prchdate,
        pymtrmid,
        docamnt,
        pchschid,
        chekbkid,
        pstgdate,
        disamtav,
        ten99type,
        docnumbr,
        frtamnt,
        simplifd,
        bktmscam,
        bktpuram,
        dex_row_id,
        ptdusrid,
        mscchamt,
        taxinvreqd,
        cntrltyp,
        duedate,
        modifdt,
        vendorid,
        distknam,
        discamnt,
        ten99amnt,
        disavtkn,
        voidpdate,
        electronic,
        ectrx,
        dex_row_ts,
        prctdisc,
        mscschid,
        noteindx,
        retnagam,
        trxsorce,
        cbvat,
        shipmthd,
        discdate,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
