with source as (

    select * from {{ source('cpqln_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        cspornbr,
        distknam,
        backouttradedisc,
        dex_row_id,
        bktmscam,
        voidstts,
        curtrxam,
        gstdsamt,
        dex_row_ts,
        slschdid,
        glpostdt,
        slsamnt,
        comdlram,
        taxschid,
        cbkidcrd,
        ppsamded,
        docdate,
        aplywith,
        postdate,
        cashamnt,
        bktslsam,
        frtschid,
        costamnt,
        dscdlram,
        tax_date,
        duedate,
        trdisamt,
        pstusrid,
        delete1,
        cbkidcsh,
        electronic,
        ectrx,
        wrofamnt,
        agngbukt,
        cshrctyp,
        dscpctam,
        voiddate,
        bchsourc,
        dinvpdof,
        mscschid,
        curncyid,
        slprsnid,
        pymtrmid,
        simplifd,
        noteindx,
        factoring,
        bachnumb,
        shipmthd,
        lstusred,
        disavtkn,
        disavamt,
        discrtnd,
        trxdscrn,
        trxsorce,
        discdate,
        lstedtdt,
        frtamnt,
        adrscode,
        eftflag,
        bktfrtam,
        corrctn,
        saledate,
        cbkidchk,
        slstercd,
        ortrxamt,
        directdebit,
        cprcstnm,
        taxamnt,
        cheknmbr,
        miscamnt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
