with source as (

    select * from {{ source('ci_dbo', 'pop30300') }}

),

renamed as (

    select
        shipmthd,
        receiptdate,
        subtotal,
        rcptnote_3,
        frtamnt,
        ortdisam,
        disavtkn,
        poptype,
        ormsctax,
        workflow_status,
        frtschid,
        ppstaxrt,
        total_landed_cost_amount,
        taxamnt,
        user2ent,
        ordavamt,
        pophdr1,
        xchgrate,
        pymtrmid,
        posteddt,
        vendname,
        dscdlram,
        glpostdt,
        bchsourc,
        miscamnt,
        msctxamt,
        ectrx,
        rcptnote_7,
        withhamt,
        disavamt,
        ptdusrid,
        vadcdtro,
        ormiscamt,
        orfrtamt,
        txrgnnum,
        taxinvreqd,
        taxschid,
        rcptnote_4,
        purchase_freight_taxable,
        taxinvrecvd,
        ten99boxnumber,
        trdpctpr,
        denxrate,
        ordistkn,
        invoicereceiptdate,
        trxsorce,
        dscpctam,
        orsubtot,
        rcptnote_1,
        bachnumb,
        obtaxamt,
        pophdr2,
        modifdt,
        prepaymentamount,
        vchrnmbr,
        ratetpid,
        orddlrat,
        curncyid,
        creatddt,
        rcptnote_8,
        tax_date,
        dex_row_id,
        exchdate,
        vnddocnm,
        ten99amnt,
        origbackoutmisctaxamt,
        refrence,
        pop_hdr_errors_4,
        backoutfreighttaxamt,
        rcptnote_5,
        time1,
        bcktxamt,
        voidstts,
        simplifd,
        frttxamt,
        mctrxstt,
        cbvat,
        rcptnote_2,
        duedate,
        revaljrnentry,
        ten99type,
        replacegoods,
        ratecalc,
        aplywith,
        revaltrxsource,
        trdisamt,
        distknam,
        originatingprepaymentamt,
        actlship,
        bsivcttl,
        ortaxamt,
        backoutmisctaxamt,
        mscschid,
        ordatkn,
        invoiceexpected,
        origbackoutfreighttaxamt,
        poplnerr,
        discdate,
        rcptnote_6,
        orfrttax,
        exgtblid,
        or1099am,
        purchase_misc_taxable,
        currnidx,
        _fivetran_deleted,
        _fivetran_synced,
        upper(trim(poprctnm)) as poprctnm,
        upper(trim(vendorid)) as vendorid

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
