with source as (

    select * from {{ source('ci_dbo', 'pm10000') }}

),

renamed as (

    select
        ppstaxrt,
        icdists,
        pymtrmid,
        pgramsbj,
        pstgstus,
        aplywith,
        chrgamnt,
        corrctn,
        dex_row_ts,
        ccrctnum,
        cashamnt,
        docdate,
        wrofamnt,
        docamnt,
        discdate,
        apdstkam,
        curtrxam,
        camcbkid,
        pchschid,
        posteddt,
        pmicmsgs,
        mdfusrid,
        ten99type,
        ectrx,
        pmwrkmsg,
        bnkrcamt,
        prctdisc,
        sourcdoc,
        campmtnm,
        pmdstmsg,
        electronic,
        cdocnmbr,
        bachnumb,
        bktmscam,
        printed,
        prchamnt,
        appldamt,
        crcrdamt,
        vchrncor,
        vadcdtro,
        doctype,
        distknam,
        ictrx,
        camtdate,
        campynbr,
        bktpuram,
        backouttradedisc,
        mscchamt,
        lngdesc,
        docprinted,
        posted,
        cntrltyp,
        corrnxst,
        invoicereceiptdate,
        frtamnt,
        duedate,
        pordnmbr,
        ccampynm,
        mscschid,
        cheknmbr,
        bchsourc,
        retnagam,
        vaddcdpr,
        prchdate,
        vchrnmbr,
        vendorid,
        cardname,
        taxschid,
        chekdate,
        shipmthd,
        taxinvreqd,
        disamtav,
        crcarddt,
        frtschid,
        docnumbr,
        chekamnt,
        chamcbid,
        cbvat,
        pstgdate,
        simplifd,
        bktfrtam,
        dex_row_id,
        un1099am,
        vchnumwk,
        ppsamded,
        taxamnt,
        pmwrkms2,
        ten99amnt,
        trxdscrn,
        gstdsamt,
        tax_date,
        chekbkid,
        curncyid,
        workflow_status,
        ten99boxnumber,
        noteindx,
        modifdt,
        dscdlram,
        txengcld,
        trdisamt,
        ptdusrid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
