with source as (

    select * from {{ source('ci_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        aplywith,
        docdate,
        curtrxam,
        bachnumb,
        cbkidcsh,
        cheknmbr,
        bktslsam,
        postdate,
        curncyid,
        bktmscam,
        distknam,
        trxdscrn,
        slsamnt,
        taxschid,
        slprsnid,
        dinvpdof,
        costamnt,
        trdisamt,
        cashamnt,
        dex_row_id,
        lstusred,
        eftflag,
        taxamnt,
        directdebit,
        cshrctyp,
        cprcstnm,
        noteindx,
        corrctn,
        dscdlram,
        bktfrtam,
        adrscode,
        miscamnt,
        cbkidcrd,
        tax_date,
        frtamnt,
        cbkidchk,
        disavamt,
        saledate,
        mscschid,
        trxsorce,
        voidstts,
        agngbukt,
        discdate,
        slstercd,
        frtschid,
        slschdid,
        lstedtdt,
        factoring,
        bchsourc,
        voiddate,
        ectrx,
        ppsamded,
        dex_row_ts,
        delete1,
        backouttradedisc,
        gstdsamt,
        comdlram,
        disavtkn,
        ortrxamt,
        dscpctam,
        simplifd,
        wrofamnt,
        glpostdt,
        duedate,
        cspornbr,
        electronic,
        pstusrid,
        discrtnd,
        shipmthd,
        pymtrmid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
