with

source as (

    select {{ convert_columns('cai_dbo', 'pop10110') }} from {{ source('ci_dbo', 'pop10110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        ccode,
        itmtrkop,
        projnum,
        itemnmbr,
        prmshpdte,
        purchase_item_tax_schedu,
        origprmdate,
        odecplcu,
        released_date,
        orextcst,
        fstrcptdt,
        release,
        purchsitetxschsrc,
        dex_row_id,
        currnidx,
        product_indicator,
        phone3,
        phone2,
        phone1,
        obtaxamt,
        purchase_site_tax_schedu,
        reqdate,
        backouttradedisctax,
        qtycance,
        freeonboard,
        noninven,
        costcatid,
        linenumber,
        vnditnum,
        polneary_4,
        polneary_3,
        polneary_6,
        polneary_5,
        polneary_8,
        invindx,
        polneary_7,
        polneary_9,
        dex_row_ts,
        purchase_iv_item_taxable,
        polnesta,
        polneary_2,
        polneary_1,
        adrscode,
        costcode,
        zipcode,
        change_order_flag,
        unitcost,
        flags,
        qty_canceled_orig,
        qtyorder,
        city,
        source_document_line_num,
        lineorigin,
        oruntcst,
        vnditdsc,
        contact,
        prmdate,
        curncyid,
        origbackouttradedisctax,
        capital_item,
        landed_cost_group_id,
        jobnumbr,
        taxamnt,
        lstrcptdt,
        country,
        doctype,
        denxrate,
        xchgrate,
        opostsub,
        bcktxamt,
        commntid,
        print_phone_numbergb,
        ortaxamt,
        source_document_number,
        releasebydate,
        extdcost,
        potype,
        po_line_status_orig,
        locncode,
        decplcur,
        shipmthd,
        reqstdby,
        decplqty,
        uofm,
        bsivcttl,
        addrsource,
        state,
        cmpnynam,
        vendorid,
        address1,
        address3,
        address2,
        costtype,
        vctnmthd,
        ratecalc,
        plnndspplid,
        qtyuncmtbase,
        qtycommittedinbaseorig,
        itemdesc,
        umqtyinb,
        qtycmtbase,
        fax,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
