with source as (

    select * from {{ source('ci_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        taxamnt,
        shipmthd,
        vadcdtro,
        un1099am,
        dinvpdof,
        prchdate,
        pgramsbj,
        discdate,
        prctdisc,
        posteddt,
        discamnt,
        workflow_status,
        bchsourc,
        trdisamt,
        pchschid,
        taxinvreqd,
        ttlpymts,
        hold,
        retnagam,
        ten99boxnumber,
        pstgdate,
        docnumbr,
        lngdesc,
        curtrxam,
        voidpdate,
        modifdt,
        disavtkn,
        mscchamt,
        mdfusrid,
        dscdlram,
        tax_date,
        cardname,
        taxschid,
        bktpuram,
        corrctn,
        bachnumb,
        chekbkid,
        docdate,
        prchamnt,
        gstdsamt,
        frtamnt,
        ptdusrid,
        backouttradedisc,
        bktmscam,
        ictrx,
        cbvat,
        vndchknm,
        aplywith,
        duedate,
        docamnt,
        ten99type,
        pymtrmid,
        ten99amnt,
        disamtav,
        frtschid,
        simplifd,
        pyenttyp,
        trxdscrn,
        trxsorce,
        vendorid,
        ponumber,
        ectrx,
        noteindx,
        docprinted,
        curncyid,
        bktfrtam,
        wrofamnt,
        dex_row_ts,
        distknam,
        ppsamded,
        cntrltyp,
        mscschid,
        electronic,
        voided,
        invoicereceiptdate,
        dex_row_id,
        pordnmbr,
        ppstaxrt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
