with

source as (

    select {{ convert_columns('cai_dbo', 'pop30110') }} from {{ source('ci_dbo', 'pop30110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        ccode,
        itmtrkop,
        projnum,
        contact,
        itemnmbr,
        prmshpdte,
        prmdate,
        purchase_item_tax_schedu,
        jobnumbr,
        landed_cost_group_id,
        taxamnt,
        lstrcptdt,
        country,
        origprmdate,
        odecplcu,
        doctype,
        released_date,
        orextcst,
        bcktxamt,
        fstrcptdt,
        release,
        commntid,
        purchsitetxschsrc,
        ortaxamt,
        print_phone_numbergb,
        source_document_number,
        dex_row_id,
        releasebydate,
        currnidx,
        product_indicator,
        extdcost,
        phone3,
        phone2,
        phone1,
        obtaxamt,
        purchase_site_tax_schedu,
        potype,
        locncode,
        reqdate,
        decplcur,
        shipmthd,
        reqstdby,
        qtycance,
        freeonboard,
        decplqty,
        uofm,
        noninven,
        bsivcttl,
        addrsource,
        state,
        costcatid,
        linenumber,
        cmpnynam,
        vnditnum,
        polneary_4,
        polneary_3,
        polneary_6,
        vendorid,
        polneary_5,
        polneary_8,
        polneary_7,
        invindx,
        purchase_iv_item_taxable,
        dex_row_ts,
        polneary_9,
        polnesta,
        address1,
        address3,
        polneary_2,
        polneary_1,
        address2,
        costtype,
        adrscode,
        costcode,
        vctnmthd,
        zipcode,
        unitcost,
        flags,
        qtyorder,
        city,
        lineorigin,
        source_document_line_num,
        oruntcst,
        itemdesc,
        umqtyinb,
        fax,
        vnditdsc,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
