with source as (

    select * from {{ source('ci_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        distknam,
        ictrx,
        vndchknm,
        aplywith,
        mscschid,
        duedate,
        ten99amnt,
        dex_row_id,
        disamtav,
        simplifd,
        pyenttyp,
        pordnmbr,
        un1099am,
        ppstaxrt,
        dinvpdof,
        prchdate,
        discdate,
        vendorid,
        workflow_status,
        bchsourc,
        docprinted,
        noteindx,
        curncyid,
        pchschid,
        dex_row_ts,
        taxinvreqd,
        ttlpymts,
        hold,
        ppsamded,
        cntrltyp,
        disavtkn,
        lngdesc,
        voided,
        pstgdate,
        docnumbr,
        electronic,
        mdfusrid,
        invoicereceiptdate,
        bktpuram,
        taxschid,
        dscdlram,
        docdate,
        bachnumb,
        frtamnt,
        shipmthd,
        taxamnt,
        prchamnt,
        gstdsamt,
        vadcdtro,
        ptdusrid,
        backouttradedisc,
        pgramsbj,
        cbvat,
        bktmscam,
        docamnt,
        prctdisc,
        ten99type,
        posteddt,
        pymtrmid,
        discamnt,
        frtschid,
        bnkrcamt,
        trxdscrn,
        trxsorce,
        trdisamt,
        retnagam,
        mscchamt,
        ten99boxnumber,
        ponumber,
        curtrxam,
        ectrx,
        modifdt,
        corrctn,
        tax_date,
        cardname,
        chekbkid,
        wrofamnt,
        bktfrtam,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
