with source as (

    select * from {{ source('ci_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        zip,
        prclevel,
        rmcosacc,
        adrscode,
        upszone,
        rmfcgacc,
        custdisc,
        rmaracc,
        shipcomplete,
        salsterr,
        hold,
        cbvat,
        txrgnnum,
        chekbkid,
        balnctyp,
        integrationsource,
        phone3,
        rmtakacc,
        dex_row_id,
        prbtadcd,
        finchdlr,
        gpsfointegrationid,
        address1,
        mxwoftyp,
        staddrcd,
        comment2,
        post_results_to,
        includeindp,
        govcrpid,
        slprsnid,
        fax,
        govindid,
        rmivacc,
        taxexmt2,
        minpypct,
        crlmtpam,
        kpdsthst,
        custclas,
        revalue_customer,
        minpydlr,
        rmslsacc,
        state,
        phone2,
        send_email_statements,
        crlmtper,
        minpytyp,
        duegrper,
        cprcstnm,
        rmsoracc,
        comment1,
        ratetpid,
        pymtrmid,
        declid,
        disgrper,
        mxwrofam,
        dex_row_ts,
        address3,
        crcardid,
        custname,
        ccode,
        creatddt,
        prstadcd,
        crcrdnum,
        taxexmt1,
        cntcprsn,
        frstindt,
        userdef2,
        stmtname,
        kptrxhst,
        crlmtamt,
        rmwracc,
        defcacty,
        shipmthd,
        userlang,
        shrtname,
        rmovrpymtwrtoffacctidx,
        bankname,
        phone1,
        integrationid,
        bnkbrnch,
        fnchpcnt,
        curncyid,
        rmavacc,
        inactive,
        noteindx,
        docfmtid,
        country,
        taxschid,
        stmtcycl,
        city,
        finchid,
        modifdt,
        orderfulfilldefault,
        fnchatyp,
        kperhist,
        address2,
        custpriority,
        kpcalhst,
        rmcshacc,
        ccrdxpdt,
        crlmttyp,
        userdef1,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
