with source as (

    select * from {{ source('ci_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        mxiafvnd,
        post_results_to,
        pmdtkidx,
        laborpmttype,
        state,
        trddisct,
        vendstts,
        pmtdscix,
        minpydlr,
        faxnumbr,
        workflow_priority,
        country,
        vndchknm,
        vendshnm,
        duegrper,
        docfmtid,
        upszone,
        address1,
        city,
        userdef1,
        prspayee,
        disgrper,
        comment1,
        acpuridx,
        kgldsths,
        parvenid,
        curncyid,
        maxindlr,
        modifdt,
        ten99type,
        txidnmbr,
        vadcdpad,
        ccode,
        ratetpid,
        dex_row_ts,
        pymtrmid,
        vadcdsfr,
        acnmvndr,
        revalue_vendor,
        noteindx,
        ppstaxrt,
        govcrpid,
        dex_row_id,
        cbvat,
        onepaypervendinv,
        taxschid,
        workflow_status,
        rtobutkn,
        vaddcdpr,
        withholdingentitytype,
        kptrxhst,
        vadcd1099,
        hold,
        shipmthd,
        freeonboard,
        creatddt,
        vadcdtro,
        ptcshacf,
        zipcode,
        vndclsid,
        crtcomdt,
        crlmtdlr,
        userlang,
        venddba,
        workflow_approval_status,
        pmtaxidx,
        credtlmt,
        pmprchix,
        taxinvrecvd,
        taxfilenummode,
        phnumbr2,
        kperhist,
        ten99boxnumber,
        address3,
        minorder,
        mxwofamt,
        pmcshidx,
        govindid,
        minpytyp,
        txrgnnum,
        declid,
        chekbkid,
        withholdingformtype,
        pmfrtidx,
        minpypct,
        purpvidx,
        phone3,
        vndcntct,
        crtexpdt,
        pmfinidx,
        kpcalhst,
        writeoff,
        pmapindx,
        pmrtngix,
        dxvarnum,
        sbppsded,
        brthdate,
        pmwrtidx,
        phnumbr1,
        vendname,
        address2,
        userdef2,
        withholdingtype,
        pmmschix,
        comment2,
        pmdavidx,
        pymntpri,
        xpdtoblg,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
