with

source as (

    select {{ convert_columns('avc_dbo', 'pop10110') }}
    from {{ source('avc_dbo', 'pop10110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        xchgrate,
        product_indicator,
        landed_cost_group_id,
        vctnmthd,
        polneary_5,
        backouttradedisctax,
        polneary_8,
        lineorigin,
        polneary_2,
        shipmthd,
        phone3,
        contact,
        address2,
        costcode,
        locncode,
        vendorid,
        jobnumbr,
        obtaxamt,
        opostsub,
        denxrate,
        reqdate,
        commntid,
        qtycommittedinbaseorig,
        country,
        dex_row_id,
        zipcode,
        purchsitetxschsrc,
        vnditdsc,
        addrsource,
        phone1,
        ratecalc,
        source_document_number,
        orextcst,
        reqstdby,
        origbackouttradedisctax,
        itemnmbr,
        unitcost,
        ortaxamt,
        qtycance,
        decplcur,
        qtycmtbase,
        polneary_3,
        bcktxamt,
        costtype,
        polnesta,
        adrscode,
        purchase_iv_item_taxable,
        uofm,
        curncyid,
        ccode,
        fax,
        qtyuncmtbase,
        polneary_4,
        address3,
        po_line_status_orig,
        origprmdate,
        city,
        vnditnum,
        invindx,
        released_date,
        bsivcttl,
        cmpnynam,
        purchase_site_tax_schedu,
        costcatid,
        prmshpdte,
        lstrcptdt,
        source_document_line_num,
        fstrcptdt,
        polneary_6,
        itmtrkop,
        projnum,
        odecplcu,
        doctype,
        phone2,
        freeonboard,
        prmdate,
        polneary_7,
        extdcost,
        flags,
        umqtyinb,
        polneary_1,
        qtyorder,
        print_phone_numbergb,
        dex_row_ts,
        releasebydate,
        purchase_item_tax_schedu,
        taxamnt,
        decplqty,
        noninven,
        itemdesc,
        currnidx,
        address1,
        state,
        qty_canceled_orig,
        release,
        polneary_9,
        capital_item,
        change_order_flag,
        oruntcst,
        plnndspplid,
        potype,
        linenumber,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
