with

source as (

    select {{ convert_columns('avc_dbo', 'pop30110') }}
    from {{ source('avc_dbo', 'pop30110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        taxamnt,
        flags,
        costcode,
        addrsource,
        purchase_item_tax_schedu,
        decplqty,
        orextcst,
        ccode,
        adrscode,
        product_indicator,
        ortaxamt,
        odecplcu,
        reqstdby,
        shipmthd,
        unitcost,
        dex_row_id,
        release,
        obtaxamt,
        print_phone_numbergb,
        decplcur,
        phone3,
        vnditdsc,
        polneary_9,
        polneary_3,
        vctnmthd,
        purchase_site_tax_schedu,
        source_document_line_num,
        released_date,
        costcatid,
        source_document_number,
        polneary_4,
        purchsitetxschsrc,
        cmpnynam,
        releasebydate,
        origprmdate,
        potype,
        itemnmbr,
        itemdesc,
        landed_cost_group_id,
        lineorigin,
        lstrcptdt,
        bsivcttl,
        city,
        invindx,
        polneary_5,
        itmtrkop,
        vendorid,
        prmshpdte,
        polneary_8,
        bcktxamt,
        fax,
        costtype,
        polneary_2,
        uofm,
        linenumber,
        polnesta,
        jobnumbr,
        country,
        projnum,
        umqtyinb,
        address3,
        phone2,
        oruntcst,
        commntid,
        freeonboard,
        fstrcptdt,
        address2,
        qtyorder,
        polneary_6,
        state,
        purchase_iv_item_taxable,
        zipcode,
        noninven,
        contact,
        reqdate,
        dex_row_ts,
        phone1,
        locncode,
        doctype,
        vnditnum,
        address1,
        polneary_7,
        prmdate,
        extdcost,
        currnidx,
        qtycance,
        polneary_1,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
