with items as (
    select
        d365_items."Item_SK",
        d365_items."Item ID",
        d365_items."Product Name",
        d365_items."Company",
        d365_items."Company Name",
        d365_items."Language ID",
        d365_items."Item Group",
        d365_items."Item Group ID",
        d365_items."Item Description",
        d365_items."Country of Origin",
        d365_items."Skin On Off",
        d365_items."Sub Category",
        d365_items."Bone In Out",
        d365_items."Coolant",
        d365_items."Harvest",
        d365_items."Package Weight",
        d365_items."Scaled",
        d365_items."Trim",
        d365_items."UB Code",
        d365_items."Whole or VA",
        d365_items."Family",
        d365_items."Form",
        d365_items."Package Unit Count",
        d365_items."Pieces Per lb Count",
        d365_items."Product Size UOM",
        d365_items."Production Phase",
        d365_items."Skinning Type",
        d365_items."ASC Certification",
        d365_items."Species",
        d365_items."Sub-Species",
        d365_items."Frozen Format",
        d365_items."Category",
        d365_items."High Level Grade",
        d365_items."Grade",
        d365_items."Brand",
        d365_items."Product Size",
        d365_items."Case Weight",
        d365_items."Case Weight UOM",
        d365_items."Cooked/Raw",
        d365_items."NFT Label",
        d365_items."Package Weight UOM",
        d365_items."MSC Certification",
        d365_items."Certification",
        d365_items.rwoa,
        d365_items."Catch Area",
        d365_items."Inside Pack",
        d365_items."Master Packaging Type",
        d365_items."Product Label",
        d365_items."Value Add",
        d365_items."Product Form - Shrimp",
        d365_items."Flavour",
        d365_items."Harvest Method",
        d365_items."Process Type",
        d365_items."MSC Number",
        d365_items.crm_item_id,
        d365_items.crm_item_sk,
        d365_items.productline_value,
        d365_items.productline_name,
        d365_items.productline_desc,
        d365_items.product_lifecycle_status,
        'D365' as sourcesystem,
        0 as sourcesystemcode
    from {{ ref('dim_item_d365') }} as d365_items

    union all

    select
        ns_items."Item_SK",
        ns_items."Item ID",
        ns_items."Product Name",
        ns_items."Company",
        ns_items."Company Name",
        ns_items."Language ID",
        ns_items."Item Group",
        ns_items."Item Group ID",
        ns_items."Item Description",
        ns_items."Country of Origin",
        ns_items."Skin On Off",
        ns_items."Sub Category",
        ns_items."Bone In Out",
        ns_items."Coolant",
        ns_items."Harvest",
        ns_items."Package Weight",
        ns_items."Scaled",
        ns_items."Trim",
        ns_items."UB Code",
        ns_items."Whole or VA",
        ns_items."Family",
        ns_items."Form",
        ns_items."Package Unit Count",
        ns_items."Pieces Per lb Count",
        ns_items."Product Size UOM",
        ns_items."Production Phase",
        ns_items."Skinning Type",
        ns_items."ASC Certification",
        ns_items."Species",
        ns_items."Sub-Species",
        ns_items."Frozen Format",
        ns_items."Category",
        ns_items."High Level Grade",
        ns_items."Grade",
        ns_items."Brand",
        ns_items."Product Size",
        ns_items."Case Weight",
        ns_items."Case Weight UOM",
        ns_items."Cooked/Raw",
        ns_items."NFT Label",
        ns_items."Package Weight UOM",
        ns_items."MSC Certification",
        ns_items."Certification",
        ns_items.rwoa,
        ns_items."Catch Area",
        ns_items."Inside Pack",
        ns_items."Master Packaging Type",
        ns_items."Product Label",
        ns_items."Value Add",
        ns_items."Product Form - Shrimp",
        ns_items."Flavour",
        ns_items."Harvest Method",
        ns_items."Process Type",
        ns_items."MSC Number",
        ns_items.crm_item_id,
        ns_items.crm_item_sk,
        '' as productline_value,
        '' as productline_name,
        '' as productline_desc,
        ns_items.product_lifecycle_status,
        'NORTHSCOPE' as sourcesystem,
        1 as sourcesystemcode
    from {{ ref('dim_item_ns') }} as ns_items
)

select
    *,
    md5(concat(coalesce(trim("Item_SK"), trim("Item ID")), sourcesystem)) as sk_item_global,
    md5(concat(trim("Item ID"), sourcesystem)) as sk_item_targets
from items
