with source as (

    select * from {{ source('nns_dbo', 'pop30300') }}

),

renamed as (

    select
        poprctnm,
        subtotal,
        duedate,
        rcptnote_1,
        pymtrmid,
        or1099am,
        rcptnote_7,
        rcptnote_4,
        mscschid,
        disavtkn,
        simplifd,
        shipmthd,
        withhamt,
        ppstaxrt,
        revaltrxsource,
        disavamt,
        currnidx,
        orsubtot,
        replacegoods,
        exchdate,
        ordatkn,
        creatddt,
        ratetpid,
        dscpctam,
        ectrx,
        trxsorce,
        ten99amnt,
        actlship,
        frtamnt,
        bchsourc,
        invoiceexpected,
        dscdlram,
        bachnumb,
        origbackoutfreighttaxamt,
        receiptdate,
        prepaymentamount,
        frttxamt,
        ormsctax,
        xchgrate,
        cbvat,
        rcptnote_5,
        pophdr2,
        user2ent,
        dex_row_id,
        obtaxamt,
        distknam,
        ptdusrid,
        taxinvrecvd,
        rcptnote_2,
        pop_hdr_errors_4,
        bsivcttl,
        vendname,
        poplnerr,
        txrgnnum,
        workflow_status,
        rcptnote_3,
        trdpctpr,
        purchase_freight_taxable,
        voidstts,
        glpostdt,
        ortdisam,
        backoutfreighttaxamt,
        taxamnt,
        refrence,
        orddlrat,
        purchase_misc_taxable,
        aplywith,
        miscamnt,
        frtschid,
        tax_date,
        msctxamt,
        vchrnmbr,
        modifdt,
        orfrttax,
        denxrate,
        ten99boxnumber,
        bcktxamt,
        vendorid,
        orfrtamt,
        total_landed_cost_amount,
        invoicereceiptdate,
        vnddocnm,
        rcptnote_6,
        backoutmisctaxamt,
        ordavamt,
        pophdr1,
        poptype,
        ratecalc,
        origbackoutmisctaxamt,
        discdate,
        rcptnote_8,
        taxschid,
        time1,
        originatingprepaymentamt,
        vadcdtro,
        ordistkn,
        exgtblid,
        curncyid,
        mctrxstt,
        revaljrnentry,
        ten99type,
        trdisamt,
        ortaxamt,
        ormiscamt,
        posteddt,
        taxinvreqd,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
