with source as (

    select * from {{ source('nns_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        discamnt,
        ten99amnt,
        voidpdate,
        aplywith,
        disavtkn,
        backouttradedisc,
        mscchamt,
        dex_row_ts,
        bchsourc,
        discdate,
        noteindx,
        ten99type,
        pyenttyp,
        curncyid,
        bachnumb,
        docamnt,
        tax_date,
        invoicereceiptdate,
        docprinted,
        docnumbr,
        gstdsamt,
        taxamnt,
        dex_row_id,
        dscdlram,
        pordnmbr,
        ictrx,
        vadcdtro,
        mdfusrid,
        pstgdate,
        chekbkid,
        taxschid,
        bktfrtam,
        hold,
        curtrxam,
        workflow_status,
        frtamnt,
        ppstaxrt,
        ttlpymts,
        vndchknm,
        frtschid,
        prchdate,
        simplifd,
        vendorid,
        wrofamnt,
        bktpuram,
        duedate,
        ppsamded,
        trdisamt,
        distknam,
        electronic,
        ectrx,
        ten99boxnumber,
        posteddt,
        ponumber,
        dinvpdof,
        pchschid,
        corrctn,
        pgramsbj,
        docdate,
        retnagam,
        cbvat,
        trxdscrn,
        voided,
        cardname,
        prctdisc,
        pymtrmid,
        lngdesc,
        cntrltyp,
        un1099am,
        trxsorce,
        taxinvreqd,
        shipmthd,
        disamtav,
        mscschid,
        prchamnt,
        ptdusrid,
        modifdt,
        bktmscam,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
