with source as (

    select * from {{ source('nns_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        ccrdxpdt,
        finchid,
        prbtadcd,
        modifdt,
        stmtname,
        minpypct,
        declid,
        country,
        fax,
        minpydlr,
        custpriority,
        zip,
        post_results_to,
        includeindp,
        crlmtpam,
        finchdlr,
        crlmtper,
        city,
        fnchatyp,
        noteindx,
        govcrpid,
        cntcprsn,
        phone1,
        prstadcd,
        address1,
        frstindt,
        rmaracc,
        docfmtid,
        address3,
        integrationid,
        disgrper,
        dex_row_id,
        bnkbrnch,
        defcacty,
        fnchpcnt,
        adrscode,
        crlmttyp,
        taxschid,
        pymtrmid,
        creatddt,
        userdef1,
        dex_row_ts,
        custdisc,
        shipcomplete,
        slprsnid,
        rmcshacc,
        hold,
        curncyid,
        userlang,
        userdef2,
        kptrxhst,
        state,
        inactive,
        prclevel,
        shrtname,
        taxexmt2,
        address2,
        rmovrpymtwrtoffacctidx,
        phone2,
        cprcstnm,
        comment1,
        custclas,
        chekbkid,
        txrgnnum,
        orderfulfilldefault,
        govindid,
        rmavacc,
        comment2,
        ccode,
        stmtcycl,
        cbvat,
        mxwrofam,
        salsterr,
        revalue_customer,
        ratetpid,
        shipmthd,
        rmsoracc,
        duegrper,
        balnctyp,
        bankname,
        staddrcd,
        crcrdnum,
        rmfcgacc,
        rmwracc,
        rmtakacc,
        kpdsthst,
        integrationsource,
        rmslsacc,
        kperhist,
        crcardid,
        rmivacc,
        mxwoftyp,
        custname,
        send_email_statements,
        phone3,
        upszone,
        taxexmt1,
        minpytyp,
        crlmtamt,
        rmcosacc,
        gpsfointegrationid,
        kpcalhst,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
