with source as (

    select * from {{ source('nns_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        comment1,
        govindid,
        ptcshacf,
        minpydlr,
        kgldsths,
        kperhist,
        crtexpdt,
        userlang,
        vadcdpad,
        modifdt,
        writeoff,
        pmtdscix,
        phnumbr2,
        declid,
        userdef2,
        ratetpid,
        dex_row_id,
        zipcode,
        vndclsid,
        pymntpri,
        venddba,
        address2,
        vadcd1099,
        vendshnm,
        noteindx,
        hold,
        upszone,
        vendstts,
        vaddcdpr,
        laborpmttype,
        onepaypervendinv,
        pmcshidx,
        pmprchix,
        workflow_status,
        vndchknm,
        xpdtoblg,
        sbppsded,
        creatddt,
        workflow_priority,
        pmdtkidx,
        pmwrtidx,
        revalue_vendor,
        dxvarnum,
        pmdavidx,
        withholdingformtype,
        acnmvndr,
        taxfilenummode,
        crtcomdt,
        disgrper,
        faxnumbr,
        comment2,
        parvenid,
        userdef1,
        vadcdsfr,
        pymtrmid,
        dex_row_ts,
        minorder,
        ten99type,
        crlmtdlr,
        phnumbr1,
        ppstaxrt,
        pmfrtidx,
        ccode,
        phone3,
        kpcalhst,
        country,
        trddisct,
        withholdingentitytype,
        brthdate,
        txidnmbr,
        address3,
        pmtaxidx,
        docfmtid,
        vndcntct,
        credtlmt,
        acpuridx,
        kptrxhst,
        purpvidx,
        cbvat,
        mxiafvnd,
        maxindlr,
        freeonboard,
        pmrtngix,
        pmapindx,
        withholdingtype,
        govcrpid,
        mxwofamt,
        ten99boxnumber,
        txrgnnum,
        minpytyp,
        duegrper,
        taxschid,
        address1,
        minpypct,
        taxinvrecvd,
        pmfinidx,
        state,
        curncyid,
        post_results_to,
        shipmthd,
        city,
        pmmschix,
        vendname,
        vadcdtro,
        prspayee,
        chekbkid,
        rtobutkn,
        workflow_approval_status,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
