with source as (

    select * from {{ source('nns_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        retnagam,
        cbvat,
        disamtav,
        prchdate,
        dinvpdof,
        corrctn,
        pordnmbr,
        pchschid,
        dscdlram,
        cntrltyp,
        modifdt,
        ten99boxnumber,
        docamnt,
        bktpuram,
        chekbkid,
        ectrx,
        vadcdtro,
        vendorid,
        bchsourc,
        noteindx,
        electronic,
        distknam,
        aplywith,
        ponumber,
        workflow_status,
        pgramsbj,
        frtamnt,
        docnumbr,
        vndchknm,
        taxschid,
        mdfusrid,
        docdate,
        curncyid,
        cardname,
        tax_date,
        bktfrtam,
        lngdesc,
        frtschid,
        curtrxam,
        prchamnt,
        dex_row_id,
        pstgdate,
        ten99type,
        hold,
        mscschid,
        mscchamt,
        docprinted,
        taxinvreqd,
        ttlpymts,
        bachnumb,
        trxdscrn,
        ppstaxrt,
        posteddt,
        disavtkn,
        discamnt,
        ten99amnt,
        simplifd,
        shipmthd,
        trdisamt,
        dex_row_ts,
        pyenttyp,
        backouttradedisc,
        wrofamnt,
        invoicereceiptdate,
        bktmscam,
        ptdusrid,
        taxamnt,
        trxsorce,
        un1099am,
        discdate,
        gstdsamt,
        duedate,
        ppsamded,
        bnkrcamt,
        prctdisc,
        voided,
        ictrx,
        pymtrmid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
