with source as (

    select * from {{ source('nns_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        cashamnt,
        frtschid,
        dscpctam,
        discrtnd,
        saledate,
        costamnt,
        mscschid,
        docdate,
        taxschid,
        disavtkn,
        shipmthd,
        backouttradedisc,
        agngbukt,
        eftflag,
        corrctn,
        slprsnid,
        aplywith,
        gstdsamt,
        slschdid,
        tax_date,
        dex_row_id,
        cbkidcsh,
        cshrctyp,
        noteindx,
        bchsourc,
        ppsamded,
        bachnumb,
        dscdlram,
        delete1,
        duedate,
        disavamt,
        frtamnt,
        bktslsam,
        bktfrtam,
        pstusrid,
        discdate,
        trxsorce,
        trxdscrn,
        pymtrmid,
        trdisamt,
        voidstts,
        lstusred,
        cbkidcrd,
        ortrxamt,
        wrofamnt,
        postdate,
        bktmscam,
        taxamnt,
        directdebit,
        miscamnt,
        dinvpdof,
        cprcstnm,
        electronic,
        ectrx,
        distknam,
        cheknmbr,
        voiddate,
        curncyid,
        comdlram,
        cbkidchk,
        curtrxam,
        adrscode,
        slsamnt,
        glpostdt,
        lstedtdt,
        slstercd,
        simplifd,
        factoring,
        cspornbr,
        dex_row_ts,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
