with

source as (

    select * from {{ source('wvcl_dbo', 'pm10000') }}

),

renamed as (

    select
        pgramsbj,
        duedate,
        bchsourc,
        trxdscrn,
        docamnt,
        cntrltyp,
        ten99boxnumber,
        bktfrtam,
        invoicereceiptdate,
        pmwrkmsg,
        frtamnt,
        ptdusrid,
        retnagam,
        prchdate,
        crcrdamt,
        bnkrcamt,
        un1099am,
        docdate,
        chekdate,
        mscchamt,
        prctdisc,
        backouttradedisc,
        bktpuram,
        gstdsamt,
        docprinted,
        discdate,
        distknam,
        cdocnmbr,
        pmdstmsg,
        pstgstus,
        cashamnt,
        workflow_status,
        prchamnt,
        mdfusrid,
        pchschid,
        ccampynm,
        camtdate,
        pordnmbr,
        posteddt,
        vendorid,
        vadcdtro,
        tax_date,
        chekbkid,
        corrctn,
        taxinvreqd,
        pstgdate,
        electronic,
        mscschid,
        corrnxst,
        dex_row_ts,
        aplywith,
        sourcdoc,
        disamtav,
        crcarddt,
        simplifd,
        bktmscam,
        vchrncor,
        bachnumb,
        vchnumwk,
        posted,
        campynbr,
        cardname,
        taxamnt,
        ppstaxrt,
        cbvat,
        pymtrmid,
        cheknmbr,
        chrgamnt,
        ccrctnum,
        wrofamnt,
        appldamt,
        shipmthd,
        ten99type,
        curtrxam,
        ten99amnt,
        noteindx,
        apdstkam,
        ectrx,
        dscdlram,
        lngdesc,
        pmicmsgs,
        chamcbid,
        campmtnm,
        printed,
        docnumbr,
        trdisamt,
        ictrx,
        taxschid,
        vchrnmbr,
        camcbkid,
        icdists,
        dex_row_id,
        chekamnt,
        curncyid,
        vaddcdpr,
        doctype,
        modifdt,
        frtschid,
        ppsamded,
        pmwrkms2,
        txengcld,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
