with cpm_transactions as (
    select
        company_name,
        status,
        transaction_date,
        period_number,
        journal_entry_number,
        voucher,
        account_number,
        main_number,
        cost_centre,
        department,
        division,
        location,
        product_line,
        cash_flow,
        company_relationship,
        account_description,
        main_account_description,
        cost_centre_description,
        department_description,
        division_description,
        location_description,
        product_line_description,
        cash_flow_description,
        company_relationship_description,
        accounting_currency_debit_amount,
        accounting_currency_credit_amount,
        customer_vendor_id,
        customer_vendor_name,
        document_number,
        document_date,
        transaction_currency,
        canceled,
        exchange_rate,
        text_description,
        transaction_currency_debit_amount,
        transaction_currency_credit_amount
    from {{ ref('int_d365_cpm__transactions') }}
),

cpm_vend_trans as (
    select
        company_name,
        status,
        transaction_date,
        period_number,
        journal_entry_number,
        voucher,
        account_number,
        main_number,
        cost_centre,
        department,
        division,
        "location",
        product_line,
        cash_flow,
        company_relationship,
        account_description,
        main_account_description,
        cost_centre_description,
        department_description,
        division_description,
        location_description,
        product_line_description,
        cash_flow_description,
        company_relationship_description,
        accounting_currency_debit_amount,
        accounting_currency_credit_amount,
        customer_vendor_id,
        customer_vendor_name,
        document_number,
        document_date,
        transaction_currency,
        canceled,
        exchange_rate,
        text_description,
        transaction_currency_debit_amount,
        transaction_currency_credit_amount
    from {{ ref('int_d365_cpm__vendor_transactions') }}
),

cpm_cust_trans as (
    select
        company_name,
        status,
        transaction_date,
        period_number,
        journal_entry_number,
        voucher,
        account_number,
        main_number,
        cost_centre,
        department,
        division,
        "location",
        product_line,
        cash_flow,
        company_relationship,
        account_description,
        main_account_description,
        cost_centre_description,
        department_description,
        division_description,
        location_description,
        product_line_description,
        cash_flow_description,
        company_relationship_description,
        accounting_currency_debit_amount,
        accounting_currency_credit_amount,
        customer_vendor_id,
        customer_vendor_name,
        document_number,
        document_date,
        transaction_currency,
        canceled,
        exchange_rate,
        text_description,
        transaction_currency_debit_amount,
        transaction_currency_credit_amount
    from {{ ref('int_d365_cpm__customer_transactions') }}
)

select * from cpm_transactions
union all
select * from cpm_vend_trans
union all
select * from cpm_cust_trans
