with

source as (

    select * from {{ source('mas_far_dbo', 'ap_invoicehistoryheader') }}

),

renamed as (

    select
        headerseqno,
        invoiceno,
        form1099,
        vendorname,
        apdivisionno,
        shiptozipcode,
        fob,
        codamount,
        retentionamt,
        nontaxableamt,
        jobno,
        purchasezipcode,
        purchasestate,
        shiptostate,
        customerno,
        purchasecity,
        taxableamt,
        invoicetype,
        udf_import_dua,
        modulecode,
        purchasecountrycode,
        shiptoaddress3,
        sourcejournalno,
        netinvoiceamt,
        freightamt,
        shiptoname,
        shiptoaddress2,
        invoicediscountdate,
        receiptdate,
        bankcode,
        shiptocode,
        purchasename,
        receiptno,
        timeupdated,
        timecreated,
        invoicedate,
        taxamt,
        transactiondate,
        taxclass,
        confirmto,
        userkey,
        discountamt,
        usetax,
        vendorno,
        purchaseorderdate,
        multiplepurchaseordersapplied,
        purchaseordertype,
        shiptocountrycode,
        dateupdated,
        prepaidcheckno,
        shipvia,
        invoiceamt,
        purchaseaddress3,
        totalcostforfrghtalloc,
        datecreated,
        shiptocity,
        codcheckno,
        box1099,
        codno,
        usercreatedkey,
        holdpayment,
        ardivisionno,
        purchaseaddress2,
        purchaseorderno,
        prepaidpaymentdate,
        separatecheck,
        purchaseaddress1,
        multipleprepaymentsapplied,
        nonrecoverableamt,
        requireddate,
        taxschedule,
        userupdatedkey,
        purchaseaddresscode,
        invoiceduedate,
        sourcejournal,
        prepaidapplytoinvoiceno,
        nontaxablemiscchargeamt,
        encryptedvals,
        termscode,
        prepaidfreight,
        shiptoaddress1,
        prepaymentamt,
        warehousecode,
        taxablemiscchargeamt,
        comment,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select *
from renamed
where coalesce(_fivetran_deleted, false) = false
