with source as (

    select * from {{ source('casl_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        rmtakacc,
        custpriority,
        mxwoftyp,
        prstadcd,
        custdisc,
        fnchatyp,
        dex_row_id,
        shipcomplete,
        rmavacc,
        frstindt,
        fnchpcnt,
        fax,
        country,
        disgrper,
        finchid,
        ratetpid,
        zip,
        cntcprsn,
        mxwrofam,
        kpdsthst,
        stmtname,
        duegrper,
        docfmtid,
        integrationid,
        city,
        revalue_customer,
        declid,
        cbvat,
        ccode,
        modifdt,
        integrationsource,
        phone1,
        govcrpid,
        crlmtper,
        post_results_to,
        shipmthd,
        inactive,
        comment2,
        ccrdxpdt,
        taxexmt1,
        staddrcd,
        dex_row_ts,
        defcacty,
        phone2,
        crlmttyp,
        hold,
        upszone,
        rmovrpymtwrtoffacctidx,
        custname,
        crcardid,
        kptrxhst,
        phone3,
        crcrdnum,
        address2,
        govindid,
        gpsfointegrationid,
        orderfulfilldefault,
        shrtname,
        taxexmt2,
        creatddt,
        txrgnnum,
        salsterr,
        state,
        stmtcycl,
        kperhist,
        rmcshacc,
        noteindx,
        userlang,
        finchdlr,
        minpydlr,
        rmaracc,
        includeindp,
        custclas,
        comment1,
        bankname,
        chekbkid,
        taxschid,
        minpytyp,
        userdef2,
        cprcstnm,
        address1,
        crlmtpam,
        bnkbrnch,
        rmcosacc,
        adrscode,
        pymtrmid,
        minpypct,
        balnctyp,
        curncyid,
        rmwracc,
        userdef1,
        rmivacc,
        send_email_statements,
        crlmtamt,
        rmslsacc,
        rmsoracc,
        kpcalhst,
        prbtadcd,
        slprsnid,
        prclevel,
        rmfcgacc,
        address3,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
