with source as (

    select * from {{ source('casl_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        modifdt,
        electronic,
        distknam,
        duedate,
        ectrx,
        wrofamnt,
        taxschid,
        pordnmbr,
        prctdisc,
        docnumbr,
        pyenttyp,
        un1099am,
        shipmthd,
        pymtrmid,
        workflow_status,
        mdfusrid,
        cntrltyp,
        corrctn,
        ppsamded,
        trdisamt,
        bchsourc,
        cbvat,
        curncyid,
        simplifd,
        vndchknm,
        bktfrtam,
        bachnumb,
        dscdlram,
        pchschid,
        docdate,
        ictrx,
        ten99type,
        ttlpymts,
        docamnt,
        vadcdtro,
        frtschid,
        chekbkid,
        pgramsbj,
        hold,
        posteddt,
        dinvpdof,
        backouttradedisc,
        discdate,
        disavtkn,
        aplywith,
        noteindx,
        trxsorce,
        dex_row_ts,
        ppstaxrt,
        dex_row_id,
        taxamnt,
        docprinted,
        ponumber,
        bktmscam,
        ptdusrid,
        gstdsamt,
        lngdesc,
        frtamnt,
        curtrxam,
        voided,
        voidpdate,
        retnagam,
        prchdate,
        disamtav,
        prchamnt,
        mscschid,
        ten99boxnumber,
        tax_date,
        taxinvreqd,
        mscchamt,
        invoicereceiptdate,
        trxdscrn,
        bktpuram,
        discamnt,
        ten99amnt,
        vendorid,
        cardname,
        pstgdate,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
