with source as (

    select * from {{ source('casl_dbo', 'pop30300') }}

),

renamed as (

    select
        rcptnote_6,
        ormiscamt,
        curncyid,
        total_landed_cost_amount,
        txrgnnum,
        orfrttax,
        currnidx,
        vendname,
        taxschid,
        bchsourc,
        pophdr1,
        duedate,
        denxrate,
        exchdate,
        trxsorce,
        workflow_status,
        ectrx,
        msctxamt,
        ppstaxrt,
        dscdlram,
        vnddocnm,
        ten99type,
        pymtrmid,
        discdate,
        orddlrat,
        orfrtamt,
        ortdisam,
        mscschid,
        simplifd,
        user2ent,
        posteddt,
        backoutmisctaxamt,
        ordavamt,
        time1,
        cbvat,
        bsivcttl,
        revaltrxsource,
        taxamnt,
        rcptnote_2,
        backoutfreighttaxamt,
        rcptnote_5,
        miscamnt,
        xchgrate,
        invoiceexpected,
        bachnumb,
        frttxamt,
        revaljrnentry,
        subtotal,
        creatddt,
        rcptnote_4,
        disavtkn,
        trdpctpr,
        modifdt,
        obtaxamt,
        frtschid,
        rcptnote_3,
        ten99amnt,
        poprctnm,
        vchrnmbr,
        purchase_misc_taxable,
        vendorid,
        ordistkn,
        ptdusrid,
        ormsctax,
        voidstts,
        distknam,
        tax_date,
        purchase_freight_taxable,
        poplnerr,
        withhamt,
        origbackoutfreighttaxamt,
        rcptnote_1,
        mctrxstt,
        refrence,
        rcptnote_7,
        taxinvrecvd,
        bcktxamt,
        prepaymentamount,
        orsubtot,
        dex_row_id,
        vadcdtro,
        frtamnt,
        ratetpid,
        ratecalc,
        poptype,
        exgtblid,
        taxinvreqd,
        ordatkn,
        rcptnote_8,
        aplywith,
        receiptdate,
        originatingprepaymentamt,
        disavamt,
        actlship,
        ten99boxnumber,
        pop_hdr_errors_4,
        origbackoutmisctaxamt,
        shipmthd,
        pophdr2,
        ortaxamt,
        glpostdt,
        trdisamt,
        invoicereceiptdate,
        dscpctam,
        replacegoods,
        or1099am,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
