with source as (

    select * from {{ source('casl_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        mxwofamt,
        vadcd1099,
        faxnumbr,
        phnumbr2,
        pmrtngix,
        workflow_priority,
        declid,
        ptcshacf,
        crtcomdt,
        minpytyp,
        pymntpri,
        pmfrtidx,
        state,
        zipcode,
        address2,
        maxindlr,
        govindid,
        upszone,
        vendshnm,
        creatddt,
        dex_row_id,
        writeoff,
        crlmtdlr,
        post_results_to,
        dex_row_ts,
        userdef2,
        pmapindx,
        trddisct,
        ratetpid,
        taxfilenummode,
        withholdingformtype,
        minorder,
        address1,
        country,
        credtlmt,
        curncyid,
        kgldsths,
        vendname,
        noteindx,
        pmprchix,
        kperhist,
        govcrpid,
        ccode,
        workflow_status,
        purpvidx,
        pmdavidx,
        userlang,
        brthdate,
        chekbkid,
        onepaypervendinv,
        vadcdpad,
        vendstts,
        xpdtoblg,
        sbppsded,
        revalue_vendor,
        shipmthd,
        parvenid,
        city,
        vadcdsfr,
        pmdtkidx,
        vadcdtro,
        docfmtid,
        acnmvndr,
        withholdingentitytype,
        ten99type,
        address3,
        pymtrmid,
        disgrper,
        workflow_approval_status,
        phone3,
        pmwrtidx,
        mxiafvnd,
        taxschid,
        duegrper,
        userdef1,
        laborpmttype,
        taxinvrecvd,
        txrgnnum,
        pmtdscix,
        modifdt,
        pmcshidx,
        cbvat,
        minpypct,
        kptrxhst,
        vndcntct,
        hold,
        ppstaxrt,
        txidnmbr,
        venddba,
        vndclsid,
        kpcalhst,
        crtexpdt,
        pmtaxidx,
        ten99boxnumber,
        vaddcdpr,
        minpydlr,
        freeonboard,
        phnumbr1,
        prspayee,
        acpuridx,
        withholdingtype,
        dxvarnum,
        comment2,
        pmfinidx,
        comment1,
        vndchknm,
        rtobutkn,
        pmmschix,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
