with source as (

    select * from {{ source('casl_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        delete1,
        frtamnt,
        dscdlram,
        mscschid,
        discdate,
        bktslsam,
        agngbukt,
        cbkidchk,
        corrctn,
        ortrxamt,
        cprcstnm,
        eftflag,
        dex_row_ts,
        glpostdt,
        disavamt,
        frtschid,
        bktmscam,
        directdebit,
        curtrxam,
        bktfrtam,
        duedate,
        voiddate,
        pymtrmid,
        cshrctyp,
        bchsourc,
        taxschid,
        bachnumb,
        cbkidcsh,
        ppsamded,
        dscpctam,
        wrofamnt,
        shipmthd,
        trdisamt,
        backouttradedisc,
        gstdsamt,
        postdate,
        slschdid,
        aplywith,
        slprsnid,
        cbkidcrd,
        cashamnt,
        disavtkn,
        docdate,
        lstusred,
        noteindx,
        lstedtdt,
        costamnt,
        cheknmbr,
        saledate,
        electronic,
        ectrx,
        trxsorce,
        discrtnd,
        dex_row_id,
        tax_date,
        pstusrid,
        slsamnt,
        dinvpdof,
        distknam,
        slstercd,
        miscamnt,
        voidstts,
        cspornbr,
        taxamnt,
        trxdscrn,
        comdlram,
        adrscode,
        factoring,
        simplifd,
        curncyid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
