with source as (

    select * from {{ source('casl_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        curtrxam,
        pstgdate,
        bktfrtam,
        vendorid,
        tax_date,
        dex_row_id,
        gstdsamt,
        docprinted,
        ponumber,
        hold,
        pchschid,
        simplifd,
        discdate,
        docdate,
        taxamnt,
        taxschid,
        pordnmbr,
        noteindx,
        prctdisc,
        vadcdtro,
        mdfusrid,
        docamnt,
        distknam,
        ttlpymts,
        chekbkid,
        duedate,
        cntrltyp,
        pgramsbj,
        posteddt,
        dscdlram,
        aplywith,
        frtschid,
        modifdt,
        frtamnt,
        vndchknm,
        ten99type,
        disamtav,
        retnagam,
        mscschid,
        pyenttyp,
        ictrx,
        prchdate,
        curncyid,
        bchsourc,
        cbvat,
        dinvpdof,
        bktpuram,
        workflow_status,
        invoicereceiptdate,
        docnumbr,
        wrofamnt,
        bachnumb,
        ectrx,
        electronic,
        dex_row_ts,
        trdisamt,
        pymtrmid,
        bnkrcamt,
        taxinvreqd,
        backouttradedisc,
        lngdesc,
        discamnt,
        trxdscrn,
        disavtkn,
        ten99amnt,
        cardname,
        voided,
        prchamnt,
        ptdusrid,
        mscchamt,
        shipmthd,
        corrctn,
        ppsamded,
        bktmscam,
        ten99boxnumber,
        un1099am,
        ppstaxrt,
        trxsorce,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
