with source as (

    select * from {{ source('stusa_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        phone2,
        rmovrpymtwrtoffacctidx,
        prclevel,
        rmivacc,
        state,
        shrtname,
        custdisc,
        custpriority,
        dex_row_ts,
        mxwoftyp,
        address2,
        minpypct,
        crcardid,
        crlmtamt,
        kpcalhst,
        creatddt,
        upszone,
        slprsnid,
        curncyid,
        gpsfointegrationid,
        address3,
        ratetpid,
        cbvat,
        bankname,
        bnkbrnch,
        mxwrofam,
        integrationsource,
        taxschid,
        pymtrmid,
        shipmthd,
        crlmtper,
        custclas,
        defcacty,
        cprcstnm,
        crlmttyp,
        city,
        taxexmt2,
        dex_row_id,
        address1,
        kperhist,
        cntcprsn,
        duegrper,
        prstadcd,
        post_results_to,
        fnchatyp,
        crlmtpam,
        stmtcycl,
        shipcomplete,
        prbtadcd,
        finchid,
        kpdsthst,
        userlang,
        stmtname,
        orderfulfilldefault,
        declid,
        country,
        taxexmt1,
        hold,
        frstindt,
        zip,
        fax,
        rmfcgacc,
        rmcosacc,
        modifdt,
        custname,
        userdef1,
        userdef2,
        staddrcd,
        phone3,
        send_email_statements,
        rmcshacc,
        minpytyp,
        integrationid,
        crcrdnum,
        finchdlr,
        minpydlr,
        rmavacc,
        adrscode,
        kptrxhst,
        revalue_customer,
        comment2,
        includeindp,
        inactive,
        rmslsacc,
        disgrper,
        rmtakacc,
        rmsoracc,
        ccrdxpdt,
        chekbkid,
        txrgnnum,
        rmwracc,
        rmaracc,
        govindid,
        balnctyp,
        phone1,
        ccode,
        salsterr,
        govcrpid,
        docfmtid,
        noteindx,
        fnchpcnt,
        comment1,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
