with source as (

    select * from {{ source('stusa_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        frtschid,
        corrctn,
        aplywith,
        taxschid,
        directdebit,
        tax_date,
        lstedtdt,
        dinvpdof,
        docdate,
        dscpctam,
        bktslsam,
        eftflag,
        mscschid,
        cheknmbr,
        cprcstnm,
        simplifd,
        frtamnt,
        curncyid,
        bktmscam,
        voidstts,
        slstercd,
        cbkidchk,
        postdate,
        cashamnt,
        voiddate,
        cspornbr,
        distknam,
        adrscode,
        curtrxam,
        slsamnt,
        ppsamded,
        bachnumb,
        ectrx,
        costamnt,
        comdlram,
        factoring,
        lstusred,
        trxsorce,
        pymtrmid,
        dex_row_ts,
        glpostdt,
        trxdscrn,
        backouttradedisc,
        miscamnt,
        electronic,
        cbkidcrd,
        pstusrid,
        taxamnt,
        disavtkn,
        wrofamnt,
        saledate,
        shipmthd,
        cshrctyp,
        duedate,
        trdisamt,
        dscdlram,
        gstdsamt,
        ortrxamt,
        bktfrtam,
        disavamt,
        slprsnid,
        delete1,
        noteindx,
        discrtnd,
        slschdid,
        cbkidcsh,
        discdate,
        dex_row_id,
        bchsourc,
        agngbukt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
