with source as (

    select * from {{ source('stusa_dbo', 'pop30300') }}

),

renamed as (

    select
        rcptnote_2,
        workflow_status,
        frtschid,
        refrence,
        origbackoutfreighttaxamt,
        time1,
        miscamnt,
        rcptnote_5,
        ppstaxrt,
        rcptnote_8,
        cbvat,
        ptdusrid,
        invoiceexpected,
        discdate,
        pophdr2,
        ten99type,
        aplywith,
        exchdate,
        distknam,
        bachnumb,
        orfrtamt,
        ortaxamt,
        actlship,
        tax_date,
        taxinvreqd,
        pop_hdr_errors_4,
        receiptdate,
        curncyid,
        exgtblid,
        orddlrat,
        taxamnt,
        vchrnmbr,
        glpostdt,
        ordistkn,
        rcptnote_7,
        vadcdtro,
        dscpctam,
        dscdlram,
        total_landed_cost_amount,
        rcptnote_6,
        poplnerr,
        purchase_freight_taxable,
        trxsorce,
        backoutmisctaxamt,
        frtamnt,
        ten99amnt,
        invoicereceiptdate,
        poptype,
        vnddocnm,
        orsubtot,
        creatddt,
        ten99boxnumber,
        originatingprepaymentamt,
        xchgrate,
        ordatkn,
        mscschid,
        shipmthd,
        posteddt,
        revaljrnentry,
        pophdr1,
        pymtrmid,
        disavamt,
        revaltrxsource,
        replacegoods,
        dex_row_id,
        voidstts,
        bsivcttl,
        disavtkn,
        rcptnote_4,
        origbackoutmisctaxamt,
        duedate,
        ratecalc,
        ormiscamt,
        vendname,
        txrgnnum,
        or1099am,
        obtaxamt,
        rcptnote_3,
        subtotal,
        mctrxstt,
        frttxamt,
        trdisamt,
        modifdt,
        trdpctpr,
        taxinvrecvd,
        orfrttax,
        taxschid,
        withhamt,
        msctxamt,
        simplifd,
        backoutfreighttaxamt,
        user2ent,
        denxrate,
        currnidx,
        ratetpid,
        ordavamt,
        ormsctax,
        ortdisam,
        rcptnote_1,
        bchsourc,
        ectrx,
        purchase_misc_taxable,
        prepaymentamount,
        bcktxamt,
        _fivetran_deleted,
        _fivetran_synced,
        upper(trim(poprctnm)) as poprctnm,
        upper(trim(vendorid)) as vendorid

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
