with source as (

    select * from {{ source('stusa_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        cbvat,
        vadcdsfr,
        pymtrmid,
        taxinvrecvd,
        pmdtkidx,
        phnumbr1,
        pmprchix,
        parvenid,
        phone3,
        pmmschix,
        pmfinidx,
        ccode,
        workflow_priority,
        userdef1,
        city,
        pmwrtidx,
        vendname,
        vadcdtro,
        userlang,
        shipmthd,
        minpytyp,
        dex_row_ts,
        acnmvndr,
        ptcshacf,
        chekbkid,
        pmdavidx,
        comment2,
        credtlmt,
        vaddcdpr,
        post_results_to,
        ten99boxnumber,
        pymntpri,
        kpcalhst,
        txrgnnum,
        hold,
        address1,
        pmapindx,
        taxschid,
        crlmtdlr,
        vendstts,
        trddisct,
        state,
        onepaypervendinv,
        kperhist,
        prspayee,
        minorder,
        purpvidx,
        ppstaxrt,
        address3,
        curncyid,
        mxwofamt,
        userdef2,
        ratetpid,
        vndcntct,
        address2,
        crtexpdt,
        vendshnm,
        vndclsid,
        vadcd1099,
        comment1,
        govindid,
        dex_row_id,
        mxiafvnd,
        ten99type,
        vadcdpad,
        dxvarnum,
        pmtdscix,
        minpypct,
        duegrper,
        withholdingentitytype,
        revalue_vendor,
        disgrper,
        rtobutkn,
        modifdt,
        crtcomdt,
        pmrtngix,
        vndchknm,
        minpydlr,
        workflow_approval_status,
        sbppsded,
        withholdingtype,
        creatddt,
        workflow_status,
        faxnumbr,
        withholdingformtype,
        govcrpid,
        upszone,
        taxfilenummode,
        maxindlr,
        pmcshidx,
        pmfrtidx,
        xpdtoblg,
        country,
        phnumbr2,
        declid,
        laborpmttype,
        docfmtid,
        writeoff,
        txidnmbr,
        acpuridx,
        venddba,
        noteindx,
        freeonboard,
        pmtaxidx,
        kgldsths,
        brthdate,
        kptrxhst,
        zipcode,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
