with source as (

    select * from {{ source('stusa_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        bnkrcamt,
        un1099am,
        docprinted,
        ttlpymts,
        chekbkid,
        pordnmbr,
        pchschid,
        dex_row_ts,
        ten99boxnumber,
        trdisamt,
        distknam,
        simplifd,
        ppstaxrt,
        bktfrtam,
        invoicereceiptdate,
        vendorid,
        cntrltyp,
        prchamnt,
        vadcdtro,
        voided,
        tax_date,
        prctdisc,
        shipmthd,
        dinvpdof,
        taxinvreqd,
        disamtav,
        trxsorce,
        ppsamded,
        ptdusrid,
        mscschid,
        discdate,
        modifdt,
        wrofamnt,
        duedate,
        gstdsamt,
        corrctn,
        taxamnt,
        pymtrmid,
        lngdesc,
        frtschid,
        cardname,
        ten99type,
        docdate,
        frtamnt,
        ectrx,
        posteddt,
        electronic,
        ictrx,
        backouttradedisc,
        docamnt,
        pyenttyp,
        discamnt,
        ten99amnt,
        dscdlram,
        disavtkn,
        bktmscam,
        mscchamt,
        cbvat,
        bachnumb,
        trxdscrn,
        pstgdate,
        bchsourc,
        curtrxam,
        prchdate,
        docnumbr,
        workflow_status,
        hold,
        bktpuram,
        ponumber,
        pgramsbj,
        vndchknm,
        taxschid,
        noteindx,
        retnagam,
        dex_row_id,
        mdfusrid,
        curncyid,
        aplywith,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
