with source as (

    select * from {{ source('stusa_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        taxinvreqd,
        disamtav,
        curncyid,
        corrctn,
        dex_row_id,
        shipmthd,
        pstgdate,
        retnagam,
        bachnumb,
        docnumbr,
        docdate,
        bchsourc,
        discdate,
        docamnt,
        bktpuram,
        trxdscrn,
        pymtrmid,
        ten99type,
        duedate,
        cntrltyp,
        modifdt,
        cardname,
        disavtkn,
        bktmscam,
        lngdesc,
        cbvat,
        voidpdate,
        wrofamnt,
        posteddt,
        prchamnt,
        dinvpdof,
        trxsorce,
        un1099am,
        prctdisc,
        ptdusrid,
        pyenttyp,
        trdisamt,
        mscschid,
        electronic,
        ppsamded,
        ectrx,
        backouttradedisc,
        vendorid,
        bktfrtam,
        vndchknm,
        ppstaxrt,
        gstdsamt,
        ponumber,
        taxamnt,
        simplifd,
        mscchamt,
        discamnt,
        ten99amnt,
        tax_date,
        voided,
        pgramsbj,
        pchschid,
        chekbkid,
        noteindx,
        taxschid,
        docprinted,
        ten99boxnumber,
        dex_row_ts,
        ttlpymts,
        aplywith,
        mdfusrid,
        vadcdtro,
        prchdate,
        ictrx,
        invoicereceiptdate,
        frtamnt,
        frtschid,
        curtrxam,
        distknam,
        dscdlram,
        hold,
        workflow_status,
        pordnmbr,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
