with

source as (

    select * from {{ source('stusa_dbo', 'pm10000') }}

),

renamed as (

    select
        bachnumb,
        bchsourc,
        vchnumwk,
        electronic,
        dex_row_id,
        ccrctnum,
        vchrnmbr,
        shipmthd,
        chekbkid,
        pymtrmid,
        printed,
        pmdstmsg,
        cheknmbr,
        camcbkid,
        taxinvreqd,
        modifdt,
        taxamnt,
        bktmscam,
        ictrx,
        vchrncor,
        docdate,
        chekamnt,
        ccampynm,
        ten99type,
        pmwrkms2,
        vadcdtro,
        disamtav,
        pmicmsgs,
        ppsamded,
        trdisamt,
        campynbr,
        ptdusrid,
        corrnxst,
        prchamnt,
        ppstaxrt,
        mscschid,
        bnkrcamt,
        aplywith,
        sourcdoc,
        apdstkam,
        taxschid,
        wrofamnt,
        appldamt,
        crcrdamt,
        retnagam,
        cashamnt,
        icdists,
        ten99boxnumber,
        cardname,
        trxdscrn,
        curtrxam,
        txengcld,
        backouttradedisc,
        dex_row_ts,
        campmtnm,
        gstdsamt,
        camtdate,
        bktfrtam,
        workflow_status,
        mscchamt,
        tax_date,
        curncyid,
        ectrx,
        pstgstus,
        un1099am,
        chamcbid,
        frtamnt,
        chekdate,
        frtschid,
        discdate,
        pmwrkmsg,
        docamnt,
        docprinted,
        distknam,
        cdocnmbr,
        vaddcdpr,
        prctdisc,
        crcarddt,
        pgramsbj,
        prchdate,
        invoicereceiptdate,
        noteindx,
        dscdlram,
        cbvat,
        posted,
        simplifd,
        docnumbr,
        mdfusrid,
        pchschid,
        bktpuram,
        chrgamnt,
        duedate,
        lngdesc,
        vendorid,
        posteddt,
        pordnmbr,
        corrctn,
        ten99amnt,
        pstgdate,
        doctype,
        cntrltyp,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
