with source as (

    select * from {{ source('kcs_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        credtlmt,
        maxindlr,
        kptrxhst,
        post_results_to,
        creatddt,
        ten99boxnumber,
        pmdtkidx,
        taxschid,
        cbvat,
        vaddcdpr,
        chekbkid,
        pmtaxidx,
        trddisct,
        taxinvrecvd,
        address3,
        pmdavidx,
        pmwrtidx,
        vndclsid,
        pmfrtidx,
        minpytyp,
        crtcomdt,
        vendshnm,
        mxwofamt,
        txidnmbr,
        pmcshidx,
        workflow_status,
        venddba,
        vndcntct,
        dex_row_ts,
        pmprchix,
        ratetpid,
        txrgnnum,
        vadcdsfr,
        hold,
        ten99type,
        userdef1,
        vadcdpad,
        mxiafvnd,
        pymtrmid,
        pmapindx,
        govindid,
        kpcalhst,
        ccode,
        phone3,
        workflow_priority,
        docfmtid,
        vendname,
        withholdingentitytype,
        rtobutkn,
        purpvidx,
        city,
        shipmthd,
        writeoff,
        freeonboard,
        laborpmttype,
        brthdate,
        parvenid,
        prspayee,
        vadcdtro,
        pymntpri,
        govcrpid,
        taxfilenummode,
        state,
        noteindx,
        minpydlr,
        withholdingformtype,
        dex_row_id,
        declid,
        vendstts,
        onepaypervendinv,
        kgldsths,
        curncyid,
        duegrper,
        vadcd1099,
        kperhist,
        phnumbr2,
        userlang,
        disgrper,
        country,
        modifdt,
        userdef2,
        pmtdscix,
        ptcshacf,
        pmrtngix,
        workflow_approval_status,
        address1,
        zipcode,
        upszone,
        withholdingtype,
        address2,
        comment1,
        dxvarnum,
        phnumbr1,
        minpypct,
        sbppsded,
        ppstaxrt,
        acnmvndr,
        crtexpdt,
        vndchknm,
        revalue_vendor,
        pmmschix,
        acpuridx,
        crlmtdlr,
        comment2,
        faxnumbr,
        pmfinidx,
        minorder,
        xpdtoblg,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
