with source as (

    select * from {{ source('kcs_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        bankname,
        shipmthd,
        pymtrmid,
        mxwrofam,
        duegrper,
        curncyid,
        rmivacc,
        phone1,
        adrscode,
        disgrper,
        taxexmt2,
        txrgnnum,
        custclas,
        salsterr,
        city,
        comment1,
        govcrpid,
        includeindp,
        govindid,
        finchid,
        userlang,
        rmcshacc,
        cbvat,
        phone2,
        dex_row_ts,
        custdisc,
        kperhist,
        ccrdxpdt,
        custpriority,
        taxexmt1,
        gpsfointegrationid,
        crcardid,
        balnctyp,
        phone3,
        kpcalhst,
        custname,
        dex_row_id,
        upszone,
        fnchpcnt,
        crcrdnum,
        staddrcd,
        rmovrpymtwrtoffacctidx,
        minpytyp,
        minpydlr,
        send_email_statements,
        finchdlr,
        integrationsource,
        ratetpid,
        noteindx,
        comment2,
        kpdsthst,
        crlmtper,
        bnkbrnch,
        crlmtamt,
        cprcstnm,
        minpypct,
        stmtname,
        creatddt,
        declid,
        modifdt,
        docfmtid,
        integrationid,
        chekbkid,
        ccode,
        prclevel,
        revalue_customer,
        prbtadcd,
        rmtakacc,
        country,
        fax,
        orderfulfilldefault,
        cntcprsn,
        rmavacc,
        crlmtpam,
        address1,
        zip,
        prstadcd,
        state,
        shrtname,
        rmaracc,
        frstindt,
        mxwoftyp,
        rmwracc,
        address2,
        defcacty,
        taxschid,
        crlmttyp,
        rmcosacc,
        inactive,
        userdef2,
        rmfcgacc,
        hold,
        post_results_to,
        slprsnid,
        rmslsacc,
        fnchatyp,
        kptrxhst,
        rmsoracc,
        stmtcycl,
        shipcomplete,
        userdef1,
        address3,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
