with source as (

    select * from {{ source('kcs_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        dinvpdof,
        curtrxam,
        ppstaxrt,
        hold,
        vndchknm,
        bktfrtam,
        modifdt,
        taxinvreqd,
        duedate,
        prchamnt,
        pchschid,
        ectrx,
        electronic,
        ictrx,
        pgramsbj,
        pymtrmid,
        backouttradedisc,
        taxschid,
        cntrltyp,
        docdate,
        mdfusrid,
        ten99type,
        un1099am,
        aplywith,
        pordnmbr,
        bktmscam,
        noteindx,
        mscchamt,
        disavtkn,
        prctdisc,
        bachnumb,
        simplifd,
        discamnt,
        ten99amnt,
        frtschid,
        chekbkid,
        vadcdtro,
        pyenttyp,
        posteddt,
        bktpuram,
        mscschid,
        workflow_status,
        voided,
        cbvat,
        retnagam,
        bchsourc,
        shipmthd,
        voidpdate,
        dscdlram,
        discdate,
        distknam,
        disamtav,
        lngdesc,
        trdisamt,
        curncyid,
        ppsamded,
        docprinted,
        invoicereceiptdate,
        frtamnt,
        ten99boxnumber,
        ttlpymts,
        prchdate,
        ponumber,
        tax_date,
        dex_row_ts,
        docnumbr,
        trxsorce,
        wrofamnt,
        ptdusrid,
        gstdsamt,
        corrctn,
        taxamnt,
        pstgdate,
        dex_row_id,
        trxdscrn,
        vendorid,
        cardname,
        docamnt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
