with source as (

    select * from {{ source('kcs_dbo', 'pop10110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        change_order_flag,
        purchsitetxschsrc,
        bsivcttl,
        extdcost,
        costcode,
        contact,
        address1,
        phone3,
        locncode,
        zipcode,
        lineorigin,
        vctnmthd,
        commntid,
        purchase_item_tax_schedu,
        vnditdsc,
        polneary_6,
        invindx,
        reqdate,
        product_indicator,
        state,
        polneary_7,
        landed_cost_group_id,
        umqtyinb,
        odecplcu,
        qtyorder,
        fax,
        decplqty,
        print_phone_numbergb,
        shipmthd,
        currnidx,
        curncyid,
        address2,
        noninven,
        address3,
        qty_canceled_orig,
        polneary_9,
        prmshpdte,
        potype,
        vendorid,
        release,
        plnndspplid,
        itemnmbr,
        itemdesc,
        oruntcst,
        source_document_line_num,
        linenumber,
        adrscode,
        lstrcptdt,
        xchgrate,
        polneary_5,
        po_line_status_orig,
        polneary_8,
        purchase_site_tax_schedu,
        polneary_2,
        cmpnynam,
        itmtrkop,
        backouttradedisctax,
        released_date,
        city,
        ccode,
        unitcost,
        uofm,
        qtycommittedinbaseorig,
        opostsub,
        doctype,
        taxamnt,
        obtaxamt,
        dex_row_id,
        denxrate,
        flags,
        addrsource,
        prmdate,
        releasebydate,
        fstrcptdt,
        freeonboard,
        origprmdate,
        polneary_1,
        projnum,
        polneary_4,
        purchase_iv_item_taxable,
        qtyuncmtbase,
        ratecalc,
        capital_item,
        dex_row_ts,
        reqstdby,
        vnditnum,
        orextcst,
        origbackouttradedisctax,
        qtycance,
        jobnumbr,
        source_document_number,
        bcktxamt,
        polnesta,
        ortaxamt,
        phone1,
        qtycmtbase,
        costtype,
        polneary_3,
        costcatid,
        phone2,
        decplcur,
        country,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
