with source as (

    select * from {{ source('kcs_dbo', 'pop30110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        polneary_1,
        source_document_line_num,
        uofm,
        polneary_4,
        decplqty,
        taxamnt,
        fax,
        projnum,
        addrsource,
        orextcst,
        flags,
        reqstdby,
        release,
        freeonboard,
        odecplcu,
        vendorid,
        prmshpdte,
        dex_row_id,
        itemdesc,
        landed_cost_group_id,
        product_indicator,
        vctnmthd,
        vnditnum,
        obtaxamt,
        address3,
        polneary_9,
        released_date,
        phone2,
        bsivcttl,
        polneary_3,
        country,
        lstrcptdt,
        locncode,
        decplcur,
        zipcode,
        jobnumbr,
        purchsitetxschsrc,
        phone1,
        address2,
        contact,
        costtype,
        state,
        dex_row_ts,
        vnditdsc,
        extdcost,
        phone3,
        polnesta,
        potype,
        linenumber,
        fstrcptdt,
        address1,
        print_phone_numbergb,
        oruntcst,
        releasebydate,
        polneary_5,
        polneary_8,
        origprmdate,
        commntid,
        polneary_2,
        costcode,
        itmtrkop,
        bcktxamt,
        umqtyinb,
        purchase_site_tax_schedu,
        doctype,
        qtycance,
        itemnmbr,
        city,
        noninven,
        source_document_number,
        unitcost,
        purchase_item_tax_schedu,
        costcatid,
        polneary_6,
        ortaxamt,
        cmpnynam,
        currnidx,
        lineorigin,
        purchase_iv_item_taxable,
        qtyorder,
        invindx,
        prmdate,
        shipmthd,
        ccode,
        reqdate,
        polneary_7,
        adrscode,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
