with source as (

    select * from {{ source('kcs_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        ppsamded,
        costamnt,
        corrctn,
        eftflag,
        bachnumb,
        glpostdt,
        dex_row_ts,
        slsamnt,
        comdlram,
        cbkidcsh,
        directdebit,
        aplywith,
        distknam,
        trxsorce,
        cashamnt,
        duedate,
        discrtnd,
        pstusrid,
        lstusred,
        delete1,
        mscschid,
        frtamnt,
        shipmthd,
        cbkidcrd,
        ortrxamt,
        disavtkn,
        miscamnt,
        voidstts,
        bchsourc,
        taxamnt,
        slschdid,
        slprsnid,
        pymtrmid,
        postdate,
        voiddate,
        tax_date,
        lstedtdt,
        factoring,
        frtschid,
        docdate,
        taxschid,
        slstercd,
        electronic,
        ectrx,
        disavamt,
        noteindx,
        saledate,
        dscpctam,
        bktfrtam,
        curtrxam,
        curncyid,
        trdisamt,
        wrofamnt,
        cheknmbr,
        dex_row_id,
        gstdsamt,
        cbkidchk,
        bktmscam,
        cprcstnm,
        cspornbr,
        backouttradedisc,
        dinvpdof,
        simplifd,
        adrscode,
        dscdlram,
        discdate,
        trxdscrn,
        bktslsam,
        cshrctyp,
        agngbukt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
