with source as (

    select * from {{ source('kcs_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        docamnt,
        aplywith,
        ten99type,
        lngdesc,
        frtamnt,
        frtschid,
        docprinted,
        simplifd,
        posteddt,
        cardname,
        trxdscrn,
        pyenttyp,
        ponumber,
        noteindx,
        bachnumb,
        docdate,
        pstgdate,
        taxamnt,
        gstdsamt,
        retnagam,
        discdate,
        curncyid,
        prctdisc,
        mscchamt,
        duedate,
        bktpuram,
        ppsamded,
        dinvpdof,
        bchsourc,
        backouttradedisc,
        bktmscam,
        discamnt,
        ten99amnt,
        disamtav,
        disavtkn,
        tax_date,
        prchamnt,
        taxschid,
        modifdt,
        vndchknm,
        cbvat,
        ttlpymts,
        ectrx,
        vadcdtro,
        chekbkid,
        pymtrmid,
        bnkrcamt,
        ten99boxnumber,
        un1099am,
        mdfusrid,
        invoicereceiptdate,
        pordnmbr,
        electronic,
        trdisamt,
        taxinvreqd,
        docnumbr,
        prchdate,
        ppstaxrt,
        dex_row_ts,
        pchschid,
        cntrltyp,
        wrofamnt,
        vendorid,
        voided,
        curtrxam,
        mscschid,
        corrctn,
        workflow_status,
        hold,
        pgramsbj,
        dex_row_id,
        distknam,
        dscdlram,
        ictrx,
        bktfrtam,
        shipmthd,
        ptdusrid,
        trxsorce,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
