with source as (

    select * from {{ source('kcs_dbo', 'pop30300') }}

),

renamed as (

    select
        orfrtamt,
        invoicereceiptdate,
        trdpctpr,
        bachnumb,
        msctxamt,
        vnddocnm,
        receiptdate,
        pophdr2,
        user2ent,
        obtaxamt,
        rcptnote_6,
        ormiscamt,
        rcptnote_3,
        invoiceexpected,
        backoutmisctaxamt,
        taxschid,
        curncyid,
        orddlrat,
        tax_date,
        bchsourc,
        cbvat,
        pop_hdr_errors_4,
        backoutfreighttaxamt,
        mctrxstt,
        trdisamt,
        taxinvreqd,
        workflow_status,
        voidstts,
        pophdr1,
        origbackoutmisctaxamt,
        prepaymentamount,
        aplywith,
        bcktxamt,
        currnidx,
        ortdisam,
        ordavamt,
        disavamt,
        orfrttax,
        modifdt,
        withhamt,
        denxrate,
        purchase_misc_taxable,
        dex_row_id,
        creatddt,
        shipmthd,
        frtamnt,
        revaljrnentry,
        distknam,
        ortaxamt,
        actlship,
        or1099am,
        orsubtot,
        ectrx,
        exgtblid,
        ten99amnt,
        subtotal,
        exchdate,
        ptdusrid,
        time1,
        ormsctax,
        ratetpid,
        vchrnmbr,
        disavtkn,
        ratecalc,
        rcptnote_7,
        rcptnote_1,
        ordistkn,
        mscschid,
        duedate,
        vadcdtro,
        ten99type,
        discdate,
        rcptnote_8,
        replacegoods,
        ppstaxrt,
        originatingprepaymentamt,
        rcptnote_5,
        rcptnote_2,
        frtschid,
        pymtrmid,
        xchgrate,
        taxinvrecvd,
        origbackoutfreighttaxamt,
        trxsorce,
        ordatkn,
        dscdlram,
        refrence,
        poplnerr,
        posteddt,
        revaltrxsource,
        frttxamt,
        miscamnt,
        simplifd,
        dscpctam,
        rcptnote_4,
        bsivcttl,
        total_landed_cost_amount,
        glpostdt,
        purchase_freight_taxable,
        vendname,
        txrgnnum,
        taxamnt,
        ten99boxnumber,
        poptype,
        _fivetran_deleted,
        _fivetran_synced,
        upper(trim(poprctnm)) as poprctnm,
        upper(trim(vendorid)) as vendorid

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
