with source as (

    select * from {{ source('grn_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        backouttradedisc,
        bktmscam,
        duedate,
        discamnt,
        ten99amnt,
        noteindx,
        vndchknm,
        modifdt,
        disavtkn,
        vendorid,
        ictrx,
        taxinvreqd,
        pchschid,
        cntrltyp,
        docamnt,
        ptdusrid,
        trxsorce,
        corrctn,
        taxamnt,
        mdfusrid,
        gstdsamt,
        ten99boxnumber,
        pyenttyp,
        aplywith,
        dscdlram,
        trxdscrn,
        bktfrtam,
        docprinted,
        dex_row_id,
        ponumber,
        ttlpymts,
        dinvpdof,
        docdate,
        docnumbr,
        cardname,
        frtamnt,
        curtrxam,
        posteddt,
        hold,
        prctdisc,
        mscschid,
        voidpdate,
        voided,
        discdate,
        bktpuram,
        ppsamded,
        simplifd,
        cbvat,
        dex_row_ts,
        trdisamt,
        distknam,
        ten99type,
        shipmthd,
        bchsourc,
        ppstaxrt,
        curncyid,
        lngdesc,
        wrofamnt,
        retnagam,
        taxschid,
        pymtrmid,
        disamtav,
        pgramsbj,
        chekbkid,
        prchdate,
        tax_date,
        pordnmbr,
        frtschid,
        invoicereceiptdate,
        un1099am,
        mscchamt,
        workflow_status,
        prchamnt,
        vadcdtro,
        ectrx,
        bachnumb,
        electronic,
        pstgdate,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
