with

source as (

    select * from {{ source('erequester_dbo', 'requisition') }}

),

renamed as (

    select
        requisitionid,
        qtyovertolerance,
        state,
        postheadernotes,
        city,
        justification,
        contactemail,
        notifyuponnonapproval,
        paidbycreditcard,
        invoicenumber,
        phone1,
        emreimbursetouserid,
        billtolocationid,
        locationid,
        freight,
        shippingccemails,
        importtypeid,
        datesubmitted,
        notifyuponapproval,
        contractnumber,
        address1,
        address4,
        userpo,
        originaluserid,
        budgeted,
        accountingsysteminvoicekey,
        contactfax,
        levelid,
        deleted,
        changeorderpoid,
        popostedby,
        userid,
        locationname,
        noreceiptnotify,
        proxynotified,
        notifyoncreatepo,
        overbudget,
        shipmethodid,
        ponumber,
        dateapproved,
        targetcompany,
        popostdate,
        billtolocationname,
        phone2,
        deptid,
        projectid,
        invoicedate,
        address2,
        approvallocation,
        canpostpostatus,
        expensereport,
        notifyproxyapprover,
        templatetypeid,
        poid,
        contractreminddate,
        pocanceldate,
        userrq,
        notes,
        contractexpiredate,
        pototalcostovertolerance,
        noticecontractexpdate,
        memo,
        preapprovalrequest,
        accountingsysteminvoicepostedby,
        batchid,
        requisitiontypeid,
        capitalprojectid,
        contactphone,
        resubmitstatusid,
        commentkey,
        receiptid,
        statusid,
        companyid,
        discountrateid,
        lastnonapprovenote,
        matchreceiptid,
        lastnonreceiptnote,
        fob,
        routingseqid,
        contactname,
        purchasereason,
        changeorderponumber,
        matchpoid,
        costovertolerance,
        address3,
        receivewhenposted,
        taxinclusive,
        poformid,
        retentionpercent,
        zip,
        assignedtobuyerid,
        title,
        daterequested,
        shippingcomments,
        requesttypeid,
        country,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
