with source as (

    select * from {{ source('erequester_dbo', 'Requisitionline') }}

),

renamed as (

    select
        requisitionlineid,
        classid,
        shippingcost,
        tolocationid,
        currencyid,
        assetid,
        taxrate,
        userdef2,
        taxschedule,
        shipdate,
        inventoryapplydate,
        customerid,
        orgid,
        currencykey,
        quantity,
        originalreqlineid,
        percentoverappramnt,
        accntreferenceid,
        uom,
        requisitionid,
        originalapprovedprice,
        notes,
        misctype,
        projectoverbudget,
        projectdivisionid,
        allocatefreight,
        procurementcategoryid,
        ponotes,
        price,
        taxable,
        overbudget,
        projecttype,
        locationid,
        statusid,
        glaccountid,
        intercompanyid,
        convertedtax,
        nondefaultvendorclassid,
        polineid,
        nonpostproject,
        poid,
        paymenttermsid,
        emtodate,
        vendoraddressid,
        emprovidername,
        usetax,
        originalapprovedqty,
        linetypeid,
        taxkey,
        binid,
        expecteddate2,
        purchasetype,
        uomconversion,
        rejected,
        warehouse,
        convertedcost,
        aliasitemid,
        emfromlocation,
        userdef3,
        targetcompany,
        vendorid,
        bpoparentrequisitionlineid,
        expecteddate1,
        changeorderpolineinfo,
        emtolocation,
        tobinid,
        origprice,
        taxamount,
        taxclass,
        shipmethodid,
        emexpensesubtypeid,
        projectunit,
        commoditycode,
        emother,
        classname,
        projectnumber,
        customername,
        projectdescription,
        deleted,
        altglaccountid,
        glaccountdesc,
        vendorname,
        empurchasedate,
        vendoritemid,
        vendorclassid,
        itemconversion,
        manufactureitemid,
        empaymenttype,
        itemid,
        projectmanageracctid,
        companyid,
        emclient,
        maspolinekey,
        emexpensetypeid,
        eminvoicenumber,
        imported,
        analyticsoverbudget,
        description,
        commentid,
        emfromdate,
        batchid,
        taxinclusive,
        altglaccountdesc,
        uomid,
        exchangerate,
        userdef1,
        postitemnotes,
        projectline,
        unlisted,
        percentoverbudget,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
