with source as (

    select * from {{ source('calp_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        minpytyp,
        pmfinidx,
        pmmschix,
        faxnumbr,
        pmwrtidx,
        vadcd1099,
        ten99boxnumber,
        mxwofamt,
        govindid,
        pmtaxidx,
        pmprchix,
        dxvarnum,
        workflow_priority,
        freeonboard,
        modifdt,
        declid,
        pmcshidx,
        post_results_to,
        comment1,
        kperhist,
        vndchknm,
        vadcdpad,
        kpcalhst,
        vndclsid,
        pmfrtidx,
        pmdavidx,
        ratetpid,
        ppstaxrt,
        vendname,
        vendshnm,
        crtexpdt,
        purpvidx,
        dex_row_ts,
        pymntpri,
        vaddcdpr,
        ten99type,
        taxschid,
        vndcntct,
        prspayee,
        userdef2,
        minorder,
        address2,
        state,
        withholdingentitytype,
        rtobutkn,
        userdef1,
        txrgnnum,
        curncyid,
        address1,
        pmdtkidx,
        crlmtdlr,
        withholdingtype,
        onepaypervendinv,
        vendstts,
        docfmtid,
        duegrper,
        cbvat,
        minpypct,
        phone3,
        city,
        address3,
        creatddt,
        workflow_approval_status,
        kptrxhst,
        pmrtngix,
        disgrper,
        acnmvndr,
        withholdingformtype,
        pymtrmid,
        taxinvrecvd,
        chekbkid,
        comment2,
        brthdate,
        mxiafvnd,
        vadcdsfr,
        ccode,
        pmtdscix,
        parvenid,
        dex_row_id,
        shipmthd,
        vadcdtro,
        hold,
        pmapindx,
        writeoff,
        laborpmttype,
        maxindlr,
        userlang,
        upszone,
        noteindx,
        venddba,
        ptcshacf,
        country,
        kgldsths,
        minpydlr,
        acpuridx,
        govcrpid,
        xpdtoblg,
        trddisct,
        sbppsded,
        zipcode,
        phnumbr1,
        credtlmt,
        taxfilenummode,
        revalue_vendor,
        workflow_status,
        phnumbr2,
        crtcomdt,
        txidnmbr,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
