with source as (

    select * from {{ source('calp_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        rmwracc,
        declid,
        fnchpcnt,
        creatddt,
        disgrper,
        send_email_statements,
        rmovrpymtwrtoffacctidx,
        crlmtpam,
        crlmttyp,
        custdisc,
        prstadcd,
        kpdsthst,
        staddrcd,
        fnchatyp,
        mxwoftyp,
        phone3,
        prbtadcd,
        address3,
        userdef1,
        ccrdxpdt,
        crcrdnum,
        revalue_customer,
        duegrper,
        custname,
        bnkbrnch,
        mxwrofam,
        taxschid,
        cbvat,
        cprcstnm,
        rmcshacc,
        address1,
        custpriority,
        cntcprsn,
        taxexmt1,
        kpcalhst,
        minpytyp,
        kperhist,
        bankname,
        ratetpid,
        shipmthd,
        city,
        taxexmt2,
        finchid,
        custclas,
        minpypct,
        rmcosacc,
        address2,
        balnctyp,
        defcacty,
        govindid,
        salsterr,
        gpsfointegrationid,
        shrtname,
        crcardid,
        dex_row_id,
        curncyid,
        state,
        integrationsource,
        crlmtamt,
        frstindt,
        pymtrmid,
        slprsnid,
        stmtcycl,
        phone2,
        prclevel,
        post_results_to,
        includeindp,
        upszone,
        orderfulfilldefault,
        comment2,
        ccode,
        govcrpid,
        phone1,
        userdef2,
        rmaracc,
        kptrxhst,
        minpydlr,
        userlang,
        rmavacc,
        modifdt,
        noteindx,
        country,
        fax,
        crlmtper,
        rmtakacc,
        rmsoracc,
        adrscode,
        zip,
        docfmtid,
        chekbkid,
        comment1,
        integrationid,
        rmslsacc,
        inactive,
        shipcomplete,
        stmtname,
        txrgnnum,
        dex_row_ts,
        rmivacc,
        rmfcgacc,
        finchdlr,
        hold,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
