with

source as (

    select * from {{ source('tfci_dbo', 'pop30110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        dex_row_id,
        uofm,
        address2,
        currnidx,
        purchsitetxschsrc,
        fax,
        country,
        product_indicator,
        phone2,
        costtype,
        odecplcu,
        addrsource,
        projnum,
        released_date,
        vendorid,
        print_phone_numbergb,
        reqstdby,
        potype,
        fstrcptdt,
        itemnmbr,
        purchase_item_tax_schedu,
        costcatid,
        extdcost,
        polneary_1,
        source_document_line_num,
        bcktxamt,
        polnesta,
        shipmthd,
        polneary_7,
        oruntcst,
        prmshpdte,
        cmpnynam,
        linenumber,
        polneary_2,
        adrscode,
        ccode,
        polneary_8,
        source_document_number,
        city,
        qtyorder,
        polneary_6,
        contact,
        state,
        purchase_site_tax_schedu,
        phone3,
        polneary_3,
        lstrcptdt,
        release,
        decplcur,
        obtaxamt,
        commntid,
        polneary_9,
        qtycance,
        umqtyinb,
        doctype,
        vnditdsc,
        invindx,
        itmtrkop,
        bsivcttl,
        unitcost,
        ortaxamt,
        address3,
        vctnmthd,
        dex_row_ts,
        freeonboard,
        releasebydate,
        origprmdate,
        costcode,
        polneary_4,
        prmdate,
        flags,
        jobnumbr,
        landed_cost_group_id,
        address1,
        zipcode,
        polneary_5,
        lineorigin,
        noninven,
        decplqty,
        reqdate,
        taxamnt,
        phone1,
        itemdesc,
        vnditnum,
        locncode,
        purchase_iv_item_taxable,
        orextcst,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
