with source as (

    select * from {{ source('tfci_dbo', 'iv00101') }}

),

renamed as (

    select
        itemnmbr,
        uscatvls_5,
        ktacctsr,
        revalue_inventory,
        uscatvls_2,
        kptrxhst,
        dex_row_ts,
        decplqty,
        ivvaridx,
        userid,
        purmcidx,
        kpcalhst,
        itmplnnngtyp,
        qtyovertolerancepercent,
        itemtype,
        asmvridx,
        minshelf2,
        altitem2,
        cgsmcidx,
        ivretidx,
        locncode,
        purchase_tax_options,
        pricegroup,
        itmgedsc,
        ivslsidx,
        lastgensn,
        ivinfidx,
        abccode,
        itemshwt,
        useqtyoveragetolerance,
        ivinusix,
        lotexpwarndays,
        ivinsvix,
        inactive,
        uscatvls_1,
        ivcogsix,
        cgsinflx,
        lottype,
        minshelf1,
        alwbkord,
        itmshnam,
        ivdmgidx,
        vctnmthd,
        itemcode,
        cntryorgn,
        noteindx,
        kpdsthst,
        modifdt,
        itemdesc,
        ivslrnix,
        tcc,
        ivivofix,
        wrntydys,
        uscatvls_6,
        itmtrkop,
        includeindp,
        ivivindx,
        lotexpwarn,
        dex_row_id,
        ivsldsix,
        lot_split_quantity,
        ivscrvix,
        uscatvls_3,
        sttstclvlprcntg,
        pinflidx,
        purchase_item_tax_schedu,
        stndcost,
        uomschdl,
        lastgenlot,
        purpvidx,
        kperhist,
        itmclscd,
        uscatvls_4,
        mstrcdty,
        qtyshorttolerancepercent,
        dpshpidx,
        taxoptns,
        selnguom,
        uppvidx,
        creatddt,
        tolerance_percentage,
        itmtshid,
        decplcur,
        useqtyshortagetolerance,
        currcost,
        altitem1,
        prclevel,
        pricmthd,
        prchsuom,
        invmcidx,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
