with source as (

    select * from {{ source('nni_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        pmfrtidx,
        crtexpdt,
        rtobutkn,
        purpvidx,
        pmdavidx,
        modifdt,
        govindid,
        kgldsths,
        acpuridx,
        address2,
        faxnumbr,
        mxiafvnd,
        vadcdpad,
        ten99type,
        comment1,
        kperhist,
        maxindlr,
        phnumbr2,
        minpypct,
        prspayee,
        freeonboard,
        crlmtdlr,
        ppstaxrt,
        duegrper,
        mxwofamt,
        dxvarnum,
        pmapindx,
        pmrtngix,
        laborpmttype,
        upszone,
        venddba,
        post_results_to,
        withholdingtype,
        pmprchix,
        crtcomdt,
        minpytyp,
        ten99boxnumber,
        pmwrtidx,
        minorder,
        txidnmbr,
        declid,
        workflow_approval_status,
        shipmthd,
        ccode,
        zipcode,
        pmdtkidx,
        withholdingentitytype,
        country,
        govcrpid,
        kptrxhst,
        docfmtid,
        ptcshacf,
        pymtrmid,
        phone3,
        userdef1,
        kpcalhst,
        vadcdsfr,
        dex_row_ts,
        workflow_priority,
        creatddt,
        parvenid,
        brthdate,
        vendname,
        vadcdtro,
        noteindx,
        city,
        sbppsded,
        xpdtoblg,
        dex_row_id,
        comment2,
        phnumbr1,
        pmcshidx,
        revalue_vendor,
        acnmvndr,
        chekbkid,
        writeoff,
        pmtdscix,
        pmmschix,
        vaddcdpr,
        vendstts,
        state,
        vndclsid,
        onepaypervendinv,
        pmtaxidx,
        withholdingformtype,
        taxschid,
        curncyid,
        credtlmt,
        taxfilenummode,
        disgrper,
        vndchknm,
        address1,
        userdef2,
        ratetpid,
        vndcntct,
        txrgnnum,
        hold,
        address3,
        taxinvrecvd,
        trddisct,
        workflow_status,
        vadcd1099,
        vendshnm,
        minpydlr,
        pymntpri,
        userlang,
        cbvat,
        pmfinidx,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
