with source as (

    select * from {{ source('nni_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        aplywith,
        un1099am,
        curncyid,
        shipmthd,
        invoicereceiptdate,
        bchsourc,
        docnumbr,
        pyenttyp,
        mscschid,
        docprinted,
        workflow_status,
        ttlpymts,
        voidpdate,
        wrofamnt,
        ten99type,
        bachnumb,
        bktpuram,
        voided,
        vadcdtro,
        cardname,
        lngdesc,
        trxdscrn,
        dinvpdof,
        pchschid,
        retnagam,
        bktfrtam,
        distknam,
        pymtrmid,
        taxinvreqd,
        curtrxam,
        dscdlram,
        docdate,
        frtamnt,
        docamnt,
        posteddt,
        ectrx,
        electronic,
        trxsorce,
        ptdusrid,
        ponumber,
        pgramsbj,
        noteindx,
        pstgdate,
        corrctn,
        ten99boxnumber,
        modifdt,
        disavtkn,
        discamnt,
        ten99amnt,
        prchdate,
        cntrltyp,
        taxamnt,
        vendorid,
        ppstaxrt,
        cbvat,
        frtschid,
        chekbkid,
        gstdsamt,
        prctdisc,
        simplifd,
        pordnmbr,
        mscchamt,
        ictrx,
        bktmscam,
        vndchknm,
        backouttradedisc,
        taxschid,
        duedate,
        prchamnt,
        mdfusrid,
        trdisamt,
        hold,
        tax_date,
        dex_row_ts,
        dex_row_id,
        ppsamded,
        discdate,
        disamtav,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
