with

source as (

    select {{ convert_columns('nni_dbo', 'pop10110') }}
    from {{ source('nni_dbo', 'pop10110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        vnditnum,
        bcktxamt,
        polnesta,
        noninven,
        odecplcu,
        fstrcptdt,
        potype,
        prmdate,
        releasebydate,
        projnum,
        address3,
        phone2,
        curncyid,
        orextcst,
        polneary_4,
        vnditdsc,
        costcatid,
        uofm,
        release,
        invindx,
        city,
        qtycmtbase,
        qty_canceled_orig,
        cmpnynam,
        opostsub,
        address1,
        released_date,
        prmshpdte,
        qtycommittedinbaseorig,
        ortaxamt,
        itemnmbr,
        product_indicator,
        freeonboard,
        polneary_3,
        change_order_flag,
        purchsitetxschsrc,
        lineorigin,
        linenumber,
        state,
        po_line_status_orig,
        vendorid,
        origbackouttradedisctax,
        polneary_1,
        costcode,
        xchgrate,
        decplqty,
        address2,
        capital_item,
        itemdesc,
        purchase_item_tax_schedu,
        purchase_site_tax_schedu,
        polneary_2,
        print_phone_numbergb,
        shipmthd,
        country,
        currnidx,
        landed_cost_group_id,
        flags,
        purchase_iv_item_taxable,
        ratecalc,
        denxrate,
        fax,
        decplcur,
        qtycance,
        qtyuncmtbase,
        qtyorder,
        ccode,
        itmtrkop,
        dex_row_ts,
        plnndspplid,
        phone3,
        source_document_line_num,
        dex_row_id,
        polneary_5,
        unitcost,
        taxamnt,
        polneary_9,
        polneary_6,
        adrscode,
        umqtyinb,
        vctnmthd,
        origprmdate,
        reqdate,
        doctype,
        costtype,
        zipcode,
        source_document_number,
        oruntcst,
        bsivcttl,
        backouttradedisctax,
        polneary_7,
        phone1,
        obtaxamt,
        extdcost,
        contact,
        commntid,
        lstrcptdt,
        polneary_8,
        jobnumbr,
        addrsource,
        locncode,
        reqstdby,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
