with source as (

    select * from {{ source('nni_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        mscchamt,
        gstdsamt,
        pchschid,
        cntrltyp,
        dinvpdof,
        discamnt,
        ten99amnt,
        taxamnt,
        curtrxam,
        voided,
        vadcdtro,
        cbvat,
        backouttradedisc,
        mdfusrid,
        prctdisc,
        pordnmbr,
        chekbkid,
        taxschid,
        vndchknm,
        bktmscam,
        disavtkn,
        duedate,
        modifdt,
        bktfrtam,
        workflow_status,
        ptdusrid,
        trxsorce,
        electronic,
        pgramsbj,
        shipmthd,
        ectrx,
        posteddt,
        frtamnt,
        docdate,
        dscdlram,
        pymtrmid,
        taxinvreqd,
        ictrx,
        ten99type,
        corrctn,
        noteindx,
        retnagam,
        ppsamded,
        bktpuram,
        bachnumb,
        frtschid,
        lngdesc,
        cardname,
        distknam,
        discdate,
        dex_row_id,
        disamtav,
        trxdscrn,
        hold,
        simplifd,
        mscschid,
        tax_date,
        docprinted,
        ttlpymts,
        pyenttyp,
        docnumbr,
        ppstaxrt,
        prchamnt,
        invoicereceiptdate,
        aplywith,
        docamnt,
        un1099am,
        bchsourc,
        vendorid,
        curncyid,
        trdisamt,
        dex_row_ts,
        prchdate,
        ten99boxnumber,
        wrofamnt,
        bnkrcamt,
        ponumber,
        pstgdate,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
