with source as (

    select * from {{ source('nni_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        ortrxamt,
        wrofamnt,
        dscpctam,
        dex_row_id,
        trdisamt,
        taxschid,
        gstdsamt,
        frtschid,
        mscschid,
        backouttradedisc,
        bktmscam,
        frtamnt,
        bktslsam,
        dscdlram,
        miscamnt,
        taxamnt,
        curncyid,
        slprsnid,
        cspornbr,
        directdebit,
        bktfrtam,
        shipmthd,
        factoring,
        cprcstnm,
        docdate,
        discrtnd,
        agngbukt,
        postdate,
        slstercd,
        tax_date,
        cbkidchk,
        ppsamded,
        simplifd,
        disavamt,
        cheknmbr,
        noteindx,
        trxsorce,
        lstusred,
        voidstts,
        bachnumb,
        duedate,
        delete1,
        adrscode,
        cshrctyp,
        slschdid,
        voiddate,
        cbkidcrd,
        corrctn,
        disavtkn,
        discdate,
        eftflag,
        trxdscrn,
        pymtrmid,
        electronic,
        ectrx,
        lstedtdt,
        glpostdt,
        costamnt,
        comdlram,
        bchsourc,
        slsamnt,
        dex_row_ts,
        pstusrid,
        dinvpdof,
        cbkidcsh,
        aplywith,
        curtrxam,
        saledate,
        cashamnt,
        distknam,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
