with source as (

    select * from {{ source('nni_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        stmtname,
        prstadcd,
        userlang,
        prbtadcd,
        ccrdxpdt,
        modifdt,
        finchid,
        country,
        userdef1,
        declid,
        mxwrofam,
        city,
        phone3,
        fax,
        hold,
        zip,
        stmtcycl,
        creatddt,
        frstindt,
        crlmtpam,
        taxexmt1,
        send_email_statements,
        orderfulfilldefault,
        integrationid,
        fnchpcnt,
        staddrcd,
        govcrpid,
        shipcomplete,
        crcrdnum,
        balnctyp,
        ccode,
        custname,
        upszone,
        comment1,
        docfmtid,
        chekbkid,
        revalue_customer,
        custpriority,
        includeindp,
        minpytyp,
        rmovrpymtwrtoffacctidx,
        minpypct,
        dex_row_id,
        phone1,
        comment2,
        dex_row_ts,
        state,
        rmaracc,
        inactive,
        phone2,
        salsterr,
        crlmtamt,
        finchdlr,
        txrgnnum,
        taxexmt2,
        rmcshacc,
        minpydlr,
        prclevel,
        govindid,
        custdisc,
        curncyid,
        post_results_to,
        custclas,
        slprsnid,
        fnchatyp,
        mxwoftyp,
        crcardid,
        gpsfointegrationid,
        kptrxhst,
        adrscode,
        kpcalhst,
        noteindx,
        integrationsource,
        shrtname,
        rmcosacc,
        duegrper,
        rmwracc,
        bnkbrnch,
        userdef2,
        bankname,
        disgrper,
        shipmthd,
        rmivacc,
        rmfcgacc,
        ratetpid,
        kperhist,
        crlmttyp,
        defcacty,
        address3,
        rmtakacc,
        address1,
        cprcstnm,
        kpdsthst,
        cntcprsn,
        crlmtper,
        rmavacc,
        pymtrmid,
        address2,
        taxschid,
        rmsoracc,
        cbvat,
        rmslsacc,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
