with

source as (

    select * from {{ source('nni_dbo', 'pm10000') }}

),

renamed as (

    select
        retnagam,
        curncyid,
        pmwrkmsg,
        frtschid,
        chamcbid,
        crcarddt,
        bnkrcamt,
        pstgstus,
        dex_row_ts,
        noteindx,
        prchamnt,
        cdocnmbr,
        doctype,
        camtdate,
        bchsourc,
        trdisamt,
        backouttradedisc,
        workflow_status,
        gstdsamt,
        docprinted,
        vadcdtro,
        posteddt,
        pmicmsgs,
        discdate,
        crcrdamt,
        chekdate,
        bktfrtam,
        chrgamnt,
        pgramsbj,
        dscdlram,
        vendorid,
        frtamnt,
        pchschid,
        corrctn,
        pstgdate,
        mdfusrid,
        taxinvreqd,
        tax_date,
        electronic,
        pmwrkms2,
        vchnumwk,
        pordnmbr,
        ten99type,
        ppsamded,
        posted,
        simplifd,
        chekbkid,
        vchrnmbr,
        duedate,
        curtrxam,
        ccrctnum,
        chekamnt,
        invoicereceiptdate,
        docdate,
        cheknmbr,
        shipmthd,
        pymtrmid,
        aplywith,
        taxamnt,
        bktmscam,
        cbvat,
        prchdate,
        apdstkam,
        ten99boxnumber,
        lngdesc,
        mscschid,
        cntrltyp,
        ten99amnt,
        ictrx,
        vchrncor,
        docnumbr,
        ccampynm,
        bktpuram,
        vaddcdpr,
        bachnumb,
        campynbr,
        wrofamnt,
        pmdstmsg,
        mscchamt,
        printed,
        prctdisc,
        icdists,
        un1099am,
        cashamnt,
        appldamt,
        sourcdoc,
        ppstaxrt,
        dex_row_id,
        distknam,
        campmtnm,
        txengcld,
        ectrx,
        modifdt,
        corrnxst,
        trxdscrn,
        docamnt,
        camcbkid,
        disamtav,
        ptdusrid,
        cardname,
        taxschid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
