with

source as (

    select {{ convert_columns('nni_dbo', 'pop30110') }}
    from {{ source('nni_dbo', 'pop30110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        unitcost,
        prmshpdte,
        adrscode,
        qtycance,
        address1,
        ortaxamt,
        polneary_9,
        vnditdsc,
        polneary_6,
        qtyorder,
        polneary_3,
        itmtrkop,
        vctnmthd,
        reqdate,
        contact,
        vnditnum,
        phone1,
        doctype,
        zipcode,
        lstrcptdt,
        shipmthd,
        dex_row_ts,
        print_phone_numbergb,
        ccode,
        polneary_7,
        purchase_iv_item_taxable,
        polneary_1,
        extdcost,
        origprmdate,
        fstrcptdt,
        noninven,
        decplqty,
        commntid,
        umqtyinb,
        polneary_8,
        oruntcst,
        bcktxamt,
        polneary_2,
        lineorigin,
        reqstdby,
        state,
        vendorid,
        dex_row_id,
        flags,
        projnum,
        phone2,
        released_date,
        country,
        odecplcu,
        fax,
        addrsource,
        uofm,
        jobnumbr,
        address2,
        bsivcttl,
        source_document_line_num,
        source_document_number,
        prmdate,
        currnidx,
        itemdesc,
        locncode,
        city,
        release,
        cmpnynam,
        freeonboard,
        decplcur,
        address3,
        purchsitetxschsrc,
        polneary_4,
        purchase_item_tax_schedu,
        costcatid,
        itemnmbr,
        landed_cost_group_id,
        product_indicator,
        releasebydate,
        costtype,
        purchase_site_tax_schedu,
        phone3,
        invindx,
        orextcst,
        polnesta,
        linenumber,
        polneary_5,
        taxamnt,
        obtaxamt,
        potype,
        costcode,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
