with source as (

    select * from {{ source('cai_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        bachnumb,
        ttlpymts,
        tax_date,
        bnkrcamt,
        lngdesc,
        un1099am,
        prchamnt,
        cardname,
        workflow_status,
        discdate,
        trxdscrn,
        cntrltyp,
        dex_row_id,
        bktfrtam,
        frtschid,
        docdate,
        shipmthd,
        mscschid,
        pstgdate,
        taxinvreqd,
        prctdisc,
        electronic,
        ectrx,
        hold,
        pyenttyp,
        bktpuram,
        dex_row_ts,
        cbvat,
        curtrxam,
        duedate,
        posteddt,
        pymtrmid,
        vadcdtro,
        noteindx,
        retnagam,
        ten99boxnumber,
        distknam,
        ppstaxrt,
        modifdt,
        prchdate,
        vndchknm,
        docamnt,
        pchschid,
        dscdlram,
        dinvpdof,
        frtamnt,
        aplywith,
        vendorid,
        chekbkid,
        pordnmbr,
        docprinted,
        mdfusrid,
        invoicereceiptdate,
        discamnt,
        ptdusrid,
        disavtkn,
        taxschid,
        trxsorce,
        simplifd,
        ten99amnt,
        ponumber,
        ppsamded,
        mscchamt,
        wrofamnt,
        bchsourc,
        bktmscam,
        gstdsamt,
        corrctn,
        curncyid,
        taxamnt,
        voided,
        disamtav,
        pgramsbj,
        trdisamt,
        backouttradedisc,
        ictrx,
        ten99type,
        docnumbr,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
