with

source as (

    select {{ convert_columns('cai_dbo', 'pop30110') }}
    from {{ source('cai_dbo', 'pop30110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        country,
        jobnumbr,
        extdcost,
        phone2,
        vctnmthd,
        released_date,
        itmtrkop,
        umqtyinb,
        itemnmbr,
        uofm,
        fax,
        dex_row_id,
        itemdesc,
        landed_cost_group_id,
        city,
        polneary_3,
        source_document_number,
        polneary_6,
        polneary_9,
        freeonboard,
        bsivcttl,
        address2,
        locncode,
        doctype,
        purchsitetxschsrc,
        shipmthd,
        polneary_2,
        bcktxamt,
        costtype,
        qtycance,
        prmshpdte,
        oruntcst,
        state,
        polnesta,
        qtyorder,
        decplcur,
        commntid,
        release,
        polneary_8,
        potype,
        reqstdby,
        linenumber,
        polneary_7,
        lstrcptdt,
        odecplcu,
        releasebydate,
        address1,
        origprmdate,
        noninven,
        product_indicator,
        polneary_1,
        polneary_4,
        addrsource,
        contact,
        dex_row_ts,
        vnditdsc,
        phone1,
        print_phone_numbergb,
        source_document_line_num,
        ortaxamt,
        adrscode,
        vnditnum,
        ccode,
        currnidx,
        zipcode,
        purchase_iv_item_taxable,
        unitcost,
        cmpnynam,
        prmdate,
        fstrcptdt,
        address3,
        costcatid,
        purchase_item_tax_schedu,
        purchase_site_tax_schedu,
        phone3,
        invindx,
        projnum,
        decplqty,
        reqdate,
        flags,
        polneary_5,
        taxamnt,
        obtaxamt,
        lineorigin,
        costcode,
        orextcst,
        vendorid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
