with source as (

    select * from {{ source('cai_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        prspayee,
        address1,
        upszone,
        crtcomdt,
        curncyid,
        ten99type,
        trddisct,
        minorder,
        credtlmt,
        phnumbr2,
        pmapindx,
        kperhist,
        workflow_status,
        withholdingentitytype,
        dex_row_id,
        state,
        crlmtdlr,
        cbvat,
        pmrtngix,
        creatddt,
        hold,
        vendname,
        phnumbr1,
        pmtdscix,
        withholdingtype,
        maxindlr,
        pmfrtidx,
        dex_row_ts,
        phone3,
        noteindx,
        minpytyp,
        pymtrmid,
        acpuridx,
        onepaypervendinv,
        govindid,
        kptrxhst,
        duegrper,
        vendstts,
        ten99boxnumber,
        city,
        kgldsths,
        vadcdpad,
        vadcdsfr,
        vadcdtro,
        parvenid,
        workflow_approval_status,
        ccode,
        shipmthd,
        zipcode,
        country,
        minpypct,
        revalue_vendor,
        govcrpid,
        ppstaxrt,
        post_results_to,
        brthdate,
        pmfinidx,
        declid,
        docfmtid,
        venddba,
        sbppsded,
        xpdtoblg,
        pmmschix,
        userlang,
        vaddcdpr,
        pmprchix,
        vndclsid,
        ptcshacf,
        mxwofamt,
        vndchknm,
        pmtaxidx,
        ratetpid,
        pmwrtidx,
        kpcalhst,
        vndcntct,
        txrgnnum,
        comment2,
        txidnmbr,
        taxfilenummode,
        taxschid,
        chekbkid,
        acnmvndr,
        dxvarnum,
        pmcshidx,
        pmdavidx,
        laborpmttype,
        purpvidx,
        userdef1,
        faxnumbr,
        disgrper,
        address2,
        modifdt,
        vadcd1099,
        comment1,
        minpydlr,
        taxinvrecvd,
        withholdingformtype,
        userdef2,
        workflow_priority,
        freeonboard,
        mxiafvnd,
        vendshnm,
        pmdtkidx,
        crtexpdt,
        pymntpri,
        address3,
        rtobutkn,
        writeoff,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
