with source as (

    select * from {{ source('cai_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        ptdusrid,
        duedate,
        simplifd,
        trxsorce,
        cbvat,
        ten99type,
        disamtav,
        voided,
        ppsamded,
        bktpuram,
        modifdt,
        pyenttyp,
        ponumber,
        docdate,
        wrofamnt,
        retnagam,
        vendorid,
        trxdscrn,
        prctdisc,
        cardname,
        frtamnt,
        ttlpymts,
        docamnt,
        distknam,
        pchschid,
        dscdlram,
        dinvpdof,
        bktfrtam,
        aplywith,
        posteddt,
        pymtrmid,
        lngdesc,
        curtrxam,
        bchsourc,
        voidpdate,
        ictrx,
        discdate,
        ten99boxnumber,
        shipmthd,
        dex_row_ts,
        docnumbr,
        hold,
        mscschid,
        ppstaxrt,
        cntrltyp,
        docprinted,
        chekbkid,
        noteindx,
        vadcdtro,
        taxamnt,
        bachnumb,
        gstdsamt,
        frtschid,
        electronic,
        un1099am,
        pstgdate,
        prchdate,
        pordnmbr,
        corrctn,
        workflow_status,
        tax_date,
        backouttradedisc,
        pgramsbj,
        trdisamt,
        ectrx,
        taxschid,
        taxinvreqd,
        disavtkn,
        discamnt,
        ten99amnt,
        invoicereceiptdate,
        mdfusrid,
        mscchamt,
        vndchknm,
        curncyid,
        bktmscam,
        prchamnt,
        dex_row_id,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
