with source as (

    select * from {{ source('cai_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        trxsorce,
        adrscode,
        duedate,
        electronic,
        bktfrtam,
        cbkidcrd,
        bachnumb,
        dscpctam,
        bktslsam,
        ectrx,
        trxdscrn,
        slschdid,
        pymtrmid,
        delete1,
        wrofamnt,
        gstdsamt,
        cprcstnm,
        glpostdt,
        dex_row_ts,
        slstercd,
        trdisamt,
        cspornbr,
        dscdlram,
        disavamt,
        aplywith,
        backouttradedisc,
        cheknmbr,
        voidstts,
        noteindx,
        postdate,
        voiddate,
        ppsamded,
        lstusred,
        comdlram,
        costamnt,
        dex_row_id,
        cbkidchk,
        mscschid,
        cshrctyp,
        eftflag,
        docdate,
        lstedtdt,
        curncyid,
        tax_date,
        corrctn,
        miscamnt,
        disavtkn,
        taxschid,
        discrtnd,
        shipmthd,
        slprsnid,
        directdebit,
        saledate,
        taxamnt,
        ortrxamt,
        dinvpdof,
        bchsourc,
        bktmscam,
        curtrxam,
        agngbukt,
        cbkidcsh,
        pstusrid,
        frtamnt,
        frtschid,
        distknam,
        cashamnt,
        factoring,
        slsamnt,
        simplifd,
        discdate,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
