with source as (

    select * from {{ source('cai_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        includeindp,
        rmcosacc,
        ratetpid,
        rmfcgacc,
        userlang,
        integrationid,
        ccode,
        staddrcd,
        frstindt,
        upszone,
        crcrdnum,
        address3,
        kperhist,
        phone3,
        finchdlr,
        mxwrofam,
        defcacty,
        stmtname,
        rmaracc,
        hold,
        ccrdxpdt,
        phone2,
        gpsfointegrationid,
        salsterr,
        txrgnnum,
        stmtcycl,
        noteindx,
        crcardid,
        crlmttyp,
        country,
        govindid,
        declid,
        orderfulfilldefault,
        chekbkid,
        dex_row_ts,
        fnchatyp,
        docfmtid,
        custname,
        comment1,
        rmtakacc,
        rmsoracc,
        post_results_to,
        mxwoftyp,
        rmavacc,
        inactive,
        shipcomplete,
        rmslsacc,
        duegrper,
        phone1,
        comment2,
        integrationsource,
        kptrxhst,
        creatddt,
        rmwracc,
        shipmthd,
        taxschid,
        rmivacc,
        userdef2,
        bankname,
        govcrpid,
        curncyid,
        slprsnid,
        custpriority,
        city,
        fax,
        minpytyp,
        zip,
        crlmtper,
        crlmtpam,
        cbvat,
        revalue_customer,
        shrtname,
        minpypct,
        taxexmt1,
        adrscode,
        prstadcd,
        fnchpcnt,
        modifdt,
        state,
        address2,
        disgrper,
        send_email_statements,
        prbtadcd,
        taxexmt2,
        rmcshacc,
        kpdsthst,
        finchid,
        custclas,
        custdisc,
        userdef1,
        minpydlr,
        prclevel,
        balnctyp,
        crlmtamt,
        address1,
        cprcstnm,
        cntcprsn,
        pymtrmid,
        dex_row_id,
        rmovrpymtwrtoffacctidx,
        kpcalhst,
        bnkbrnch,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
