with

source as (

    select {{ convert_columns('cai_dbo', 'pop10110') }}
    from {{ source('cai_dbo', 'pop10110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        qtyorder,
        adrscode,
        itemnmbr,
        qtyuncmtbase,
        qtycance,
        umqtyinb,
        polnesta,
        odecplcu,
        denxrate,
        potype,
        uofm,
        lineorigin,
        costcatid,
        ccode,
        city,
        decplqty,
        dex_row_id,
        reqdate,
        cmpnynam,
        polneary_5,
        product_indicator,
        po_line_status_orig,
        freeonboard,
        bsivcttl,
        shipmthd,
        polneary_3,
        purchsitetxschsrc,
        costtype,
        address3,
        vendorid,
        purchase_site_tax_schedu,
        address2,
        purchase_iv_item_taxable,
        prmshpdte,
        costcode,
        ortaxamt,
        xchgrate,
        itemdesc,
        polneary_2,
        decplcur,
        purchase_item_tax_schedu,
        qtycommittedinbaseorig,
        polneary_7,
        currnidx,
        address1,
        flags,
        origbackouttradedisctax,
        addrsource,
        orextcst,
        polneary_1,
        lstrcptdt,
        polneary_4,
        state,
        ratecalc,
        opostsub,
        print_phone_numbergb,
        qtycmtbase,
        qty_canceled_orig,
        curncyid,
        prmdate,
        phone3,
        unitcost,
        released_date,
        invindx,
        vnditdsc,
        capital_item,
        releasebydate,
        bcktxamt,
        fstrcptdt,
        origprmdate,
        phone2,
        extdcost,
        landed_cost_group_id,
        oruntcst,
        vnditnum,
        country,
        backouttradedisctax,
        dex_row_ts,
        polneary_6,
        polneary_9,
        fax,
        doctype,
        projnum,
        itmtrkop,
        locncode,
        source_document_line_num,
        linenumber,
        zipcode,
        change_order_flag,
        release,
        noninven,
        plnndspplid,
        vctnmthd,
        contact,
        taxamnt,
        obtaxamt,
        phone1,
        commntid,
        polneary_8,
        jobnumbr,
        reqstdby,
        source_document_number,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
