with

source as (

    select * from {{ source('cai_dbo', 'pm10000') }}

),

renamed as (

    select
        bachnumb,
        bchsourc,
        vchnumwk,
        chekdate,
        vadcdtro,
        pstgdate,
        posteddt,
        ten99amnt,
        taxamnt,
        discdate,
        doctype,
        prchdate,
        ppstaxrt,
        pstgstus,
        printed,
        lngdesc,
        pmdstmsg,
        bktmscam,
        curtrxam,
        docnumbr,
        electronic,
        ccampynm,
        docdate,
        chekbkid,
        apdstkam,
        dscdlram,
        duedate,
        cheknmbr,
        noteindx,
        chekamnt,
        ppsamded,
        chrgamnt,
        cbvat,
        workflow_status,
        posted,
        invoicereceiptdate,
        camtdate,
        tax_date,
        mdfusrid,
        pchschid,
        pordnmbr,
        vendorid,
        ten99boxnumber,
        corrctn,
        frtamnt,
        vaddcdpr,
        docamnt,
        gstdsamt,
        mscchamt,
        un1099am,
        cntrltyp,
        dex_row_id,
        bktfrtam,
        icdists,
        pgramsbj,
        retnagam,
        crcrdamt,
        cdocnmbr,
        bktpuram,
        mscschid,
        simplifd,
        vchrncor,
        backouttradedisc,
        trdisamt,
        ectrx,
        crcarddt,
        ten99type,
        corrnxst,
        prchamnt,
        taxinvreqd,
        pymtrmid,
        curncyid,
        ccrctnum,
        distknam,
        ictrx,
        txengcld,
        prctdisc,
        shipmthd,
        frtschid,
        cashamnt,
        bnkrcamt,
        chamcbid,
        appldamt,
        wrofamnt,
        pmwrkmsg,
        modifdt,
        docprinted,
        pmicmsgs,
        aplywith,
        sourcdoc,
        campmtnm,
        campynbr,
        disamtav,
        pmwrkms2,
        ptdusrid,
        dex_row_ts,
        taxschid,
        cardname,
        trxdscrn,
        vchrnmbr,
        camcbkid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
