with

source as (

    select * from {{ source('caglp_dbo', 'pm10000') }}

),

renamed as (

    select
        ptdusrid,
        bktfrtam,
        mscchamt,
        un1099am,
        modifdt,
        docdate,
        docamnt,
        docnumbr,
        gstdsamt,
        ectrx,
        bchsourc,
        ten99type,
        bktpuram,
        invoicereceiptdate,
        frtschid,
        duedate,
        crcrdamt,
        ccampynm,
        vadcdtro,
        apdstkam,
        trdisamt,
        corrctn,
        backouttradedisc,
        prchamnt,
        distknam,
        curtrxam,
        cheknmbr,
        retnagam,
        pmdstmsg,
        ten99boxnumber,
        appldamt,
        pordnmbr,
        pchschid,
        mdfusrid,
        docprinted,
        lngdesc,
        vendorid,
        cashamnt,
        wrofamnt,
        simplifd,
        ppstaxrt,
        bnkrcamt,
        txengcld,
        tax_date,
        bachnumb,
        vchnumwk,
        taxinvreqd,
        prctdisc,
        ten99amnt,
        dex_row_ts,
        disamtav,
        electronic,
        sourcdoc,
        camtdate,
        campynbr,
        bktmscam,
        crcarddt,
        cbvat,
        aplywith,
        workflow_status,
        dex_row_id,
        pmwrkms2,
        pmwrkmsg,
        pmicmsgs,
        chekdate,
        ictrx,
        posted,
        cdocnmbr,
        vaddcdpr,
        taxamnt,
        pstgstus,
        vchrnmbr,
        prchdate,
        ccrctnum,
        icdists,
        curncyid,
        pstgdate,
        chekbkid,
        noteindx,
        pymtrmid,
        camcbkid,
        chamcbid,
        shipmthd,
        posteddt,
        ppsamded,
        vchrncor,
        pgramsbj,
        discdate,
        chrgamnt,
        corrnxst,
        chekamnt,
        mscschid,
        printed,
        cardname,
        taxschid,
        trxdscrn,
        doctype,
        dscdlram,
        cntrltyp,
        frtamnt,
        campmtnm,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
