with source as (

    select * from {{ source('caglp_dbo', 'rm20101') }}

),

renamed as (

    select
        cshrctyp,
        bachnumb,
        tax_date,
        dex_row_id,
        lstusred,
        pymtrmid,
        trxsorce,
        trxdscrn,
        cbkidcrd,
        bktfrtam,
        disavamt,
        rmdtypal,
        pstusrid,
        voidstts,
        noteindx,
        aplywith,
        docnumbr,
        lstedtdt,
        cprcstnm,
        custnmbr,
        cheknmbr,
        dscdlram,
        gstdsamt,
        curncyid,
        delete1,
        voiddate,
        cbkidchk,
        dscpctam,
        slstercd,
        backouttradedisc,
        wrofamnt,
        adrscode,
        trdisamt,
        bktslsam,
        cspornbr,
        ectrx,
        docdate,
        electronic,
        ppsamded,
        frtschid,
        simplifd,
        slsamnt,
        taxschid,
        comdlram,
        miscamnt,
        postdate,
        discdate,
        mscschid,
        bktmscam,
        factoring,
        discrtnd,
        duedate,
        costamnt,
        cashamnt,
        distknam,
        dex_row_ts,
        glpostdt,
        curtrxam,
        shipmthd,
        frtamnt,
        saledate,
        agngbukt,
        ortrxamt,
        taxamnt,
        slschdid,
        eftflag,
        slprsnid,
        dinvpdof,
        disavtkn,
        corrctn,
        cbkidcsh,
        directdebit,
        bchsourc,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
