with source as (

    select * from {{ source('caglp_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        retnagam,
        vendorid,
        disamtav,
        ten99boxnumber,
        discdate,
        ictrx,
        voidpdate,
        ponumber,
        hold,
        frtamnt,
        aplywith,
        dscdlram,
        distknam,
        ppsamded,
        prchdate,
        pchschid,
        taxinvreqd,
        posteddt,
        prctdisc,
        docdate,
        cardname,
        trxdscrn,
        wrofamnt,
        pgramsbj,
        pymtrmid,
        lngdesc,
        docprinted,
        gstdsamt,
        taxamnt,
        voided,
        ttlpymts,
        trxsorce,
        cntrltyp,
        ptdusrid,
        corrctn,
        docamnt,
        mscschid,
        cbvat,
        curncyid,
        ten99type,
        simplifd,
        bktfrtam,
        bchsourc,
        shipmthd,
        duedate,
        prchamnt,
        dinvpdof,
        pyenttyp,
        docnumbr,
        un1099am,
        curtrxam,
        modifdt,
        backouttradedisc,
        trdisamt,
        noteindx,
        vadcdtro,
        invoicereceiptdate,
        chekbkid,
        electronic,
        disavtkn,
        taxschid,
        ectrx,
        bktmscam,
        workflow_status,
        mdfusrid,
        bachnumb,
        dex_row_id,
        dex_row_ts,
        pstgdate,
        vndchknm,
        ppstaxrt,
        mscchamt,
        frtschid,
        discamnt,
        ten99amnt,
        bktpuram,
        tax_date,
        pordnmbr,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
