with source as (

    select * from {{ source('caglp_dbo', 'rm00101') }}

),

renamed as (

    select
        hold,
        fnchpcnt,
        integrationid,
        address3,
        crcrdnum,
        rmaracc,
        bnkbrnch,
        comment2,
        disgrper,
        send_email_statements,
        duegrper,
        crlmtpam,
        ratetpid,
        rmcshacc,
        upszone,
        kpdsthst,
        mxwoftyp,
        userdef1,
        custdisc,
        staddrcd,
        shipcomplete,
        phone3,
        creatddt,
        phone2,
        minpydlr,
        stmtname,
        includeindp,
        mxwrofam,
        declid,
        country,
        fax,
        revalue_customer,
        shrtname,
        zip,
        orderfulfilldefault,
        fnchatyp,
        comment1,
        chekbkid,
        crlmtamt,
        txrgnnum,
        post_results_to,
        phone1,
        crlmtper,
        govindid,
        stmtcycl,
        ccode,
        rmovrpymtwrtoffacctidx,
        dex_row_id,
        salsterr,
        crlmttyp,
        govcrpid,
        docfmtid,
        shipmthd,
        defcacty,
        bankname,
        modifdt,
        adrscode,
        ccrdxpdt,
        taxschid,
        kpcalhst,
        pymtrmid,
        integrationsource,
        crcardid,
        kptrxhst,
        custname,
        minpytyp,
        taxexmt1,
        frstindt,
        userlang,
        userdef2,
        slprsnid,
        curncyid,
        inactive,
        gpsfointegrationid,
        rmcosacc,
        rmwracc,
        minpypct,
        prbtadcd,
        finchid,
        kperhist,
        finchdlr,
        prclevel,
        prstadcd,
        state,
        rmslsacc,
        rmivacc,
        taxexmt2,
        noteindx,
        address2,
        rmfcgacc,
        cbvat,
        custclas,
        cprcstnm,
        rmtakacc,
        custpriority,
        address1,
        rmsoracc,
        city,
        dex_row_ts,
        cntcprsn,
        custnmbr,
        balnctyp,
        rmavacc,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
