with source as (

    select * from {{ source('caglp_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        frtschid,
        bnkrcamt,
        un1099am,
        cardname,
        ttlpymts,
        trdisamt,
        distknam,
        wrofamnt,
        corrctn,
        aplywith,
        mscschid,
        bktpuram,
        voided,
        pgramsbj,
        dex_row_ts,
        ppstaxrt,
        trxdscrn,
        ten99type,
        bachnumb,
        curtrxam,
        ictrx,
        shipmthd,
        bktfrtam,
        trxsorce,
        ptdusrid,
        modifdt,
        cntrltyp,
        dscdlram,
        posteddt,
        pyenttyp,
        simplifd,
        docprinted,
        hold,
        dinvpdof,
        pymtrmid,
        prctdisc,
        lngdesc,
        frtamnt,
        pstgdate,
        chekbkid,
        noteindx,
        pordnmbr,
        pchschid,
        docamnt,
        backouttradedisc,
        taxinvreqd,
        tax_date,
        docdate,
        vendorid,
        vadcdtro,
        duedate,
        retnagam,
        ten99boxnumber,
        taxamnt,
        gstdsamt,
        bchsourc,
        discdate,
        disamtav,
        cbvat,
        ppsamded,
        docnumbr,
        ponumber,
        workflow_status,
        dex_row_id,
        ten99amnt,
        disavtkn,
        ectrx,
        discamnt,
        prchdate,
        taxschid,
        mscchamt,
        vndchknm,
        invoicereceiptdate,
        mdfusrid,
        bktmscam,
        electronic,
        curncyid,
        prchamnt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
