with source as (

    select * from {{ source('caglp_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        minpytyp,
        govcrpid,
        upszone,
        address1,
        kgldsths,
        rtobutkn,
        post_results_to,
        curncyid,
        state,
        workflow_priority,
        vendname,
        workflow_status,
        pmtdscix,
        pmcshidx,
        ten99boxnumber,
        dex_row_ts,
        faxnumbr,
        govindid,
        prspayee,
        vadcdsfr,
        pymtrmid,
        userlang,
        pmwrtidx,
        ptcshacf,
        phnumbr1,
        parvenid,
        minpydlr,
        vadcdpad,
        phone3,
        ppstaxrt,
        ccode,
        pmapindx,
        pmdtkidx,
        phnumbr2,
        declid,
        credtlmt,
        mxwofamt,
        docfmtid,
        txidnmbr,
        trddisct,
        venddba,
        purpvidx,
        country,
        zipcode,
        pmfrtidx,
        pmdavidx,
        onepaypervendinv,
        vaddcdpr,
        laborpmttype,
        txrgnnum,
        vendstts,
        duegrper,
        withholdingtype,
        minpypct,
        taxschid,
        kptrxhst,
        crtexpdt,
        cbvat,
        shipmthd,
        minorder,
        vadcdtro,
        kpcalhst,
        taxfilenummode,
        acnmvndr,
        taxinvrecvd,
        vndchknm,
        chekbkid,
        disgrper,
        dxvarnum,
        pmprchix,
        crlmtdlr,
        pmrtngix,
        withholdingformtype,
        city,
        modifdt,
        workflow_approval_status,
        comment2,
        xpdtoblg,
        comment1,
        creatddt,
        pmfinidx,
        maxindlr,
        sbppsded,
        hold,
        noteindx,
        crtcomdt,
        pmmschix,
        revalue_vendor,
        writeoff,
        userdef1,
        dex_row_id,
        address3,
        freeonboard,
        mxiafvnd,
        brthdate,
        userdef2,
        vndcntct,
        withholdingentitytype,
        pmtaxidx,
        ratetpid,
        pymntpri,
        ten99type,
        kperhist,
        address2,
        acpuridx,
        vndclsid,
        vadcd1099,
        vendshnm,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
