with source as (

    select * from {{ source('cos_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        kptrxhst,
        phone2,
        rmivacc,
        rmovrpymtwrtoffacctidx,
        custpriority,
        salsterr,
        rmwracc,
        revalue_customer,
        shrtname,
        state,
        cbvat,
        fnchatyp,
        minpypct,
        crcardid,
        creatddt,
        minpydlr,
        finchdlr,
        noteindx,
        address2,
        crlmtpam,
        gpsfointegrationid,
        slprsnid,
        prclevel,
        crlmttyp,
        upszone,
        ratetpid,
        crcrdnum,
        crlmtper,
        shipmthd,
        bankname,
        shipcomplete,
        rmcshacc,
        pymtrmid,
        taxschid,
        bnkbrnch,
        fnchpcnt,
        custclas,
        hold,
        cprcstnm,
        taxexmt2,
        custdisc,
        inactive,
        city,
        disgrper,
        frstindt,
        finchid,
        orderfulfilldefault,
        prbtadcd,
        userlang,
        cntcprsn,
        fax,
        stmtcycl,
        address1,
        prstadcd,
        includeindp,
        dex_row_id,
        taxexmt1,
        balnctyp,
        modifdt,
        ccrdxpdt,
        staddrcd,
        phone3,
        rmaracc,
        custname,
        mxwrofam,
        userdef1,
        defcacty,
        address3,
        integrationsource,
        integrationid,
        kpdsthst,
        send_email_statements,
        comment2,
        userdef2,
        rmtakacc,
        rmavacc,
        curncyid,
        duegrper,
        phone1,
        adrscode,
        minpytyp,
        kpcalhst,
        post_results_to,
        kperhist,
        comment1,
        rmslsacc,
        docfmtid,
        zip,
        rmsoracc,
        ccode,
        country,
        rmcosacc,
        rmfcgacc,
        govcrpid,
        crlmtamt,
        stmtname,
        txrgnnum,
        dex_row_ts,
        chekbkid,
        mxwoftyp,
        govindid,
        declid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
