with source as (

    select * from {{ source('cos_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        ictrx,
        chekbkid,
        disamtav,
        ten99boxnumber,
        mdfusrid,
        discdate,
        retnagam,
        vadcdtro,
        pymtrmid,
        dex_row_ts,
        pgramsbj,
        bktpuram,
        cbvat,
        corrctn,
        pchschid,
        voided,
        docamnt,
        tax_date,
        docnumbr,
        taxinvreqd,
        dex_row_id,
        frtamnt,
        ttlpymts,
        shipmthd,
        noteindx,
        vendorid,
        electronic,
        dinvpdof,
        posteddt,
        ppstaxrt,
        mscschid,
        workflow_status,
        dscdlram,
        trxsorce,
        ptdusrid,
        distknam,
        ectrx,
        curtrxam,
        duedate,
        cardname,
        modifdt,
        docprinted,
        frtschid,
        bachnumb,
        trxdscrn,
        taxamnt,
        aplywith,
        ten99type,
        lngdesc,
        docdate,
        gstdsamt,
        ten99amnt,
        disavtkn,
        discamnt,
        mscchamt,
        bktfrtam,
        ponumber,
        prctdisc,
        bnkrcamt,
        bchsourc,
        un1099am,
        pstgdate,
        bktmscam,
        prchamnt,
        curncyid,
        wrofamnt,
        pyenttyp,
        taxschid,
        vndchknm,
        pordnmbr,
        ppsamded,
        backouttradedisc,
        trdisamt,
        cntrltyp,
        prchdate,
        simplifd,
        hold,
        invoicereceiptdate,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
