with source as (

    select * from {{ source('cos_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        frtschid,
        taxschid,
        voiddate,
        cashamnt,
        dinvpdof,
        mscschid,
        cbkidchk,
        slstercd,
        discrtnd,
        disavtkn,
        lstedtdt,
        costamnt,
        agngbukt,
        simplifd,
        factoring,
        cheknmbr,
        cshrctyp,
        postdate,
        ppsamded,
        docdate,
        cprcstnm,
        tax_date,
        dex_row_id,
        cspornbr,
        duedate,
        directdebit,
        disavamt,
        adrscode,
        eftflag,
        backouttradedisc,
        noteindx,
        trxdscrn,
        curncyid,
        bachnumb,
        frtamnt,
        dscdlram,
        gstdsamt,
        cbkidcsh,
        delete1,
        trdisamt,
        corrctn,
        bktslsam,
        curtrxam,
        bktfrtam,
        dex_row_ts,
        glpostdt,
        taxamnt,
        bktmscam,
        voidstts,
        wrofamnt,
        pstusrid,
        miscamnt,
        trxsorce,
        aplywith,
        lstusred,
        ortrxamt,
        discdate,
        shipmthd,
        slsamnt,
        distknam,
        bchsourc,
        electronic,
        slschdid,
        ectrx,
        cbkidcrd,
        saledate,
        comdlram,
        pymtrmid,
        slprsnid,
        dscpctam,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
