with source as (

    select * from {{ source('cos_dbo', 'pop30300') }}

),

renamed as (

    select
        poprctnm,
        disavtkn,
        rcptnote_7,
        ppstaxrt,
        frtschid,
        subtotal,
        aplywith,
        taxinvreqd,
        dscpctam,
        disavamt,
        rcptnote_1,
        refrence,
        rcptnote_4,
        ordatkn,
        bsivcttl,
        poptype,
        orsubtot,
        discdate,
        ten99amnt,
        withhamt,
        frtamnt,
        exchdate,
        time1,
        dscdlram,
        bachnumb,
        vnddocnm,
        invoiceexpected,
        prepaymentamount,
        poplnerr,
        replacegoods,
        actlship,
        ormsctax,
        xchgrate,
        invoicereceiptdate,
        distknam,
        vchrnmbr,
        currnidx,
        exgtblid,
        glpostdt,
        rcptnote_2,
        curncyid,
        frttxamt,
        ectrx,
        rcptnote_3,
        simplifd,
        workflow_status,
        vadcdtro,
        vendorid,
        obtaxamt,
        taxinvrecvd,
        mscschid,
        trdpctpr,
        taxamnt,
        pymtrmid,
        ten99boxnumber,
        orddlrat,
        backoutfreighttaxamt,
        ordavamt,
        dex_row_id,
        posteddt,
        pophdr2,
        pop_hdr_errors_4,
        miscamnt,
        creatddt,
        msctxamt,
        revaltrxsource,
        trxsorce,
        revaljrnentry,
        purchase_misc_taxable,
        receiptdate,
        denxrate,
        orfrtamt,
        orfrttax,
        cbvat,
        duedate,
        bcktxamt,
        rcptnote_5,
        purchase_freight_taxable,
        origbackoutfreighttaxamt,
        vendname,
        rcptnote_6,
        voidstts,
        txrgnnum,
        backoutmisctaxamt,
        shipmthd,
        ortdisam,
        total_landed_cost_amount,
        tax_date,
        mctrxstt,
        user2ent,
        bchsourc,
        taxschid,
        origbackoutmisctaxamt,
        modifdt,
        ptdusrid,
        ordistkn,
        ten99type,
        pophdr1,
        ortaxamt,
        ratetpid,
        ratecalc,
        originatingprepaymentamt,
        rcptnote_8,
        trdisamt,
        ormiscamt,
        or1099am,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
