with source as (

    select * from {{ source('cos_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        parvenid,
        userdef1,
        pmtaxidx,
        pmprchix,
        vadcdsfr,
        pymtrmid,
        pmdtkidx,
        pmmschix,
        minpydlr,
        ccode,
        phone3,
        ptcshacf,
        pmfinidx,
        phnumbr1,
        docfmtid,
        pmcshidx,
        userlang,
        city,
        shipmthd,
        acnmvndr,
        dex_row_ts,
        sbppsded,
        comment2,
        purpvidx,
        noteindx,
        vadcdtro,
        credtlmt,
        vaddcdpr,
        withholdingformtype,
        freeonboard,
        kptrxhst,
        state,
        pmdavidx,
        taxfilenummode,
        pmfrtidx,
        pymntpri,
        workflow_status,
        chekbkid,
        laborpmttype,
        address3,
        crtexpdt,
        revalue_vendor,
        vendname,
        writeoff,
        curncyid,
        vndclsid,
        kgldsths,
        vadcd1099,
        vendshnm,
        xpdtoblg,
        disgrper,
        address1,
        pmwrtidx,
        taxschid,
        userdef2,
        vndcntct,
        txrgnnum,
        workflow_priority,
        ratetpid,
        minorder,
        govindid,
        comment1,
        mxiafvnd,
        dex_row_id,
        faxnumbr,
        address2,
        hold,
        crtcomdt,
        dxvarnum,
        rtobutkn,
        pmtdscix,
        vndchknm,
        onepaypervendinv,
        kperhist,
        pmapindx,
        vadcdpad,
        crlmtdlr,
        withholdingentitytype,
        vendstts,
        trddisct,
        ten99type,
        maxindlr,
        modifdt,
        brthdate,
        govcrpid,
        upszone,
        acpuridx,
        taxinvrecvd,
        post_results_to,
        creatddt,
        declid,
        mxwofamt,
        withholdingtype,
        cbvat,
        pmrtngix,
        phnumbr2,
        prspayee,
        ppstaxrt,
        country,
        zipcode,
        workflow_approval_status,
        ten99boxnumber,
        venddba,
        minpypct,
        duegrper,
        txidnmbr,
        minpytyp,
        kpcalhst,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
