with source as (

    select * from {{ source('cos_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        noteindx,
        prchdate,
        posteddt,
        disavtkn,
        workflow_status,
        discamnt,
        ten99amnt,
        docamnt,
        backouttradedisc,
        mscschid,
        pstgdate,
        gstdsamt,
        taxamnt,
        pyenttyp,
        aplywith,
        shipmthd,
        bchsourc,
        simplifd,
        dex_row_id,
        curncyid,
        pymtrmid,
        prctdisc,
        lngdesc,
        trxdscrn,
        retnagam,
        ten99boxnumber,
        bktfrtam,
        curtrxam,
        dscdlram,
        dinvpdof,
        ponumber,
        docnumbr,
        ttlpymts,
        frtamnt,
        cardname,
        docdate,
        ppstaxrt,
        cbvat,
        corrctn,
        tax_date,
        vendorid,
        electronic,
        invoicereceiptdate,
        hold,
        distknam,
        bktpuram,
        ppsamded,
        ptdusrid,
        ectrx,
        trdisamt,
        pchschid,
        trxsorce,
        vndchknm,
        wrofamnt,
        taxinvreqd,
        discdate,
        pordnmbr,
        disamtav,
        mdfusrid,
        modifdt,
        chekbkid,
        taxschid,
        duedate,
        frtschid,
        voidpdate,
        cntrltyp,
        bachnumb,
        ictrx,
        docprinted,
        mscchamt,
        un1099am,
        voided,
        pgramsbj,
        bktmscam,
        dex_row_ts,
        prchamnt,
        vadcdtro,
        ten99type,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
