with source as (

    select * from {{ source('culmarex_dw_dbo', 'nav_onestream_vendor_ledger_entry') }}

),

renamed as (

    select
        id,
        description2,
        pmt__disc__tolerance_date,
        succeeded_vat_registration_no_,
        special_scheme_code,
        closed_by_currency_amount,
        correction_type,
        no__series,
        buy_from_vendor_no_,
        remaining_amount__lcy__stats_,
        applies_to_doc__type,
        company,
        bal__account_type,
        currency_code,
        reversed_by_entry_no_,
        transaction_no_,
        document_type,
        closed_by_amount__lcy_,
        applies_to_ext__doc__no_,
        due_date,
        applies_to_bill_no_,
        payment_terms_code,
        purchaser_code,
        original_pmt__disc__possible,
        max__payment_tolerance,
        closed_at_date,
        applies_to_doc__no_,
        on_hold,
        autodocument_no_,
        journal_batch_name,
        pmt__tolerance__lcy_,
        vendor_no_,
        closed_by_amount,
        amount__lcy__stats_,
        open,
        exported_to_payment_file,
        vendor_name,
        closed_by_entry_no_,
        closed_by_currency_code,
        purchase__lcy_,
        recipient_bank_account,
        description,
        document_situation,
        source_code,
        ic_partner_code,
        id_type,
        payment_reference,
        bal__account_no_,
        reason_code,
        accepted_payment_tolerance,
        prepayment,
        adjusted_currency_factor,
        bill_no_,
        pmt__disc__rcd__lcy_,
        vendor_posting_group,
        creditor_no_,
        document_date,
        document_status,
        amount_to_apply,
        reversed_entry_no_,
        entry_no_,
        accepted_pmt__disc__tolerance,
        applying_entry,
        applies_to_id,
        external_document_no_,
        corrected_invoice_no_,
        positive,
        payment_method_code,
        generated_autodocument,
        invoice_type,
        message_to_recipient,
        original_currency_factor,
        global_dimension_1_code,
        remaining_pmt__disc__possible,
        succeeded_company_name,
        posting_date,
        global_dimension_2_code,
        inv__discount__lcy_,
        user_id,
        cr__memo_type,
        pmt__discount_date,
        document_no_,
        dimension_set_id,
        reversed,
        _fivetran_deleted,
        _fivetran_synced
    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
