with source as (

    select * from {{ source('culmarex_dw_dbo', 'nav_onestream_vendor') }}

),

renamed as (

    select
        id,
        cod__banco_kiriba,
        shipping_agent_code,
        genera_json_ped__compra,
        contact,
        budgeted_amount,
        invoice_disc__code,
        last_date_modified,
        tax_area_code,
        ic_partner_code,
        lead_time_calculation,
        no__series,
        location_code,
        fecha_caducidad_cert__resid_,
        creditor_no_,
        block_payment_tolerance,
        no__serie_abono_compra,
        city,
        grupo_irpf,
        cod__retencion,
        company,
        no_,
        gln,
        country_region_code,
        application_method,
        mail_envio_json,
        vat_registration_no_,
        payment_days_code,
        validate_eu_vat_reg__no_,
        payment_method_code,
        payment_terms_code,
        empresa_asociada,
        blocked,
        telex_answer_back,
        cod__cliente,
        currency_code,
        priority,
        tax_liable,
        telex_no_,
        tipo_proveedor_sii,
        privacy_blocked,
        responsibility_center,
        saldo_cliente,
        address_2,
        fin__charge_terms_code,
        picture,
        no__cliente_skretting,
        gen__bus__posting_group,
        proveedor_dua,
        disable_search_by_name,
        eori_number,
        preferred_bank_account_code,
        id_nav,
        shipment_method_code,
        primary_contact_no_,
        base_calendar_code,
        proveedor_generico_dua,
        territory_code,
        clave_de_factura,
        cc_vendedor,
        payment_terms_id,
        payment_method_id,
        image,
        home_page,
        post_code,
        cash_flow_payment_terms_code,
        informar_a_kiriba,
        fax_no_,
        e_mail,
        county,
        tipo_identificacion,
        vat_bus__posting_group,
        global_dimension_2_code,
        statistics_group,
        language_code,
        search_name,
        prices_including_vat,
        partner_type,
        last_modified_date_time,
        currency_id,
        phone_no_,
        non_paymt__periods_code,
        our_account_no_,
        global_dimension_1_code,
        email_por_destinatario,
        name,
        self_employed,
        pay_to_vendor_no_,
        name_2,
        prepayment__,
        purchaser_code,
        document_sending_profile,
        no_replica_referencias_cruzada,
        cod__plantilla_mailing,
        no__serie_factura_compra,
        pagare_no_a_la_orden,
        clave_de_abono,
        kiriba_sent_date,
        address,
        vendor_posting_group,
        _fivetran_deleted,
        _fivetran_synced
    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
