with source as (

    select * from {{ source('culmarex_dw_dbo', 'nav_onestream_cust__ledger_entry') }}

),

renamed as (

    select
        id,
        due_date,
        applies_to_id,
        no__cheque_recibido,
        fecha_vencimiento_cheque,
        journal_batch_name,
        bill_no_,
        adjusted_currency_factor,
        remaining_pmt__disc__possible,
        posting_date,
        currency_code,
        applying_entry,
        entry_no_,
        transaction_no_,
        pmt__tolerance__lcy_,
        max__payment_tolerance,
        prepayment,
        profit__lcy_,
        closed_by_amount,
        applies_to_doc__type,
        global_dimension_1_code,
        reason_code,
        amount__lcy__stats_,
        succeeded_vat_registration_no_,
        cr__memo_type,
        document_situation,
        special_scheme_code,
        salesperson_code,
        applies_to_bill_no_,
        source_code,
        payment_method_code,
        bal__account_type,
        last_issued_reminder_level,
        original_currency_factor,
        closed_at_date,
        closed_by_currency_code,
        on_hold,
        description,
        exported_to_payment_file,
        open,
        user_id,
        venta_a_,
        correction_type,
        payment_reference,
        original_pmt__disc__possible,
        pmt__disc__given__lcy_,
        corrected_invoice_no_,
        company,
        no__series,
        document_no_,
        remaining_amount__lcy__stats_,
        reversed_by_entry_no_,
        ic_partner_code,
        document_status,
        pmt__disc__tolerance_date,
        reversed_entry_no_,
        payment_terms_code,
        amount_to_apply,
        reversed,
        sell_to_customer_no_,
        document_type,
        inv__discount__lcy_,
        closed_by_amount__lcy_,
        pmt__discount_date,
        closed_by_entry_no_,
        document_date,
        invoice_type,
        sales__lcy_,
        customer_posting_group,
        direct_debit_mandate_id,
        recipient_bank_account,
        applies_to_ext__doc__no_,
        customer_name,
        bal__account_no_,
        accepted_payment_tolerance,
        message_to_recipient,
        accepted_pmt__disc__tolerance,
        customer_no_,
        succeeded_company_name,
        positive,
        external_document_no_,
        description2,
        dimension_set_id,
        calculate_interest,
        applies_to_doc__no_,
        id_type,
        closed_by_currency_amount,
        closing_interest_calculated,
        global_dimension_2_code,
        _fivetran_deleted,
        _fivetran_synced
    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
