with source as (

    select * from {{ source('northscope_sb1', 'erpx_imitem') }}

),

renamed as (

    select
        itemclasssk,
        lastuser,
        expirationdays,
        allowvariableorderedqty,
        lotholdreturn,
        createddatetime,
        defaultsopriceuomsk,
        freightaccrualcreditactsk,
        freightrevenueactsk,
        salesinvoicedescription,
        unrealpurchpricevaractsk,
        assemblyvaractsk,
        attributeclasssk,
        productionbatchclasssk,
        costgroupsk,
        palletconfigurationsk,
        isitemvariableweight,
        defaultreportinguomsk,
        qualitytestclasssk,
        brokerageexpactsk,
        trackmethoden,
        barcodelabeldescription,
        itemdescription,
        freightaccrualdebitactsk,
        cogsactsk,
        manageitemsbyen,
        invoffsetactsk,
        gtin,
        inuseactsk,
        varianceactsk,
        unitdecimals,
        shippingweight,
        defaultimunituomsk,
        currencydecimals,
        currentcost,
        taxableforsales,
        valuationmethoden,
        itemattributestring,
        deductioncodesk,
        shippingdescription,
        isinactive,
        marketcost,
        defaultsoweightuomsk,
        brokeragewriteoffactsk,
        damagedactsk,
        itemtypesk,
        hostsystemlink,
        upc,
        grosspalletweight,
        inserviceactsk,
        lastupdated,
        transferfrtexpenseglaccountsk,
        isvisibletowms,
        brokerageaccrualactsk,
        requirewholeunits,
        markdownactsk,
        purchpricevaractsk,
        createdby,
        searchtext,
        minmarginpercent,
        dataentitycompanysk,
        cubeweight,
        costuomsk,
        weightdecimals,
        unittareweight,
        depreciationactsk,
        inventoryrtnactsk,
        defaultimweightuomsk,
        baseuomsk,
        lotholdnew,
        inventoryactsk,
        dropshipitemsactsk,
        standardcost,
        transferfrtaccrualglaccountsk,
        salesactsk,
        salesreturnsactsk,
        _fivetran_deleted,
        _fivetran_synced,
        trim(itemid) as itemid,
        trim(itemsk) as itemsk,
        trim(defaultsounituomsk) as defaultsounituomsk,
        trim(uomschedulesk) as uomschedulesk

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
