with source as (

    select * from {{ source('nb678_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        brthdate,
        userlang,
        vendshnm,
        vadcdpad,
        vndchknm,
        ratetpid,
        creatddt,
        comment1,
        faxnumbr,
        pmwrtidx,
        minpydlr,
        pmcshidx,
        dxvarnum,
        pmprchix,
        pmtdscix,
        writeoff,
        sbppsded,
        chekbkid,
        laborpmttype,
        txidnmbr,
        vendstts,
        onepaypervendinv,
        zipcode,
        city,
        vadcdtro,
        revalue_vendor,
        disgrper,
        declid,
        dex_row_id,
        phnumbr2,
        shipmthd,
        credtlmt,
        workflow_priority,
        xpdtoblg,
        trddisct,
        withholdingformtype,
        kptrxhst,
        acpuridx,
        workflow_status,
        dex_row_ts,
        phone3,
        mxwofamt,
        upszone,
        pmmschix,
        taxfilenummode,
        venddba,
        pmtaxidx,
        ptcshacf,
        docfmtid,
        kgldsths,
        govindid,
        country,
        pmfinidx,
        govcrpid,
        pymtrmid,
        rtobutkn,
        ppstaxrt,
        ccode,
        vendname,
        pmapindx,
        crtexpdt,
        ten99type,
        userdef1,
        kperhist,
        address1,
        curncyid,
        pmfrtidx,
        parvenid,
        crlmtdlr,
        post_results_to,
        freeonboard,
        vadcdsfr,
        mxiafvnd,
        pmdavidx,
        phnumbr1,
        minorder,
        acnmvndr,
        pmrtngix,
        minpytyp,
        withholdingtype,
        userdef2,
        comment2,
        vndcntct,
        address3,
        crtcomdt,
        noteindx,
        ten99boxnumber,
        state,
        minpypct,
        pmdtkidx,
        maxindlr,
        duegrper,
        prspayee,
        taxschid,
        cbvat,
        withholdingentitytype,
        txrgnnum,
        kpcalhst,
        hold,
        workflow_approval_status,
        purpvidx,
        pymntpri,
        vndclsid,
        vadcd1099,
        address2,
        vaddcdpr,
        taxinvrecvd,
        modifdt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
