with source as (

    select * from {{ source('nb678_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        city,
        custname,
        address1,
        zip,
        minpypct,
        taxexmt1,
        rmcshacc,
        kpcalhst,
        taxschid,
        country,
        fax,
        inactive,
        crlmtpam,
        rmaracc,
        finchid,
        integrationsource,
        mxwoftyp,
        kptrxhst,
        shipmthd,
        prbtadcd,
        adrscode,
        post_results_to,
        userdef2,
        fnchatyp,
        curncyid,
        docfmtid,
        minpydlr,
        comment1,
        crcardid,
        staddrcd,
        phone3,
        includeindp,
        txrgnnum,
        rmivacc,
        govindid,
        mxwrofam,
        crlmttyp,
        disgrper,
        custdisc,
        defcacty,
        rmcosacc,
        crlmtper,
        rmwracc,
        shipcomplete,
        stmtname,
        rmfcgacc,
        declid,
        comment2,
        integrationid,
        ccrdxpdt,
        ccode,
        revalue_customer,
        crlmtamt,
        govcrpid,
        userlang,
        phone1,
        rmslsacc,
        salsterr,
        rmtakacc,
        chekbkid,
        rmavacc,
        upszone,
        rmsoracc,
        prclevel,
        hold,
        phone2,
        orderfulfilldefault,
        address3,
        crcrdnum,
        shrtname,
        gpsfointegrationid,
        stmtcycl,
        duegrper,
        send_email_statements,
        finchdlr,
        frstindt,
        fnchpcnt,
        kperhist,
        balnctyp,
        noteindx,
        userdef1,
        dex_row_ts,
        slprsnid,
        taxexmt2,
        pymtrmid,
        address2,
        ratetpid,
        custclas,
        bnkbrnch,
        cbvat,
        custpriority,
        state,
        bankname,
        modifdt,
        rmovrpymtwrtoffacctidx,
        cntcprsn,
        creatddt,
        kpdsthst,
        prstadcd,
        cprcstnm,
        minpytyp,
        dex_row_id,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
