with

source as (
    select {{ convert_columns('nb681_dbo', 'pm10000') }}
    from {{ source('nb681_dbo', 'pm10000') }}
),

renamed as (

    select
        trxdscrn,
        prchamnt,
        dex_row_ts,
        bktmscam,
        prctdisc,
        ccrctnum,
        crcarddt,
        bnkrcamt,
        retnagam,
        corrctn,
        shipmthd,
        pymtrmid,
        aplywith,
        cntrltyp,
        frtamnt,
        prchdate,
        taxschid,
        vendorid,
        apdstkam,
        vchrnmbr,
        vaddcdpr,
        backouttradedisc,
        mscchamt,
        cheknmbr,
        txengcld,
        pordnmbr,
        pstgstus,
        pgramsbj,
        chekbkid,
        appldamt,
        ppstaxrt,
        lngdesc,
        vchnumwk,
        campynbr,
        pstgdate,
        trdisamt,
        dscdlram,
        ten99type,
        chamcbid,
        docnumbr,
        chekdate,
        frtschid,
        ten99boxnumber,
        simplifd,
        cbvat,
        cdocnmbr,
        cardname,
        taxinvreqd,
        gstdsamt,
        curtrxam,
        sourcdoc,
        ten99amnt,
        docamnt,
        wrofamnt,
        ppsamded,
        posteddt,
        bchsourc,
        ccampynm,
        cashamnt,
        mdfusrid,
        mscschid,
        duedate,
        invoicereceiptdate,
        bktfrtam,
        pchschid,
        discdate,
        chrgamnt,
        docdate,
        dex_row_id,
        camtdate,
        corrnxst,
        disamtav,
        posted,
        docprinted,
        pmdstmsg,
        ictrx,
        vadcdtro,
        vchrncor,
        pmwrkmsg,
        workflow_status,
        noteindx,
        bachnumb,
        pmicmsgs,
        ptdusrid,
        printed,
        campmtnm,
        modifdt,
        pmwrkms2,
        icdists,
        taxamnt,
        electronic,
        un1099am,
        bktpuram,
        doctype,
        tax_date,
        distknam,
        curncyid,
        ectrx,
        crcrdamt,
        camcbkid,
        chekamnt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'TRUE'
