with

source as (

    select {{ convert_columns('causa_dbo', 'pop10110') }}
    from {{ source('causa_dbo', 'pop10110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        polneary_2,
        plnndspplid,
        polneary_5,
        source_document_line_num,
        linenumber,
        polneary_8,
        xchgrate,
        itemnmbr,
        itmtrkop,
        jobnumbr,
        backouttradedisctax,
        po_line_status_orig,
        freeonboard,
        flags,
        doctype,
        purchase_site_tax_schedu,
        itemdesc,
        qtyuncmtbase,
        lstrcptdt,
        addrsource,
        oruntcst,
        address2,
        phone1,
        noninven,
        unitcost,
        phone2,
        odecplcu,
        taxamnt,
        country,
        print_phone_numbergb,
        projnum,
        costcatid,
        dex_row_id,
        capital_item,
        orextcst,
        denxrate,
        qtycance,
        phone3,
        potype,
        extdcost,
        polneary_6,
        obtaxamt,
        currnidx,
        invindx,
        origprmdate,
        release,
        umqtyinb,
        reqdate,
        polneary_7,
        city,
        vctnmthd,
        lineorigin,
        purchase_item_tax_schedu,
        bsivcttl,
        change_order_flag,
        purchsitetxschsrc,
        address1,
        qty_canceled_orig,
        bcktxamt,
        qtycmtbase,
        state,
        commntid,
        costcode,
        reqstdby,
        polneary_3,
        vendorid,
        locncode,
        polneary_9,
        source_document_number,
        polneary_4,
        zipcode,
        decplqty,
        contact,
        product_indicator,
        released_date,
        landed_cost_group_id,
        qtycommittedinbaseorig,
        prmshpdte,
        purchase_iv_item_taxable,
        opostsub,
        vnditnum,
        qtyorder,
        address3,
        ortaxamt,
        shipmthd,
        ratecalc,
        origbackouttradedisctax,
        costtype,
        polnesta,
        fax,
        prmdate,
        adrscode,
        uofm,
        decplcur,
        cmpnynam,
        polneary_1,
        releasebydate,
        fstrcptdt,
        dex_row_ts,
        vnditdsc,
        ccode,
        curncyid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
