with source as (

    select * from {{ source('causa_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        integrationsource,
        crlmtper,
        comment2,
        hold,
        ccode,
        crlmtamt,
        noteindx,
        finchdlr,
        send_email_statements,
        address3,
        integrationid,
        crcrdnum,
        cprcstnm,
        ccrdxpdt,
        rmtakacc,
        staddrcd,
        minpypct,
        rmsoracc,
        prclevel,
        upszone,
        userdef1,
        rmovrpymtwrtoffacctidx,
        phone2,
        shipcomplete,
        minpydlr,
        kpdsthst,
        bnkbrnch,
        dex_row_id,
        rmavacc,
        minpytyp,
        rmcosacc,
        salsterr,
        rmwracc,
        rmfcgacc,
        govindid,
        shrtname,
        custpriority,
        declid,
        includeindp,
        stmtname,
        userlang,
        txrgnnum,
        rmslsacc,
        prbtadcd,
        custdisc,
        revalue_customer,
        docfmtid,
        slprsnid,
        crlmtpam,
        comment1,
        rmivacc,
        chekbkid,
        adrscode,
        curncyid,
        balnctyp,
        country,
        zip,
        fnchpcnt,
        fax,
        govcrpid,
        rmaracc,
        userdef2,
        phone1,
        bankname,
        disgrper,
        kpcalhst,
        cntcprsn,
        pymtrmid,
        mxwrofam,
        address1,
        inactive,
        custname,
        address2,
        kperhist,
        taxschid,
        orderfulfilldefault,
        taxexmt2,
        prstadcd,
        state,
        crcardid,
        cbvat,
        dex_row_ts,
        phone3,
        crlmttyp,
        mxwoftyp,
        frstindt,
        gpsfointegrationid,
        kptrxhst,
        defcacty,
        taxexmt1,
        city,
        rmcshacc,
        finchid,
        ratetpid,
        custclas,
        creatddt,
        stmtcycl,
        duegrper,
        modifdt,
        shipmthd,
        fnchatyp,
        post_results_to,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
