with source as (

    select * from {{ source('causa_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        ponumber,
        invoicereceiptdate,
        prchamnt,
        trxsorce,
        ptdusrid,
        ictrx,
        tax_date,
        dex_row_ts,
        ttlpymts,
        bktfrtam,
        hold,
        vendorid,
        trxdscrn,
        taxinvreqd,
        trdisamt,
        voidpdate,
        distknam,
        ppstaxrt,
        cardname,
        curtrxam,
        pgramsbj,
        un1099am,
        aplywith,
        frtschid,
        taxamnt,
        ten99type,
        ppsamded,
        gstdsamt,
        cntrltyp,
        dex_row_id,
        wrofamnt,
        vndchknm,
        discdate,
        pyenttyp,
        curncyid,
        corrctn,
        docprinted,
        bchsourc,
        docamnt,
        prctdisc,
        pstgdate,
        docdate,
        simplifd,
        docnumbr,
        posteddt,
        workflow_status,
        voided,
        shipmthd,
        prchdate,
        taxschid,
        mdfusrid,
        pordnmbr,
        disamtav,
        duedate,
        chekbkid,
        vadcdtro,
        modifdt,
        bktmscam,
        frtamnt,
        mscschid,
        backouttradedisc,
        dscdlram,
        bachnumb,
        dinvpdof,
        pchschid,
        ten99boxnumber,
        bktpuram,
        discamnt,
        ten99amnt,
        disavtkn,
        mscchamt,
        ectrx,
        noteindx,
        electronic,
        retnagam,
        pymtrmid,
        lngdesc,
        cbvat,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
