with source as (

    select * from {{ source('causa_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        taxamnt,
        cbkidcrd,
        miscamnt,
        dex_row_id,
        slschdid,
        saledate,
        ortrxamt,
        gstdsamt,
        eftflag,
        trxsorce,
        trxdscrn,
        backouttradedisc,
        bktmscam,
        slsamnt,
        cheknmbr,
        aplywith,
        curtrxam,
        cspornbr,
        ppsamded,
        glpostdt,
        dex_row_ts,
        adrscode,
        distknam,
        disavamt,
        tax_date,
        delete1,
        cbkidcsh,
        costamnt,
        dscdlram,
        dinvpdof,
        frtschid,
        voidstts,
        trdisamt,
        discdate,
        wrofamnt,
        ectrx,
        pstusrid,
        electronic,
        bktslsam,
        mscschid,
        noteindx,
        slprsnid,
        cbkidchk,
        cprcstnm,
        curncyid,
        cashamnt,
        simplifd,
        factoring,
        bchsourc,
        duedate,
        dscpctam,
        lstedtdt,
        bktfrtam,
        discrtnd,
        disavtkn,
        pymtrmid,
        docdate,
        cshrctyp,
        slstercd,
        comdlram,
        frtamnt,
        shipmthd,
        bachnumb,
        corrctn,
        voiddate,
        taxschid,
        lstusred,
        agngbukt,
        postdate,
        directdebit,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
