with source as (

    select * from {{ source('causa_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        pmfrtidx,
        taxfilenummode,
        modifdt,
        purpvidx,
        withholdingformtype,
        pmdavidx,
        curncyid,
        crtexpdt,
        address1,
        govcrpid,
        country,
        rtobutkn,
        vendstts,
        noteindx,
        upszone,
        minpydlr,
        onepaypervendinv,
        zipcode,
        userlang,
        kgldsths,
        pymntpri,
        disgrper,
        pmtaxidx,
        declid,
        ptcshacf,
        ccode,
        withholdingtype,
        acpuridx,
        phone3,
        faxnumbr,
        mxiafvnd,
        docfmtid,
        pmmschix,
        pmfinidx,
        acnmvndr,
        prspayee,
        pymtrmid,
        pmapindx,
        govindid,
        withholdingentitytype,
        ten99type,
        comment2,
        workflow_priority,
        mxwofamt,
        writeoff,
        phnumbr1,
        dxvarnum,
        txidnmbr,
        phnumbr2,
        dex_row_ts,
        pmrtngix,
        laborpmttype,
        ratetpid,
        venddba,
        brthdate,
        freeonboard,
        txrgnnum,
        post_results_to,
        kptrxhst,
        vndchknm,
        cbvat,
        vaddcdpr,
        ten99boxnumber,
        maxindlr,
        vendshnm,
        vndclsid,
        trddisct,
        credtlmt,
        minpytyp,
        crlmtdlr,
        vadcdpad,
        comment1,
        minorder,
        shipmthd,
        address3,
        taxinvrecvd,
        workflow_status,
        kpcalhst,
        sbppsded,
        pmwrtidx,
        xpdtoblg,
        workflow_approval_status,
        parvenid,
        revalue_vendor,
        vadcdtro,
        minpypct,
        crtcomdt,
        pmdtkidx,
        duegrper,
        address2,
        vadcdsfr,
        vadcd1099,
        dex_row_id,
        hold,
        city,
        vndcntct,
        chekbkid,
        taxschid,
        userdef2,
        ppstaxrt,
        kperhist,
        creatddt,
        pmtdscix,
        userdef1,
        pmcshidx,
        vendname,
        state,
        pmprchix,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
