with source as (

    select * from {{ source('causa_dbo', 'pop30300') }}

),

renamed as (

    select
        ten99amnt,
        replacegoods,
        ptdusrid,
        ectrx,
        ordistkn,
        ormsctax,
        distknam,
        vchrnmbr,
        ortaxamt,
        exchdate,
        prepaymentamount,
        orsubtot,
        withhamt,
        ratecalc,
        frtamnt,
        actlship,
        simplifd,
        frtschid,
        rcptnote_4,
        origbackoutfreighttaxamt,
        rcptnote_5,
        creatddt,
        ten99type,
        disavamt,
        time1,
        poplnerr,
        refrence,
        ordatkn,
        ratetpid,
        posteddt,
        orddlrat,
        workflow_status,
        voidstts,
        or1099am,
        trdisamt,
        taxinvreqd,
        user2ent,
        currnidx,
        rcptnote_7,
        aplywith,
        pop_hdr_errors_4,
        pymtrmid,
        revaljrnentry,
        rcptnote_8,
        originatingprepaymentamt,
        discdate,
        purchase_misc_taxable,
        bchsourc,
        ormiscamt,
        rcptnote_6,
        txrgnnum,
        rcptnote_3,
        mctrxstt,
        taxschid,
        total_landed_cost_amount,
        orfrttax,
        bachnumb,
        trdpctpr,
        obtaxamt,
        backoutmisctaxamt,
        orfrtamt,
        vnddocnm,
        vendname,
        invoicereceiptdate,
        dscdlram,
        frttxamt,
        shipmthd,
        pophdr2,
        trxsorce,
        ortdisam,
        modifdt,
        origbackoutmisctaxamt,
        taxamnt,
        glpostdt,
        taxinvrecvd,
        xchgrate,
        miscamnt,
        denxrate,
        pophdr1,
        ten99boxnumber,
        revaltrxsource,
        ppstaxrt,
        dex_row_id,
        mscschid,
        bcktxamt,
        ordavamt,
        bsivcttl,
        subtotal,
        invoiceexpected,
        poptype,
        receiptdate,
        rcptnote_1,
        vadcdtro,
        purchase_freight_taxable,
        duedate,
        disavtkn,
        cbvat,
        curncyid,
        dscpctam,
        rcptnote_2,
        tax_date,
        msctxamt,
        backoutfreighttaxamt,
        exgtblid,
        _fivetran_deleted,
        _fivetran_synced,
        upper(trim(poprctnm)) as poprctnm,
        upper(trim(vendorid)) as vendorid

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
