with source as (

    select * from {{ source('causa_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        discamnt,
        disavtkn,
        bktmscam,
        taxamnt,
        ten99amnt,
        modifdt,
        duedate,
        dinvpdof,
        prchdate,
        backouttradedisc,
        mscschid,
        aplywith,
        ten99type,
        shipmthd,
        lngdesc,
        voided,
        curncyid,
        pyenttyp,
        workflow_status,
        bchsourc,
        docdate,
        noteindx,
        gstdsamt,
        dscdlram,
        pstgdate,
        ponumber,
        docnumbr,
        docamnt,
        invoicereceiptdate,
        prctdisc,
        cardname,
        dex_row_id,
        frtamnt,
        docprinted,
        curtrxam,
        trxdscrn,
        vendorid,
        bktfrtam,
        hold,
        simplifd,
        ttlpymts,
        wrofamnt,
        discdate,
        vndchknm,
        distknam,
        bktpuram,
        trdisamt,
        ppsamded,
        tax_date,
        pchschid,
        ten99boxnumber,
        ppstaxrt,
        bnkrcamt,
        ptdusrid,
        trxsorce,
        retnagam,
        mdfusrid,
        pymtrmid,
        ictrx,
        cntrltyp,
        dex_row_ts,
        prchamnt,
        posteddt,
        taxschid,
        cbvat,
        disamtav,
        corrctn,
        pordnmbr,
        pgramsbj,
        frtschid,
        chekbkid,
        un1099am,
        taxinvreqd,
        bachnumb,
        ectrx,
        mscchamt,
        electronic,
        vadcdtro,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
