with

source as (

    select {{ convert_columns('causa_dbo', 'pop30110') }}
    from {{ source('causa_dbo', 'pop30110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        ortaxamt,
        phone2,
        orextcst,
        prmshpdte,
        country,
        itemdesc,
        locncode,
        vendorid,
        unitcost,
        city,
        source_document_line_num,
        source_document_number,
        release,
        projnum,
        releasebydate,
        address3,
        fax,
        freeonboard,
        taxamnt,
        obtaxamt,
        uofm,
        landed_cost_group_id,
        jobnumbr,
        addrsource,
        origprmdate,
        vctnmthd,
        product_indicator,
        odecplcu,
        cmpnynam,
        qtyorder,
        extdcost,
        polneary_6,
        prmdate,
        potype,
        invindx,
        qtycance,
        polneary_1,
        decplcur,
        purchase_site_tax_schedu,
        itemnmbr,
        reqdate,
        polneary_7,
        purchase_item_tax_schedu,
        phone3,
        costcatid,
        polneary_5,
        costcode,
        bcktxamt,
        dex_row_id,
        polneary_8,
        costtype,
        oruntcst,
        purchsitetxschsrc,
        linenumber,
        polnesta,
        vnditnum,
        print_phone_numbergb,
        adrscode,
        ccode,
        phone1,
        contact,
        released_date,
        polneary_2,
        fstrcptdt,
        vnditdsc,
        shipmthd,
        itmtrkop,
        umqtyinb,
        dex_row_ts,
        commntid,
        zipcode,
        currnidx,
        address2,
        polneary_3,
        reqstdby,
        doctype,
        state,
        flags,
        polneary_9,
        lstrcptdt,
        polneary_4,
        lineorigin,
        bsivcttl,
        decplqty,
        address1,
        noninven,
        purchase_iv_item_taxable,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
