with

source as (

    select * from {{ source('causa_dbo', 'pm10000') }}

),

renamed as (

    select
        bachnumb,
        bchsourc,
        vchnumwk,
        curtrxam,
        vadcdtro,
        pgramsbj,
        dex_row_ts,
        crcarddt,
        chekamnt,
        ectrx,
        disamtav,
        pmwrkmsg,
        ppsamded,
        camcbkid,
        trxdscrn,
        tax_date,
        distknam,
        apdstkam,
        pordnmbr,
        mdfusrid,
        bktmscam,
        prctdisc,
        vchrnmbr,
        ptdusrid,
        taxamnt,
        icdists,
        pmwrkms2,
        corrctn,
        un1099am,
        mscchamt,
        curncyid,
        frtschid,
        cheknmbr,
        crcrdamt,
        gstdsamt,
        pmicmsgs,
        camtdate,
        posteddt,
        docprinted,
        dex_row_id,
        simplifd,
        prchamnt,
        doctype,
        lngdesc,
        wrofamnt,
        cntrltyp,
        appldamt,
        docdate,
        cashamnt,
        docnumbr,
        bnkrcamt,
        taxinvreqd,
        retnagam,
        txengcld,
        ictrx,
        trdisamt,
        pchschid,
        electronic,
        ppstaxrt,
        modifdt,
        vaddcdpr,
        invoicereceiptdate,
        cdocnmbr,
        campmtnm,
        duedate,
        backouttradedisc,
        prchdate,
        docamnt,
        cbvat,
        posted,
        aplywith,
        vendorid,
        chamcbid,
        cardname,
        taxschid,
        ten99type,
        sourcdoc,
        pstgdate,
        campynbr,
        pymtrmid,
        workflow_status,
        pstgstus,
        chekbkid,
        bktpuram,
        ccrctnum,
        corrnxst,
        discdate,
        printed,
        ten99amnt,
        frtamnt,
        noteindx,
        ccampynm,
        pmdstmsg,
        mscschid,
        chekdate,
        ten99boxnumber,
        shipmthd,
        bktfrtam,
        chrgamnt,
        vchrncor,
        dscdlram,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
