with source as (

    select * from {{ source('tns_dbo', 'pop10110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        reqdate,
        dex_row_id,
        decplcur,
        ratecalc,
        unitcost,
        ortaxamt,
        vendorid,
        taxamnt,
        obtaxamt,
        state,
        landed_cost_group_id,
        qtycommittedinbaseorig,
        backouttradedisctax,
        oruntcst,
        origbackouttradedisctax,
        currnidx,
        country,
        address1,
        contact,
        costcode,
        polneary_4,
        jobnumbr,
        locncode,
        purchase_item_tax_schedu,
        address2,
        change_order_flag,
        commntid,
        zipcode,
        purchase_iv_item_taxable,
        releasebydate,
        ccode,
        itmtrkop,
        source_document_line_num,
        polneary_5,
        vctnmthd,
        vnditdsc,
        curncyid,
        qtycmtbase,
        polneary_8,
        bcktxamt,
        itemnmbr,
        orextcst,
        lstrcptdt,
        fax,
        adrscode,
        addrsource,
        extdcost,
        polneary_7,
        doctype,
        print_phone_numbergb,
        qtycance,
        shipmthd,
        bsivcttl,
        polneary_6,
        denxrate,
        flags,
        cmpnynam,
        address3,
        noninven,
        uofm,
        invindx,
        odecplcu,
        umqtyinb,
        decplqty,
        costcatid,
        prmshpdte,
        phone2,
        itemdesc,
        dex_row_ts,
        origprmdate,
        vnditnum,
        polnesta,
        qtyuncmtbase,
        costtype,
        polneary_9,
        potype,
        polneary_3,
        prmdate,
        released_date,
        purchase_site_tax_schedu,
        reqstdby,
        plnndspplid,
        source_document_number,
        fstrcptdt,
        release,
        phone1,
        polneary_2,
        lineorigin,
        linenumber,
        purchsitetxschsrc,
        qty_canceled_orig,
        xchgrate,
        projnum,
        product_indicator,
        po_line_status_orig,
        freeonboard,
        qtyorder,
        polneary_1,
        capital_item,
        phone3,
        city,
        opostsub,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
