with source as (

    select * from {{ source('tns_dbo', 'pop30300') }}

),

renamed as (

    select
        dex_row_id,
        disavamt,
        posteddt,
        dscpctam,
        disavtkn,
        trdisamt,
        ppstaxrt,
        or1099am,
        aplywith,
        bachnumb,
        vnddocnm,
        receiptdate,
        origbackoutmisctaxamt,
        taxinvrecvd,
        frtschid,
        taxinvreqd,
        subtotal,
        withhamt,
        frttxamt,
        duedate,
        pophdr2,
        rcptnote_4,
        distknam,
        xchgrate,
        poptype,
        taxschid,
        ten99amnt,
        ormiscamt,
        backoutmisctaxamt,
        total_landed_cost_amount,
        cbvat,
        ordistkn,
        vchrnmbr,
        bsivcttl,
        curncyid,
        tax_date,
        invoiceexpected,
        orfrtamt,
        orsubtot,
        shipmthd,
        currnidx,
        dscdlram,
        frtamnt,
        rcptnote_6,
        pophdr1,
        ortaxamt,
        exchdate,
        invoicereceiptdate,
        rcptnote_8,
        actlship,
        workflow_status,
        revaljrnentry,
        rcptnote_7,
        originatingprepaymentamt,
        ordatkn,
        glpostdt,
        ten99boxnumber,
        ratetpid,
        exgtblid,
        miscamnt,
        time1,
        orddlrat,
        taxamnt,
        ortdisam,
        vadcdtro,
        mscschid,
        ectrx,
        ordavamt,
        voidstts,
        discdate,
        purchase_misc_taxable,
        purchase_freight_taxable,
        origbackoutfreighttaxamt,
        rcptnote_5,
        trxsorce,
        revaltrxsource,
        denxrate,
        simplifd,
        mctrxstt,
        ten99type,
        rcptnote_3,
        obtaxamt,
        ormsctax,
        orfrttax,
        pop_hdr_errors_4,
        bchsourc,
        prepaymentamount,
        txrgnnum,
        vendname,
        poplnerr,
        trdpctpr,
        pymtrmid,
        ratecalc,
        user2ent,
        bcktxamt,
        rcptnote_2,
        backoutfreighttaxamt,
        modifdt,
        rcptnote_1,
        creatddt,
        msctxamt,
        replacegoods,
        refrence,
        ptdusrid,
        _fivetran_deleted,
        _fivetran_synced,
        upper(trim(poprctnm)) as poprctnm,
        upper(trim(vendorid)) as vendorid

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
