with source as (

    select * from {{ source('tns_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        city,
        workflow_priority,
        shipmthd,
        acnmvndr,
        dex_row_id,
        crtcomdt,
        vndcntct,
        comment2,
        txidnmbr,
        vadcdtro,
        parvenid,
        taxinvrecvd,
        minpydlr,
        vaddcdpr,
        pymtrmid,
        writeoff,
        kpcalhst,
        phone3,
        creatddt,
        ccode,
        docfmtid,
        xpdtoblg,
        address3,
        trddisct,
        taxfilenummode,
        credtlmt,
        vendshnm,
        curncyid,
        withholdingformtype,
        revalue_vendor,
        address1,
        modifdt,
        vndclsid,
        purpvidx,
        vadcdpad,
        txrgnnum,
        sbppsded,
        ratetpid,
        userdef1,
        vadcdsfr,
        pmapindx,
        userlang,
        pmrtngix,
        state,
        taxschid,
        hold,
        cbvat,
        crtexpdt,
        chekbkid,
        mxwofamt,
        disgrper,
        vendname,
        ptcshacf,
        workflow_status,
        pmfinidx,
        pmprchix,
        kperhist,
        vadcd1099,
        pmmschix,
        pmtaxidx,
        phnumbr2,
        pmdtkidx,
        rtobutkn,
        zipcode,
        pmwrtidx,
        ten99type,
        faxnumbr,
        kgldsths,
        duegrper,
        userdef2,
        withholdingentitytype,
        onepaypervendinv,
        minpypct,
        govcrpid,
        laborpmttype,
        vendstts,
        comment1,
        crlmtdlr,
        address2,
        govindid,
        minorder,
        pymntpri,
        declid,
        dex_row_ts,
        mxiafvnd,
        prspayee,
        freeonboard,
        brthdate,
        country,
        vndchknm,
        pmdavidx,
        acpuridx,
        ten99boxnumber,
        venddba,
        post_results_to,
        maxindlr,
        upszone,
        ppstaxrt,
        withholdingtype,
        minpytyp,
        kptrxhst,
        noteindx,
        dxvarnum,
        workflow_approval_status,
        phnumbr1,
        pmfrtidx,
        pmcshidx,
        pmtdscix,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
