with source as (

    select * from {{ source('tns_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        wrofamnt,
        voided,
        ppsamded,
        bktpuram,
        dex_row_ts,
        discdate,
        pgramsbj,
        vendorid,
        vndchknm,
        trdisamt,
        cntrltyp,
        retnagam,
        bnkrcamt,
        ten99boxnumber,
        invoicereceiptdate,
        trxsorce,
        distknam,
        corrctn,
        ptdusrid,
        ppstaxrt,
        aplywith,
        dscdlram,
        docprinted,
        ictrx,
        dex_row_id,
        frtamnt,
        simplifd,
        trxdscrn,
        cardname,
        docamnt,
        tax_date,
        ttlpymts,
        ponumber,
        docnumbr,
        bktfrtam,
        modifdt,
        curncyid,
        mscchamt,
        duedate,
        backouttradedisc,
        pyenttyp,
        hold,
        gstdsamt,
        taxamnt,
        bktmscam,
        bchsourc,
        posteddt,
        dinvpdof,
        workflow_status,
        curtrxam,
        docdate,
        mscschid,
        ten99type,
        mdfusrid,
        taxinvreqd,
        noteindx,
        shipmthd,
        taxschid,
        lngdesc,
        prchamnt,
        pstgdate,
        vadcdtro,
        frtschid,
        prctdisc,
        pordnmbr,
        pymtrmid,
        prchdate,
        disamtav,
        un1099am,
        chekbkid,
        electronic,
        ectrx,
        cbvat,
        bachnumb,
        pchschid,
        disavtkn,
        discamnt,
        ten99amnt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
