with source as (

    select * from {{ source('tns_dbo', 'pm10000') }}

),

renamed as (

    select
        bachnumb,
        bchsourc,
        vchnumwk,
        vchrncor,
        cardname,
        sourcdoc,
        txengcld,
        crcrdamt,
        mscchamt,
        camtdate,
        pymtrmid,
        discdate,
        ten99type,
        cheknmbr,
        gstdsamt,
        mscschid,
        bktpuram,
        campynbr,
        distknam,
        apdstkam,
        docamnt,
        chekdate,
        ccrctnum,
        camcbkid,
        cntrltyp,
        cbvat,
        posted,
        aplywith,
        crcarddt,
        ictrx,
        vchrnmbr,
        taxschid,
        mdfusrid,
        ppstaxrt,
        retnagam,
        campmtnm,
        icdists,
        curtrxam,
        backouttradedisc,
        cdocnmbr,
        trdisamt,
        disamtav,
        modifdt,
        chekbkid,
        corrnxst,
        shipmthd,
        ectrx,
        vadcdtro,
        printed,
        appldamt,
        wrofamnt,
        dex_row_ts,
        prchamnt,
        bnkrcamt,
        ccampynm,
        un1099am,
        prctdisc,
        cashamnt,
        pstgstus,
        frtschid,
        pmdstmsg,
        docprinted,
        curncyid,
        dex_row_id,
        workflow_status,
        pmwrkms2,
        docdate,
        chamcbid,
        taxamnt,
        pmicmsgs,
        doctype,
        trxdscrn,
        bktmscam,
        vendorid,
        pmwrkmsg,
        ptdusrid,
        pgramsbj,
        pchschid,
        pordnmbr,
        invoicereceiptdate,
        chekamnt,
        ppsamded,
        docnumbr,
        duedate,
        corrctn,
        prchdate,
        ten99boxnumber,
        lngdesc,
        vaddcdpr,
        noteindx,
        pstgdate,
        dscdlram,
        electronic,
        frtamnt,
        ten99amnt,
        posteddt,
        tax_date,
        taxinvreqd,
        simplifd,
        chrgamnt,
        bktfrtam,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
