with source as (

    select * from {{ source('tns_dbo', 'iv00101') }}

),

renamed as (

    select
        itemnmbr,
        decplcur,
        itmgedsc,
        ivcogsix,
        ivvaridx,
        minshelf2,
        itmplnnngtyp,
        cgsinflx,
        purpvidx,
        selnguom,
        decplqty,
        purmcidx,
        kptrxhst,
        purchase_tax_options,
        purchase_item_tax_schedu,
        lotexpwarndays,
        uscatvls_2,
        altitem1,
        modifdt,
        ivretidx,
        itemtype,
        uscatvls_5,
        lottype,
        lastgensn,
        ivinusix,
        dex_row_ts,
        ivslsidx,
        ivslrnix,
        asmvridx,
        revalue_inventory,
        ivinfidx,
        itemcode,
        noteindx,
        altitem2,
        alwbkord,
        uscatvls_1,
        useqtyoveragetolerance,
        kperhist,
        ivinsvix,
        pricegroup,
        kpcalhst,
        dex_row_id,
        vctnmthd,
        uomschdl,
        uscatvls_3,
        ivsldsix,
        inactive,
        includeindp,
        lot_split_quantity,
        pricmthd,
        tolerance_percentage,
        sttstclvlprcntg,
        locncode,
        uscatvls_6,
        itmtrkop,
        mstrcdty,
        itmtshid,
        prchsuom,
        ivscrvix,
        tcc,
        stndcost,
        taxoptns,
        itemshwt,
        currcost,
        cntryorgn,
        minshelf1,
        ivivofix,
        ivivindx,
        wrntydys,
        cgsmcidx,
        lotexpwarn,
        itmshnam,
        userid,
        useqtyshortagetolerance,
        qtyshorttolerancepercent,
        prclevel,
        dpshpidx,
        qtyovertolerancepercent,
        kpdsthst,
        ivdmgidx,
        uscatvls_4,
        ktacctsr,
        lastgenlot,
        itemdesc,
        itmclscd,
        creatddt,
        pinflidx,
        invmcidx,
        abccode,
        uppvidx,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
