with source as (

    select * from {{ source('tns_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        mdfusrid,
        pymtrmid,
        pordnmbr,
        prchdate,
        docamnt,
        vadcdtro,
        chekbkid,
        frtamnt,
        taxschid,
        pstgdate,
        prctdisc,
        docprinted,
        backouttradedisc,
        docdate,
        disamtav,
        ictrx,
        dscdlram,
        duedate,
        bktmscam,
        taxinvreqd,
        modifdt,
        ppsamded,
        corrctn,
        vndchknm,
        ten99boxnumber,
        voidpdate,
        docnumbr,
        ponumber,
        voided,
        wrofamnt,
        posteddt,
        bchsourc,
        dinvpdof,
        taxamnt,
        workflow_status,
        dex_row_id,
        gstdsamt,
        curncyid,
        trxdscrn,
        tax_date,
        ttlpymts,
        ppstaxrt,
        trdisamt,
        cbvat,
        bachnumb,
        bktfrtam,
        electronic,
        ectrx,
        frtschid,
        curtrxam,
        cardname,
        un1099am,
        pgramsbj,
        vendorid,
        prchamnt,
        discdate,
        hold,
        mscchamt,
        mscschid,
        ten99type,
        discamnt,
        ten99amnt,
        disavtkn,
        dex_row_ts,
        bktpuram,
        ptdusrid,
        distknam,
        pchschid,
        trxsorce,
        simplifd,
        pyenttyp,
        retnagam,
        aplywith,
        shipmthd,
        cntrltyp,
        noteindx,
        invoicereceiptdate,
        lngdesc,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
