with source as (

    select * from {{ source('tns_dbo', 'pop30110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        polneary_2,
        vnditnum,
        polneary_5,
        linenumber,
        purchsitetxschsrc,
        bcktxamt,
        purchase_item_tax_schedu,
        fstrcptdt,
        shipmthd,
        print_phone_numbergb,
        oruntcst,
        dex_row_id,
        released_date,
        dex_row_ts,
        potype,
        polnesta,
        costtype,
        address2,
        adrscode,
        polneary_8,
        ccode,
        phone1,
        product_indicator,
        odecplcu,
        projnum,
        releasebydate,
        phone3,
        polneary_7,
        flags,
        extdcost,
        doctype,
        country,
        polneary_1,
        lineorigin,
        phone2,
        costcode,
        currnidx,
        noninven,
        polneary_6,
        vendorid,
        lstrcptdt,
        purchase_site_tax_schedu,
        source_document_number,
        city,
        reqdate,
        invindx,
        purchase_iv_item_taxable,
        ortaxamt,
        costcatid,
        source_document_line_num,
        cmpnynam,
        decplcur,
        itemnmbr,
        landed_cost_group_id,
        decplqty,
        freeonboard,
        unitcost,
        address3,
        qtycance,
        bsivcttl,
        prmshpdte,
        zipcode,
        qtyorder,
        jobnumbr,
        taxamnt,
        obtaxamt,
        release,
        vctnmthd,
        orextcst,
        itemdesc,
        locncode,
        addrsource,
        contact,
        uofm,
        origprmdate,
        itmtrkop,
        vnditdsc,
        umqtyinb,
        fax,
        polneary_4,
        polneary_9,
        polneary_3,
        prmdate,
        address1,
        commntid,
        reqstdby,
        state,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
