with

source as (

    select * from {{ source('cos_dbo', 'pm10000') }}

),

renamed as (

    select
        bachnumb,
        bchsourc,
        vchnumwk,
        bktpuram,
        corrnxst,
        ccrctnum,
        shipmthd,
        aplywith,
        distknam,
        camcbkid,
        ten99type,
        un1099am,
        chekbkid,
        vchrnmbr,
        ccampynm,
        mdfusrid,
        pmwrkms2,
        mscchamt,
        sourcdoc,
        docdate,
        gstdsamt,
        apdstkam,
        simplifd,
        pmwrkmsg,
        crcrdamt,
        bktmscam,
        ptdusrid,
        campynbr,
        crcarddt,
        pgramsbj,
        ppsamded,
        prctdisc,
        dex_row_ts,
        trxdscrn,
        cntrltyp,
        ten99amnt,
        vadcdtro,
        taxinvreqd,
        cardname,
        electronic,
        taxschid,
        bktfrtam,
        vchrncor,
        modifdt,
        frtamnt,
        campmtnm,
        pymtrmid,
        posted,
        mscschid,
        chekamnt,
        corrctn,
        cbvat,
        appldamt,
        workflow_status,
        chrgamnt,
        docprinted,
        pstgstus,
        discdate,
        posteddt,
        dscdlram,
        camtdate,
        prchamnt,
        vendorid,
        cashamnt,
        noteindx,
        wrofamnt,
        trdisamt,
        frtschid,
        backouttradedisc,
        chekdate,
        doctype,
        prchdate,
        ppstaxrt,
        cdocnmbr,
        curncyid,
        chamcbid,
        ectrx,
        invoicereceiptdate,
        pmicmsgs,
        vaddcdpr,
        duedate,
        taxamnt,
        ten99boxnumber,
        curtrxam,
        pmdstmsg,
        printed,
        retnagam,
        bnkrcamt,
        txengcld,
        pchschid,
        pordnmbr,
        icdists,
        tax_date,
        docnumbr,
        pstgdate,
        ictrx,
        docamnt,
        cheknmbr,
        disamtav,
        lngdesc,
        dex_row_id,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
