with source as (

    select * from {{ source('slgp_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        comdlram,
        eftflag,
        saledate,
        costamnt,
        directdebit,
        ppsamded,
        slstercd,
        taxschid,
        corrctn,
        docdate,
        slsamnt,
        backouttradedisc,
        delete1,
        disavtkn,
        miscamnt,
        tax_date,
        frtschid,
        taxamnt,
        mscschid,
        agngbukt,
        wrofamnt,
        dex_row_ts,
        slprsnid,
        dex_row_id,
        shipmthd,
        lstedtdt,
        glpostdt,
        frtamnt,
        cbkidcrd,
        bktmscam,
        cashamnt,
        postdate,
        bchsourc,
        aplywith,
        slschdid,
        curtrxam,
        distknam,
        voiddate,
        cbkidcsh,
        duedate,
        pstusrid,
        pymtrmid,
        cshrctyp,
        electronic,
        ectrx,
        bachnumb,
        dscdlram,
        trxsorce,
        lstusred,
        voidstts,
        bktslsam,
        gstdsamt,
        curncyid,
        ortrxamt,
        trdisamt,
        cheknmbr,
        cbkidchk,
        dinvpdof,
        cprcstnm,
        discrtnd,
        trxdscrn,
        cspornbr,
        bktfrtam,
        noteindx,
        disavamt,
        discdate,
        dscpctam,
        factoring,
        adrscode,
        simplifd,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
