with

source as (

    select * from {{ source('slgp_dbo', 'pm10000') }}

),

renamed as (

    select
        shipmthd,
        dex_row_ts,
        distknam,
        ccrctnum,
        chekbkid,
        vchrnmbr,
        ccampynm,
        mdfusrid,
        camcbkid,
        apdstkam,
        chekamnt,
        pgramsbj,
        docnumbr,
        pymtrmid,
        cheknmbr,
        pordnmbr,
        cntrltyp,
        crcarddt,
        disamtav,
        lngdesc,
        ectrx,
        ppsamded,
        trxdscrn,
        pmwrkms2,
        dex_row_id,
        aplywith,
        bachnumb,
        un1099am,
        pmicmsgs,
        sourcdoc,
        cardname,
        prctdisc,
        bktmscam,
        ptdusrid,
        campynbr,
        icdists,
        retnagam,
        appldamt,
        wrofamnt,
        docprinted,
        crcrdamt,
        curncyid,
        frtschid,
        vaddcdpr,
        mscchamt,
        curtrxam,
        gstdsamt,
        backouttradedisc,
        prchamnt,
        noteindx,
        ictrx,
        pmwrkmsg,
        chamcbid,
        trdisamt,
        vendorid,
        doctype,
        bnkrcamt,
        invoicereceiptdate,
        cashamnt,
        modifdt,
        duedate,
        dscdlram,
        simplifd,
        taxschid,
        pchschid,
        txengcld,
        printed,
        campmtnm,
        electronic,
        taxinvreqd,
        docdate,
        chekdate,
        ppstaxrt,
        docamnt,
        corrnxst,
        bktfrtam,
        frtamnt,
        discdate,
        vchnumwk,
        posteddt,
        mscschid,
        taxamnt,
        ten99type,
        bchsourc,
        prchdate,
        cbvat,
        vchrncor,
        corrctn,
        camtdate,
        chrgamnt,
        tax_date,
        ten99boxnumber,
        vadcdtro,
        posted,
        workflow_status,
        pstgdate,
        pstgstus,
        ten99amnt,
        bktpuram,
        pmdstmsg,
        cdocnmbr,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
