with source as (

    select * from {{ source('slgp_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        curtrxam,
        dex_row_ts,
        voidpdate,
        taxinvreqd,
        mscschid,
        bachnumb,
        bktfrtam,
        mscchamt,
        hold,
        discamnt,
        bchsourc,
        ten99amnt,
        shipmthd,
        pyenttyp,
        disavtkn,
        tax_date,
        discdate,
        curncyid,
        corrctn,
        lngdesc,
        gstdsamt,
        taxamnt,
        workflow_status,
        ictrx,
        docprinted,
        un1099am,
        mdfusrid,
        taxschid,
        frtschid,
        ppstaxrt,
        prchamnt,
        vadcdtro,
        bktmscam,
        pordnmbr,
        disamtav,
        aplywith,
        trdisamt,
        dinvpdof,
        simplifd,
        ppsamded,
        posteddt,
        backouttradedisc,
        chekbkid,
        ten99boxnumber,
        voided,
        retnagam,
        docdate,
        modifdt,
        vndchknm,
        cntrltyp,
        dex_row_id,
        wrofamnt,
        cbvat,
        pchschid,
        docamnt,
        bktpuram,
        duedate,
        prctdisc,
        frtamnt,
        pymtrmid,
        pstgdate,
        noteindx,
        ponumber,
        docnumbr,
        electronic,
        trxsorce,
        ectrx,
        ttlpymts,
        prchdate,
        dscdlram,
        cardname,
        invoicereceiptdate,
        distknam,
        ptdusrid,
        pgramsbj,
        vendorid,
        trxdscrn,
        ten99type,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
