# This check ensures you haven't committed any secrets to the repository
name: secrets-scanning-ci-4

parameters:
  - name: jobName
    default: 'SecretsCI'
  - name: jobDisplay
    default: 'Secrets Scanning'

resources:
  pipelines:
    - pipeline: python-ci-3
      source: python-ci-3
      trigger: true

trigger: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: ${{ parameters.jobName }}
    timeoutInMinutes: 10
    displayName: ${{ parameters.jobDisplay }}

    workspace:
      clean: outputs

    steps:
      # Checkout repo
      - checkout: self
        fetchDepth: 1
        clean: true

      # Install detect-secrets
      - script: |
          pip install detect-secrets
        displayName: Install detect-secrets

      # Test detect-secrets installation
      - script: |
          echo "detect-secrets Version:" && detect-secrets --version
        displayName: Test the install

      # Scan codebase for passwords, API keys etc.
      - script: |
          # backup the list of known secrets
          cp .secrets.baseline .secrets.new

          # find all the secrets in the repository
          detect-secrets scan --baseline .secrets.new $(find . -type f ! -name '.secrets.*' ! -path '*/.git*')

          # if there is any difference between the known and newly detected secrets, break the build
          list_secrets() 
          { jq -r '.results | keys[] as $key | "\($key),\(.[$key] | .[] | .hashed_secret)"' "$1" | sort; }

          if ! diff <(list_secrets .secrets.baseline) <(list_secrets .secrets.new) >&2; then
            echo "Detected new secrets in the repo" >&2
            exit 1
          fi
        displayName: Scan codebase for secrets
