with

source as (

    select * from {{ source('tnsc_dbo', 'pm10000') }}

),

renamed as (

    select
        bachnumb,
        bchsourc,
        vchnumwk,
        duedate,
        bktfrtam,
        frtamnt,
        frtschid,
        un1099am,
        docdate,
        modifdt,
        ten99type,
        trxdscrn,
        chamcbid,
        prchdate,
        retnagam,
        crcrdamt,
        ectrx,
        cdocnmbr,
        curncyid,
        mscchamt,
        invoicereceiptdate,
        backouttradedisc,
        bktpuram,
        gstdsamt,
        icdists,
        posteddt,
        noteindx,
        cntrltyp,
        trdisamt,
        doctype,
        dscdlram,
        campmtnm,
        ptdusrid,
        vadcdtro,
        camcbkid,
        taxschid,
        ccampynm,
        apdstkam,
        shipmthd,
        chekamnt,
        crcarddt,
        docprinted,
        pymtrmid,
        mscschid,
        pgramsbj,
        ppsamded,
        dex_row_ts,
        txengcld,
        vchrncor,
        workflow_status,
        sourcdoc,
        chekbkid,
        taxamnt,
        vchrnmbr,
        taxinvreqd,
        ictrx,
        ccrctnum,
        posted,
        bktmscam,
        aplywith,
        cardname,
        simplifd,
        pmdstmsg,
        chrgamnt,
        corrnxst,
        tax_date,
        cbvat,
        campynbr,
        prctdisc,
        appldamt,
        wrofamnt,
        electronic,
        pstgstus,
        ten99amnt,
        vaddcdpr,
        curtrxam,
        camtdate,
        prchamnt,
        discdate,
        ten99boxnumber,
        mdfusrid,
        corrctn,
        docnumbr,
        chekdate,
        bnkrcamt,
        pstgdate,
        vendorid,
        cashamnt,
        printed,
        pchschid,
        pordnmbr,
        dex_row_id,
        pmwrkmsg,
        pmicmsgs,
        pmwrkms2,
        disamtav,
        distknam,
        cheknmbr,
        lngdesc,
        docamnt,
        ppstaxrt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
