with source as (

    select * from {{ source('tnsc_dbo', 'pop30300') }}

),

renamed as (

    select
        poprctnm,
        trdisamt,
        originatingprepaymentamt,
        revaltrxsource,
        xchgrate,
        glpostdt,
        ordatkn,
        exgtblid,
        replacegoods,
        tax_date,
        disavamt,
        simplifd,
        dscpctam,
        ratetpid,
        pymtrmid,
        pop_hdr_errors_4,
        shipmthd,
        rcptnote_7,
        currnidx,
        total_landed_cost_amount,
        rcptnote_1,
        dscdlram,
        workflow_status,
        rcptnote_6,
        modifdt,
        backoutmisctaxamt,
        invoicereceiptdate,
        ectrx,
        trdpctpr,
        vendorid,
        orfrtamt,
        mctrxstt,
        ten99type,
        msctxamt,
        frtamnt,
        vchrnmbr,
        curncyid,
        distknam,
        discdate,
        taxinvreqd,
        purchase_misc_taxable,
        bachnumb,
        time1,
        backoutfreighttaxamt,
        voidstts,
        trxsorce,
        aplywith,
        dex_row_id,
        disavtkn,
        rcptnote_4,
        vnddocnm,
        obtaxamt,
        vadcdtro,
        posteddt,
        rcptnote_3,
        frttxamt,
        subtotal,
        mscschid,
        rcptnote_2,
        bcktxamt,
        rcptnote_5,
        origbackoutfreighttaxamt,
        refrence,
        ten99boxnumber,
        duedate,
        rcptnote_8,
        miscamnt,
        actlship,
        taxamnt,
        frtschid,
        ratecalc,
        orddlrat,
        ordavamt,
        taxinvrecvd,
        ordistkn,
        exchdate,
        ormsctax,
        creatddt,
        ortdisam,
        revaljrnentry,
        ten99amnt,
        prepaymentamount,
        orsubtot,
        ptdusrid,
        bsivcttl,
        cbvat,
        poplnerr,
        pophdr1,
        ortaxamt,
        txrgnnum,
        vendname,
        bchsourc,
        receiptdate,
        withhamt,
        orfrttax,
        denxrate,
        taxschid,
        purchase_freight_taxable,
        poptype,
        pophdr2,
        user2ent,
        or1099am,
        ppstaxrt,
        origbackoutmisctaxamt,
        ormiscamt,
        invoiceexpected,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
