with

source as (

    select {{ convert_columns('tnsc_dbo', 'pop10110') }}
    from {{ source('tnsc_dbo', 'pop10110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        polneary_1,
        polneary_4,
        city,
        costcatid,
        uofm,
        taxamnt,
        vnditnum,
        dex_row_ts,
        purchase_iv_item_taxable,
        purchase_site_tax_schedu,
        polneary_7,
        cmpnynam,
        decplcur,
        qty_canceled_orig,
        currnidx,
        bcktxamt,
        flags,
        print_phone_numbergb,
        qtycmtbase,
        unitcost,
        product_indicator,
        itemnmbr,
        opostsub,
        vctnmthd,
        orextcst,
        address3,
        projnum,
        invindx,
        purchsitetxschsrc,
        phone2,
        itmtrkop,
        source_document_line_num,
        linenumber,
        phone1,
        plnndspplid,
        vnditdsc,
        xchgrate,
        reqdate,
        change_order_flag,
        ccode,
        lstrcptdt,
        curncyid,
        source_document_number,
        jobnumbr,
        reqstdby,
        ortaxamt,
        qtycommittedinbaseorig,
        adrscode,
        polneary_3,
        origprmdate,
        polneary_2,
        potype,
        landed_cost_group_id,
        lineorigin,
        origbackouttradedisctax,
        fax,
        qtyuncmtbase,
        release,
        qtyorder,
        releasebydate,
        decplqty,
        denxrate,
        shipmthd,
        zipcode,
        bsivcttl,
        locncode,
        umqtyinb,
        contact,
        phone3,
        costcode,
        capital_item,
        freeonboard,
        commntid,
        polneary_6,
        dex_row_id,
        address2,
        country,
        doctype,
        polneary_5,
        odecplcu,
        noninven,
        qtycance,
        po_line_status_orig,
        vendorid,
        extdcost,
        released_date,
        address1,
        itemdesc,
        oruntcst,
        prmshpdte,
        purchase_item_tax_schedu,
        addrsource,
        state,
        prmdate,
        polneary_9,
        obtaxamt,
        polneary_8,
        ratecalc,
        fstrcptdt,
        polnesta,
        costtype,
        backouttradedisctax,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
