with source as (

    select * from {{ source('tnsc_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        disamtav,
        taxschid,
        docnumbr,
        invoicereceiptdate,
        retnagam,
        pordnmbr,
        bktpuram,
        discdate,
        aplywith,
        curncyid,
        workflow_status,
        shipmthd,
        bchsourc,
        pyenttyp,
        docamnt,
        mdfusrid,
        pymtrmid,
        prctdisc,
        tax_date,
        dex_row_ts,
        corrctn,
        ttlpymts,
        mscschid,
        noteindx,
        cntrltyp,
        pgramsbj,
        ictrx,
        vendorid,
        docprinted,
        trxdscrn,
        cardname,
        distknam,
        hold,
        ten99type,
        frtamnt,
        dscdlram,
        prchdate,
        curtrxam,
        trxsorce,
        bktfrtam,
        ponumber,
        posteddt,
        ptdusrid,
        duedate,
        cbvat,
        lngdesc,
        gstdsamt,
        mscchamt,
        discamnt,
        pstgdate,
        voided,
        disavtkn,
        taxamnt,
        simplifd,
        ten99amnt,
        docdate,
        vndchknm,
        trdisamt,
        un1099am,
        bktmscam,
        wrofamnt,
        frtschid,
        taxinvreqd,
        dinvpdof,
        pchschid,
        prchamnt,
        ppstaxrt,
        modifdt,
        dex_row_id,
        ectrx,
        chekbkid,
        voidpdate,
        backouttradedisc,
        electronic,
        vadcdtro,
        ten99boxnumber,
        bachnumb,
        ppsamded,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
