with source as (

    select * from {{ source('tnsc_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        faxnumbr,
        rtobutkn,
        vadcd1099,
        dex_row_ts,
        declid,
        pmwrtidx,
        kperhist,
        vadcdpad,
        dxvarnum,
        ptcshacf,
        mxwofamt,
        post_results_to,
        brthdate,
        pmtdscix,
        noteindx,
        vndchknm,
        minpytyp,
        pmcshidx,
        comment1,
        pmprchix,
        workflow_priority,
        kgldsths,
        ten99boxnumber,
        curncyid,
        freeonboard,
        vendshnm,
        vndclsid,
        pmdtkidx,
        writeoff,
        vendname,
        vaddcdpr,
        crlmtdlr,
        prspayee,
        minorder,
        pymntpri,
        taxschid,
        address2,
        state,
        purpvidx,
        userdef1,
        txrgnnum,
        userdef2,
        vndcntct,
        address1,
        ratetpid,
        ten99type,
        crtexpdt,
        withholdingentitytype,
        docfmtid,
        acnmvndr,
        workflow_approval_status,
        phone3,
        city,
        mxiafvnd,
        pmapindx,
        address3,
        pymtrmid,
        laborpmttype,
        modifdt,
        chekbkid,
        withholdingtype,
        vadcdsfr,
        pmfrtidx,
        comment2,
        kpcalhst,
        pmdavidx,
        cbvat,
        ppstaxrt,
        vadcdtro,
        minpypct,
        shipmthd,
        disgrper,
        duegrper,
        kptrxhst,
        taxinvrecvd,
        withholdingformtype,
        parvenid,
        pmrtngix,
        workflow_status,
        maxindlr,
        crtcomdt,
        trddisct,
        country,
        taxfilenummode,
        revalue_vendor,
        hold,
        ccode,
        dex_row_id,
        userlang,
        govcrpid,
        xpdtoblg,
        phnumbr1,
        pmfinidx,
        creatddt,
        vendstts,
        acpuridx,
        zipcode,
        onepaypervendinv,
        govindid,
        pmtaxidx,
        pmmschix,
        upszone,
        minpydlr,
        credtlmt,
        venddba,
        phnumbr2,
        sbppsded,
        txidnmbr,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
