with source as (

    select * from {{ source('tnsc_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        fnchatyp,
        mxwoftyp,
        custpriority,
        rmcshacc,
        prstadcd,
        hold,
        rmaracc,
        duegrper,
        shipcomplete,
        staddrcd,
        disgrper,
        prbtadcd,
        custname,
        crlmtpam,
        phone3,
        address3,
        crcrdnum,
        kpdsthst,
        custdisc,
        userdef1,
        kperhist,
        taxschid,
        mxwrofam,
        bnkbrnch,
        revalue_customer,
        cprcstnm,
        address1,
        includeindp,
        minpypct,
        taxexmt1,
        minpytyp,
        fnchpcnt,
        cntcprsn,
        balnctyp,
        bankname,
        shipmthd,
        ratetpid,
        city,
        send_email_statements,
        finchid,
        rmovrpymtwrtoffacctidx,
        custclas,
        dex_row_id,
        gpsfointegrationid,
        rmsoracc,
        shrtname,
        taxexmt2,
        stmtcycl,
        rmtakacc,
        rmavacc,
        crcardid,
        salsterr,
        ccrdxpdt,
        kpcalhst,
        address2,
        state,
        modifdt,
        inactive,
        curncyid,
        rmcosacc,
        orderfulfilldefault,
        pymtrmid,
        prclevel,
        phone2,
        userlang,
        cbvat,
        slprsnid,
        noteindx,
        upszone,
        post_results_to,
        govcrpid,
        ccode,
        minpydlr,
        crlmtper,
        finchdlr,
        userdef2,
        integrationsource,
        frstindt,
        dex_row_ts,
        creatddt,
        rmivacc,
        comment2,
        phone1,
        adrscode,
        crlmtamt,
        kptrxhst,
        rmfcgacc,
        fax,
        docfmtid,
        crlmttyp,
        comment1,
        stmtname,
        zip,
        rmslsacc,
        chekbkid,
        integrationid,
        rmwracc,
        declid,
        defcacty,
        txrgnnum,
        country,
        govindid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
