with source as (

    select * from {{ source('tnsc_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        slprsnid,
        cbkidchk,
        saledate,
        agngbukt,
        mscschid,
        cprcstnm,
        dscdlram,
        eftflag,
        bktslsam,
        corrctn,
        docdate,
        trdisamt,
        tax_date,
        gstdsamt,
        pstusrid,
        ortrxamt,
        slstercd,
        frtschid,
        ectrx,
        aplywith,
        discrtnd,
        disavamt,
        discdate,
        noteindx,
        dscpctam,
        curncyid,
        bktfrtam,
        trxdscrn,
        delete1,
        cbkidcrd,
        costamnt,
        slschdid,
        ppsamded,
        adrscode,
        duedate,
        comdlram,
        slsamnt,
        simplifd,
        lstusred,
        electronic,
        backouttradedisc,
        cspornbr,
        taxamnt,
        dinvpdof,
        miscamnt,
        disavtkn,
        cheknmbr,
        trxsorce,
        voidstts,
        glpostdt,
        curtrxam,
        pymtrmid,
        lstedtdt,
        wrofamnt,
        cbkidcsh,
        taxschid,
        dex_row_ts,
        bktmscam,
        cshrctyp,
        frtamnt,
        postdate,
        factoring,
        dex_row_id,
        bchsourc,
        directdebit,
        distknam,
        voiddate,
        bachnumb,
        shipmthd,
        cashamnt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
