with source as (

    select * from {{ source('tnsc_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        vendorid,
        ttlpymts,
        bnkrcamt,
        un1099am,
        voided,
        vndchknm,
        dex_row_id,
        modifdt,
        ppstaxrt,
        trdisamt,
        pchschid,
        cbvat,
        ten99boxnumber,
        bktfrtam,
        pgramsbj,
        prchamnt,
        prchdate,
        dinvpdof,
        ponumber,
        pymtrmid,
        docdate,
        simplifd,
        curtrxam,
        trxdscrn,
        docprinted,
        bktpuram,
        lngdesc,
        cardname,
        distknam,
        trxsorce,
        shipmthd,
        noteindx,
        prctdisc,
        cntrltyp,
        aplywith,
        retnagam,
        ptdusrid,
        mscschid,
        docamnt,
        hold,
        pyenttyp,
        taxinvreqd,
        discdate,
        frtamnt,
        curncyid,
        bktmscam,
        ten99type,
        docnumbr,
        backouttradedisc,
        bachnumb,
        bchsourc,
        pstgdate,
        discamnt,
        dscdlram,
        ten99amnt,
        disamtav,
        disavtkn,
        mscchamt,
        posteddt,
        invoicereceiptdate,
        mdfusrid,
        ictrx,
        chekbkid,
        taxschid,
        ppsamded,
        ectrx,
        vadcdtro,
        electronic,
        dex_row_ts,
        frtschid,
        corrctn,
        gstdsamt,
        taxamnt,
        tax_date,
        wrofamnt,
        duedate,
        pordnmbr,
        workflow_status,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
