with source as (

    select * from {{ source('slade_sap', 'lfa1') }}

),

renamed as (

    select

        bahns,
        psovn,
        qssysdat,
        uptim_simp_tm,
        loevm,
        taxbs,
        sperm,
        vbund,
        telf2,
        land1,
        esrnr,
        qssys,
        begru,
        erdat,
        kraus,
        pfach,
        stenr,
        ipisp,
        ltsna,
        plkal,
        psois,
        zzcertificate,
        bbbnr,
        werks,
        fiskn,
        adrnr,
        sperr,
        spras,
        confs,
        telf1,
        fisku,
        stcd1,
        stcd4,
        xlfza,
        revdb,
        gbdat_simp_dt,
        telx1,
        lzone,
        sortl,
        stkza,
        pstl2,
        staging_time,
        regio,
        j_1kftind,
        stkzn,
        qssysdat_simp_dt,
        datlt,
        werkr,
        pson3,
        uptim,
        stgdl,
        sexkz,
        mcod3,
        stcd3,
        j_sc_capital,
        psost,
        konzs,
        regss,
        profs,
        lnrza,
        duefl,
        dtams,
        psotl,
        anred,
        j_sc_currency,
        stras,
        name4,
        telbx,
        bbsnr,
        pson2,
        gbort,
        mandt,
        scheduling_type,
        mcod2,
        stceg,
        xzemp,
        brsch,
        sfrgr,
        txjcd,
        sperz,
        podkzb,
        pstlz,
        lfurl,
        name3,
        lifnr,
        bubkz,
        j_1kfrepre,
        ort02,
        submi_relevant,
        pson1,
        teltx,
        mcod1,
        revdb_simp_dt,
        xcpdk,
        stcdt,
        psofg,
        emnfr,
        kunnr,
        pfort,
        psohs,
        ernam,
        telfx,
        erdat_simp_dt,
        name2,
        j_1kftbus,
        stkzu,
        ort01,
        ktock,
        updat_simp_dt,
        dtaws,
        actss,
        fityp,
        sperq,
        nodel,
        gbdat,
        ktokk,
        carrier_conf,
        updat,
        pmt_office,
        dlgrp,
        scacd,
        alc,
        name1,
        transport_chain,
        stcd2,
        zzggcert,
        zzasccert,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
