with source as (

    select * from {{ source('slade_sap', 't001') }}

),

renamed as (

    select

        fdbuk,
        mregl,
        xkkbi,
        xeink,
        kopim,
        waabw,
        periv,
        fmhrdate,
        fm_derive_acc,
        umkrs,
        bapovar,
        txkrs,
        impda,
        xvalv,
        kokfi,
        mwskv,
        bukrs_glob,
        xbbko,
        rcomp,
        xgsbe,
        xbbba,
        xfdmm,
        dtaxr,
        dttdsp,
        dtamtc,
        buvar,
        wfvar,
        xcession,
        xextb,
        dkweg,
        xfmca,
        xbbbe,
        xfdsd,
        xvvwa,
        xjvaa,
        xfdis,
        waers,
        mwska,
        kkber,
        wt_newwt,
        spras,
        fstvare,
        txjcd,
        xmwsn,
        xnegp,
        land1,
        xfmcb,
        ebukr,
        xbbbf,
        butxt,
        xcos,
        ktopl,
        xkdft,
        xgjrv,
        opvar,
        dttaxc,
        mandt,
        xstdt,
        fstva,
        ktop2,
        fikrs,
        pp_pdate,
        fmhrdate_simp_dt,
        xsplt,
        xfmco,
        xprod,
        stceg,
        xcovr,
        bukrs,
        ort01,
        offsacct,
        surccm,
        adrnr,
        infmt,
        xslta,
        dtprov,
        xskfn,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
