with source as (

    select * from {{ source('slade_sap', 'bkpf') }}

),

renamed as (

    select

        belnr,
        bukrs,
        gjahr,
        mandt,
        hwae2,
        duefl,
        brnch,
        psoty,
        psotm_simp_tm,
        grpid,
        bldat,
        psodt,
        psobt,
        glvor,
        xusvr,
        budat_simp_dt,
        xblnr_alt,
        offset_refer_dat_simp_dt,
        dokid,
        awsys,
        kurs2,
        sname,
        frath,
        stodt_simp_dt,
        xstov,
        xref2_hd,
        offset_refer_dat,
        blart,
        psotm,
        intdate,
        monat,
        usnam,
        stodt,
        xrueb,
        propmano,
        fm_umart,
        hwae3,
        umrd3,
        wwert_simp_dt,
        wwert,
        knumv,
        basw2,
        xsnet,
        curt2,
        exclude_flag,
        arcid,
        xref1_hd,
        awkey,
        numpg,
        stjah,
        reindat,
        xnetb,
        offset_status,
        budat,
        iblar,
        intform,
        kurs3,
        ccnum,
        fikrs,
        bktxt,
        psozl,
        aedat,
        aedat_simp_dt,
        cpudt_simp_dt,
        kuty2,
        reindat_simp_dt,
        intdate_simp_dt,
        kzwrs,
        dbblg,
        stgrd,
        psofn,
        basw3,
        tcode,
        ppnam,
        ldgrp,
        bldat_simp_dt,
        kzkrs,
        curt3,
        stblg,
        psobt_simp_dt,
        adisc,
        cpudt,
        bstat,
        sampled,
        ssblk,
        cputm_simp_tm,
        penrc,
        waers,
        lotkz,
        bvorg,
        psodt_simp_dt,
        xwvof,
        kuty3,
        ausbk,
        upddt,
        cputm,
        hwaer,
        xreversal,
        xblnr,
        rldnr,
        batch,
        upddt_simp_dt,
        kursf,
        psoks,
        psosg,
        xmwst,
        psoak,
        awtyp,
        txkrs,
        blind,
        ccins,
        umrd2,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
