with

source as (

    select * from {{ source('tfc_dbo', 'pm10000') }}

),

renamed as (

    select
        bachnumb,
        bchsourc,
        vchnumwk,
        vendorid,
        campmtnm,
        docamnt,
        dex_row_id,
        taxschid,
        corrctn,
        chamcbid,
        pchschid,
        gstdsamt,
        corrnxst,
        bktfrtam,
        modifdt,
        mscchamt,
        retnagam,
        ten99boxnumber,
        vaddcdpr,
        simplifd,
        duedate,
        backouttradedisc,
        curncyid,
        trdisamt,
        pgramsbj,
        crcrdamt,
        cntrltyp,
        cdocnmbr,
        dscdlram,
        sourcdoc,
        cardname,
        apdstkam,
        trxdscrn,
        noteindx,
        mscschid,
        taxinvreqd,
        frtschid,
        bktpuram,
        electronic,
        ptdusrid,
        vchrncor,
        campynbr,
        workflow_status,
        ten99type,
        posted,
        vchrnmbr,
        discdate,
        ccrctnum,
        pymtrmid,
        chrgamnt,
        chekamnt,
        chekdate,
        cbvat,
        pstgstus,
        frtamnt,
        ten99amnt,
        doctype,
        disamtav,
        lngdesc,
        camtdate,
        ccampynm,
        tax_date,
        taxamnt,
        pordnmbr,
        shipmthd,
        ppsamded,
        docnumbr,
        pmwrkms2,
        camcbkid,
        mdfusrid,
        docprinted,
        posteddt,
        chekbkid,
        dex_row_ts,
        curtrxam,
        pmwrkmsg,
        pmdstmsg,
        printed,
        vadcdtro,
        pstgdate,
        ppstaxrt,
        bktmscam,
        pmicmsgs,
        ictrx,
        prchamnt,
        cashamnt,
        wrofamnt,
        appldamt,
        invoicereceiptdate,
        ectrx,
        prchdate,
        distknam,
        txengcld,
        bnkrcamt,
        un1099am,
        prctdisc,
        cheknmbr,
        icdists,
        aplywith,
        crcarddt,
        docdate,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
