with

source as (

    select * from {{ source('tfc_dbo', 'pop10110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        polneary_6,
        bsivcttl,
        polneary_3,
        decplcur,
        polneary_9,
        itemnmbr,
        invindx,
        adrscode,
        purchase_site_tax_schedu,
        ratecalc,
        cmpnynam,
        itemdesc,
        print_phone_numbergb,
        costcatid,
        flags,
        qtyorder,
        qtyuncmtbase,
        phone1,
        qtycance,
        phone2,
        product_indicator,
        qty_canceled_orig,
        bcktxamt,
        qtycmtbase,
        addrsource,
        reqdate,
        address3,
        fax,
        potype,
        releasebydate,
        capital_item,
        source_document_line_num,
        vctnmthd,
        orextcst,
        shipmthd,
        lineorigin,
        denxrate,
        source_document_number,
        itmtrkop,
        jobnumbr,
        vnditnum,
        reqstdby,
        vnditdsc,
        uofm,
        currnidx,
        extdcost,
        change_order_flag,
        umqtyinb,
        polneary_7,
        curncyid,
        ccode,
        plnndspplid,
        linenumber,
        backouttradedisctax,
        landed_cost_group_id,
        prmshpdte,
        polneary_8,
        taxamnt,
        obtaxamt,
        state,
        phone3,
        commntid,
        ortaxamt,
        lstrcptdt,
        release,
        costcode,
        contact,
        opostsub,
        oruntcst,
        noninven,
        unitcost,
        zipcode,
        doctype,
        costtype,
        address1,
        po_line_status_orig,
        purchase_item_tax_schedu,
        locncode,
        fstrcptdt,
        odecplcu,
        prmdate,
        polneary_4,
        vendorid,
        released_date,
        polneary_5,
        freeonboard,
        origprmdate,
        decplqty,
        dex_row_ts,
        country,
        projnum,
        address2,
        polnesta,
        purchsitetxschsrc,
        xchgrate,
        city,
        polneary_1,
        purchase_iv_item_taxable,
        origbackouttradedisctax,
        polneary_2,
        dex_row_id,
        qtycommittedinbaseorig,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
