with source as (

    select * from {{ source('tfc_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        ppstaxrt,
        trxdscrn,
        pgramsbj,
        retnagam,
        disamtav,
        cardname,
        pstgdate,
        lngdesc,
        simplifd,
        tax_date,
        bktpuram,
        dex_row_id,
        bachnumb,
        discdate,
        docprinted,
        docamnt,
        dex_row_ts,
        docdate,
        ponumber,
        cbvat,
        vendorid,
        noteindx,
        shipmthd,
        duedate,
        posteddt,
        frtamnt,
        ten99boxnumber,
        hold,
        dscdlram,
        trxsorce,
        modifdt,
        distknam,
        ptdusrid,
        mscschid,
        aplywith,
        vadcdtro,
        pordnmbr,
        electronic,
        prchdate,
        workflow_status,
        mdfusrid,
        curtrxam,
        pyenttyp,
        chekbkid,
        taxschid,
        dinvpdof,
        pymtrmid,
        ectrx,
        gstdsamt,
        taxamnt,
        prchamnt,
        mscchamt,
        prctdisc,
        ictrx,
        ttlpymts,
        bktfrtam,
        disavtkn,
        docnumbr,
        discamnt,
        ten99amnt,
        pchschid,
        cntrltyp,
        curncyid,
        trdisamt,
        bnkrcamt,
        bchsourc,
        ten99type,
        un1099am,
        voided,
        invoicereceiptdate,
        bktmscam,
        ppsamded,
        wrofamnt,
        vndchknm,
        taxinvreqd,
        frtschid,
        backouttradedisc,
        corrctn,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
