with source as (

    select * from {{ source('tfc_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        directdebit,
        cbkidcsh,
        bachnumb,
        pstusrid,
        cashamnt,
        discrtnd,
        bchsourc,
        costamnt,
        glpostdt,
        disavtkn,
        cprcstnm,
        corrctn,
        eftflag,
        lstusred,
        dex_row_ts,
        duedate,
        trxsorce,
        curncyid,
        voiddate,
        backouttradedisc,
        cbkidchk,
        cspornbr,
        adrscode,
        aplywith,
        docdate,
        noteindx,
        postdate,
        delete1,
        voidstts,
        ppsamded,
        trxdscrn,
        bktslsam,
        electronic,
        ectrx,
        dscdlram,
        saledate,
        taxschid,
        frtamnt,
        trdisamt,
        curtrxam,
        disavamt,
        gstdsamt,
        frtschid,
        factoring,
        simplifd,
        bktfrtam,
        ortrxamt,
        tax_date,
        bktmscam,
        taxamnt,
        wrofamnt,
        slstercd,
        lstedtdt,
        cheknmbr,
        miscamnt,
        dex_row_id,
        dscpctam,
        dinvpdof,
        slsamnt,
        distknam,
        mscschid,
        cshrctyp,
        comdlram,
        agngbukt,
        discdate,
        cbkidcrd,
        slschdid,
        pymtrmid,
        shipmthd,
        slprsnid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
