with source as (

    select * from {{ source('tfc_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        custdisc,
        rmwracc,
        staddrcd,
        integrationid,
        ratetpid,
        kpcalhst,
        custpriority,
        bnkbrnch,
        frstindt,
        disgrper,
        crlmttyp,
        mxwoftyp,
        inactive,
        comment2,
        phone3,
        kperhist,
        minpypct,
        mxwrofam,
        rmivacc,
        rmovrpymtwrtoffacctidx,
        cbvat,
        rmslsacc,
        address3,
        crcrdnum,
        modifdt,
        upszone,
        userdef1,
        finchid,
        includeindp,
        revalue_customer,
        rmaracc,
        address1,
        prstadcd,
        taxexmt1,
        cntcprsn,
        cprcstnm,
        rmcshacc,
        state,
        ccrdxpdt,
        dex_row_ts,
        taxexmt2,
        balnctyp,
        city,
        crlmtamt,
        send_email_statements,
        custclas,
        fnchpcnt,
        rmcosacc,
        bankname,
        rmfcgacc,
        creatddt,
        stmtcycl,
        shipmthd,
        pymtrmid,
        dex_row_id,
        userdef2,
        hold,
        curncyid,
        adrscode,
        shipcomplete,
        phone1,
        defcacty,
        finchdlr,
        rmtakacc,
        noteindx,
        rmavacc,
        minpydlr,
        crlmtpam,
        taxschid,
        crcardid,
        gpsfointegrationid,
        address2,
        userlang,
        slprsnid,
        rmsoracc,
        kpdsthst,
        custname,
        minpytyp,
        prclevel,
        prbtadcd,
        fax,
        phone2,
        crlmtper,
        kptrxhst,
        txrgnnum,
        shrtname,
        duegrper,
        govcrpid,
        comment1,
        salsterr,
        docfmtid,
        chekbkid,
        declid,
        stmtname,
        zip,
        integrationsource,
        orderfulfilldefault,
        ccode,
        country,
        govindid,
        fnchatyp,
        post_results_to,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
