with source as (

    select * from {{ source('tfc_dbo', 'pop30300') }}

),

renamed as (

    select
        dscpctam,
        ortdisam,
        ordavamt,
        backoutfreighttaxamt,
        pophdr2,
        orddlrat,
        taxamnt,
        pop_hdr_errors_4,
        miscamnt,
        receiptdate,
        msctxamt,
        invoicereceiptdate,
        ppstaxrt,
        ratetpid,
        denxrate,
        workflow_status,
        posteddt,
        orfrttax,
        orfrtamt,
        revaltrxsource,
        bcktxamt,
        rcptnote_5,
        backoutmisctaxamt,
        total_landed_cost_amount,
        origbackoutfreighttaxamt,
        tax_date,
        mctrxstt,
        rcptnote_6,
        frtschid,
        taxinvreqd,
        shipmthd,
        trxsorce,
        origbackoutmisctaxamt,
        ordistkn,
        currnidx,
        originatingprepaymentamt,
        modifdt,
        curncyid,
        creatddt,
        trdisamt,
        vchrnmbr,
        rcptnote_8,
        exgtblid,
        mscschid,
        purchase_misc_taxable,
        vadcdtro,
        or1099am,
        ormiscamt,
        ortaxamt,
        aplywith,
        rcptnote_7,
        vnddocnm,
        rcptnote_4,
        disavtkn,
        replacegoods,
        user2ent,
        subtotal,
        withhamt,
        ratecalc,
        disavamt,
        taxschid,
        actlship,
        bachnumb,
        rcptnote_1,
        ordatkn,
        simplifd,
        orsubtot,
        exchdate,
        voidstts,
        txrgnnum,
        vendname,
        pophdr1,
        time1,
        ten99type,
        frtamnt,
        ten99amnt,
        dex_row_id,
        dscdlram,
        discdate,
        ectrx,
        duedate,
        prepaymentamount,
        glpostdt,
        refrence,
        frttxamt,
        xchgrate,
        ormsctax,
        cbvat,
        taxinvrecvd,
        pymtrmid,
        ptdusrid,
        distknam,
        rcptnote_2,
        purchase_freight_taxable,
        bchsourc,
        revaljrnentry,
        ten99boxnumber,
        bsivcttl,
        rcptnote_3,
        poplnerr,
        poptype,
        trdpctpr,
        obtaxamt,
        invoiceexpected,
        _fivetran_deleted,
        _fivetran_synced,
        upper(trim(poprctnm)) as poprctnm,
        upper(trim(vendorid)) as vendorid

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
