with source as (

    select * from {{ source('culc4_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        voided,
        mscschid,
        trdisamt,
        corrctn,
        distknam,
        un1099am,
        cbvat,
        discdate,
        bktpuram,
        docnumbr,
        tax_date,
        cardname,
        prchamnt,
        bktfrtam,
        ttlpymts,
        bachnumb,
        taxschid,
        invoicereceiptdate,
        chekbkid,
        pordnmbr,
        ponumber,
        disamtav,
        frtschid,
        workflow_status,
        bchsourc,
        dex_row_ts,
        wrofamnt,
        ppsamded,
        taxamnt,
        curncyid,
        gstdsamt,
        prchdate,
        pstgdate,
        electronic,
        ten99boxnumber,
        ectrx,
        mdfusrid,
        vndchknm,
        ppstaxrt,
        bnkrcamt,
        ten99type,
        vendorid,
        dinvpdof,
        taxinvreqd,
        docamnt,
        backouttradedisc,
        frtamnt,
        pchschid,
        discamnt,
        ten99amnt,
        pyenttyp,
        dex_row_id,
        bktmscam,
        duedate,
        vadcdtro,
        modifdt,
        disavtkn,
        mscchamt,
        prctdisc,
        posteddt,
        simplifd,
        aplywith,
        pymtrmid,
        docprinted,
        ictrx,
        docdate,
        trxdscrn,
        curtrxam,
        pgramsbj,
        dscdlram,
        shipmthd,
        ptdusrid,
        trxsorce,
        cntrltyp,
        lngdesc,
        hold,
        retnagam,
        noteindx,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
