with source as (

    select * from {{ source('culc4_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        retnagam,
        ponumber,
        docdate,
        ptdusrid,
        prctdisc,
        prchdate,
        trxsorce,
        docprinted,
        pstgdate,
        pyenttyp,
        aplywith,
        docamnt,
        bktpuram,
        lngdesc,
        workflow_status,
        posteddt,
        ten99boxnumber,
        backouttradedisc,
        bachnumb,
        bktmscam,
        dex_row_id,
        pchschid,
        wrofamnt,
        trdisamt,
        discamnt,
        ten99amnt,
        mscchamt,
        modifdt,
        disavtkn,
        vndchknm,
        duedate,
        chekbkid,
        vadcdtro,
        pordnmbr,
        ppsamded,
        dex_row_ts,
        prchamnt,
        frtschid,
        discdate,
        un1099am,
        cbvat,
        disamtav,
        bktfrtam,
        docnumbr,
        invoicereceiptdate,
        taxschid,
        tax_date,
        mdfusrid,
        voidpdate,
        ppstaxrt,
        shipmthd,
        simplifd,
        electronic,
        curncyid,
        ectrx,
        gstdsamt,
        pymtrmid,
        bchsourc,
        taxamnt,
        taxinvreqd,
        dinvpdof,
        noteindx,
        ten99type,
        cntrltyp,
        distknam,
        hold,
        vendorid,
        trxdscrn,
        ttlpymts,
        ictrx,
        voided,
        mscschid,
        dscdlram,
        pgramsbj,
        cardname,
        corrctn,
        curtrxam,
        frtamnt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
