with source as (

    select * from {{ source('culc4_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        kperhist,
        purpvidx,
        crtcomdt,
        curncyid,
        workflow_priority,
        acpuridx,
        address1,
        kgldsths,
        ptcshacf,
        vendname,
        pmdavidx,
        ccode,
        rtobutkn,
        state,
        zipcode,
        pmdtkidx,
        govcrpid,
        userlang,
        pymntpri,
        pymtrmid,
        pmfinidx,
        pmmschix,
        country,
        userdef2,
        vadcd1099,
        upszone,
        pmwrtidx,
        withholdingformtype,
        revalue_vendor,
        faxnumbr,
        taxfilenummode,
        acnmvndr,
        xpdtoblg,
        sbppsded,
        address3,
        phnumbr2,
        pmtaxidx,
        dex_row_ts,
        brthdate,
        freeonboard,
        workflow_status,
        minorder,
        phnumbr1,
        kptrxhst,
        laborpmttype,
        crlmtdlr,
        writeoff,
        mxwofamt,
        dex_row_id,
        comment1,
        dxvarnum,
        pmprchix,
        comment2,
        pmcshidx,
        pmfrtidx,
        pmtdscix,
        mxiafvnd,
        ratetpid,
        vndclsid,
        ten99type,
        vndchknm,
        workflow_approval_status,
        disgrper,
        taxschid,
        onepaypervendinv,
        vndcntct,
        txidnmbr,
        minpydlr,
        vaddcdpr,
        vendshnm,
        txrgnnum,
        govindid,
        vendstts,
        address2,
        withholdingentitytype,
        venddba,
        credtlmt,
        modifdt,
        crtexpdt,
        trddisct,
        docfmtid,
        ten99boxnumber,
        shipmthd,
        userdef1,
        declid,
        withholdingtype,
        hold,
        phone3,
        creatddt,
        cbvat,
        chekbkid,
        taxinvrecvd,
        duegrper,
        minpytyp,
        vadcdpad,
        vadcdtro,
        parvenid,
        prspayee,
        pmrtngix,
        pmapindx,
        minpypct,
        post_results_to,
        maxindlr,
        city,
        kpcalhst,
        vadcdsfr,
        noteindx,
        ppstaxrt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
