with source as (

    select * from {{ source('ifs_prod_omeg1app', 'purchase_order_tab') }}

),

renamed as (

    select
        order_no,
        contact,
        date_entered,
        pick_list_flag,
        recipient_name,
        central_order_flag,
        delivery_terms,
        language_code,
        reject_reason_id,
        authorize_id,
        change_request_sent,
        addr_state,
        tax_exempt,
        county,
        order_date,
        pay_tax,
        delivery_address,
        label_note,
        addr_1,
        rowkey,
        addr_no,
        change_date,
        addr_3,
        rowstate,
        addr_2,
        addr_5,
        pre_accounting_id,
        addr_4,
        vendor_co_no,
        text_id_,
        total_amt_at_auth,
        rejected_date,
        orders_sequence_no,
        rejected_by,
        authorization_rejected,
        ext_transport_calendar_id,
        printed_flag,
        note_id,
        forwarder_id,
        task_id,
        country_code,
        revision,
        vendor_no,
        zip_code,
        contract,
        wanted_receipt_date,
        cancel_reason,
        order_sent,
        currency_code,
        template_id,
        ship_via_code,
        document_address_id,
        orders_version_no,
        del_terms_location,
        case_id,
        rowversion,
        invoicing_supplier,
        note_text,
        reference,
        intrastat_exempt,
        addr_flag,
        address1,
        project_id,
        buyer_code,
        address2,
        authorize_code,
        blanket_date,
        order_code,
        consolidated_flag,
        approval_rule,
        customer_po_no,
        internal_destination,
        doc_addr_no,
        schedule_agreement_order,
        ordchg_version_no,
        project_address_id,
        ordchg_sequence_no,
        city,
        project_address_flag,
        purchase_code,
        destination_id,
        pay_term_id,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
