with source as (

    select * from {{ source('ifs_prod_omeg1app', 'gen_led_voucher_row_tab') }}

),

renamed as (

    select
        accounting_year,
        company,
        row_no,
        voucher_no,
        voucher_type,
        matching_period,
        third_currency_credit_amount,
        quantity,
        third_currency_debit_amount,
        auto_tax_vou_entry,
        voucher_date,
        text,
        internal_accounting,
        account,
        curr_accounting,
        corrected,
        trans_code,
        allocation_id,
        aut_coding_seq,
        mpccom_accounting_id,
        internal_seq_number,
        credit_amount,
        aut_coding_parent_row,
        project_accounting,
        sequence_no,
        rowkey,
        exclude_periodical_cap,
        old_row_no,
        code_j,
        activate_code,
        currency_credit_amount,
        code_g,
        code_f,
        several_count_acc,
        code_i,
        code_h,
        code_c,
        code_b,
        code_e,
        reference_serie,
        code_d,
        optional_code,
        old_period,
        period_allocation,
        row_group_id,
        aut_coding_rule,
        reference_row_no,
        currency_code,
        parent_row,
        matching_year,
        matching_no,
        currency_rate,
        matching_date,
        object_id,
        rowversion,
        project_activity_id,
        accounting_period,
        summerized,
        multi_company_id,
        counter_account,
        ncf_settlement_date,
        currency_debet_amount,
        project_id,
        posting_combination_id,
        vou_text_udpdated,
        ledger_count_acc,
        reference_number,
        conversion_factor,
        journal_id,
        debet_amount,
        party_type_id,
        org_parent_row,
        autobook,
        process_code,
        transfer_id,
        year_period_key,
        alloc_line_id,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
