with source as (

    select * from {{ source('ifs_prod_omeg1app', 'accounting_code_part_value_tab') }}

),

renamed as (

    select
        code_part,
        code_part_value,
        company,
        accnt_group,
        req_text,
        ncf_override_fee,
        unit_price,
        voucher_date,
        text,
        rowtype,
        project_reopened,
        valid_until,
        logical_account_type,
        poc_method,
        grant_allowance,
        req_quantity,
        project_origin,
        revision_accounting,
        conv_factor,
        req_code_f,
        req_code_e,
        req_code_h,
        project_type,
        ledg_flag,
        capitalization_post_method,
        req_code_g,
        req_code_b,
        req_code_d,
        project_group,
        req_code_c,
        rowkey,
        bud_account,
        req_code_j,
        curr_balance,
        req_code_i,
        req_process_code,
        exclude_periodical_cap,
        specific_cap_principles,
        code_j,
        closed_acc_period,
        code_g,
        code_f,
        ncf_inv_stat_fee,
        code_i,
        req_budget_quantity,
        code_h,
        code_c,
        code_b,
        code_e,
        cons_accnt,
        code_d,
        finally_invoiced,
        party,
        req_budget_code_b,
        req_budget_code_c,
        req_budget_code_d,
        req_budget_code_e,
        user_group,
        revenue_recog_method,
        req_budget_code_f,
        req_budget_code_g,
        req_budget_code_h,
        contract,
        project_progress_method,
        stat_account,
        externally_created,
        accnt_type,
        description,
        rowversion,
        tax_code_mandatory,
        project_leader,
        req_budget_code_i,
        req_budget_code_j,
        valid_from,
        sort_value,
        exclude_proj_followup,
        project_status,
        accounting_text_id,
        posting_combination_id,
        no_archiving_trans,
        ready_date,
        finally_invo_acc_period,
        cons_code_part_value,
        voucher_type,
        customer_no,
        curr_rate,
        process_code,
        contrib_margin,
        tax_handling_value,
        order_number,
        tax_flag,
        close_at_final_invo,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
