with source as (

    select * from {{ source('northscope', 'erpx_imitemset') }}

),

renamed as (

    select
        includeditemscount,
        description,
        itemsettypeen,
        lastuser,
        lastupdated,
        rulexml,
        autogenerateddescription,
        _fivetran_deleted,
        _fivetran_synced,
        trim(dataentitycompanysk) as dataentitycompanysk,
        trim(itemsetsk) as itemsetsk,
        trim(itemsetname) as itemsetname

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
