with source as (

    select * from {{ source('hsi_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        curncyid,
        comment1,
        slprsnid,
        userlang,
        crcardid,
        gpsfointegrationid,
        adrscode,
        stmtcycl,
        minpydlr,
        orderfulfilldefault,
        dex_row_ts,
        revalue_customer,
        creatddt,
        salsterr,
        govcrpid,
        shrtname,
        shipmthd,
        send_email_statements,
        bankname,
        taxexmt2,
        rmaracc,
        govindid,
        txrgnnum,
        custclas,
        city,
        rmcshacc,
        crlmtper,
        zip,
        integrationsource,
        fax,
        post_results_to,
        crlmtamt,
        kpcalhst,
        duegrper,
        cntcprsn,
        cbvat,
        dex_row_id,
        cprcstnm,
        state,
        address1,
        crlmtpam,
        bnkbrnch,
        userdef2,
        kpdsthst,
        address3,
        prbtadcd,
        taxschid,
        address2,
        pymtrmid,
        mxwrofam,
        prclevel,
        userdef1,
        defcacty,
        kperhist,
        crlmttyp,
        docfmtid,
        phone3,
        frstindt,
        custpriority,
        rmivacc,
        rmovrpymtwrtoffacctidx,
        includeindp,
        rmwracc,
        prstadcd,
        fnchatyp,
        modifdt,
        declid,
        ratetpid,
        integrationid,
        mxwoftyp,
        disgrper,
        ccode,
        finchid,
        country,
        custdisc,
        stmtname,
        chekbkid,
        inactive,
        upszone,
        taxexmt1,
        rmavacc,
        rmsoracc,
        hold,
        fnchpcnt,
        comment2,
        rmtakacc,
        rmslsacc,
        phone1,
        minpytyp,
        kptrxhst,
        minpypct,
        noteindx,
        rmcosacc,
        ccrdxpdt,
        shipcomplete,
        finchdlr,
        rmfcgacc,
        staddrcd,
        balnctyp,
        phone2,
        crcrdnum,
        custname,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
