with source as (

    select * from {{ source('hsi_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        gstdsamt,
        disavtkn,
        discamnt,
        ten99amnt,
        bktmscam,
        prchdate,
        workflow_status,
        taxamnt,
        pordnmbr,
        pchschid,
        mscchamt,
        noteindx,
        chekbkid,
        pstgdate,
        electronic,
        ectrx,
        pymtrmid,
        taxinvreqd,
        docamnt,
        mdfusrid,
        pyenttyp,
        simplifd,
        docdate,
        taxschid,
        shipmthd,
        prctdisc,
        vndchknm,
        discdate,
        dex_row_id,
        prchamnt,
        modifdt,
        duedate,
        dinvpdof,
        voidpdate,
        cntrltyp,
        trdisamt,
        cbvat,
        un1099am,
        bachnumb,
        posteddt,
        backouttradedisc,
        vadcdtro,
        disamtav,
        ppsamded,
        ten99type,
        cardname,
        bktpuram,
        frtschid,
        wrofamnt,
        tax_date,
        ppstaxrt,
        pgramsbj,
        docprinted,
        lngdesc,
        trxdscrn,
        invoicereceiptdate,
        mscschid,
        trxsorce,
        dex_row_ts,
        aplywith,
        voided,
        bchsourc,
        curncyid,
        docnumbr,
        ictrx,
        ptdusrid,
        bktfrtam,
        ponumber,
        vendorid,
        retnagam,
        hold,
        ttlpymts,
        curtrxam,
        corrctn,
        distknam,
        frtamnt,
        dscdlram,
        ten99boxnumber,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
