with source as (

    select * from {{ source('hsi_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        ponumber,
        disamtav,
        ptdusrid,
        trxsorce,
        discdate,
        dscdlram,
        ten99boxnumber,
        dex_row_ts,
        invoicereceiptdate,
        pgramsbj,
        frtamnt,
        bachnumb,
        ectrx,
        backouttradedisc,
        pchschid,
        bktmscam,
        prctdisc,
        electronic,
        dex_row_id,
        vndchknm,
        vadcdtro,
        ppsamded,
        trdisamt,
        docamnt,
        pordnmbr,
        chekbkid,
        taxamnt,
        pyenttyp,
        taxinvreqd,
        tax_date,
        cntrltyp,
        gstdsamt,
        bnkrcamt,
        frtschid,
        wrofamnt,
        docnumbr,
        bktfrtam,
        duedate,
        corrctn,
        ten99type,
        bchsourc,
        modifdt,
        cbvat,
        shipmthd,
        taxschid,
        docdate,
        mdfusrid,
        ttlpymts,
        posteddt,
        pymtrmid,
        dinvpdof,
        ictrx,
        curncyid,
        curtrxam,
        un1099am,
        prchamnt,
        voided,
        mscchamt,
        prchdate,
        pstgdate,
        distknam,
        noteindx,
        discamnt,
        ten99amnt,
        disavtkn,
        cardname,
        lngdesc,
        docprinted,
        ppstaxrt,
        bktpuram,
        aplywith,
        trxdscrn,
        vendorid,
        workflow_status,
        hold,
        mscschid,
        retnagam,
        simplifd,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
