with source as (

    select * from {{ source('hsi_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        txidnmbr,
        vadcdtro,
        comment2,
        address3,
        city,
        minpydlr,
        mxiafvnd,
        dex_row_id,
        acnmvndr,
        xpdtoblg,
        docfmtid,
        revalue_vendor,
        chekbkid,
        vaddcdpr,
        pmtdscix,
        txrgnnum,
        duegrper,
        ppstaxrt,
        minpypct,
        disgrper,
        userdef1,
        dex_row_ts,
        vndclsid,
        venddba,
        workflow_approval_status,
        sbppsded,
        ratetpid,
        vndcntct,
        taxschid,
        credtlmt,
        rtobutkn,
        vendshnm,
        withholdingformtype,
        kperhist,
        taxfilenummode,
        post_results_to,
        mxwofamt,
        address2,
        modifdt,
        workflow_status,
        phnumbr1,
        pmfrtidx,
        dxvarnum,
        pmcshidx,
        pmwrtidx,
        taxinvrecvd,
        onepaypervendinv,
        pmdavidx,
        faxnumbr,
        prspayee,
        crtexpdt,
        vendstts,
        trddisct,
        comment1,
        vndchknm,
        kpcalhst,
        crlmtdlr,
        declid,
        userdef2,
        pmtaxidx,
        zipcode,
        vadcd1099,
        pmdtkidx,
        pmmschix,
        ptcshacf,
        pmfinidx,
        pmprchix,
        userlang,
        cbvat,
        minorder,
        hold,
        pymntpri,
        govcrpid,
        purpvidx,
        writeoff,
        state,
        upszone,
        crtcomdt,
        creatddt,
        curncyid,
        ten99boxnumber,
        phnumbr2,
        address1,
        minpytyp,
        workflow_priority,
        kgldsths,
        vendname,
        country,
        ccode,
        freeonboard,
        acpuridx,
        pmapindx,
        pmrtngix,
        govindid,
        withholdingtype,
        laborpmttype,
        pymtrmid,
        vadcdsfr,
        kptrxhst,
        phone3,
        withholdingentitytype,
        maxindlr,
        shipmthd,
        ten99type,
        noteindx,
        parvenid,
        brthdate,
        vadcdpad,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
