with source as (

    select * from {{ source('hsi_dbo', 'pop30300') }}

),

renamed as (

    select
        poprctnm,
        or1099am,
        revaljrnentry,
        subtotal,
        withhamt,
        rcptnote_7,
        disavtkn,
        rcptnote_1,
        rcptnote_4,
        poplnerr,
        vnddocnm,
        bsivcttl,
        time1,
        purchase_misc_taxable,
        ten99boxnumber,
        dex_row_id,
        bachnumb,
        taxinvreqd,
        discdate,
        disavamt,
        replacegoods,
        refrence,
        bchsourc,
        ratecalc,
        aplywith,
        distknam,
        user2ent,
        ortaxamt,
        curncyid,
        frttxamt,
        trdisamt,
        dscdlram,
        tax_date,
        origbackoutfreighttaxamt,
        vchrnmbr,
        originatingprepaymentamt,
        ptdusrid,
        rcptnote_5,
        xchgrate,
        poptype,
        exchdate,
        pymtrmid,
        rcptnote_8,
        trxsorce,
        receiptdate,
        pophdr2,
        rcptnote_6,
        glpostdt,
        ten99amnt,
        ordatkn,
        purchase_freight_taxable,
        total_landed_cost_amount,
        vendname,
        txrgnnum,
        revaltrxsource,
        ordistkn,
        frtschid,
        orddlrat,
        pop_hdr_errors_4,
        actlship,
        frtamnt,
        invoicereceiptdate,
        backoutmisctaxamt,
        orsubtot,
        orfrtamt,
        exgtblid,
        posteddt,
        ordavamt,
        ppstaxrt,
        workflow_status,
        invoiceexpected,
        ortdisam,
        pophdr1,
        miscamnt,
        taxamnt,
        dscpctam,
        msctxamt,
        backoutfreighttaxamt,
        ratetpid,
        denxrate,
        currnidx,
        obtaxamt,
        ormiscamt,
        duedate,
        vendorid,
        trdpctpr,
        cbvat,
        rcptnote_3,
        mscschid,
        vadcdtro,
        simplifd,
        origbackoutmisctaxamt,
        rcptnote_2,
        mctrxstt,
        ten99type,
        orfrttax,
        taxinvrecvd,
        taxschid,
        ormsctax,
        ectrx,
        bcktxamt,
        creatddt,
        voidstts,
        shipmthd,
        prepaymentamount,
        modifdt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
