with source as (

    select * from {{ source('hsi_dbo', 'iv00101') }}

),

renamed as (

    select
        itemnmbr,
        minshelf2,
        purpvidx,
        purchase_tax_options,
        altitem1,
        decplcur,
        itemtype,
        ivcogsix,
        userid,
        pricegroup,
        lastgensn,
        inactive,
        qtyshorttolerancepercent,
        itmgedsc,
        ivinsvix,
        uppvidx,
        includeindp,
        modifdt,
        lot_split_quantity,
        wrntydys,
        dex_row_ts,
        revalue_inventory,
        purmcidx,
        selnguom,
        ktacctsr,
        lotexpwarn,
        itmshnam,
        lastgenlot,
        uscatvls_4,
        stndcost,
        itmtshid,
        asmvridx,
        decplqty,
        itmclscd,
        ivsldsix,
        cgsmcidx,
        useqtyshortagetolerance,
        purchase_item_tax_schedu,
        minshelf1,
        currcost,
        ivslsidx,
        dpshpidx,
        uscatvls_5,
        kpdsthst,
        prchsuom,
        ivivofix,
        kptrxhst,
        prclevel,
        dex_row_id,
        noteindx,
        taxoptns,
        sttstclvlprcntg,
        ivscrvix,
        itmtrkop,
        creatddt,
        tolerance_percentage,
        uomschdl,
        cntryorgn,
        mstrcdty,
        ivinfidx,
        vctnmthd,
        tcc,
        itemdesc,
        pricmthd,
        kperhist,
        abccode,
        ivinusix,
        invmcidx,
        altitem2,
        pinflidx,
        uscatvls_6,
        ivdmgidx,
        uscatvls_3,
        locncode,
        uscatvls_1,
        itemcode,
        ivslrnix,
        alwbkord,
        qtyovertolerancepercent,
        kpcalhst,
        cgsinflx,
        uscatvls_2,
        lotexpwarndays,
        ivretidx,
        useqtyoveragetolerance,
        ivvaridx,
        itmplnnngtyp,
        itemshwt,
        ivivindx,
        lottype,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
