with source as (

    select * from {{ source('hsi_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        disavtkn,
        discrtnd,
        voiddate,
        bchsourc,
        dinvpdof,
        delete1,
        comdlram,
        cbkidcsh,
        simplifd,
        pstusrid,
        agngbukt,
        cprcstnm,
        cbkidchk,
        aplywith,
        distknam,
        factoring,
        postdate,
        directdebit,
        eftflag,
        trxsorce,
        docdate,
        lstusred,
        dex_row_id,
        bktmscam,
        corrctn,
        slschdid,
        mscschid,
        slsamnt,
        glpostdt,
        curtrxam,
        dex_row_ts,
        costamnt,
        taxschid,
        pymtrmid,
        lstedtdt,
        slprsnid,
        shipmthd,
        cbkidcrd,
        bachnumb,
        cashamnt,
        dscpctam,
        dscdlram,
        slstercd,
        cspornbr,
        frtamnt,
        gstdsamt,
        voidstts,
        wrofamnt,
        saledate,
        trdisamt,
        cheknmbr,
        bktslsam,
        ectrx,
        backouttradedisc,
        trxdscrn,
        cshrctyp,
        taxamnt,
        electronic,
        discdate,
        miscamnt,
        frtschid,
        ortrxamt,
        duedate,
        adrscode,
        tax_date,
        ppsamded,
        curncyid,
        bktfrtam,
        noteindx,
        disavamt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
