with source as (

    select * from {{ source('cap_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        backouttradedisc,
        dinvpdof,
        discamnt,
        ten99amnt,
        ponumber,
        bktmscam,
        voided,
        simplifd,
        trxdscrn,
        disavtkn,
        cbvat,
        mscchamt,
        ten99boxnumber,
        noteindx,
        docamnt,
        vendorid,
        cardname,
        taxamnt,
        gstdsamt,
        modifdt,
        bachnumb,
        dex_row_id,
        duedate,
        cntrltyp,
        ppstaxrt,
        invoicereceiptdate,
        bktfrtam,
        retnagam,
        pyenttyp,
        mscschid,
        prchdate,
        pchschid,
        prctdisc,
        dex_row_ts,
        tax_date,
        ttlpymts,
        frtamnt,
        ptdusrid,
        pymtrmid,
        lngdesc,
        electronic,
        trxsorce,
        pstgdate,
        curtrxam,
        ectrx,
        dscdlram,
        shipmthd,
        distknam,
        ictrx,
        docnumbr,
        bchsourc,
        discdate,
        wrofamnt,
        taxinvreqd,
        chekbkid,
        ten99type,
        voidpdate,
        vadcdtro,
        corrctn,
        bktpuram,
        pgramsbj,
        posteddt,
        aplywith,
        docprinted,
        workflow_status,
        prchamnt,
        frtschid,
        docdate,
        curncyid,
        un1099am,
        pordnmbr,
        taxschid,
        hold,
        ppsamded,
        mdfusrid,
        trdisamt,
        disamtav,
        vndchknm,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
