with source as (

    select * from {{ source('cap_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        taxschid,
        revalue_customer,
        govcrpid,
        phone1,
        rmwracc,
        userdef2,
        custdisc,
        cbvat,
        fnchpcnt,
        crlmttyp,
        kptrxhst,
        shipmthd,
        rmovrpymtwrtoffacctidx,
        zip,
        city,
        custname,
        rmslsacc,
        finchdlr,
        fax,
        noteindx,
        adrscode,
        taxexmt1,
        slprsnid,
        prbtadcd,
        kpcalhst,
        rmivacc,
        curncyid,
        crlmtpam,
        send_email_statements,
        rmcshacc,
        custpriority,
        shrtname,
        govindid,
        gpsfointegrationid,
        salsterr,
        crcardid,
        ccrdxpdt,
        hold,
        phone2,
        declid,
        shipcomplete,
        txrgnnum,
        stmtname,
        userlang,
        country,
        inactive,
        docfmtid,
        integrationid,
        comment1,
        disgrper,
        rmfcgacc,
        comment2,
        ccode,
        stmtcycl,
        includeindp,
        defcacty,
        rmcosacc,
        balnctyp,
        upszone,
        rmsoracc,
        address3,
        ratetpid,
        chekbkid,
        dex_row_id,
        crcrdnum,
        rmtakacc,
        staddrcd,
        prclevel,
        phone3,
        minpytyp,
        crlmtper,
        mxwrofam,
        address2,
        minpypct,
        rmaracc,
        crlmtamt,
        post_results_to,
        userdef1,
        dex_row_ts,
        finchid,
        taxexmt2,
        custclas,
        frstindt,
        pymtrmid,
        rmavacc,
        minpydlr,
        cntcprsn,
        fnchatyp,
        bankname,
        state,
        mxwoftyp,
        cprcstnm,
        kperhist,
        creatddt,
        orderfulfilldefault,
        bnkbrnch,
        duegrper,
        prstadcd,
        kpdsthst,
        integrationsource,
        address1,
        modifdt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
