with source as (

    select * from {{ source('cap_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        electronic,
        mscschid,
        disamtav,
        pstgdate,
        pgramsbj,
        posteddt,
        curncyid,
        dscdlram,
        bachnumb,
        ppsamded,
        ectrx,
        bktpuram,
        ictrx,
        shipmthd,
        cardname,
        docdate,
        frtschid,
        ten99boxnumber,
        pymtrmid,
        corrctn,
        distknam,
        voided,
        frtamnt,
        vadcdtro,
        lngdesc,
        prchdate,
        taxinvreqd,
        ppstaxrt,
        noteindx,
        retnagam,
        pchschid,
        curtrxam,
        vendorid,
        invoicereceiptdate,
        vndchknm,
        workflow_status,
        simplifd,
        prchamnt,
        ptdusrid,
        mscchamt,
        discamnt,
        disavtkn,
        docprinted,
        trxsorce,
        ten99amnt,
        pyenttyp,
        bktmscam,
        ttlpymts,
        bktfrtam,
        prctdisc,
        chekbkid,
        pordnmbr,
        dex_row_ts,
        discdate,
        trdisamt,
        modifdt,
        ten99type,
        taxschid,
        cbvat,
        trxdscrn,
        un1099am,
        docamnt,
        backouttradedisc,
        cntrltyp,
        hold,
        duedate,
        dinvpdof,
        mdfusrid,
        tax_date,
        gstdsamt,
        docnumbr,
        bchsourc,
        dex_row_id,
        taxamnt,
        ponumber,
        bnkrcamt,
        wrofamnt,
        aplywith,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
