with

source as (

    select * from {{ source('cap_dbo', 'pm10000') }}

),

renamed as (

    select
        bachnumb,
        bchsourc,
        vchnumwk,
        prchdate,
        corrctn,
        vaddcdpr,
        crcrdamt,
        corrnxst,
        apdstkam,
        cbvat,
        aplywith,
        dex_row_id,
        invoicereceiptdate,
        bktfrtam,
        posteddt,
        un1099am,
        mscchamt,
        cdocnmbr,
        curtrxam,
        pstgdate,
        gstdsamt,
        ten99type,
        bktpuram,
        taxinvreqd,
        electronic,
        chekamnt,
        frtamnt,
        camtdate,
        modifdt,
        duedate,
        cntrltyp,
        doctype,
        bktmscam,
        cheknmbr,
        simplifd,
        pmwrkms2,
        posted,
        pmicmsgs,
        crcarddt,
        pordnmbr,
        vendorid,
        pchschid,
        ppsamded,
        docdate,
        pmwrkmsg,
        cashamnt,
        wrofamnt,
        appldamt,
        docnumbr,
        mdfusrid,
        noteindx,
        prchamnt,
        prctdisc,
        chrgamnt,
        lngdesc,
        dscdlram,
        dex_row_ts,
        trdisamt,
        pgramsbj,
        ccampynm,
        ten99amnt,
        vadcdtro,
        docprinted,
        chekbkid,
        backouttradedisc,
        ictrx,
        tax_date,
        vchrncor,
        ppstaxrt,
        retnagam,
        sourcdoc,
        bnkrcamt,
        shipmthd,
        frtschid,
        taxamnt,
        pymtrmid,
        curncyid,
        mscschid,
        chamcbid,
        pstgstus,
        discdate,
        printed,
        camcbkid,
        campynbr,
        pmdstmsg,
        txengcld,
        ccrctnum,
        vchrnmbr,
        ectrx,
        campmtnm,
        cardname,
        distknam,
        icdists,
        taxschid,
        ptdusrid,
        disamtav,
        ten99boxnumber,
        trxdscrn,
        docamnt,
        chekdate,
        workflow_status,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
