with source as (

    select * from {{ source('cap_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        slschdid,
        ectrx,
        electronic,
        adrscode,
        discrtnd,
        simplifd,
        factoring,
        trxdscrn,
        bachnumb,
        agngbukt,
        dex_row_ts,
        glpostdt,
        disavtkn,
        cshrctyp,
        cbkidcrd,
        duedate,
        ppsamded,
        backouttradedisc,
        voidstts,
        noteindx,
        bktfrtam,
        lstusred,
        cspornbr,
        dinvpdof,
        trxsorce,
        slstercd,
        discdate,
        cprcstnm,
        cheknmbr,
        disavamt,
        dex_row_id,
        frtamnt,
        directdebit,
        cbkidchk,
        tax_date,
        dscdlram,
        mscschid,
        lstedtdt,
        eftflag,
        curncyid,
        slprsnid,
        trdisamt,
        gstdsamt,
        docdate,
        aplywith,
        ortrxamt,
        taxamnt,
        saledate,
        taxschid,
        miscamnt,
        corrctn,
        wrofamnt,
        shipmthd,
        bktslsam,
        pymtrmid,
        pstusrid,
        cbkidcsh,
        dscpctam,
        bchsourc,
        slsamnt,
        costamnt,
        frtschid,
        comdlram,
        bktmscam,
        delete1,
        voiddate,
        curtrxam,
        cashamnt,
        postdate,
        distknam,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
