with source as (

    select * from {{ source('cap_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        vndclsid,
        pmwrtidx,
        ratetpid,
        creatddt,
        venddba,
        minpydlr,
        minpytyp,
        txrgnnum,
        pmprchix,
        pmfinidx,
        pmmschix,
        vndchknm,
        crtcomdt,
        pmcshidx,
        xpdtoblg,
        vadcdpad,
        dxvarnum,
        taxschid,
        comment2,
        pmdtkidx,
        brthdate,
        credtlmt,
        revalue_vendor,
        noteindx,
        trddisct,
        sbppsded,
        acnmvndr,
        chekbkid,
        purpvidx,
        docfmtid,
        writeoff,
        userlang,
        city,
        phone3,
        vadcdtro,
        workflow_status,
        phnumbr2,
        parvenid,
        ptcshacf,
        taxfilenummode,
        txidnmbr,
        shipmthd,
        freeonboard,
        withholdingformtype,
        ccode,
        zipcode,
        workflow_priority,
        pymtrmid,
        laborpmttype,
        declid,
        country,
        govindid,
        kptrxhst,
        kgldsths,
        dex_row_ts,
        govcrpid,
        hold,
        duegrper,
        minpypct,
        crlmtdlr,
        upszone,
        pmapindx,
        withholdingtype,
        pmrtngix,
        workflow_approval_status,
        curncyid,
        minorder,
        disgrper,
        address1,
        mxiafvnd,
        prspayee,
        ten99type,
        phnumbr1,
        vadcdsfr,
        state,
        crtexpdt,
        userdef1,
        rtobutkn,
        vendname,
        withholdingentitytype,
        vendstts,
        maxindlr,
        onepaypervendinv,
        ppstaxrt,
        pmdavidx,
        vadcd1099,
        faxnumbr,
        mxwofamt,
        cbvat,
        acpuridx,
        userdef2,
        vndcntct,
        kperhist,
        comment1,
        pmfrtidx,
        pmtdscix,
        post_results_to,
        address2,
        dex_row_id,
        ten99boxnumber,
        modifdt,
        kpcalhst,
        vendshnm,
        vaddcdpr,
        address3,
        pmtaxidx,
        taxinvrecvd,
        pymntpri,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
