with source as (

    select * from {{ source('cap_dbo', 'pop30300') }}

),

renamed as (

    select
        rcptnote_7,
        invoicereceiptdate,
        taxinvreqd,
        disavtkn,
        bchsourc,
        subtotal,
        taxschid,
        curncyid,
        taxinvrecvd,
        vendname,
        dscpctam,
        receiptdate,
        rcptnote_1,
        rcptnote_4,
        txrgnnum,
        poplnerr,
        withhamt,
        poptype,
        disavamt,
        user2ent,
        ordatkn,
        ppstaxrt,
        shipmthd,
        frtamnt,
        modifdt,
        bsivcttl,
        ten99amnt,
        pymtrmid,
        glpostdt,
        creatddt,
        aplywith,
        orsubtot,
        prepaymentamount,
        replacegoods,
        dscdlram,
        purchase_misc_taxable,
        ormsctax,
        origbackoutfreighttaxamt,
        posteddt,
        xchgrate,
        rcptnote_5,
        time1,
        simplifd,
        rcptnote_2,
        workflow_status,
        trdpctpr,
        pophdr2,
        pop_hdr_errors_4,
        distknam,
        frttxamt,
        rcptnote_3,
        obtaxamt,
        currnidx,
        ratetpid,
        discdate,
        ectrx,
        ortdisam,
        ordavamt,
        backoutfreighttaxamt,
        taxamnt,
        ptdusrid,
        orddlrat,
        actlship,
        vchrnmbr,
        exchdate,
        msctxamt,
        dex_row_id,
        ratecalc,
        cbvat,
        miscamnt,
        pophdr1,
        denxrate,
        revaljrnentry,
        ten99type,
        orfrttax,
        backoutmisctaxamt,
        total_landed_cost_amount,
        rcptnote_6,
        refrence,
        voidstts,
        invoiceexpected,
        bcktxamt,
        orfrtamt,
        revaltrxsource,
        ordistkn,
        origbackoutmisctaxamt,
        purchase_freight_taxable,
        exgtblid,
        mctrxstt,
        originatingprepaymentamt,
        rcptnote_8,
        frtschid,
        mscschid,
        vadcdtro,
        trxsorce,
        ortaxamt,
        ten99boxnumber,
        tax_date,
        vnddocnm,
        duedate,
        ormiscamt,
        or1099am,
        trdisamt,
        bachnumb,
        _fivetran_deleted,
        _fivetran_synced,
        upper(trim(poprctnm)) as poprctnm,
        upper(trim(vendorid)) as vendorid

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
