with source as (

    select * from {{ source('cafl_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        distknam,
        backouttradedisc,
        taxamnt,
        pymtrmid,
        miscamnt,
        bktmscam,
        cbkidcsh,
        ortrxamt,
        slsamnt,
        cprcstnm,
        curtrxam,
        trxdscrn,
        voiddate,
        costamnt,
        ppsamded,
        dex_row_id,
        discdate,
        dinvpdof,
        curncyid,
        electronic,
        ectrx,
        bchsourc,
        postdate,
        adrscode,
        disavamt,
        dscpctam,
        dscdlram,
        docdate,
        cshrctyp,
        gstdsamt,
        wrofamnt,
        trdisamt,
        pstusrid,
        tax_date,
        duedate,
        bktslsam,
        factoring,
        frtschid,
        simplifd,
        delete1,
        slstercd,
        saledate,
        agngbukt,
        corrctn,
        eftflag,
        cspornbr,
        noteindx,
        directdebit,
        bktfrtam,
        cashamnt,
        disavtkn,
        mscschid,
        cbkidchk,
        discrtnd,
        slschdid,
        cbkidcrd,
        lstedtdt,
        slprsnid,
        dex_row_ts,
        glpostdt,
        frtamnt,
        trxsorce,
        cheknmbr,
        comdlram,
        bachnumb,
        shipmthd,
        lstusred,
        taxschid,
        aplywith,
        voidstts,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
