with source as (

    select * from {{ source('cafl_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        staddrcd,
        rmaracc,
        noteindx,
        finchdlr,
        inactive,
        rmcshacc,
        integrationid,
        crlmtper,
        userdef1,
        crcrdnum,
        address3,
        creatddt,
        docfmtid,
        phone3,
        comment2,
        prstadcd,
        bnkbrnch,
        integrationsource,
        rmwracc,
        kpcalhst,
        kptrxhst,
        minpydlr,
        fnchatyp,
        post_results_to,
        rmslsacc,
        fax,
        custdisc,
        stmtcycl,
        prclevel,
        rmcosacc,
        rmfcgacc,
        rmivacc,
        country,
        defcacty,
        kpdsthst,
        chekbkid,
        crlmttyp,
        kperhist,
        prbtadcd,
        modifdt,
        govindid,
        shrtname,
        govcrpid,
        declid,
        userdef2,
        ccode,
        stmtname,
        userlang,
        txrgnnum,
        cbvat,
        dex_row_ts,
        zip,
        adrscode,
        pymtrmid,
        curncyid,
        mxwrofam,
        slprsnid,
        gpsfointegrationid,
        bankname,
        comment1,
        crcardid,
        phone1,
        rmsoracc,
        duegrper,
        hold,
        salsterr,
        disgrper,
        state,
        rmavacc,
        send_email_statements,
        fnchpcnt,
        phone2,
        dex_row_id,
        rmtakacc,
        ccrdxpdt,
        rmovrpymtwrtoffacctidx,
        address2,
        orderfulfilldefault,
        taxschid,
        frstindt,
        crlmtpam,
        cntcprsn,
        taxexmt1,
        address1,
        upszone,
        finchid,
        shipcomplete,
        custname,
        city,
        custpriority,
        cprcstnm,
        mxwoftyp,
        balnctyp,
        includeindp,
        taxexmt2,
        custclas,
        shipmthd,
        minpypct,
        crlmtamt,
        minpytyp,
        ratetpid,
        revalue_customer,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
