with source as (

    select * from {{ source('cafl_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        backouttradedisc,
        bktmscam,
        discamnt,
        ten99amnt,
        noteindx,
        cbvat,
        disavtkn,
        trxdscrn,
        ponumber,
        tax_date,
        docamnt,
        ptdusrid,
        lngdesc,
        prctdisc,
        trxsorce,
        electronic,
        taxamnt,
        gstdsamt,
        pyenttyp,
        ectrx,
        workflow_status,
        posteddt,
        bktfrtam,
        dscdlram,
        cntrltyp,
        taxinvreqd,
        dex_row_id,
        ten99type,
        mscschid,
        ttlpymts,
        voided,
        corrctn,
        curtrxam,
        frtamnt,
        cardname,
        vendorid,
        ictrx,
        docdate,
        ppstaxrt,
        pgramsbj,
        distknam,
        taxschid,
        pordnmbr,
        docnumbr,
        chekbkid,
        dinvpdof,
        ppsamded,
        trdisamt,
        duedate,
        bktpuram,
        prchdate,
        bchsourc,
        shipmthd,
        docprinted,
        curncyid,
        modifdt,
        pymtrmid,
        bnkrcamt,
        mdfusrid,
        simplifd,
        wrofamnt,
        hold,
        retnagam,
        invoicereceiptdate,
        vndchknm,
        disamtav,
        ten99boxnumber,
        pchschid,
        aplywith,
        frtschid,
        pstgdate,
        un1099am,
        prchamnt,
        discdate,
        vadcdtro,
        mscchamt,
        dex_row_ts,
        bachnumb,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
