with

source as (

    select * from {{ source('cafl_dbo', 'pm10000') }}

),

renamed as (

    select
        cntrltyp,
        trxdscrn,
        curtrxam,
        cbvat,
        ten99boxnumber,
        posted,
        simplifd,
        chekamnt,
        aplywith,
        corrctn,
        pgramsbj,
        ppsamded,
        taxamnt,
        distknam,
        curncyid,
        frtschid,
        ictrx,
        ptdusrid,
        pordnmbr,
        apdstkam,
        mdfusrid,
        bktmscam,
        duedate,
        printed,
        lngdesc,
        chamcbid,
        pmwrkmsg,
        pchschid,
        dex_row_id,
        icdists,
        bktpuram,
        dscdlram,
        prctdisc,
        ten99amnt,
        tax_date,
        txengcld,
        noteindx,
        cheknmbr,
        chrgamnt,
        frtamnt,
        bktfrtam,
        ectrx,
        docnumbr,
        corrnxst,
        discdate,
        bnkrcamt,
        docprinted,
        posteddt,
        vchnumwk,
        doctype,
        trdisamt,
        mscschid,
        pmwrkms2,
        bachnumb,
        retnagam,
        pmdstmsg,
        backouttradedisc,
        ppstaxrt,
        pstgdate,
        vaddcdpr,
        chekdate,
        camtdate,
        cardname,
        workflow_status,
        taxschid,
        pmicmsgs,
        vchrnmbr,
        invoicereceiptdate,
        vendorid,
        prchdate,
        sourcdoc,
        campynbr,
        dex_row_ts,
        mscchamt,
        camcbkid,
        ten99type,
        shipmthd,
        crcrdamt,
        un1099am,
        ccrctnum,
        crcarddt,
        cdocnmbr,
        pstgstus,
        campmtnm,
        gstdsamt,
        docamnt,
        docdate,
        disamtav,
        pymtrmid,
        vadcdtro,
        taxinvreqd,
        cashamnt,
        appldamt,
        wrofamnt,
        chekbkid,
        prchamnt,
        ccampynm,
        modifdt,
        bchsourc,
        electronic,
        vchrncor,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
