with source as (

    select * from {{ source('cafl_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        zipcode,
        userdef2,
        pymntpri,
        govcrpid,
        taxfilenummode,
        withholdingformtype,
        noteindx,
        upszone,
        vadcd1099,
        kpcalhst,
        sbppsded,
        xpdtoblg,
        minpydlr,
        declid,
        ccode,
        writeoff,
        revalue_vendor,
        laborpmttype,
        modifdt,
        phnumbr1,
        disgrper,
        pmmschix,
        comment1,
        dxvarnum,
        taxinvrecvd,
        country,
        pymtrmid,
        brthdate,
        onepaypervendinv,
        vendstts,
        govindid,
        workflow_priority,
        faxnumbr,
        creatddt,
        pmapindx,
        pmrtngix,
        acnmvndr,
        ptcshacf,
        phnumbr2,
        cbvat,
        hold,
        userlang,
        chekbkid,
        taxschid,
        crtcomdt,
        vndcntct,
        pmdavidx,
        workflow_status,
        txidnmbr,
        freeonboard,
        ppstaxrt,
        acpuridx,
        kperhist,
        vaddcdpr,
        kgldsths,
        txrgnnum,
        trddisct,
        credtlmt,
        purpvidx,
        maxindlr,
        vadcdtro,
        comment2,
        venddba,
        city,
        ten99boxnumber,
        crlmtdlr,
        prspayee,
        docfmtid,
        vndchknm,
        mxiafvnd,
        post_results_to,
        shipmthd,
        pmdtkidx,
        address3,
        rtobutkn,
        phone3,
        minorder,
        crtexpdt,
        pmfinidx,
        workflow_approval_status,
        withholdingentitytype,
        pmtaxidx,
        minpypct,
        dex_row_id,
        pmprchix,
        vadcdpad,
        parvenid,
        minpytyp,
        pmwrtidx,
        vendshnm,
        duegrper,
        address2,
        vadcdsfr,
        vndclsid,
        ten99type,
        dex_row_ts,
        ratetpid,
        curncyid,
        mxwofamt,
        address1,
        kptrxhst,
        userdef1,
        withholdingtype,
        vendname,
        pmcshidx,
        pmfrtidx,
        state,
        pmtdscix,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
