with source as (

    select * from {{ source('cafl_dbo', 'pop30300') }}

),

renamed as (

    select
        disavtkn,
        vendorid,
        rcptnote_7,
        ptdusrid,
        currnidx,
        rcptnote_4,
        rcptnote_1,
        dex_row_id,
        revaljrnentry,
        poprctnm,
        or1099am,
        time1,
        subtotal,
        ppstaxrt,
        glpostdt,
        distknam,
        frtschid,
        pophdr2,
        orsubtot,
        pop_hdr_errors_4,
        frtamnt,
        disavamt,
        xchgrate,
        ten99amnt,
        actlship,
        withhamt,
        dscdlram,
        taxinvreqd,
        tax_date,
        revaltrxsource,
        exchdate,
        ratecalc,
        mscschid,
        dscpctam,
        backoutmisctaxamt,
        exgtblid,
        ordistkn,
        vadcdtro,
        poplnerr,
        origbackoutmisctaxamt,
        receiptdate,
        trxsorce,
        ortaxamt,
        duedate,
        trdisamt,
        ordatkn,
        bachnumb,
        originatingprepaymentamt,
        ormiscamt,
        aplywith,
        vchrnmbr,
        rcptnote_8,
        ten99type,
        vnddocnm,
        mctrxstt,
        replacegoods,
        taxamnt,
        ordavamt,
        txrgnnum,
        backoutfreighttaxamt,
        ortdisam,
        posteddt,
        creatddt,
        taxschid,
        ectrx,
        curncyid,
        orddlrat,
        voidstts,
        denxrate,
        shipmthd,
        bcktxamt,
        orfrtamt,
        rcptnote_6,
        pymtrmid,
        origbackoutfreighttaxamt,
        total_landed_cost_amount,
        purchase_freight_taxable,
        rcptnote_5,
        miscamnt,
        purchase_misc_taxable,
        modifdt,
        vendname,
        ten99boxnumber,
        invoicereceiptdate,
        poptype,
        orfrttax,
        prepaymentamount,
        ratetpid,
        refrence,
        cbvat,
        pophdr1,
        frttxamt,
        taxinvrecvd,
        ormsctax,
        user2ent,
        simplifd,
        trdpctpr,
        msctxamt,
        invoiceexpected,
        obtaxamt,
        discdate,
        workflow_status,
        rcptnote_3,
        bsivcttl,
        rcptnote_2,
        bchsourc,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
