with source as (

    select * from {{ source('cafl_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        prchamnt,
        pchschid,
        ttlpymts,
        bktfrtam,
        docdate,
        vndchknm,
        vendorid,
        chekbkid,
        curtrxam,
        trdisamt,
        pordnmbr,
        vadcdtro,
        ten99type,
        un1099am,
        voided,
        docprinted,
        ppstaxrt,
        posteddt,
        dinvpdof,
        distknam,
        pstgdate,
        ponumber,
        wrofamnt,
        gstdsamt,
        docnumbr,
        taxamnt,
        taxschid,
        workflow_status,
        pgramsbj,
        mdfusrid,
        dex_row_id,
        taxinvreqd,
        prchdate,
        curncyid,
        bchsourc,
        docamnt,
        bachnumb,
        corrctn,
        cntrltyp,
        tax_date,
        ectrx,
        retnagam,
        dex_row_ts,
        electronic,
        ten99boxnumber,
        trxdscrn,
        frtschid,
        invoicereceiptdate,
        cardname,
        backouttradedisc,
        frtamnt,
        mscschid,
        disamtav,
        dscdlram,
        ppsamded,
        bktpuram,
        cbvat,
        simplifd,
        discamnt,
        trxsorce,
        ten99amnt,
        disavtkn,
        bktmscam,
        ptdusrid,
        pyenttyp,
        ictrx,
        shipmthd,
        mscchamt,
        noteindx,
        hold,
        discdate,
        pymtrmid,
        lngdesc,
        modifdt,
        voidpdate,
        aplywith,
        prctdisc,
        duedate,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
