with

source as (

    select * from {{ source('metaviewer_dbo', 'payables_base') }}

),

renamed as (

    select
        docid,
        approver_3,
        new_erp_buyer_id,
        tax_schedule_id,
        invoice_amount,
        approver_4,
        approver_5,
        company,
        profile_id,
        invoice_post_date_error,
        document_class_type,
        fisherman_invoice,
        vendor_name,
        current_approver,
        approver_1,
        approver_2,
        landed_cost,
        bol_reference,
        posting_date,
        invoice_date,
        erp_batch_number,
        currency,
        po_entered_as_nonpo,
        invoice___error,
        pay_amount,
        vendor_number,
        email_sender,
        erp_buyer_id,
        erp_reference_number,
        misc_amount,
        change_exchange_rate,
        payable_type,
        payment_terms,
        inter_company,
        receipt_number,
        additional_approver,
        subtype,
        freight_amount,
        batch_name,
        document_code,
        pre_approved,
        email_recipient,
        datarev,
        expedite_reason,
        expedite,
        incorrect_vendor,
        early_pay_discount,
        email_subject,
        exchange_rate,
        transaction_description,
        po_number,
        backup_approver_error,
        rct_invoice_match_error,
        invoice_number,
        invoice_amnt_currency_error,
        tax_amount,
        profile_name,
        po_reference,
        hst_error,
        payment_number,
        profile_create_date,
        coding_ic_error,
        due_date,
        error_date_time,
        keyed_in_wrong_company,
        early_pay_date,
        cast("1099_AMOUNT" as number) as amount_1099,
        new_exchange_rate,
        original_exchange_rate,
        capture_type,
        vendor,
        description_error,
        company_name,
        prepaid,
        profile_review,
        company_id,
        lastchange,
        purchasing_category,
        start_approval_date,
        payment_batch,
        remaining_po_amount,
        _fivetran_deleted,
        _fivetran_synced,
        trim(cast("1099_VENDOR" as varchar)) as is_1099_vendor

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
