with

source as (

    select {{ convert_columns('gmg_dbo', 'pop30110') }}
    from {{ source('gmg_dbo', 'pop30110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        projnum,
        vendorid,
        fax,
        potype,
        polnesta,
        bcktxamt,
        country,
        polneary_5,
        jobnumbr,
        lstrcptdt,
        uofm,
        releasebydate,
        polneary_2,
        polneary_8,
        costtype,
        linenumber,
        phone2,
        origprmdate,
        extdcost,
        reqstdby,
        lineorigin,
        costcatid,
        cmpnynam,
        prmdate,
        vctnmthd,
        ccode,
        purchase_item_tax_schedu,
        itemnmbr,
        shipmthd,
        reqdate,
        polneary_3,
        dex_row_id,
        polneary_9,
        purchsitetxschsrc,
        itmtrkop,
        print_phone_numbergb,
        umqtyinb,
        source_document_line_num,
        oruntcst,
        source_document_number,
        city,
        released_date,
        adrscode,
        obtaxamt,
        contact,
        phone3,
        addrsource,
        vnditdsc,
        address1,
        orextcst,
        commntid,
        purchase_iv_item_taxable,
        flags,
        decplcur,
        purchase_site_tax_schedu,
        state,
        decplqty,
        polneary_4,
        costcode,
        qtyorder,
        qtycance,
        polneary_1,
        address3,
        phone1,
        polneary_7,
        currnidx,
        noninven,
        fstrcptdt,
        release,
        bsivcttl,
        taxamnt,
        dex_row_ts,
        odecplcu,
        product_indicator,
        landed_cost_group_id,
        address2,
        polneary_6,
        freeonboard,
        ortaxamt,
        doctype,
        zipcode,
        invindx,
        locncode,
        itemdesc,
        prmshpdte,
        vnditnum,
        unitcost,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
