with

source as (

    select {{ convert_columns('gmg_dbo', 'pop10110') }}
    from {{ source('gmg_dbo', 'pop10110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        opostsub,
        qtycommittedinbaseorig,
        address1,
        releasebydate,
        flags,
        contact,
        purchase_iv_item_taxable,
        addrsource,
        purchase_item_tax_schedu,
        currnidx,
        bsivcttl,
        commntid,
        phone3,
        taxamnt,
        obtaxamt,
        decplcur,
        polneary_4,
        polneary_1,
        locncode,
        polneary_7,
        source_document_number,
        dex_row_id,
        zipcode,
        costcode,
        itmtrkop,
        vendorid,
        projnum,
        print_phone_numbergb,
        orextcst,
        lstrcptdt,
        country,
        unitcost,
        capital_item,
        polneary_5,
        polneary_2,
        qtycmtbase,
        bcktxamt,
        origprmdate,
        xchgrate,
        address2,
        city,
        origbackouttradedisctax,
        reqdate,
        state,
        polneary_3,
        polnesta,
        ortaxamt,
        ratecalc,
        costtype,
        itemnmbr,
        adrscode,
        umqtyinb,
        decplqty,
        purchase_site_tax_schedu,
        itemdesc,
        qtyuncmtbase,
        qtycance,
        costcatid,
        denxrate,
        phone1,
        po_line_status_orig,
        noninven,
        polneary_6,
        vctnmthd,
        qtyorder,
        odecplcu,
        phone2,
        doctype,
        invindx,
        address3,
        prmshpdte,
        purchsitetxschsrc,
        shipmthd,
        change_order_flag,
        released_date,
        plnndspplid,
        qty_canceled_orig,
        polneary_8,
        product_indicator,
        freeonboard,
        source_document_line_num,
        jobnumbr,
        extdcost,
        vnditnum,
        reqstdby,
        uofm,
        oruntcst,
        cmpnynam,
        potype,
        backouttradedisctax,
        prmdate,
        vnditdsc,
        curncyid,
        fstrcptdt,
        release,
        ccode,
        linenumber,
        dex_row_ts,
        lineorigin,
        landed_cost_group_id,
        polneary_9,
        fax,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
