with source as (

    select * from {{ source('gmg_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        frtamnt,
        pyenttyp,
        dex_row_ts,
        vendorid,
        docamnt,
        hold,
        ptdusrid,
        corrctn,
        invoicereceiptdate,
        taxinvreqd,
        workflow_status,
        bktmscam,
        disavtkn,
        prctdisc,
        vndchknm,
        trxsorce,
        mscchamt,
        voidpdate,
        discamnt,
        ten99amnt,
        curtrxam,
        cntrltyp,
        trxdscrn,
        cardname,
        dscdlram,
        ponumber,
        distknam,
        tax_date,
        docnumbr,
        ten99type,
        discdate,
        retnagam,
        pstgdate,
        noteindx,
        ictrx,
        docprinted,
        un1099am,
        curncyid,
        bchsourc,
        ttlpymts,
        mscschid,
        duedate,
        prchamnt,
        voided,
        pgramsbj,
        posteddt,
        prchdate,
        simplifd,
        bktfrtam,
        bktpuram,
        aplywith,
        taxschid,
        pymtrmid,
        shipmthd,
        modifdt,
        mdfusrid,
        chekbkid,
        vadcdtro,
        lngdesc,
        taxamnt,
        dinvpdof,
        gstdsamt,
        frtschid,
        disamtav,
        dex_row_id,
        pchschid,
        cbvat,
        pordnmbr,
        electronic,
        wrofamnt,
        ectrx,
        backouttradedisc,
        ppsamded,
        trdisamt,
        ten99boxnumber,
        docdate,
        bachnumb,
        ppstaxrt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
