with

source as (

    select * from {{ source('gmg_dbo', 'pm10000') }}

),

renamed as (

    select
        bachnumb,
        bchsourc,
        vchnumwk,
        crcrdamt,
        dex_row_ts,
        bktpuram,
        vaddcdpr,
        campynbr,
        electronic,
        printed,
        crcarddt,
        ictrx,
        taxinvreqd,
        taxschid,
        frtamnt,
        cardname,
        vendorid,
        ten99boxnumber,
        posted,
        gstdsamt,
        txengcld,
        bktfrtam,
        cdocnmbr,
        sourcdoc,
        chamcbid,
        mscchamt,
        un1099am,
        tax_date,
        curtrxam,
        posteddt,
        ppsamded,
        chekamnt,
        prctdisc,
        dex_row_id,
        bktmscam,
        trdisamt,
        simplifd,
        aplywith,
        pmdstmsg,
        camtdate,
        pchschid,
        apdstkam,
        prchdate,
        docnumbr,
        cheknmbr,
        docprinted,
        ppstaxrt,
        lngdesc,
        ptdusrid,
        duedate,
        ectrx,
        docdate,
        wrofamnt,
        appldamt,
        workflow_status,
        chrgamnt,
        modifdt,
        invoicereceiptdate,
        vadcdtro,
        trxdscrn,
        pordnmbr,
        noteindx,
        prchamnt,
        icdists,
        dscdlram,
        mdfusrid,
        cashamnt,
        pstgdate,
        corrctn,
        backouttradedisc,
        ten99amnt,
        frtschid,
        curncyid,
        pstgstus,
        ccrctnum,
        retnagam,
        discdate,
        vchrnmbr,
        chekdate,
        shipmthd,
        bnkrcamt,
        cbvat,
        camcbkid,
        taxamnt,
        corrnxst,
        chekbkid,
        ccampynm,
        ten99type,
        doctype,
        docamnt,
        pmwrkmsg,
        disamtav,
        pmwrkms2,
        cntrltyp,
        campmtnm,
        vchrncor,
        pgramsbj,
        pymtrmid,
        mscschid,
        pmicmsgs,
        distknam,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
