with source as (

    select * from {{ source('gmg_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        ppsamded,
        dex_row_id,
        cardname,
        dinvpdof,
        frtschid,
        prchdate,
        docprinted,
        simplifd,
        aplywith,
        wrofamnt,
        bktpuram,
        cntrltyp,
        ten99boxnumber,
        bachnumb,
        lngdesc,
        modifdt,
        duedate,
        disamtav,
        distknam,
        trdisamt,
        un1099am,
        dscdlram,
        pgramsbj,
        ponumber,
        shipmthd,
        ptdusrid,
        trxsorce,
        invoicereceiptdate,
        prchamnt,
        hold,
        vendorid,
        mscschid,
        pstgdate,
        noteindx,
        trxdscrn,
        prctdisc,
        retnagam,
        pyenttyp,
        gstdsamt,
        taxamnt,
        mscchamt,
        tax_date,
        ten99type,
        disavtkn,
        electronic,
        vadcdtro,
        discamnt,
        ten99amnt,
        ectrx,
        mdfusrid,
        pymtrmid,
        backouttradedisc,
        dex_row_ts,
        ictrx,
        discdate,
        bktmscam,
        docnumbr,
        pchschid,
        curtrxam,
        frtamnt,
        cbvat,
        docdate,
        bchsourc,
        voided,
        corrctn,
        docamnt,
        curncyid,
        ttlpymts,
        bnkrcamt,
        bktfrtam,
        ppstaxrt,
        vndchknm,
        taxschid,
        chekbkid,
        pordnmbr,
        taxinvreqd,
        posteddt,
        workflow_status,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
