with source as (

    select * from {{ source('gmg_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        shipmthd,
        dex_row_id,
        ccrdxpdt,
        bankname,
        rmsoracc,
        rmcosacc,
        taxschid,
        custpriority,
        adrscode,
        rmtakacc,
        userdef2,
        rmfcgacc,
        fnchatyp,
        curncyid,
        phone1,
        minpypct,
        crcardid,
        inactive,
        kperhist,
        slprsnid,
        gpsfointegrationid,
        address2,
        noteindx,
        mxwoftyp,
        pymtrmid,
        disgrper,
        crlmtpam,
        custdisc,
        custname,
        phone2,
        prbtadcd,
        revalue_customer,
        fax,
        shrtname,
        includeindp,
        salsterr,
        rmaracc,
        integrationsource,
        post_results_to,
        duegrper,
        stmtcycl,
        comment1,
        zip,
        kpcalhst,
        docfmtid,
        country,
        govcrpid,
        govindid,
        ccode,
        crlmtper,
        defcacty,
        rmwracc,
        chekbkid,
        txrgnnum,
        stmtname,
        declid,
        crlmttyp,
        rmavacc,
        kpdsthst,
        userlang,
        address3,
        integrationid,
        crcrdnum,
        bnkbrnch,
        send_email_statements,
        shipcomplete,
        ratetpid,
        rmslsacc,
        orderfulfilldefault,
        rmivacc,
        hold,
        comment2,
        userdef1,
        mxwrofam,
        phone3,
        dex_row_ts,
        rmcshacc,
        staddrcd,
        prclevel,
        upszone,
        crlmtamt,
        kptrxhst,
        cbvat,
        fnchpcnt,
        finchdlr,
        frstindt,
        cntcprsn,
        prstadcd,
        minpytyp,
        taxexmt1,
        address1,
        state,
        cprcstnm,
        rmovrpymtwrtoffacctidx,
        custclas,
        minpydlr,
        balnctyp,
        modifdt,
        taxexmt2,
        creatddt,
        finchid,
        city,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
