with source as (

    select * from {{ source('gmg_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        taxinvrecvd,
        vaddcdpr,
        pmrtngix,
        crtexpdt,
        kptrxhst,
        pmapindx,
        cbvat,
        ptcshacf,
        chekbkid,
        writeoff,
        userlang,
        vadcdtro,
        shipmthd,
        noteindx,
        dex_row_id,
        address3,
        comment2,
        city,
        pmdavidx,
        workflow_priority,
        vadcdpad,
        minpytyp,
        kpcalhst,
        taxfilenummode,
        mxwofamt,
        vndchknm,
        withholdingformtype,
        ten99boxnumber,
        pymtrmid,
        post_results_to,
        govindid,
        faxnumbr,
        pmtdscix,
        prspayee,
        pmfrtidx,
        dxvarnum,
        docfmtid,
        phone3,
        acnmvndr,
        phnumbr1,
        pmtaxidx,
        phnumbr2,
        rtobutkn,
        zipcode,
        country,
        onepaypervendinv,
        trddisct,
        vendstts,
        pmfinidx,
        venddba,
        credtlmt,
        acpuridx,
        txidnmbr,
        upszone,
        ten99type,
        pmcshidx,
        pmwrtidx,
        mxiafvnd,
        dex_row_ts,
        state,
        brthdate,
        pymntpri,
        pmmschix,
        minorder,
        govcrpid,
        crlmtdlr,
        disgrper,
        workflow_approval_status,
        declid,
        ccode,
        duegrper,
        workflow_status,
        maxindlr,
        ppstaxrt,
        minpypct,
        kgldsths,
        pmprchix,
        parvenid,
        crtcomdt,
        comment1,
        hold,
        address2,
        vadcdsfr,
        userdef1,
        withholdingtype,
        laborpmttype,
        pmdtkidx,
        xpdtoblg,
        revalue_vendor,
        creatddt,
        vendname,
        kperhist,
        vendshnm,
        vndclsid,
        vadcd1099,
        taxschid,
        ratetpid,
        freeonboard,
        withholdingentitytype,
        curncyid,
        purpvidx,
        userdef2,
        minpydlr,
        modifdt,
        vndcntct,
        address1,
        txrgnnum,
        sbppsded,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
