with source as (

    select * from {{ source('gmg_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        saledate,
        lstusred,
        dscpctam,
        eftflag,
        bachnumb,
        corrctn,
        directdebit,
        adrscode,
        noteindx,
        aplywith,
        agngbukt,
        pstusrid,
        cbkidcsh,
        lstedtdt,
        tax_date,
        trxsorce,
        cprcstnm,
        glpostdt,
        cheknmbr,
        cspornbr,
        dex_row_ts,
        disavamt,
        ppsamded,
        disavtkn,
        delete1,
        dinvpdof,
        curncyid,
        discrtnd,
        bktfrtam,
        trxdscrn,
        ortrxamt,
        wrofamnt,
        bktmscam,
        duedate,
        taxschid,
        electronic,
        dex_row_id,
        factoring,
        miscamnt,
        frtschid,
        taxamnt,
        mscschid,
        ectrx,
        discdate,
        dscdlram,
        bktslsam,
        frtamnt,
        slstercd,
        cbkidchk,
        voidstts,
        slsamnt,
        backouttradedisc,
        gstdsamt,
        trdisamt,
        costamnt,
        shipmthd,
        comdlram,
        simplifd,
        voiddate,
        bchsourc,
        cshrctyp,
        slprsnid,
        cbkidcrd,
        postdate,
        cashamnt,
        pymtrmid,
        distknam,
        slschdid,
        curtrxam,
        docdate,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
