with source as (

    select * from {{ source('cph_dbo', 'pm10000') }}

),

renamed as (

    select
        bachnumb,
        bchsourc,
        vchnumwk,
        prchamnt,
        ictrx,
        dex_row_id,
        campynbr,
        prchdate,
        trdisamt,
        noteindx,
        electronic,
        ppstaxrt,
        txengcld,
        sourcdoc,
        cardname,
        backouttradedisc,
        chrgamnt,
        simplifd,
        retnagam,
        vchrncor,
        discdate,
        cheknmbr,
        ten99type,
        pymtrmid,
        pchschid,
        wrofamnt,
        appldamt,
        chekdate,
        mscschid,
        corrnxst,
        bnkrcamt,
        docdate,
        dscdlram,
        campmtnm,
        cashamnt,
        printed,
        taxinvreqd,
        shipmthd,
        bktfrtam,
        tax_date,
        pmicmsgs,
        camtdate,
        disamtav,
        ten99amnt,
        chekbkid,
        icdists,
        docprinted,
        pordnmbr,
        ccampynm,
        vendorid,
        docamnt,
        pmwrkms2,
        duedate,
        mdfusrid,
        doctype,
        posteddt,
        invoicereceiptdate,
        vadcdtro,
        cdocnmbr,
        taxamnt,
        aplywith,
        cntrltyp,
        pstgdate,
        pgramsbj,
        ectrx,
        trxdscrn,
        distknam,
        bktpuram,
        curtrxam,
        ptdusrid,
        docnumbr,
        ppsamded,
        chekamnt,
        pmwrkmsg,
        pmdstmsg,
        lngdesc,
        crcarddt,
        prctdisc,
        frtamnt,
        workflow_status,
        corrctn,
        chamcbid,
        ccrctnum,
        pstgstus,
        un1099am,
        mscchamt,
        taxschid,
        camcbkid,
        modifdt,
        gstdsamt,
        vchrnmbr,
        frtschid,
        posted,
        crcrdamt,
        cbvat,
        ten99boxnumber,
        curncyid,
        vaddcdpr,
        dex_row_ts,
        bktmscam,
        apdstkam,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
