with open_invoices as (
    select
        transaction_id,
        company_id,
        vendor_id,
        document_type_id,
        currency_id,
        voucher,
        bach_number,
        payment_terms as pymtrmid,
        userid,
        document_number,
        document_date,
        gl_posting_date,
        due_date,
        po_number,
        company_currency,
        functional_document_amount,
        functional_transaction_amount,
        converted_originating_document_amount as originating_document_amount,
        converted_originating_transaction_amount as originating_transaction_amount,
        cad_amount,
        usd_amount,
        cad_purchase_amount,
        usd_purchase_amount,
        current_amount_due_dt,
        "1_to_15_days_amount_due_dt",
        "16_to_30_days_amount_due_dt",
        "31_to_60_days_amount_due_dt",
        "61_to_90_days_amount_due_dt",
        "91_and_over_amount_due_dt",
        current_amount_doc_dt,
        "1_to_15_days_amount_doc_dt",
        "16_to_30_days_amount_doc_dt",
        "31_to_60_days_amount_doc_dt",
        "61_to_90_days_amount_doc_dt",
        "91_and_over_amount_doc_dt",
        current_org_amt_due_dt,
        "1_to_15_days_org_amt_due_dt",
        "16_to_30_days_org_amt_due_dt",
        "31_to_60_days_org_amt_due_dt",
        "61_to_90_days_org_amt_due_dt",
        "91_and_over_org_amt_due_dt",
        current_org_amt_doc_dt,
        "1_to_15_days_org_amt_doc_dt",
        "16_to_30_days_org_amt_doc_dt",
        "31_to_60_days_org_amt_doc_dt",
        "61_to_90_days_org_amt_doc_dt",
        "91_and_over_org_amt_doc_dt",
        sk_vendor_global,
        sk_doctype_global,
        status

    from {{ ref('int_global_ap__gp__open_invoices') }}
)

select * from open_invoices
