with

source as (

    select * from {{ source('finops_adls_crp', 'dir_party_table') }}

),

renamed as (

    select
        recid,
        _sys_row_id,
        lsn,
        last_processed_change_date_time,
        data_lake_modified_date_time,
        instancerelationtype,
        languageid,
        name,
        namealias,
        partynumber,
        primaryaddresslocation,
        primarycontactemail,
        primarycontactfax,
        primarycontactphone,
        primarycontacttelex,
        primarycontacturl,
        primarycontactfacebook,
        primarycontacttwitter,
        primarycontactlinkedin,
        addressbooknames,
        legacyinstancerelationtype,
        omoperatingunitnumber,
        omoperatingunittype,
        hcmworker,
        dunsnumberrecid,
        abc,
        numberofemployees,
        orgnumber,
        anniversaryday,
        anniversarymonth,
        anniversaryyear,
        birthday,
        birthmonth,
        birthyear,
        communicatorsignin,
        gender,
        maritalstatus,
        namesequence,
        personalsuffix,
        personaltitle,
        combinedfedstatefiler,
        companytype_mx,
        conversiondate,
        coregnum,
        dataarea,
        foreignentityindicator,
        isconsolidationcompany,
        iseliminationcompany,
        key_,
        lastfilingindicator,
        legalnature_it,
        planningcompany,
        printinnkppinaddress_ru,
        resident_w,
        tax_1099_regnum,
        validate_1099_onentry,
        businesscommenceddate_jp,
        businessinitialcapital_jp,
        printcorrinvoicelabel_de,
        printcorrinvoicelabeleffdate_de,
        printenterpriseregister_no,
        localizationcountryregioncode,
        dashboardimagetype,
        companynafcode,
        payminstruction_1,
        payminstruction_2,
        payminstruction_3,
        payminstruction_4,
        companyinitialcapital_fr,
        eeenablepersonaldatareadlog,
        eeenablerolechangelog,
        profitmarginscheme_ae,
        vatrefund_ae,
        vatoncustomerbehalf_ae,
        taxablepersonname_ae,
        declarantname_ae,
        taxableagentname_ae,
        taxableagencyname_ae,
        organizationtype,
        description,
        isactive,
        teammembershipcriterion,
        partition,
        recversion,
        modifieddatetime,
        modifiedby,
        createddatetime,
        createdby,
        relationtype,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
