with

source as (

    select * from {{ source('finops_adls_crp', 'cust_table') }}

),

renamed as (

    select
        recid,
        _sys_row_id,
        lsn,
        last_processed_change_date_time,
        data_lake_modified_date_time,
        paymtermid::string as cspaymtermid,
        accountnum,
        accountstatement,
        affiliated_ru,
        bankcustpaymidtable,
        blocked,
        cashdiscbasedays,
        companynafcode,
        companytype_mx,
        consday_jp,
        creditcardaddressverification,
        creditcardaddressverificationlevel,
        creditcardaddressverificationvoid,
        creditcardcvc,
        creditmax,
        currency::string as cscurrency,
        custexcludecollectionfee,
        custexcludeinterestcharges,
        custfinaluser_br,
        custgroup::string as cscustgroup,
        custtradingpartnercode,
        custwhtcontributiontype_br,
        defaultdimension,
        defaultdirectdebitmandate,
        dlvmode,
        einvoice,
        einvoiceattachment,
        entrycertificaterequired_w,
        exportsales_pl,
        expressbilloflading,
        federalcomments,
        fednonfedindicator,
        fiscaldoctype_pl,
        forecastdmpinclude,
        foreignresident_ru,
        generateincomingfiscaldocument_br,
        girotype,
        girotypeaccountstatement,
        girotypecollectionletter,
        girotypefreetextinvoice,
        girotypeinterestnote,
        girotypeprojinvoice,
        icmscontributor_br,
        identificationnumber,
        incltax,
        intercompanyallowindirectcreation,
        intercompanyautocreateorders,
        intercompanydirectdelivery,
        inventlocation,
        inventprofiletype_ru,
        inventsiteid,
        invoiceaccount::string as csinvoiceaccount,
        invoiceaddress,
        invoicepostingtype_ru,
        irs_1099_cindicator,
        isresident_lv,
        issueownentrycertificate_w,
        lineofbusinessid,
        lvpaymtranscodes,
        maincontactworker::string as csmaincontactworker,
        mandatorycreditlimit,
        mandatoryvatdate_pl,
        memo,
        onetimecustomer,
        ouraccountnum,
        packagedepositexcempt_pl,
        party::string as csparty,
        paymmode,
        pdsfreightaccrued,
        rfidcasetagging,
        rfiditemtagging,
        rfidpallettagging,
        servicecodeondlvaddress_br,
        shipcarrierblindshipment,
        shipcarrierfuelsurcharge,
        suframa_br,
        suframapiscofins_br,
        taxgroup,
        taxwithholdcalculate_in,
        taxwithholdcalculate_th,
        unitedvatinvoice_lt,
        usecashdisc,
        usepurchrequest,
        vendaccount,
        websalesorderdisplay,
        einvoiceregister_it,
        presencetype_br,
        taxgstreliefgroupheading_my,
        custwriteoffrefrecid,
        isexternallymaintained,
        cfdienabled_mx,
        foreigntrade_mx,
        workflowstate,
        useoriginaldocumentasfacture_ru,
        collectionlettercode,
        blockfloorlimituseinchannel,
        cfdiskipiepstaxes_mx,
        simplifytaxintgrexportdocvalidation_cn,
        simplenational_br,
        vatnumrecid,
        vatnumtabletype,
        usualexporter_it,
        ispublicsector_it,
        simplifytaxintgrexporttaxregvalidation_cn,
        printdynamicqrcode_in,
        credmaneligiblecreditlimitdate,
        credmanexclude,
        credmaneligiblecreditmax,
        credmanbusinessstarted,
        credmantitleheld,
        credmancustcreditmaxalt,
        credmancustomersince,
        credmanwithagency,
        credmanstatusreasonid,
        credmancreditlimitexpirydate,
        credmancreditlimitdate,
        credmanlastreviewdate,
        credmannextschedreviewdate,
        credmancustunlimitedcredit,
        revrecdisableintercompany,
        partition,
        recversion,
        modifieddatetime,
        modifiedby,
        createddatetime,
        overridesalestax,
        invoicetype_w,
        cfditemporaryexport_mx,
        _fivetran_deleted,
        _fivetran_synced,
        upper(dataareaid::string) as csdataareaid,
        trim(credmanaccountstatusid::string) as cscredmanaccountstatusid

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
