with

source as (

    select * from {{ source('finops_adls_crp', 'invent_table') }}

),

renamed as (

    select
        recid,
        _sys_row_id,
        lsn,
        last_processed_change_date_time,
        data_lake_modified_date_time,
        abccontributionmargin,
        abcrevenue,
        abctieup,
        abcvalue,
        alcoholstrength_ru,
        approxtaxvalue_br,
        autoreportfinished,
        batchmergedatecalculationmethod,
        batchnumgroupid,
        bomlevel,
        bommanualreceipt,
        bomunitid,
        costgroupid,
        costmodel,
        customsexporttariffcodetable_in,
        customsimporttariffcodetable_in,
        defaultdimension,
        density,
        depth,
        excisetariffcodes_in,
        eximproductgrouptable_in,
        fiscallifoavoidcalc,
        fiscallifonormalvalue,
        fiscallifonormalvaluecalc,
        forecastdmpinclude,
        grossdepth,
        grossheight,
        grosswidth,
        height,
        icmsonservice_br,
        intrastatcommodity,
        intrastatexclude,
        inventfiscallifogroup,
        itembuyergroupid,
        itemdimcostprice,
        itemtype,
        matchingpolicy,
        minimumpalletquantity,
        namealias,
        netweight,
        ngpcodestable_fr,
        pdsbestbefore,
        pdscwwmsminimumpalletqty,
        pdscwwmsqtyperlayer,
        pdscwwmsstandardpalletqty,
        pdspotencyattribrecording,
        pdsshelfadvice,
        pdsshelflife,
        pdstargetfactor,
        pdsvendorcheckitem,
        phantom,
        pmfproducttype,
        pmfyieldpct,
        primaryvendorid,
        prodflushingprincip,
        prodgroupid,
        prodpoolid,
        product,
        purchmodel,
        qtyperlayer,
        reqgroupid,
        salescontributionratio,
        salesmodel,
        salespercentmarkup,
        salespricemodelbasic,
        scrapconst,
        scrapvar,
        serialnumgroupid,
        servicecodetable_in,
        skipintracompanysync_ru,
        sortcode,
        standardpalletquantity,
        statisticsfactor,
        taraweight,
        taxationorigin_br,
        taxpackagingqty,
        unitvolume,
        usealtitemid,
        width,
        wmsarrivalhandlingtime,
        wmspickingqtytime,
        dsa_in,
        exciserecordtype_in,
        hsncodetable_in,
        serviceaccountingcodetable_in,
        exempt_in,
        productlifecyclestateid::string as prodlifecyclestateid,
        scaleindicator_br,
        nongst_in,
        taxratetype,
        intrastatchargeperkg,
        hmimindicator,
        coodualuseproduct,
        costbomlevel,
        revrecexcludefromcarveout,
        revrecmedianprice,
        revrecmedianpricemaximumtolerance,
        revrecmedianpriceminimumtolerance,
        revrecrevenuerecognitionenabled,
        revrecrevenuetype,
        revrecbundle,
        partition,
        recversion,
        modifieddatetime,
        modifiedby,
        createddatetime,
        createdby,
        displayhazard_mx,
        _fivetran_deleted,
        _fivetran_synced,
        bomwhsreleasepolicy,
        trim(itemid) as itemid,
        upper(trim(dataareaid)) as dataareaid

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
