with source as (

    select * from {{ source('hpi_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        aplywith,
        mdfusrid,
        vadcdtro,
        pordnmbr,
        prchdate,
        frtamnt,
        pymtrmid,
        prctdisc,
        dscdlram,
        docprinted,
        dinvpdof,
        chekbkid,
        docamnt,
        disamtav,
        pchschid,
        bktmscam,
        ten99amnt,
        disavtkn,
        docnumbr,
        discamnt,
        simplifd,
        dex_row_id,
        gstdsamt,
        curncyid,
        taxamnt,
        cbvat,
        bchsourc,
        ppstaxrt,
        posteddt,
        ten99boxnumber,
        ppsamded,
        backouttradedisc,
        modifdt,
        workflow_status,
        duedate,
        wrofamnt,
        bnkrcamt,
        taxschid,
        vndchknm,
        ttlpymts,
        ectrx,
        trxdscrn,
        tax_date,
        lngdesc,
        un1099am,
        cardname,
        trdisamt,
        frtschid,
        bachnumb,
        bktfrtam,
        ponumber,
        pgramsbj,
        taxinvreqd,
        discdate,
        pstgdate,
        dex_row_ts,
        hold,
        prchamnt,
        electronic,
        vendorid,
        corrctn,
        mscchamt,
        docdate,
        pyenttyp,
        curtrxam,
        invoicereceiptdate,
        mscschid,
        distknam,
        ten99type,
        bktpuram,
        trxsorce,
        cntrltyp,
        noteindx,
        ptdusrid,
        voided,
        ictrx,
        shipmthd,
        retnagam,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
