with source as (

    select * from {{ source('hpi_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        prclevel,
        send_email_statements,
        minpypct,
        rmcshacc,
        ccrdxpdt,
        kpdsthst,
        phone2,
        finchdlr,
        shipcomplete,
        state,
        minpydlr,
        shrtname,
        post_results_to,
        crlmtamt,
        taxexmt2,
        txrgnnum,
        custpriority,
        crlmtper,
        govindid,
        custclas,
        salsterr,
        cprcstnm,
        rmaracc,
        chekbkid,
        integrationid,
        ccode,
        modifdt,
        comment1,
        crlmttyp,
        revalue_customer,
        fnchpcnt,
        balnctyp,
        pymtrmid,
        disgrper,
        adrscode,
        cbvat,
        creatddt,
        curncyid,
        bnkbrnch,
        taxschid,
        frstindt,
        kperhist,
        rmslsacc,
        address2,
        userdef2,
        rmwracc,
        userlang,
        crlmtpam,
        rmcosacc,
        rmtakacc,
        rmsoracc,
        userdef1,
        address3,
        rmivacc,
        rmfcgacc,
        custdisc,
        kpcalhst,
        prbtadcd,
        slprsnid,
        mxwrofam,
        cntcprsn,
        country,
        finchid,
        address1,
        zip,
        taxexmt1,
        fax,
        rmavacc,
        phone1,
        prstadcd,
        city,
        docfmtid,
        stmtname,
        declid,
        includeindp,
        bankname,
        govcrpid,
        defcacty,
        rmovrpymtwrtoffacctidx,
        comment2,
        stmtcycl,
        duegrper,
        ratetpid,
        shipmthd,
        fnchatyp,
        minpytyp,
        orderfulfilldefault,
        inactive,
        mxwoftyp,
        integrationsource,
        dex_row_id,
        dex_row_ts,
        gpsfointegrationid,
        custname,
        upszone,
        noteindx,
        hold,
        crcardid,
        crcrdnum,
        staddrcd,
        phone3,
        kptrxhst,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
