with source as (

    select * from {{ source('hpi_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        userlang,
        noteindx,
        phnumbr1,
        modifdt,
        parvenid,
        minpydlr,
        ptcshacf,
        crtexpdt,
        pymtrmid,
        writeoff,
        userdef1,
        vendname,
        phone3,
        ccode,
        curncyid,
        kgldsths,
        kperhist,
        docfmtid,
        country,
        pmtdscix,
        address1,
        pmcshidx,
        txidnmbr,
        vndcntct,
        upszone,
        vendstts,
        laborpmttype,
        onepaypervendinv,
        vaddcdpr,
        pymntpri,
        prspayee,
        kpcalhst,
        pmfinidx,
        address3,
        pmtaxidx,
        workflow_priority,
        rtobutkn,
        workflow_status,
        withholdingformtype,
        vndchknm,
        taxfilenummode,
        acnmvndr,
        mxwofamt,
        disgrper,
        pmmschix,
        comment2,
        faxnumbr,
        address2,
        maxindlr,
        taxinvrecvd,
        comment1,
        govindid,
        vadcdpad,
        dxvarnum,
        kptrxhst,
        acpuridx,
        crlmtdlr,
        pmdavidx,
        minorder,
        purpvidx,
        trddisct,
        vndclsid,
        vadcd1099,
        withholdingentitytype,
        creatddt,
        ratetpid,
        phnumbr2,
        mxiafvnd,
        pmrtngix,
        freeonboard,
        userdef2,
        ten99type,
        vendshnm,
        pmfrtidx,
        zipcode,
        txrgnnum,
        credtlmt,
        pmapindx,
        cbvat,
        venddba,
        dex_row_ts,
        hold,
        dex_row_id,
        withholdingtype,
        state,
        crtcomdt,
        govcrpid,
        taxschid,
        chekbkid,
        sbppsded,
        declid,
        pmprchix,
        pmwrtidx,
        workflow_approval_status,
        shipmthd,
        xpdtoblg,
        post_results_to,
        ten99boxnumber,
        vadcdtro,
        ppstaxrt,
        brthdate,
        minpypct,
        revalue_vendor,
        city,
        duegrper,
        vadcdsfr,
        minpytyp,
        pmdtkidx,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
