with source as (

    select * from {{ source('tnsus_dbo', 'pop30300') }}

),

renamed as (

    select
        backoutmisctaxamt,
        simplifd,
        mscschid,
        total_landed_cost_amount,
        purchase_freight_taxable,
        voidstts,
        shipmthd,
        denxrate,
        orfrttax,
        msctxamt,
        exgtblid,
        actlship,
        vadcdtro,
        dscdlram,
        curncyid,
        ordavamt,
        ortdisam,
        ten99boxnumber,
        duedate,
        purchase_misc_taxable,
        pymtrmid,
        orfrtamt,
        rcptnote_6,
        exchdate,
        miscamnt,
        bchsourc,
        rcptnote_4,
        rcptnote_1,
        backoutfreighttaxamt,
        disavtkn,
        taxamnt,
        creatddt,
        ratecalc,
        xchgrate,
        replacegoods,
        trdpctpr,
        rcptnote_2,
        frttxamt,
        ten99type,
        distknam,
        mctrxstt,
        subtotal,
        ectrx,
        pophdr1,
        obtaxamt,
        dex_row_id,
        ratetpid,
        taxschid,
        rcptnote_3,
        ordistkn,
        refrence,
        ten99amnt,
        pop_hdr_errors_4,
        tax_date,
        ormsctax,
        pophdr2,
        ppstaxrt,
        frtschid,
        glpostdt,
        taxinvrecvd,
        modifdt,
        workflow_status,
        frtamnt,
        taxinvreqd,
        invoicereceiptdate,
        rcptnote_5,
        withhamt,
        revaljrnentry,
        origbackoutfreighttaxamt,
        user2ent,
        bsivcttl,
        prepaymentamount,
        ptdusrid,
        currnidx,
        aplywith,
        receiptdate,
        bcktxamt,
        dscpctam,
        poplnerr,
        orsubtot,
        time1,
        poptype,
        orddlrat,
        vendname,
        invoiceexpected,
        rcptnote_7,
        vnddocnm,
        ordatkn,
        posteddt,
        txrgnnum,
        discdate,
        disavamt,
        originatingprepaymentamt,
        cbvat,
        rcptnote_8,
        vchrnmbr,
        origbackoutmisctaxamt,
        revaltrxsource,
        trxsorce,
        ortaxamt,
        bachnumb,
        trdisamt,
        ormiscamt,
        or1099am,
        _fivetran_deleted,
        _fivetran_synced,
        upper(trim(poprctnm)) as poprctnm,
        upper(trim(vendorid)) as vendorid

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
