with

source as (

    select * from {{ source('tnsus_dbo', 'pm10000') }}

),

renamed as (

    select
        corrnxst,
        bktpuram,
        aplywith,
        curncyid,
        cbvat,
        crcrdamt,
        simplifd,
        frtschid,
        chamcbid,
        apdstkam,
        txengcld,
        cdocnmbr,
        ten99boxnumber,
        bchsourc,
        posted,
        docamnt,
        distknam,
        corrctn,
        ppsamded,
        icdists,
        vaddcdpr,
        ectrx,
        modifdt,
        chekamnt,
        pgramsbj,
        campynbr,
        dex_row_ts,
        cntrltyp,
        frtamnt,
        printed,
        taxamnt,
        bktfrtam,
        doctype,
        ten99type,
        sourcdoc,
        campmtnm,
        noteindx,
        ten99amnt,
        taxschid,
        camcbkid,
        trxdscrn,
        ptdusrid,
        cardname,
        wrofamnt,
        pstgstus,
        appldamt,
        chekbkid,
        vchrnmbr,
        chrgamnt,
        chekdate,
        ccrctnum,
        workflow_status,
        cashamnt,
        docprinted,
        dscdlram,
        shipmthd,
        pstgdate,
        pymtrmid,
        pmwrkms2,
        cheknmbr,
        lngdesc,
        mscschid,
        pmdstmsg,
        vchrncor,
        docnumbr,
        pmicmsgs,
        disamtav,
        bachnumb,
        discdate,
        ccampynm,
        pmwrkmsg,
        vadcdtro,
        electronic,
        duedate,
        retnagam,
        dex_row_id,
        crcarddt,
        ictrx,
        taxinvreqd,
        bnkrcamt,
        docdate,
        tax_date,
        bktmscam,
        prctdisc,
        camtdate,
        trdisamt,
        vendorid,
        mdfusrid,
        mscchamt,
        prchamnt,
        un1099am,
        curtrxam,
        invoicereceiptdate,
        ppstaxrt,
        vchnumwk,
        pchschid,
        pordnmbr,
        prchdate,
        backouttradedisc,
        posteddt,
        gstdsamt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
