with source as (

    select * from {{ source('tnsus_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        stmtname,
        kptrxhst,
        cbvat,
        prstadcd,
        revalue_customer,
        finchid,
        fnchatyp,
        prbtadcd,
        creatddt,
        country,
        declid,
        userdef1,
        rmslsacc,
        city,
        zip,
        phone3,
        minpydlr,
        fax,
        dex_row_ts,
        inactive,
        rmaracc,
        disgrper,
        custdisc,
        mxwoftyp,
        taxexmt1,
        bnkbrnch,
        minpytyp,
        rmovrpymtwrtoffacctidx,
        ratetpid,
        userdef2,
        shipmthd,
        shipcomplete,
        bankname,
        modifdt,
        address3,
        fnchpcnt,
        finchdlr,
        cprcstnm,
        address1,
        cntcprsn,
        minpypct,
        pymtrmid,
        balnctyp,
        taxschid,
        frstindt,
        noteindx,
        custpriority,
        rmcshacc,
        state,
        userlang,
        phone2,
        salsterr,
        rmavacc,
        orderfulfilldefault,
        address2,
        gpsfointegrationid,
        taxexmt2,
        prclevel,
        txrgnnum,
        rmsoracc,
        custclas,
        rmtakacc,
        includeindp,
        stmtcycl,
        govindid,
        curncyid,
        hold,
        dex_row_id,
        slprsnid,
        crcardid,
        shrtname,
        kpdsthst,
        adrscode,
        kperhist,
        ccrdxpdt,
        integrationid,
        rmivacc,
        integrationsource,
        crlmtamt,
        duegrper,
        send_email_statements,
        post_results_to,
        staddrcd,
        rmwracc,
        govcrpid,
        crcrdnum,
        ccode,
        upszone,
        crlmttyp,
        kpcalhst,
        docfmtid,
        custname,
        chekbkid,
        comment1,
        rmfcgacc,
        mxwrofam,
        rmcosacc,
        crlmtper,
        comment2,
        defcacty,
        crlmtpam,
        phone1,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
