with source as (

    select * from {{ source('tnsus_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        duedate,
        frtschid,
        mscschid,
        cbkidchk,
        factoring,
        discdate,
        taxschid,
        postdate,
        disavtkn,
        shipmthd,
        slprsnid,
        curncyid,
        dinvpdof,
        agngbukt,
        slsamnt,
        cprcstnm,
        costamnt,
        comdlram,
        voiddate,
        slstercd,
        cspornbr,
        electronic,
        ectrx,
        cheknmbr,
        cashamnt,
        dscpctam,
        lstedtdt,
        dex_row_id,
        trxsorce,
        glpostdt,
        distknam,
        lstusred,
        curtrxam,
        dex_row_ts,
        saledate,
        adrscode,
        trdisamt,
        dscdlram,
        gstdsamt,
        aplywith,
        delete1,
        corrctn,
        bachnumb,
        frtamnt,
        bktmscam,
        eftflag,
        ortrxamt,
        docdate,
        backouttradedisc,
        miscamnt,
        voidstts,
        cbkidcrd,
        taxamnt,
        wrofamnt,
        cshrctyp,
        slschdid,
        bktslsam,
        pymtrmid,
        trxdscrn,
        ppsamded,
        simplifd,
        bchsourc,
        cbkidcsh,
        directdebit,
        pstusrid,
        bktfrtam,
        disavamt,
        noteindx,
        discrtnd,
        tax_date,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
