with source as (

    select * from {{ source('tnsus_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        bchsourc,
        workflow_status,
        noteindx,
        duedate,
        shipmthd,
        disavtkn,
        docnumbr,
        bktmscam,
        mscschid,
        gstdsamt,
        taxamnt,
        posteddt,
        mscchamt,
        prctdisc,
        dinvpdof,
        docdate,
        discamnt,
        ten99amnt,
        bachnumb,
        simplifd,
        pyenttyp,
        pstgdate,
        vadcdtro,
        docamnt,
        aplywith,
        cardname,
        cntrltyp,
        disamtav,
        ten99type,
        pchschid,
        voided,
        prchamnt,
        docprinted,
        un1099am,
        ictrx,
        voidpdate,
        pymtrmid,
        pgramsbj,
        modifdt,
        trdisamt,
        lngdesc,
        ppsamded,
        backouttradedisc,
        ppstaxrt,
        corrctn,
        dex_row_id,
        taxinvreqd,
        dex_row_ts,
        electronic,
        ponumber,
        trxsorce,
        ectrx,
        discdate,
        ptdusrid,
        ttlpymts,
        wrofamnt,
        hold,
        tax_date,
        invoicereceiptdate,
        trxdscrn,
        vendorid,
        bktpuram,
        frtschid,
        bktfrtam,
        cbvat,
        chekbkid,
        ten99boxnumber,
        pordnmbr,
        retnagam,
        prchdate,
        vndchknm,
        taxschid,
        frtamnt,
        curtrxam,
        mdfusrid,
        dscdlram,
        curncyid,
        distknam,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
