with source as (

    select * from {{ source('tnsus_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        ictrx,
        pchschid,
        tax_date,
        ten99boxnumber,
        vndchknm,
        disamtav,
        ppsamded,
        bktpuram,
        pstgdate,
        vendorid,
        dscdlram,
        mdfusrid,
        pordnmbr,
        cbvat,
        chekbkid,
        taxschid,
        voided,
        ptdusrid,
        bnkrcamt,
        un1099am,
        trxsorce,
        hold,
        ttlpymts,
        dex_row_id,
        shipmthd,
        invoicereceiptdate,
        pgramsbj,
        prctdisc,
        backouttradedisc,
        docamnt,
        trdisamt,
        pymtrmid,
        pyenttyp,
        wrofamnt,
        vadcdtro,
        duedate,
        dex_row_ts,
        gstdsamt,
        taxamnt,
        cntrltyp,
        simplifd,
        discdate,
        bachnumb,
        ten99type,
        dinvpdof,
        frtschid,
        prchdate,
        curtrxam,
        cardname,
        aplywith,
        docprinted,
        lngdesc,
        discamnt,
        ten99amnt,
        disavtkn,
        trxdscrn,
        modifdt,
        mscchamt,
        bktfrtam,
        mscschid,
        prchamnt,
        bktmscam,
        taxinvreqd,
        ponumber,
        docdate,
        posteddt,
        frtamnt,
        bchsourc,
        workflow_status,
        corrctn,
        distknam,
        curncyid,
        electronic,
        ectrx,
        ppstaxrt,
        noteindx,
        retnagam,
        docnumbr,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
