with source as (

    select * from {{ source('tnsus_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        kpcalhst,
        govindid,
        faxnumbr,
        address2,
        vadcdpad,
        comment1,
        pmcshidx,
        ptcshacf,
        xpdtoblg,
        phnumbr2,
        writeoff,
        minpydlr,
        dxvarnum,
        workflow_priority,
        minpytyp,
        taxinvrecvd,
        pmdtkidx,
        dex_row_id,
        vaddcdpr,
        crtexpdt,
        cbvat,
        pmprchix,
        ten99boxnumber,
        vndclsid,
        state,
        curncyid,
        laborpmttype,
        taxschid,
        freeonboard,
        modifdt,
        pmtdscix,
        address1,
        revalue_vendor,
        vndchknm,
        userdef2,
        withholdingtype,
        vndcntct,
        txrgnnum,
        ratetpid,
        address3,
        sbppsded,
        maxindlr,
        vendshnm,
        vadcd1099,
        kperhist,
        pymntpri,
        pmdavidx,
        noteindx,
        pmwrtidx,
        withholdingentitytype,
        mxiafvnd,
        ten99type,
        phone3,
        pymtrmid,
        userdef1,
        acpuridx,
        rtobutkn,
        hold,
        vadcdsfr,
        crlmtdlr,
        pmapindx,
        parvenid,
        vadcdtro,
        pmfrtidx,
        minorder,
        ppstaxrt,
        duegrper,
        vendname,
        disgrper,
        purpvidx,
        city,
        prspayee,
        workflow_approval_status,
        comment2,
        creatddt,
        acnmvndr,
        kgldsths,
        chekbkid,
        minpypct,
        crtcomdt,
        phnumbr1,
        upszone,
        pmtaxidx,
        venddba,
        credtlmt,
        post_results_to,
        dex_row_ts,
        mxwofamt,
        taxfilenummode,
        withholdingformtype,
        kptrxhst,
        workflow_status,
        pmfinidx,
        pmmschix,
        txidnmbr,
        declid,
        shipmthd,
        ccode,
        pmrtngix,
        userlang,
        brthdate,
        zipcode,
        country,
        govcrpid,
        trddisct,
        vendstts,
        docfmtid,
        onepaypervendinv,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
