with

source as (

    select * from {{ source('crm_dev3', 'systemuser') }}

),

renamed as (

    select
        ownerid,
        msdyn_usertype,
        address_1_fax,
        organizationid,
        nickname,
        address_1_postofficebox,
        applicationid,
        address_1_upszone,
        photourl,
        address_1_latitude,
        address_1_shippingmethodcode,
        title,
        address_1_utcoffset,
        _createdonbehalfby_value,
        homephone,
        skills,
        emailrouteraccessapproval,
        address_2_latitude,
        governmentid,
        traversedpath,
        address_2_longitude,
        _createdby_value,
        defaultfilterspopulated,
        address_1_telephone_3,
        mobilephone,
        displayinserviceviews,
        address_2_fax,
        preferredaddresscode,
        address_2_city,
        defaultodbfoldername,
        cai_salespersonid,
        address_2_stateorprovince,
        address_2_line_2,
        userpuid,
        passporthi,
        cai_department,
        _modifiedonbehalfby_value,
        azuredeletedon,
        address_1_composite,
        address_1_city,
        address_2_county,
        versionnumber,
        entityimage_timestamp,
        internalemailaddress,
        salutation,
        isemailaddressapprovedbyo_365_admin,
        address_1_county,
        _businessunitid_value,
        invitestatuscode,
        msdyn_isexpertenabledforswarm,
        entityimageid,
        _parentsystemuserid_value,
        stageid,
        address_1_addresstypecode,
        outgoingemaildeliverymethod,
        address_2_postalcode,
        passportlo,
        importsequencenumber,
        timezoneruleversionnumber,
        modifiedon,
        sharepointemailaddress,
        msdyn_botdescription,
        yammeruserid,
        address_1_longitude,
        address_1_name,
        _queueid_value,
        setupuser,
        overriddencreatedon,
        isintegrationuser,
        personalemailaddress,
        utcconversiontimezonecode,
        preferredemailcode,
        address_2_composite,
        address_1_telephone_1,
        msdyn_gdproptout,
        _mobileofflineprofileid_value,
        address_2_country,
        windowsliveid,
        address_1_line_1,
        yomimiddlename,
        entityimage,
        islicensed,
        _transactioncurrencyid_value,
        _calendarid_value,
        address_1_line_3,
        fullname,
        entityimage_url,
        systemuserid,
        _modifiedby_value,
        address_1_line_2,
        azurestate,
        address_2_upszone,
        address_1_stateorprovince,
        address_2_line_3,
        address_2_name,
        msdyn_botsecretkeys,
        userlicensetype,
        _positionid_value,
        accessmode,
        msdyn_gridwrappercontrolfield,
        _siteid_value,
        address_2_line_1,
        _defaultmailbox_value,
        middlename,
        isdisabled,
        issyncwithdirectory,
        employeeid,
        mobilealertemail,
        address_2_telephone_2,
        identityid,
        _msdyn_defaultpresenceiduser_value,
        _territoryid_value,
        msdyn_botendpoint,
        createdon,
        azureactivedirectoryobjectid,
        yomifirstname,
        address_2_shippingmethodcode,
        address_2_telephone_3,
        yomilastname,
        deletedstate,
        yomifullname,
        address_2_addresstypecode,
        address_1_addressid,
        incomingemaildeliverymethod,
        yammeremailaddress,
        address_1_postalcode,
        exchangerate,
        jobtitle,
        address_2_postofficebox,
        caltype,
        address_2_addressid,
        processid,
        applicationiduri,
        address_2_telephone_1,
        preferredphonecode,
        address_2_utcoffset,
        address_1_telephone_2,
        msdyn_capacity,
        disabledreason,
        address_1_country,
        domainname,
        _fivetran_deleted,
        _fivetran_synced,
        msdyn_bothandle,
        msdyn_botapplicationid,
        msdyn_agent_type,
        msdyn_owningenvironmentid,
        msdyn_botprovider,
        trim(firstname) as firstname,
        trim(lastname) as lastname

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
