with

source as (

    select * from {{ source('crm_dev3', 'account') }}

),

renamed as (

    select
        accountid::string as csaccountid,
        lastusedincampaign,
        address_1_name,
        timezoneruleversionnumber,
        _owningbusinessunit_value,
        overriddencreatedon,
        entityimageid,
        ownershipcode,
        customersizecode,
        donotpostalmail,
        cai_url,
        address_2_city,
        creditlimit,
        entityimage_url,
        _primarycontactid_value,
        versionnumber,
        _territoryid_value,
        entityimage_timestamp,
        telephone_3,
        address_2_stateorprovince,
        openrevenue_date,
        cai_edicustomer,
        address_1_freighttermscode,
        _cai_marinerinsidesale_value,
        lastonholdtime,
        address_2_line_1,
        onholdtime,
        adx_createdbyusername,
        _createdbyexternalparty_value,
        telephone_2,
        preferredappointmenttimecode,
        marketcap_base,
        primarysatoriid,
        shippingmethodcode,
        address_1_addressid,
        address_2_telephone_1,
        address_1_fax,
        address_1_composite,
        _createdonbehalfby_value,
        stageid,
        _msa_managingpartnerid_value,
        address_2_latitude,
        entityimage,
        address_1_postofficebox,
        donotsendmm,
        address_1_telephone_2,
        aging_90_base,
        address_2_postalcode,
        address_2_name,
        _modifiedonbehalfby_value,
        preferredappointmentdaycode,
        _owningteam_value,
        _masterid_value,
        aging_30,
        paymenttermscode::string as cspaymenttermscode,
        address_2_county,
        donotbulkemail,
        _originatingleadid_value,
        emailaddress_3,
        _modifiedbyexternalparty_value,
        processid,
        websiteurl,
        revenue,
        merged,
        address_1_shippingmethodcode,
        description,
        fax,
        cai_w_9,
        address_1_stateorprovince,
        followemail,
        utcconversiontimezonecode,
        cai_rebatecustomer,
        cai_seafaxnumber,
        sic,
        address_1_line_2,
        _owninguser_value,
        _cai_insidesales_value,
        _msdyn_segmentid_value,
        territorycode,
        creditlimit_base,
        teamsfollowed,
        _preferredsystemuserid_value,
        _defaultpricelevelid_value,
        address_1_primarycontactname,
        openrevenue,
        statecode::string as csstatecode,
        donotfax,
        address_1_county,
        address_2_telephone_3,
        address_2_postofficebox,
        marketingonly,
        _preferredserviceid_value,
        cai_accounttype,
        accountratingcode,
        address_1_upszone,
        address_2_composite,
        marketcap,
        donotemail,
        aging_60,
        cai_sellto::string as cscai_sellto,
        openrevenue_state,
        customertypecode::string as cscustomertypecode,
        telephone_1,
        _createdby_value,
        cai_crmaccountid,
        _modifiedby_value,
        yominame,
        address_2_primarycontactname,
        opendeals_state,
        address_2_country,
        businesstypecode,
        address_2_longitude,
        adx_modifiedbyipaddress,
        timespentbymeonemailandmeetings,
        address_1_postalcode,
        traversedpath,
        _transactioncurrencyid_value::string as cs_transactioncurrencyid_value,
        numberofemployees,
        tickersymbol,
        cai_customerspecificlabeling,
        address_1_city,
        aging_90,
        address_1_longitude,
        participatesinworkflow,
        openrevenue_base,
        revenue_base,
        donotbulkpostalmail,
        cai_customerlabelrequirments,
        creditonhold,
        address_1_telephone_1,
        createdon,
        name,
        cai_accountspayable,
        exchangerate,
        cai_customerportal,
        address_2_addresstypecode,
        address_2_shippingmethodcode,
        _cai_wancheseinsidesale_value,
        address_2_line_2,
        cai_marketsegment,
        address_2_addressid,
        _msdyn_salesaccelerationinsightid_value,
        primarytwitterid,
        accountnumber,
        adx_modifiedbyusername,
        address_1_line_1,
        sharesoutstanding,
        _slaid_value,
        ftpsiteurl,
        importsequencenumber,
        address_2_freighttermscode,
        donotphone,
        accountclassificationcode,
        _preferredequipmentid_value,
        cai_freightterms,
        address_2_telephone_2,
        address_1_addresstypecode,
        address_1_utcoffset,
        _parentaccountid_value,
        _cai_omegainsidesales_value,
        address_2_fax,
        aging_60_base,
        msdyn_gdproptout,
        stockexchange,
        address_1_line_3,
        _cai_covertsinsidesales_value,
        preferredcontactmethodcode,
        aging_30_base,
        statuscode,
        address_2_upszone,
        _slainvokedid_value,
        address_1_latitude,
        address_1_country,
        modifiedon,
        address_2_line_3,
        address_2_utcoffset,
        cai_customeraccounttype,
        emailaddress_1,
        opendeals,
        opendeals_date,
        _ownerid_value::string as cs_ownerid_value,
        emailaddress_2,
        adx_createdbyipaddress,
        industrycode,
        address_1_telephone_3,
        accountcategorycode,
        _fivetran_deleted,
        _fivetran_synced,
        _msdyn_accountkpiid_value,
        cai_d_365_customeraccountnumber,
        cai_academytype

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
