with alldata as (
    select
        status,
        source,
        company,
        accountnum,
        name as custname,
        invoiceaccount,
        custgroup,
        invoicinganddeliveryonhold,
        accountstatus,
        currency,
        employeeresponsibleid,
        employeeresponsible,
        paytermid,
        street,
        city,
        state,
        county,
        zipcode,
        country,
        ownertype,
        companyuid,
        accountuid,
        accountstatusuid,
        currencyuid,
        errorlog,
        credmanstatusreasonid
    from {{ ref('int_d365_crm__d365customer') }}
    union all
    select
        status,
        source,
        company,
        accountnum,
        name as custname,
        invoiceaccount,
        custgroup,
        invoicinganddeliveryonhold,
        accountstatus,
        currency,
        employeeresponsibleid,
        employeeresponsible,
        paytermid,
        street,
        city,
        state,
        county,
        zipcode,
        country,
        ownertype,
        companyuid,
        accountuid,
        accountstatusuid,
        currencyuid,
        errorlog,
        credmanstatusreasonid
    from {{ ref('int_d365_crm__crmcustomer') }}
    union all
    select
        status,
        source,
        company,
        accountnum,
        name as custname,
        invoiceaccount,
        custgroup,
        invoicinganddeliveryonhold,
        accountstatus,
        currency,
        employeeresponsibleid,
        employeeresponsible,
        paytermid,
        street,
        city,
        state,
        county,
        zipcode,
        country,
        ownertype,
        companyuid,
        accountuid,
        accountstatusuid,
        currencyuid,
        errorlog,
        credmanstatusreasonid
    from {{ ref('int_d365_crm__d365_importcustomers') }}
    union all
    select
        status,
        source,
        company,
        accountnum,
        cusname as custname,
        invoiceaccount,
        custgroup,
        invoicinganddeliveryonhold,
        accountstatus,
        currency,
        employeeresponsibleid,
        employeeresponsible,
        paytermid,
        street,
        city,
        state,
        county,
        zipcode,
        country,
        ownertype,
        companyuid,
        accountuid,
        accountstatusuid,
        currencyuid,
        errorlog,
        credmanstatusreasonid
    from {{ ref('int_d365_crm__crm_importcustomers') }}
)

select * from alldata
