with source as (
    select *
    from {{ source('finops_synapse', 'dimensionattribute') }}
),

renamed as (
    select
        id,
        sink_created_on,
        sink_modified_on,
        type,
        usetranslationnamemethod,
        copyvaluesoncreate,
        givederiveddimensionsprecedence,
        isbalancing_psn,
        sysdatastatecode,
        backingentitykeyfieldid,
        backingentitykeyfieldname,
        backingentitytableid,
        backingentitytablename,
        backingentitytype,
        backingentityvaluefieldid,
        backingentityvaluefieldname,
        hashkey,
        keyattribute,
        name,
        nameattribute,
        reportcolumnname,
        translationkeyfieldid,
        translationkeyfieldname,
        translationlanguageidfieldid,
        translationlanguageidfieldname,
        translationnamefieldid,
        translationnamefieldname,
        translationtableid,
        translationtablename,
        valueattribute,
        viewname,
        translationviewkeyfieldname,
        translationviewlanguageidfieldname,
        translationviewname,
        translationviewnamefieldname,
        translationviewsystemlanguageidfieldname,
        translationviewtranslatednamefieldname,
        translationviewvaluefieldname,
        translationviewid,
        translationviewkeyfieldid,
        translationviewlanguageidfieldid,
        translationviewnamefieldid,
        translationviewsystemlanguageidfieldid,
        translationviewtranslatednamefieldid,
        translationviewvaluefieldid,
        dimensionkeycolumnname,
        dimensionvaluecolumnname,
        balancingdimension_psn,
        modifieddatetime,
        modifiedby,
        modifiedtransactionid,
        createddatetime,
        createdby,
        createdtransactionid,
        dataareaid,
        recversion,
        partition,
        sysrowversion,
        recid,
        tableid,
        versionnumber,
        createdon,
        modifiedon,
        _fivetran_deleted,
        _fivetran_synced
    from source
)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
