{{ config(materialized='view') }}

with source as (
    select *
    from {{ source('finops_synapse', 'inventtrans') }}
),

renamed as (
    select
        id,
        sink_created_on,
        sink_modified_on,
        groupreftype_ru,
        intercompanyinventdimtransferred,
        invoicereturned,
        packingslipreturned,
        statusissue,
        statusreceipt,
        storno_ru,
        stornophysical_ru,
        transchildtype,
        valueopen,
        valueopenseccur_ru,
        itmskipvarianceupdate,
        itmmustskipadjustment,
        sysdatastatecode,
        activitynumber,
        costamountadjustment,
        costamountoperations,
        costamountphysical,
        costamountposted,
        costamountseccuradjustment_ru,
        costamountseccurphysical_ru,
        costamountseccurposted_ru,
        costamountsettled,
        costamountsettledseccur_ru,
        costamountstd,
        costamountstdseccur_ru,
        currencycode,
        dateclosed,
        dateclosedseccur_ru,
        dateexpected,
        datefinancial,
        dateinvent,
        datephysical,
        datestatus,
        grouprefid_ru,
        inventdimfixed,
        inventdimid,
        inventdimidsales_ru,
        inventtransorigin,
        inventtransorigindelivery_ru,
        inventtransoriginsales_ru,
        inventtransorigintransit_ru,
        invoiceid,
        itemid,
        markingrefinventtransorigin,
        packingslipid,
        pdscwqty,
        pdscwsettled,
        pickingrouteid,
        projadjustrefid,
        projcategoryid,
        projid,
        qty,
        qtysettled,
        qtysettledseccur_ru,
        returninventtransorigin,
        revenueamountphysical,
        shippingdateconfirmed,
        shippingdaterequested,
        taxamountphysical,
        timeexpected,
        transchildrefid,
        voucher,
        voucherphysical,
        nonfinancialtransferinventclosing,
        loadid,
        itmcosttypeid,
        itmcosttransrecid,
        modifieddatetime,
        modifiedby,
        modifiedtransactionid,
        createddatetime,
        createdby,
        createdtransactionid,
        dataareaid,
        recversion,
        partition,
        sysrowversion,
        recid,
        tableid,
        versionnumber,
        createdon,
        modifiedon,
        _fivetran_deleted,
        _fivetran_synced
    from source
)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
