with

source as (

    select * from {{ source('finops_synapse', 'prodtable') }}

),

renamed as (

    select
        id,
        sink_created_on,
        sink_modified_on,
        backorderstatus,
        checkroute,
        inventreftype,
        latestscheddirection,
        pmfbulkord,
        pmfcobyvarallow,
        pmfreworkbatch,
        pmftotalcostallocation,
        prodlocked,
        prodpostingtype,
        prodstatus,
        prodtype,
        profitset,
        projlinkedtoorder,
        projpostingtype,
        reflookup,
        reservation,
        routejobs,
        schedstatus,
        prodwhsreleasepolicy,
        skipcreatebomlines,
        skipcreaterouteoperations,
        sysdatastatecode,
        activitynumber,
        bomdate,
        bomid,
        calcdate,
        collectreflevel,
        collectrefprodid,
        currencycode_ru,
        defaultdimension,
        density,
        depth,
        dlvdate,
        dlvtime,
        finisheddate,
        ganttcolorid,
        height,
        inventdimid,
        inventrefid,
        inventreftransid,
        inventtransid,
        itemid,
        latestscheddate,
        latestschedtime,
        name,
        pdscwbatchest,
        pdscwbatchsched,
        pdscwbatchsize,
        pdscwbatchstup,
        pdscwremaininventphysical,
        pmfconsordid,
        pmfyieldpct,
        pricegroup_ru,
        prodgroupid,
        prodid,
        prodorigid,
        prodpoolid,
        prodprio,
        projcategoryid,
        projcostamount,
        projcostprice,
        projid,
        projlinepropertyid,
        projsalescurrencyid,
        projsalesprice,
        projsalesunitid,
        projtaxgroupid,
        projtaxitemgroupid,
        projtransid,
        propertyid,
        qtycalc,
        qtysched,
        qtystup,
        realdate,
        releaseddate,
        remaininventphysical,
        reqplanidsched,
        reqpoid,
        routeid,
        scheddate,
        schedend,
        schedfromtime,
        schedstart,
        schedtotime,
        stupdate,
        width,
        planningpriority,
        modifieddatetime,
        modifiedby,
        modifiedtransactionid,
        createddatetime,
        createdby,
        createdtransactionid,
        dataareaid,
        recversion,
        partition,
        sysrowversion,
        recid,
        tableid,
        versionnumber,
        createdon,
        modifiedon,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
