{{ config(materialized='view') }}

with source as (
    select *
    from {{ source('finops_synapse', 'ledgerjournaltable') }}
),

renamed as (
    select
        id,
        sink_created_on,
        sink_modified_on,
        assettransfertype_lt,
        bankremittancetype,
        currentoperationstax,
        custvendneginstprotestprocess,
        detailsummaryposting,
        eurotriangulation,
        fixedexchrate,
        fixedoffsetaccount,
        journaltype,
        ledgerjournalincltax,
        offsetaccounttype,
        paymentsgenerated_it,
        posted,
        protestsettledbill,
        removelineafterposting,
        reverseentry,
        systemblocked,
        taxobligationcompany,
        voucherallocatedatposting,
        workflowapprovalstatus,
        isledgerdimensionnameupdated,
        reportingcurrencyfixedexchrate,
        delaytaxcalculation,
        overridesalestax,
        isadjustmentjournal,
        systemblockedreason,
        simulationposted_it,
        banktranssummarizationenabled,
        banktranssummarizationcriteria,
        sysdatastatecode,
        userblockid,
        approver,
        bankaccountid,
        currencycode,
        defaultdimension,
        documentnum,
        endbalance,
        exchrate,
        exchratesecondary,
        groupblockid,
        inuseby,
        journalbalance,
        journalname,
        journalnum,
        journaltotalcredit,
        journaltotaldebit,
        journaltotaloffsetbalance,
        lineslimitbeforedistribution,
        log,
        name,
        numbersequencetable,
        numoflines,
        offsetledgerdimension,
        originalcompany,
        originaljournalnum,
        parentjournalnum,
        posteddatetime,
        rejectedby,
        reportedasreadyby,
        retailstatementid,
        reversedate,
        sessionid,
        sessionlogindatetime,
        reportingcurrencyexchrate,
        reportingcurrencyexchratesecondary,
        journaltotalcreditreportingcurrency,
        journaltotaldebitreportingcurrency,
        integrationkey,
        fintag,
        assetleaseprocessid,
        revrecreallocationid,
        modifieddatetime,
        modifiedby,
        modifiedtransactionid,
        createddatetime,
        createdby,
        createdtransactionid,
        dataareaid,
        recversion,
        partition,
        sysrowversion,
        recid,
        tableid,
        versionnumber,
        createdon,
        modifiedon,
        _fivetran_deleted,
        _fivetran_synced
    from source
)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
