{{ config(materialized='view') }}

with source as (
    select *
    from {{ source('finops_synapse', 'inventlocation') }}
),

renamed as (
    select
        id,
        sink_created_on,
        sink_modified_on,
        allowlaborstandards,
        allowmarkingreservationremoval,
        consolidateshipatrtw,
        cyclecountallowpalletmove,
        decrementloadline,
        fshstore,
        inventcountinggroup_br,
        inventlocationtype,
        inventprofiletype_ru,
        manual,
        printbolbeforeshipconfirm,
        prodreserveonlywhse,
        removeinventblockingonstatuschange,
        reqrefill,
        reserveatloadpost,
        retailinventnegfinancial,
        retailinventnegphysical,
        uniquecheckdigits,
        usewmsorders,
        whsenabled,
        whsrawmaterialpolicy,
        wmsaislenameactive,
        wmslevelnameactive,
        wmspositionnameactive,
        wmsracknameactive,
        warehouseautoreleasereservation,
        releasetowarehouserule,
        autoupdateshipment,
        enablequalitymanagement,
        loadreleasereservationpolicy,
        whsprodorderbackflushmustusereservedqty,
        inventusedefaultproductionlocationforformulabom,
        rafpostingmethod,
        sysdatastatecode,
        activitytype_ru,
        branchnumber,
        custaccount_br,
        custaccount_hu,
        defaultkanbanfinishedgoodslocation,
        defaultproductionfinishgoodslocation,
        defaultshipmaintenanceloc,
        defaultstatusid,
        emptypalletlocation,
        inventlocationid,
        inventlocationidgoodsinroute_ru,
        inventlocationidquarantine,
        inventlocationidreqmain,
        inventlocationidtransit,
        inventlocationlevel,
        inventprofileid_ru,
        inventsiteid,
        maxpickingroutetime,
        maxpickingroutevolume,
        name,
        numbersequencegroup_ru,
        pickinglinetime,
        rbodefaultinventprofileid_ru,
        rbodefaultwmslocationid,
        rbodefaultwmspalletid,
        reqcalendarid,
        retailweightex_1,
        retailwmslocationiddefaultreturn,
        retailwmspalletiddefaultreturn,
        vendaccount,
        vendaccountcustom_ru,
        wmslevelformat,
        wmslocationiddefaultissue,
        wmslocationiddefaultreceipt,
        wmslocationidgoodsinroute_ru,
        wmspositionformat,
        wmsrackformat,
        defaultproductioninputlocation,
        defaultreturncreditonlylocation,
        defaultcontainertypecode,
        workprocessingpolicyname,
        defaultqualitymaintenancelocation,
        hmimexportlanguage,
        hmimdomesticlanguage,
        defaultfinalshipmentlocation,
        defaultsortinglocation,
        rejectorderfulfillment,
        itminventlocationidunder,
        itminventlocationidgit,
        modifieddatetime,
        modifiedby,
        modifiedtransactionid,
        createddatetime,
        createdby,
        createdtransactionid,
        dataareaid,
        recversion,
        partition,
        sysrowversion,
        recid,
        tableid,
        versionnumber,
        createdon,
        modifiedon,
        _fivetran_deleted,
        _fivetran_synced
    from source
)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
