{{ config(materialized='view') }}

with source as (
    select *
    from {{ source('finops_synapse', 'pdsrebatetable') }}
),

renamed as (
    select
        id,
        sink_created_on,
        sink_modified_on,
        pdsmarkforcredit,
        pdspaymttype,
        pdsrebateamttype,
        pdsrebatestatus,
        sysdatastatecode,
        currencycode,
        custaccount,
        custinvoicetransrefrecid,
        defaultdimension,
        inventtransid,
        itemid,
        ledgerdimension,
        offsetdefaultdimension,
        offsetledgerdimension,
        pdscorrectedrebateamt,
        pdscustinvoicejourrefrecid,
        pdscustomerref,
        pdscustrebategroupid,
        pdscwsalesinvoicedqty,
        pdsitemrebategroupid,
        pdsprocessdate,
        pdsrebateadjustmentdate,
        pdsrebateagreementrefrecid,
        pdsrebateamt,
        pdsrebatebalance,
        pdsrebateid,
        pdsrebatejournalrefnum,
        pdsrebatepayto,
        pdsrebatetype,
        pdsrebatevalue,
        pdsstartingrebateamt,
        rebateagreementlinerefrecid,
        rebatecalcdate,
        salesamount,
        salesid,
        salesinvoicedate,
        salesinvoicedqty,
        salesinvoiceid,
        saleslinerefrecid,
        salesnetextendedprice,
        salespriceunit,
        salestablerefrecid,
        tammerchandisingeventid,
        taxgroup,
        taxitemgroup,
        modifieddatetime,
        modifiedby,
        modifiedtransactionid,
        createddatetime,
        createdby,
        createdtransactionid,
        dataareaid,
        recversion,
        partition,
        sysrowversion,
        recid,
        tableid,
        versionnumber,
        createdon,
        modifiedon,
        _fivetran_deleted,
        _fivetran_synced
    from source
)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
