with

source as (

    select * from {{ source('finops_synapse', 'custtrans') }}

),

renamed as (

    select
        id,
        sink_created_on,
        sink_modified_on,
        approved,
        billofexchangestatus,
        cancelledpayment,
        cashpayment,
        collectionletter,
        collectionlettercode,
        correct,
        eurotriangulation,
        fixedexchrate,
        interest,
        invoiceproject,
        paymmethod,
        prepayment,
        retailcusttrans,
        settlement,
        transtype,
        custautomationexclude,
        custautomationpredunningsent,
        custautomationpredictionsent,
        invoicetype_it,
        credmanexcludefromcreditcontrol,
        sysdatastatecode,
        postingprofileclose,
        accountingevent,
        accountnum,
        amountcur,
        amountmst,
        approver,
        bankcentralbankpurposecode,
        bankcentralbankpurposetext,
        banklcexportline,
        bankremittancefileid,
        billofexchangeid,
        billofexchangeseqnum,
        cashdisccode,
        cashdiscbasedate,
        closed,
        companybankaccountid,
        controlnum,
        currencycode,
        custbillingclassification,
        custexchadjustmentrealized,
        custexchadjustmentunrealized,
        defaultdimension,
        deliverymode,
        directdebitmandate,
        documentdate,
        documentnum,
        duedate,
        exchadjustment,
        exchadjustmentreporting,
        exchrate,
        exchratesecond,
        invoice,
        lastexchadj,
        lastexchadjrate,
        lastexchadjratereporting,
        lastexchadjvoucher,
        lastsettleaccountnum,
        lastsettlecompany,
        lastsettledate,
        lastsettlevoucher,
        mcrpaymorderid,
        offsetrecid,
        orderaccount,
        paymid,
        paymmode,
        paymreference,
        paymspec,
        postingprofile,
        reasonrefrecid,
        reportingcurrencyamount,
        reportingcurrencyexchrate,
        reportingcurrencyexchratesecondary,
        reportingcurrencycrossrate,
        reportingexchadjustmentrealized,
        reportingexchadjustmentunrealized,
        retailstoreid,
        retailterminalid,
        retailtransactionid,
        settleamountcur,
        settleamountmst,
        settleamountreporting,
        taxinvoicesalesid,
        thirdpartybankaccountid,
        transdate,
        txt,
        voucher,
        paymschedid,
        paymtermid,
        settleamount_mx,
        modifieddatetime,
        modifiedby,
        modifiedtransactionid,
        createddatetime,
        createdby,
        createdtransactionid,
        dataareaid,
        recversion,
        partition,
        sysrowversion,
        recid,
        tableid,
        versionnumber,
        createdon,
        modifiedon,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
