with source as (
    select *
    from {{ source('finops_synapse', 'custpackingsliptrans') }}
),

renamed as (
    select
        id,
        sink_created_on,
        sink_modified_on,
        deliverytype,
        fullymatched,
        inventreftype,
        scrap,
        stockedproduct,
        sysdatastatecode,
        amountcur,
        countryregionofshipment,
        currencycode,
        defaultdimension,
        deliverydate,
        deliverypostaladdress,
        dlvterm,
        externalitemid,
        intercompanyinventtransid,
        intrastatdispatchid,
        intrastatfulfillmentdate_hu,
        inventdimid,
        inventqty,
        inventrefid,
        inventreftransid,
        inventtransid,
        invoicetransrefrecid,
        intrastatcommodity,
        itemid,
        lineheader,
        linenum,
        name,
        ngpcodestable_fr,
        numbersequencegroup,
        ordered,
        origcountryregionid,
        origsalesid,
        origstateid,
        packingslipid,
        pdscwqty,
        pdscwremain,
        port,
        priceunit,
        qty,
        remain,
        remaininvent,
        salescategory,
        salesgroup,
        salesid,
        saleslineshippingdateconfirmed,
        saleslineshippingdaterequested,
        salesunit,
        sourcedocumentline,
        statisticvalue_lt,
        statprocid,
        statvaluemst,
        transactioncode,
        transport,
        valuemst,
        weight,
        itemcodeid,
        parmline,
        deferredpostinvoicetransrecid,
        stateofshipment,
        fintag,
        modifieddatetime,
        modifiedby,
        modifiedtransactionid,
        createddatetime,
        createdby,
        createdtransactionid,
        dataareaid,
        recversion,
        partition,
        sysrowversion,
        recid,
        tableid,
        versionnumber,
        createdon,
        modifiedon,
        _fivetran_deleted,
        _fivetran_synced
    from source
)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
