with
source as (select * from {{ source("finops_synapse", "mainaccount") }}),

renamed as (
    select
        id,
        sink_created_on,
        sink_modified_on,
        adjustmentmethod_mx,
        closetype,
        closing,
        debitcreditbalancedemand,
        debitcreditcheck,
        debitcreditproposal,
        exchangeadjusted,
        financialreportingtranslationtype,
        inflationadjustment_mx,
        mandatorypaymentreference,
        monetary,
        postingtype,
        repomotype_mx,
        reportingaccounttype,
        type,
        validatecurrency,
        validateposting,
        validateuser,
        sysdatastatecode,
        accountcategoryref,
        consolidationmainaccount,
        currencycode,
        exchangeadjustmentratetype,
        financialreportingexchangeratetype,
        ledgerchartofaccounts,
        mainaccountid,
        mainaccounttemplate,
        name,
        offsetledgerdimension,
        openingaccount,
        parentmainaccount,
        srucode,
        transferyearendaccount_es,
        unitofmeasure,
        userinfoid,
        parentmainaccount_br,
        reportingexchangeadjustmentratetype,
        standardmainaccount_w,
        modifieddatetime,
        modifiedby,
        modifiedtransactionid,
        createddatetime,
        createdby,
        createdtransactionid,
        dataareaid,
        recversion,
        partition,
        sysrowversion,
        recid,
        tableid,
        versionnumber,
        createdon,
        modifiedon,
        _fivetran_deleted,
        _fivetran_synced
    from source
)

select *
from renamed
where coalesce(_fivetran_deleted, false) = false
