{{ config(materialized='view') }}

with source as (
    select *
    from {{ source('finops_synapse', 'inventsum') }}
),

renamed as (
    select
        id,
        sink_created_on as last_processed_change_date_time,
        sink_modified_on as data_lake_modified_date_time,
        closed,
        closedqty,
        isexcludedfrominventoryvalue,
        sysdatastatecode,
        arrived,
        availordered,
        availphysical,
        deducted,
        inventdimid,
        itemid,
        lastupddateexpected,
        lastupddatephysical,
        onorder,
        ordered,
        pdscwarrived,
        pdscwavailordered,
        pdscwavailphysical,
        pdscwdeducted,
        pdscwonorder,
        pdscwordered,
        pdscwphysicalinvent,
        pdscwpicked,
        pdscwpostedqty,
        pdscwquotationissue,
        pdscwquotationreceipt,
        pdscwreceived,
        pdscwregistered,
        pdscwreservordered,
        pdscwreservphysical,
        physicalinvent,
        physicalvalue,
        physicalvalueseccur_ru,
        picked,
        postedqty,
        postedvalue,
        postedvalueseccur_ru,
        quotationissue,
        quotationreceipt,
        received,
        registered,
        reservordered,
        reservphysical,
        configid,
        inventcolorid,
        inventgtdid_ru,
        inventlocationid,
        inventownerid_ru,
        inventprofileid_ru,
        inventserialid,
        inventsiteid,
        inventsizeid,
        inventstatusid,
        inventstyleid,
        inventversionid,
        licenseplateid,
        wmslocationid,
        wmspalletid,
        inventdimension_1,
        inventdimension_2,
        inventdimension_3,
        inventdimension_4,
        inventdimension_5,
        inventdimension_6,
        inventdimension_7,
        inventdimension_8,
        inventdimension_9,
        inventdimension_10,
        inventdimension_11,
        inventdimension_12,
        modifieddatetime,
        modifiedby,
        modifiedtransactionid,
        createddatetime,
        createdby,
        createdtransactionid,
        dataareaid,
        recversion,
        partition,
        sysrowversion,
        recid,
        tableid,
        versionnumber,
        createdon,
        modifiedon,
        _fivetran_deleted,
        _fivetran_synced,
        upper(inventbatchid) as inventbatchid
    from source
)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
