with source as (

    select * from {{ source('sti_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        vadcdpad,
        dxvarnum,
        duegrper,
        pmtdscix,
        onepaypervendinv,
        minpypct,
        disgrper,
        cbvat,
        vendshnm,
        workflow_approval_status,
        withholdingentitytype,
        vendstts,
        kptrxhst,
        taxinvrecvd,
        address2,
        faxnumbr,
        govindid,
        vndclsid,
        mxiafvnd,
        ratetpid,
        minorder,
        venddba,
        txrgnnum,
        laborpmttype,
        phnumbr2,
        chekbkid,
        writeoff,
        txidnmbr,
        pmapindx,
        maxindlr,
        declid,
        upszone,
        city,
        govcrpid,
        sbppsded,
        zipcode,
        trddisct,
        docfmtid,
        withholdingformtype,
        modifdt,
        crtexpdt,
        phone3,
        revalue_vendor,
        taxfilenummode,
        vadcdtro,
        ptcshacf,
        noteindx,
        shipmthd,
        parvenid,
        workflow_status,
        pmrtngix,
        userlang,
        xpdtoblg,
        phnumbr1,
        creatddt,
        vadcdsfr,
        ccode,
        purpvidx,
        pymtrmid,
        country,
        ten99boxnumber,
        minpytyp,
        kgldsths,
        credtlmt,
        workflow_priority,
        pmtaxidx,
        crtcomdt,
        pmdtkidx,
        address1,
        freeonboard,
        post_results_to,
        pmmschix,
        vendname,
        minpydlr,
        userdef1,
        acpuridx,
        kperhist,
        state,
        pmfinidx,
        curncyid,
        pymntpri,
        taxschid,
        hold,
        pmcshidx,
        pmwrtidx,
        vndcntct,
        ppstaxrt,
        userdef2,
        vaddcdpr,
        dex_row_ts,
        ten99type,
        crlmtdlr,
        vadcd1099,
        acnmvndr,
        comment2,
        dex_row_id,
        mxwofamt,
        vndchknm,
        kpcalhst,
        rtobutkn,
        address3,
        pmdavidx,
        pmfrtidx,
        comment1,
        brthdate,
        prspayee,
        withholdingtype,
        pmprchix,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
