with source as (

    select * from {{ source('sti_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        ten99boxnumber,
        retnagam,
        ictrx,
        dscdlram,
        bachnumb,
        disamtav,
        dinvpdof,
        taxinvreqd,
        cardname,
        curncyid,
        cntrltyp,
        lngdesc,
        docamnt,
        shipmthd,
        tax_date,
        frtschid,
        hold,
        bktpuram,
        ppstaxrt,
        mscschid,
        docprinted,
        electronic,
        aplywith,
        backouttradedisc,
        workflow_status,
        dex_row_id,
        pgramsbj,
        pymtrmid,
        wrofamnt,
        un1099am,
        gstdsamt,
        bktmscam,
        posteddt,
        taxamnt,
        modifdt,
        duedate,
        vadcdtro,
        ppsamded,
        pchschid,
        trdisamt,
        voidpdate,
        bktfrtam,
        vndchknm,
        voided,
        simplifd,
        prchamnt,
        curtrxam,
        vendorid,
        cbvat,
        chekbkid,
        pordnmbr,
        discdate,
        mscchamt,
        pstgdate,
        mdfusrid,
        ttlpymts,
        trxsorce,
        dex_row_ts,
        taxschid,
        disavtkn,
        discamnt,
        ten99amnt,
        ptdusrid,
        ten99type,
        distknam,
        ectrx,
        docdate,
        noteindx,
        invoicereceiptdate,
        bchsourc,
        trxdscrn,
        corrctn,
        frtamnt,
        pyenttyp,
        prctdisc,
        prchdate,
        ponumber,
        docnumbr,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
