with source as (

    select * from {{ source('sti_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        country,
        fax,
        taxexmt1,
        balnctyp,
        prbtadcd,
        kpcalhst,
        address1,
        prstadcd,
        cntcprsn,
        defcacty,
        creatddt,
        rmaracc,
        govcrpid,
        integrationsource,
        declid,
        stmtname,
        city,
        shipmthd,
        stmtcycl,
        finchid,
        orderfulfilldefault,
        post_results_to,
        zip,
        staddrcd,
        rmslsacc,
        minpydlr,
        finchdlr,
        revalue_customer,
        includeindp,
        rmsoracc,
        phone3,
        crcrdnum,
        comment1,
        modifdt,
        rmcosacc,
        rmfcgacc,
        crcardid,
        docfmtid,
        integrationid,
        phone1,
        gpsfointegrationid,
        crlmtper,
        inactive,
        comment2,
        userlang,
        upszone,
        kptrxhst,
        shipcomplete,
        frstindt,
        custname,
        hold,
        phone2,
        noteindx,
        prclevel,
        chekbkid,
        custdisc,
        cprcstnm,
        disgrper,
        state,
        mxwoftyp,
        send_email_statements,
        kpdsthst,
        crlmttyp,
        salsterr,
        shrtname,
        taxexmt2,
        govindid,
        rmovrpymtwrtoffacctidx,
        rmivacc,
        txrgnnum,
        ccode,
        duegrper,
        rmtakacc,
        rmwracc,
        ratetpid,
        custclas,
        rmavacc,
        fnchatyp,
        fnchpcnt,
        pymtrmid,
        dex_row_id,
        adrscode,
        minpypct,
        bankname,
        slprsnid,
        address3,
        cbvat,
        mxwrofam,
        kperhist,
        dex_row_ts,
        crlmtamt,
        curncyid,
        userdef2,
        minpytyp,
        address2,
        taxschid,
        rmcshacc,
        custpriority,
        bnkbrnch,
        userdef1,
        ccrdxpdt,
        crlmtpam,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
