with source as (

    select * from {{ source('sti_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        cshrctyp,
        eftflag,
        discdate,
        aplywith,
        dex_row_id,
        directdebit,
        cspornbr,
        cheknmbr,
        postdate,
        dscdlram,
        cbkidchk,
        slstercd,
        delete1,
        slprsnid,
        frtamnt,
        cbkidcrd,
        cashamnt,
        mscschid,
        bktslsam,
        trxsorce,
        wrofamnt,
        slschdid,
        saledate,
        bktmscam,
        shipmthd,
        corrctn,
        agngbukt,
        taxschid,
        curtrxam,
        costamnt,
        bachnumb,
        dex_row_ts,
        glpostdt,
        lstedtdt,
        pymtrmid,
        electronic,
        pstusrid,
        tax_date,
        slsamnt,
        miscamnt,
        distknam,
        ppsamded,
        simplifd,
        ectrx,
        taxamnt,
        factoring,
        voiddate,
        lstusred,
        cprcstnm,
        comdlram,
        adrscode,
        bchsourc,
        gstdsamt,
        backouttradedisc,
        docdate,
        cbkidcsh,
        dscpctam,
        dinvpdof,
        trdisamt,
        duedate,
        disavtkn,
        curncyid,
        trxdscrn,
        ortrxamt,
        voidstts,
        bktfrtam,
        noteindx,
        disavamt,
        frtschid,
        discrtnd,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
