with source as (

    select * from {{ source('sti_dbo', 'pop30300') }}

),

renamed as (

    select
        actlship,
        trxsorce,
        ratecalc,
        pymtrmid,
        shipmthd,
        exchdate,
        discdate,
        rcptnote_8,
        origbackoutfreighttaxamt,
        pophdr1,
        rcptnote_2,
        miscamnt,
        rcptnote_5,
        taxamnt,
        invoiceexpected,
        ten99boxnumber,
        cbvat,
        exgtblid,
        vadcdtro,
        mscschid,
        dex_row_id,
        purchase_misc_taxable,
        curncyid,
        currnidx,
        denxrate,
        trdpctpr,
        taxinvrecvd,
        obtaxamt,
        purchase_freight_taxable,
        msctxamt,
        bsivcttl,
        glpostdt,
        ratetpid,
        workflow_status,
        orfrttax,
        bchsourc,
        duedate,
        withhamt,
        backoutfreighttaxamt,
        prepaymentamount,
        ortdisam,
        pophdr2,
        rcptnote_1,
        simplifd,
        ppstaxrt,
        pop_hdr_errors_4,
        ordavamt,
        taxschid,
        ormsctax,
        bcktxamt,
        invoicereceiptdate,
        revaljrnentry,
        replacegoods,
        frtschid,
        ordatkn,
        trdisamt,
        poptype,
        originatingprepaymentamt,
        poplnerr,
        modifdt,
        disavamt,
        xchgrate,
        receiptdate,
        vchrnmbr,
        tax_date,
        ectrx,
        disavtkn,
        rcptnote_4,
        or1099am,
        refrence,
        ptdusrid,
        frttxamt,
        rcptnote_3,
        dscpctam,
        origbackoutmisctaxamt,
        subtotal,
        posteddt,
        taxinvreqd,
        user2ent,
        vnddocnm,
        orsubtot,
        orfrtamt,
        distknam,
        creatddt,
        rcptnote_6,
        ormiscamt,
        ortaxamt,
        frtamnt,
        ten99amnt,
        aplywith,
        voidstts,
        total_landed_cost_amount,
        bachnumb,
        time1,
        rcptnote_7,
        txrgnnum,
        revaltrxsource,
        vendname,
        mctrxstt,
        dscdlram,
        backoutmisctaxamt,
        ordistkn,
        ten99type,
        orddlrat,
        _fivetran_deleted,
        _fivetran_synced,
        upper(trim(poprctnm)) as poprctnm,
        upper(trim(vendorid)) as vendorid

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
