with source as (

    select * from {{ source('sti_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        taxschid,
        posteddt,
        pymtrmid,
        docdate,
        bnkrcamt,
        mdfusrid,
        trdisamt,
        vadcdtro,
        pordnmbr,
        ttlpymts,
        distknam,
        pstgdate,
        prchamnt,
        docnumbr,
        ppstaxrt,
        shipmthd,
        simplifd,
        ppsamded,
        pchschid,
        curncyid,
        aplywith,
        bchsourc,
        un1099am,
        cbvat,
        modifdt,
        bktfrtam,
        vndchknm,
        ten99type,
        pgramsbj,
        gstdsamt,
        bachnumb,
        duedate,
        frtschid,
        wrofamnt,
        tax_date,
        dex_row_ts,
        discdate,
        chekbkid,
        taxamnt,
        prctdisc,
        dex_row_id,
        docamnt,
        invoicereceiptdate,
        noteindx,
        discamnt,
        ten99amnt,
        disavtkn,
        ectrx,
        trxsorce,
        electronic,
        hold,
        dscdlram,
        mscchamt,
        taxinvreqd,
        ponumber,
        pyenttyp,
        backouttradedisc,
        prchdate,
        bktmscam,
        lngdesc,
        workflow_status,
        disamtav,
        cntrltyp,
        frtamnt,
        curtrxam,
        dinvpdof,
        mscschid,
        corrctn,
        retnagam,
        ten99boxnumber,
        ptdusrid,
        docprinted,
        bktpuram,
        voided,
        ictrx,
        trxdscrn,
        cardname,
        vendorid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
