with

source as (

    select * from {{ source('sti_dbo', 'pm10000') }}

),

renamed as (

    select
        bachnumb,
        bchsourc,
        vchnumwk,
        chamcbid,
        taxinvreqd,
        ictrx,
        vendorid,
        electronic,
        campmtnm,
        taxschid,
        pchschid,
        cdocnmbr,
        txengcld,
        taxamnt,
        workflow_status,
        printed,
        bktmscam,
        crcarddt,
        disamtav,
        ten99boxnumber,
        corrnxst,
        ppsamded,
        simplifd,
        pmwrkms2,
        corrctn,
        ppstaxrt,
        dscdlram,
        chekamnt,
        vadcdtro,
        pmicmsgs,
        dex_row_ts,
        posted,
        bktpuram,
        chrgamnt,
        cbvat,
        noteindx,
        mdfusrid,
        prctdisc,
        pmwrkmsg,
        ten99amnt,
        un1099am,
        prchdate,
        gstdsamt,
        camcbkid,
        bktfrtam,
        ccampynm,
        ccrctnum,
        chekdate,
        crcrdamt,
        pordnmbr,
        pstgdate,
        chekbkid,
        dex_row_id,
        frtamnt,
        discdate,
        pymtrmid,
        cheknmbr,
        modifdt,
        ectrx,
        docamnt,
        lngdesc,
        mscschid,
        vchrncor,
        docnumbr,
        distknam,
        shipmthd,
        backouttradedisc,
        tax_date,
        trdisamt,
        prchamnt,
        trxdscrn,
        bnkrcamt,
        doctype,
        cntrltyp,
        ptdusrid,
        apdstkam,
        docdate,
        cardname,
        icdists,
        vaddcdpr,
        pmdstmsg,
        pgramsbj,
        appldamt,
        wrofamnt,
        pstgstus,
        duedate,
        docprinted,
        cashamnt,
        vchrnmbr,
        sourcdoc,
        ten99type,
        curncyid,
        campynbr,
        frtschid,
        mscchamt,
        invoicereceiptdate,
        curtrxam,
        retnagam,
        aplywith,
        camtdate,
        posteddt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
