with

source as (

    select {{ convert_columns('sti_dbo', 'pop30110') }}
    from {{ source('sti_dbo', 'pop30110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        commntid,
        product_indicator,
        odecplcu,
        vnditdsc,
        phone3,
        zipcode,
        currnidx,
        contact,
        state,
        polneary_5,
        polneary_8,
        purchase_site_tax_schedu,
        adrscode,
        address3,
        print_phone_numbergb,
        addrsource,
        extdcost,
        prmshpdte,
        released_date,
        itemdesc,
        landed_cost_group_id,
        polneary_6,
        obtaxamt,
        phone1,
        lstrcptdt,
        flags,
        locncode,
        ortaxamt,
        vnditnum,
        lineorigin,
        releasebydate,
        purchase_iv_item_taxable,
        address1,
        noninven,
        invindx,
        unitcost,
        decplqty,
        dex_row_ts,
        itmtrkop,
        doctype,
        orextcst,
        prmdate,
        taxamnt,
        bsivcttl,
        address2,
        vendorid,
        freeonboard,
        reqstdby,
        projnum,
        shipmthd,
        uofm,
        polneary_4,
        polneary_7,
        jobnumbr,
        phone2,
        vctnmthd,
        fax,
        polneary_1,
        country,
        qtycance,
        qtyorder,
        polneary_9,
        costtype,
        source_document_line_num,
        polneary_3,
        purchase_item_tax_schedu,
        polnesta,
        linenumber,
        city,
        reqdate,
        costcode,
        ccode,
        purchsitetxschsrc,
        release,
        polneary_2,
        origprmdate,
        cmpnynam,
        decplcur,
        bcktxamt,
        potype,
        source_document_number,
        dex_row_id,
        fstrcptdt,
        costcatid,
        oruntcst,
        umqtyinb,
        itemnmbr,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
