with

source as (

    select {{ convert_columns('sti_dbo', 'pop10110') }}
    from {{ source('sti_dbo', 'pop10110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        umqtyinb,
        doctype,
        costtype,
        freeonboard,
        bsivcttl,
        projnum,
        prmdate,
        origprmdate,
        fstrcptdt,
        source_document_number,
        lstrcptdt,
        reqstdby,
        vnditnum,
        po_line_status_orig,
        qtyuncmtbase,
        polneary_9,
        noninven,
        city,
        released_date,
        polneary_3,
        plnndspplid,
        vnditdsc,
        releasebydate,
        source_document_line_num,
        linenumber,
        uofm,
        polneary_2,
        capital_item,
        release,
        curncyid,
        costcode,
        polnesta,
        state,
        xchgrate,
        flags,
        vendorid,
        currnidx,
        print_phone_numbergb,
        dex_row_ts,
        oruntcst,
        cmpnynam,
        itemdesc,
        itmtrkop,
        purchase_site_tax_schedu,
        itemnmbr,
        ratecalc,
        address1,
        odecplcu,
        qty_canceled_orig,
        address3,
        dex_row_id,
        purchase_item_tax_schedu,
        opostsub,
        addrsource,
        qtyorder,
        invindx,
        address2,
        taxamnt,
        jobnumbr,
        qtycommittedinbaseorig,
        polneary_4,
        polneary_7,
        polneary_1,
        shipmthd,
        change_order_flag,
        vctnmthd,
        purchase_iv_item_taxable,
        obtaxamt,
        landed_cost_group_id,
        decplcur,
        backouttradedisctax,
        adrscode,
        origbackouttradedisctax,
        ortaxamt,
        ccode,
        fax,
        phone3,
        commntid,
        contact,
        potype,
        locncode,
        polneary_5,
        polneary_8,
        reqdate,
        costcatid,
        extdcost,
        prmshpdte,
        purchsitetxschsrc,
        lineorigin,
        polneary_6,
        qtycmtbase,
        phone2,
        denxrate,
        bcktxamt,
        orextcst,
        zipcode,
        phone1,
        country,
        product_indicator,
        decplqty,
        qtycance,
        unitcost,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
