with

source as (

    select * from {{ source('ndhc_dbo', 'pm10000') }}

),

renamed as (

    select
        bachnumb,
        bchsourc,
        vchnumwk,
        chekdate,
        cheknmbr,
        pmwrkms2,
        pstgdate,
        distknam,
        ccrctnum,
        vchrnmbr,
        pmicmsgs,
        chekbkid,
        cardname,
        ppsamded,
        curtrxam,
        ten99type,
        chekamnt,
        camcbkid,
        sourcdoc,
        docprinted,
        mdfusrid,
        campynbr,
        discdate,
        pmdstmsg,
        docdate,
        gstdsamt,
        un1099am,
        pmwrkmsg,
        icdists,
        workflow_status,
        ccampynm,
        taxschid,
        campmtnm,
        printed,
        tax_date,
        vadcdtro,
        mscchamt,
        ppstaxrt,
        bktmscam,
        ten99boxnumber,
        invoicereceiptdate,
        ectrx,
        corrnxst,
        prchdate,
        apdstkam,
        duedate,
        crcrdamt,
        vchrncor,
        camtdate,
        txengcld,
        posteddt,
        mscschid,
        pymtrmid,
        shipmthd,
        prctdisc,
        trdisamt,
        backouttradedisc,
        dex_row_id,
        noteindx,
        prchamnt,
        cbvat,
        taxinvreqd,
        ictrx,
        retnagam,
        posted,
        simplifd,
        aplywith,
        appldamt,
        chamcbid,
        wrofamnt,
        chrgamnt,
        trxdscrn,
        cashamnt,
        crcarddt,
        cdocnmbr,
        ptdusrid,
        dscdlram,
        bnkrcamt,
        pstgstus,
        frtamnt,
        curncyid,
        frtschid,
        modifdt,
        docnumbr,
        bktfrtam,
        vendorid,
        docamnt,
        vaddcdpr,
        disamtav,
        pordnmbr,
        pchschid,
        ten99amnt,
        bktpuram,
        cntrltyp,
        pgramsbj,
        electronic,
        corrctn,
        lngdesc,
        dex_row_ts,
        doctype,
        taxamnt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
