with source as (

    select * from {{ source('ndhc_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        noteindx,
        voiddate,
        agngbukt,
        shipmthd,
        cprcstnm,
        cbkidchk,
        dinvpdof,
        bchsourc,
        cashamnt,
        duedate,
        dscpctam,
        pymtrmid,
        curncyid,
        slprsnid,
        postdate,
        frtschid,
        ectrx,
        costamnt,
        electronic,
        dscdlram,
        docdate,
        cbkidcsh,
        lstedtdt,
        factoring,
        bktslsam,
        pstusrid,
        wrofamnt,
        cshrctyp,
        cheknmbr,
        taxamnt,
        bktmscam,
        distknam,
        simplifd,
        cspornbr,
        backouttradedisc,
        curtrxam,
        gstdsamt,
        trdisamt,
        slstercd,
        glpostdt,
        delete1,
        dex_row_ts,
        cbkidcrd,
        frtamnt,
        slsamnt,
        dex_row_id,
        adrscode,
        comdlram,
        trxdscrn,
        slschdid,
        saledate,
        ppsamded,
        bktfrtam,
        bachnumb,
        aplywith,
        corrctn,
        eftflag,
        disavamt,
        voidstts,
        directdebit,
        tax_date,
        discrtnd,
        taxschid,
        trxsorce,
        mscschid,
        lstusred,
        miscamnt,
        disavtkn,
        ortrxamt,
        discdate,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
