with fact_cost as (
    select
        fct.pk_global_sales,
        fct.inventtransid,
        fct."Order ID",
        fct."Company",
        fct."Order Status ID",
        fct."Order_Type_SK",
        fct."Inventory Location ID",
        fct."Inventory Site ID",
        fct."Create Date",
        fct."Delivery Date",
        fct."Invoice Account",
        fct."Customer Invoice Date",
        fct."Customer Account",
        fct."Shipping Date Confirmed",
        fct."Shipping Date Requested",
        fct."Item ID",
        fct."Salesperson_SK",
        fct."Flag_Price_Adjustment",
        fct."Invoice ID",
        fct."Ordered Amount",
        fct."Sales Amount",
        fct."Sales Price",
        fct."Invoice Amount",
        fct."Freight Rate",
        fct.ub_price_high,
        fct.ub_price_avg,
        fct.ub_price_low,
        fct."Ordered Qty",
        fct."Ordered Volume (Lbs)",
        fct."Sales Qty",
        fct."Sales Volume (Lbs)",
        fct."Invoice Volume (Lbs)",
        fct."Inv Qty",
        fct."Estimated Cost",
        fct."Posted Cost",
        fct."Adjusted Cost",
        fct."Settled Cost",
        fct."Rebates",
        fct."Returned Invoice",
        fct."Date Financial",
        fct."Financial Division ID",
        fct."Delivery Address ID",
        fct."Delivery Terms",
        fct."Customer PO",
        fct."Mode",
        fct."Last Data Refresh",
        fct."Exchange Rate (USD-CAD)",
        'D365' as sourcesystem,
        0 as sourcesystemcode,
        fct."Price UOM",
        fct."Weight UOM",
        upper(trim(fct."Sales Unit")) as "Sales Unit",
        upper(fct."Currency") as "Currency"
    from {{ ref('int_global_sales__fact_cost_d365') }} as fct
)

select * from fact_cost
