name: "CD - Snowflake Source Permissions"

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'hv_edp_dbt/models/bronze/**/*.yml'
      - 'hv_edp_dbt/models/sources.yml'

variables:
  - group: 'Snowflake Service Account'

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: SourcesCD
    timeoutInMinutes: 10
    displayName: 'Grant source objects proper permissions'

    workspace:
      clean: outputs

    steps:
      - checkout: self
        fetchDepth: 0
        clean: true

      - script: |
          ls -R $(System.DefaultWorkingDirectory)
        displayName: 'List directory contents'

      - script: |
          echo "Build.SourceVersion: $(Build.SourceVersion)"
        displayName: 'Print Build.SourceVersion'

      - script: |
          pip install snowflake-connector-python pyyaml
        displayName: 'Install Snowflake connector and PyYAML'

      - script: |
          echo "All changes in this commit:"
          git ls-files hv_edp_dbt/models | grep '\.yml$'
        displayName: 'List all .yml files in models'

      - script: |
          db_added=( $(git diff origin/main -- 'hv_edp_dbt/models/**/*.yml' | grep -E '^\+.*database:' | awk -F'database: ' '{print $2}') )
          array_str=$(IFS=,; echo "${db_added[*]}")
          if [[ "${#db_added[@]}" -gt 0 ]]; then
              for db in "${db_added[@]}"; do
                  echo "The $db was added to the project."
              done
          fi
          echo "##vso[task.setvariable variable=db_list]$array_str"
        name: SetOutput
        displayName: 'List new databases'

      - script: |
          python python/snowflake_permissions.py
        displayName: 'Run Snowflake permissions script'
        env:
          SNOWFLAKE_ACCOUNT: $(SNOWFLAKE_ACCOUNT)
          SNOWFLAKE_USER: $(SNOWFLAKE_USER)
          SNOWFLAKE_PASSWORD: $(SNOWFLAKE_PASSWORD)
          SNOWFLAKE_ROLE: $(SNOWFLAKE_ROLE)
          SNOWFLAKE_WAREHOUSE: $(SNOWFLAKE_WAREHOUSE)
