name: "CI - Secrets Scanning"

trigger: none

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: SecretsCI
    timeoutInMinutes: 10
    displayName: 'Secrets Scanning'

    workspace:
      clean: outputs

    steps:
      - checkout: self
        fetchDepth: 1
        clean: true

      - script: |
          pip install detect-secrets
        displayName: Install detect-secrets

      - script: |
          echo "detect-secrets Version:" && detect-secrets --version
        displayName: Test the install

      - script: |
          # Backup the list of known secrets
          if [ -f ".secrets.baseline" ]; then
            cp .secrets.baseline .secrets.new
          else
            echo "{}" > .secrets.new
          fi

          # Find all the secrets in the repository
          detect-secrets scan --baseline .secrets.new $(find . -type f ! -name '.secrets.*' ! -path '*/.git*' ! -path '*/target/*' ! -path '*/dbt_packages/*')

          # If there is any difference between the known and newly detected secrets, break the build
          list_secrets() {
            jq -r '.results | keys[] as $key | "\($key),\(.[$key] | .[] | .hashed_secret)"' "$1" | sort
          }

          if [ -f ".secrets.baseline" ]; then
            if ! diff <(list_secrets .secrets.baseline) <(list_secrets .secrets.new) >&2; then
              echo "Detected new secrets in the repo" >&2
              exit 1
            fi
          else
            echo "No .secrets.baseline file found. Creating one..."
            mv .secrets.new .secrets.baseline
            echo "Please commit the .secrets.baseline file to the repository."
          fi
        displayName: Scan codebase for secrets
