with

source as (

    select * from {{ source('bhfc_dbo', 'pm10000') }}

),

renamed as (

    select
        disamtav,
        chekdate,
        frtschid,
        cdocnmbr,
        pmdstmsg,
        corrctn,
        cardname,
        campmtnm,
        aplywith,
        cntrltyp,
        sourcdoc,
        retnagam,
        noteindx,
        posteddt,
        invoicereceiptdate,
        duedate,
        frtamnt,
        mdfusrid,
        pchschid,
        discdate,
        doctype,
        txengcld,
        pmwrkms2,
        taxamnt,
        docdate,
        un1099am,
        bktpuram,
        camtdate,
        distknam,
        crcrdamt,
        appldamt,
        vadcdtro,
        prchamnt,
        vchrncor,
        bktmscam,
        prctdisc,
        pymtrmid,
        bachnumb,
        ten99type,
        ptdusrid,
        simplifd,
        bnkrcamt,
        cbvat,
        modifdt,
        taxinvreqd,
        tax_date,
        curncyid,
        apdstkam,
        chekbkid,
        backouttradedisc,
        wrofamnt,
        pstgstus,
        pgramsbj,
        cashamnt,
        trxdscrn,
        camcbkid,
        mscchamt,
        dex_row_ts,
        vchnumwk,
        ccrctnum,
        ppstaxrt,
        corrnxst,
        posted,
        chamcbid,
        crcarddt,
        docprinted,
        docnumbr,
        shipmthd,
        trdisamt,
        ictrx,
        ten99boxnumber,
        taxschid,
        workflow_status,
        prchdate,
        dscdlram,
        vendorid,
        vchrnmbr,
        vaddcdpr,
        pmwrkmsg,
        bchsourc,
        dex_row_id,
        cheknmbr,
        mscschid,
        icdists,
        pmicmsgs,
        electronic,
        printed,
        ccampynm,
        pordnmbr,
        gstdsamt,
        curtrxam,
        ten99amnt,
        docamnt,
        ppsamded,
        lngdesc,
        bktfrtam,
        ectrx,
        campynbr,
        chrgamnt,
        pstgdate,
        chekamnt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
