with

source as (

    select {{ convert_columns('bhfc_dbo', 'pm00200') }}
    from {{ source('bhfc_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        userdef2,
        govindid,
        vendname,
        phnumbr1,
        ten99type,
        pmwrtidx,
        address3,
        dxvarnum,
        brthdate,
        vndcntct,
        xpdtoblg,
        prspayee,
        phone3,
        pmdavidx,
        disgrper,
        crtexpdt,
        purpvidx,
        pmmschix,
        duegrper,
        pmfrtidx,
        declid,
        txrgnnum,
        chekbkid,
        vadcdtro,
        workflow_priority,
        vendstts,
        sbppsded,
        phnumbr2,
        minorder,
        mxwofamt,
        shipmthd,
        trddisct,
        pmrtngix,
        vadcd1099,
        pmapindx,
        kpcalhst,
        pmfinidx,
        post_results_to,
        mxiafvnd,
        pmtaxidx,
        venddba,
        vndclsid,
        zipcode,
        withholdingtype,
        crlmtdlr,
        crtcomdt,
        pmcshidx,
        kperhist,
        vaddcdpr,
        laborpmttype,
        creatddt,
        pmprchix,
        writeoff,
        pymtrmid,
        ratetpid,
        taxschid,
        vadcdpad,
        txidnmbr,
        minpypct,
        withholdingformtype,
        minpytyp,
        govcrpid,
        maxindlr,
        taxinvrecvd,
        acnmvndr,
        hold,
        noteindx,
        kptrxhst,
        taxfilenummode,
        vadcdsfr,
        rtobutkn,
        ccode,
        credtlmt,
        workflow_approval_status,
        dex_row_ts,
        vndchknm,
        curncyid,
        cbvat,
        parvenid,
        userlang,
        modifdt,
        dex_row_id,
        ptcshacf,
        ten99boxnumber,
        state,
        freeonboard,
        comment1,
        userdef1,
        city,
        address1,
        withholdingentitytype,
        docfmtid,
        upszone,
        vendshnm,
        country,
        workflow_status,
        address2,
        onepaypervendinv,
        faxnumbr,
        acpuridx,
        kgldsths,
        pmtdscix,
        minpydlr,
        revalue_vendor,
        ppstaxrt,
        pmdtkidx,
        pymntpri,
        comment2,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
