with source as (

    select * from {{ source('bhfc_dbo', 'pop30300') }}

),

renamed as (

    select
        rcptnote_8,
        purchase_misc_taxable,
        purchase_freight_taxable,
        receiptdate,
        rcptnote_2,
        bcktxamt,
        voidstts,
        rcptnote_5,
        cbvat,
        vchrnmbr,
        ormsctax,
        miscamnt,
        posteddt,
        mctrxstt,
        ordistkn,
        vadcdtro,
        orddlrat,
        exgtblid,
        prepaymentamount,
        taxamnt,
        tax_date,
        orsubtot,
        revaljrnentry,
        ten99amnt,
        origbackoutfreighttaxamt,
        ortdisam,
        ptdusrid,
        ordavamt,
        refrence,
        poptype,
        msctxamt,
        ectrx,
        poplnerr,
        rcptnote_1,
        rcptnote_4,
        distknam,
        shipmthd,
        ratecalc,
        invoiceexpected,
        modifdt,
        simplifd,
        backoutfreighttaxamt,
        disavtkn,
        ten99boxnumber,
        subtotal,
        dscpctam,
        ratetpid,
        bsivcttl,
        obtaxamt,
        rcptnote_3,
        creatddt,
        taxschid,
        trdpctpr,
        originatingprepaymentamt,
        xchgrate,
        trdisamt,
        discdate,
        vendname,
        currnidx,
        bchsourc,
        frttxamt,
        curncyid,
        time1,
        workflow_status,
        vnddocnm,
        taxinvrecvd,
        ordatkn,
        origbackoutmisctaxamt,
        txrgnnum,
        disavamt,
        exchdate,
        ten99type,
        total_landed_cost_amount,
        backoutmisctaxamt,
        pop_hdr_errors_4,
        user2ent,
        ppstaxrt,
        orfrttax,
        rcptnote_6,
        frtamnt,
        pymtrmid,
        dscdlram,
        glpostdt,
        duedate,
        mscschid,
        replacegoods,
        orfrtamt,
        revaltrxsource,
        withhamt,
        denxrate,
        frtschid,
        rcptnote_7,
        pophdr2,
        aplywith,
        actlship,
        or1099am,
        invoicereceiptdate,
        bachnumb,
        trxsorce,
        pophdr1,
        ormiscamt,
        taxinvreqd,
        ortaxamt,
        dex_row_id,
        _fivetran_deleted,
        _fivetran_synced,
        upper(trim(poprctnm)) as poprctnm,
        upper(trim(vendorid)) as vendorid

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
