with

source as (

    select * from {{ source('bhfc_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        docprinted,
        pyenttyp,
        ten99type,
        trxsorce,
        trxdscrn,
        un1099am,
        frtschid,
        modifdt,
        pymtrmid,
        disamtav,
        vndchknm,
        simplifd,
        ptdusrid,
        ten99boxnumber,
        shipmthd,
        distknam,
        chekbkid,
        aplywith,
        cbvat,
        ictrx,
        taxschid,
        wrofamnt,
        bktfrtam,
        bachnumb,
        mdfusrid,
        dex_row_id,
        posteddt,
        docnumbr,
        cardname,
        duedate,
        lngdesc,
        mscchamt,
        corrctn,
        curtrxam,
        workflow_status,
        ectrx,
        pchschid,
        retnagam,
        docdate,
        prctdisc,
        curncyid,
        tax_date,
        trdisamt,
        pgramsbj,
        bchsourc,
        invoicereceiptdate,
        pstgdate,
        voidpdate,
        ppstaxrt,
        vendorid,
        discamnt,
        ten99amnt,
        docamnt,
        dex_row_ts,
        bktmscam,
        vadcdtro,
        backouttradedisc,
        cntrltyp,
        pordnmbr,
        frtamnt,
        gstdsamt,
        taxamnt,
        prchamnt,
        dscdlram,
        bktpuram,
        discdate,
        mscschid,
        disavtkn,
        prchdate,
        dinvpdof,
        voided,
        electronic,
        ppsamded,
        ttlpymts,
        hold,
        taxinvreqd,
        noteindx,
        ponumber,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
