with

source as (

    select {{ convert_columns('tnm_dbo', 'pop10110') }}
    from {{ source('tnm_dbo', 'pop10110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        vnditdsc,
        oruntcst,
        backouttradedisctax,
        address1,
        reqstdby,
        product_indicator,
        polneary_8,
        curncyid,
        purchase_item_tax_schedu,
        decplcur,
        source_document_number,
        xchgrate,
        obtaxamt,
        contact,
        purchase_iv_item_taxable,
        ortaxamt,
        qtycommittedinbaseorig,
        polneary_2,
        costcode,
        change_order_flag,
        phone3,
        phone2,
        vendorid,
        lineorigin,
        projnum,
        ratecalc,
        polneary_1,
        potype,
        qtyorder,
        origbackouttradedisctax,
        currnidx,
        zipcode,
        flags,
        invindx,
        uofm,
        vnditnum,
        locncode,
        capital_item,
        cmpnynam,
        commntid,
        addrsource,
        qty_canceled_orig,
        opostsub,
        odecplcu,
        adrscode,
        fax,
        released_date,
        source_document_line_num,
        prmdate,
        itmtrkop,
        releasebydate,
        print_phone_numbergb,
        noninven,
        vctnmthd,
        fstrcptdt,
        landed_cost_group_id,
        dex_row_id,
        extdcost,
        ccode,
        doctype,
        dex_row_ts,
        release,
        freeonboard,
        jobnumbr,
        phone1,
        decplqty,
        prmshpdte,
        address2,
        plnndspplid,
        itemnmbr,
        linenumber,
        shipmthd,
        country,
        costtype,
        polneary_9,
        address3,
        polneary_3,
        polneary_7,
        city,
        qtycance,
        polneary_4,
        origprmdate,
        polnesta,
        lstrcptdt,
        orextcst,
        qtyuncmtbase,
        costcatid,
        umqtyinb,
        purchase_site_tax_schedu,
        taxamnt,
        reqdate,
        state,
        purchsitetxschsrc,
        bcktxamt,
        qtycmtbase,
        itemdesc,
        unitcost,
        polneary_5,
        denxrate,
        bsivcttl,
        polneary_6,
        po_line_status_orig,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
