with source as (

    select * from {{ source('tnm_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        taxschid,
        phone1,
        userdef2,
        minpydlr,
        modifdt,
        ccrdxpdt,
        address1,
        zip,
        fnchatyp,
        fnchpcnt,
        finchdlr,
        duegrper,
        shipmthd,
        taxexmt1,
        adrscode,
        rmavacc,
        pymtrmid,
        frstindt,
        rmovrpymtwrtoffacctidx,
        curncyid,
        custpriority,
        custname,
        rmsoracc,
        rmivacc,
        kperhist,
        crcardid,
        prbtadcd,
        rmtakacc,
        slprsnid,
        crlmttyp,
        taxexmt2,
        gpsfointegrationid,
        rmfcgacc,
        address2,
        creatddt,
        dex_row_id,
        custclas,
        rmcosacc,
        prstadcd,
        state,
        kpcalhst,
        revalue_customer,
        send_email_statements,
        cntcprsn,
        ratetpid,
        finchid,
        includeindp,
        userlang,
        disgrper,
        city,
        noteindx,
        bankname,
        custdisc,
        mxwrofam,
        stmtcycl,
        cprcstnm,
        rmaracc,
        bnkbrnch,
        comment2,
        dex_row_ts,
        orderfulfilldefault,
        prclevel,
        rmcshacc,
        shipcomplete,
        phone2,
        kpdsthst,
        userdef1,
        upszone,
        crlmtper,
        balnctyp,
        address3,
        defcacty,
        crcrdnum,
        phone3,
        staddrcd,
        govindid,
        txrgnnum,
        rmslsacc,
        inactive,
        salsterr,
        rmwracc,
        hold,
        post_results_to,
        kptrxhst,
        minpypct,
        shrtname,
        minpytyp,
        cbvat,
        crlmtamt,
        country,
        fax,
        integrationsource,
        crlmtpam,
        stmtname,
        comment1,
        mxwoftyp,
        docfmtid,
        integrationid,
        declid,
        govcrpid,
        chekbkid,
        ccode,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
