with source as (

    select * from {{ source('tnm_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        cntrltyp,
        curtrxam,
        ectrx,
        ponumber,
        ptdusrid,
        voidpdate,
        trxsorce,
        discamnt,
        ten99amnt,
        disavtkn,
        lngdesc,
        dex_row_ts,
        prchamnt,
        simplifd,
        electronic,
        bktmscam,
        mscchamt,
        bktfrtam,
        discdate,
        ttlpymts,
        prctdisc,
        taxinvreqd,
        un1099am,
        workflow_status,
        dex_row_id,
        voided,
        ppstaxrt,
        tax_date,
        invoicereceiptdate,
        mscschid,
        hold,
        prchdate,
        ictrx,
        trdisamt,
        backouttradedisc,
        docamnt,
        pstgdate,
        wrofamnt,
        taxamnt,
        trxdscrn,
        gstdsamt,
        corrctn,
        ten99boxnumber,
        vendorid,
        cardname,
        docprinted,
        taxschid,
        dinvpdof,
        mdfusrid,
        aplywith,
        disamtav,
        docnumbr,
        duedate,
        pordnmbr,
        modifdt,
        bktpuram,
        ppsamded,
        dscdlram,
        shipmthd,
        pymtrmid,
        docdate,
        curncyid,
        bchsourc,
        pgramsbj,
        frtamnt,
        vndchknm,
        posteddt,
        pyenttyp,
        pchschid,
        cbvat,
        distknam,
        frtschid,
        bachnumb,
        ten99type,
        noteindx,
        retnagam,
        vadcdtro,
        chekbkid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
