with source as (

    select * from {{ source('tnm_dbo', 'pm20000') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        mscschid,
        frtamnt,
        ppstaxrt,
        curncyid,
        taxinvreqd,
        bchsourc,
        docnumbr,
        noteindx,
        retnagam,
        bachnumb,
        disamtav,
        prchdate,
        dinvpdof,
        dscdlram,
        pgramsbj,
        backouttradedisc,
        invoicereceiptdate,
        pymtrmid,
        aplywith,
        gstdsamt,
        taxamnt,
        ten99boxnumber,
        cardname,
        lngdesc,
        wrofamnt,
        trxdscrn,
        trxsorce,
        ptdusrid,
        bktfrtam,
        simplifd,
        docprinted,
        hold,
        workflow_status,
        docamnt,
        shipmthd,
        corrctn,
        pstgdate,
        vendorid,
        ttlpymts,
        voided,
        un1099am,
        cbvat,
        prctdisc,
        bnkrcamt,
        prchamnt,
        docdate,
        pchschid,
        ponumber,
        posteddt,
        ictrx,
        curtrxam,
        dex_row_id,
        distknam,
        ppsamded,
        trdisamt,
        mdfusrid,
        duedate,
        mscchamt,
        ectrx,
        ten99type,
        pordnmbr,
        modifdt,
        vadcdtro,
        dex_row_ts,
        frtschid,
        bktmscam,
        discdate,
        chekbkid,
        pyenttyp,
        disavtkn,
        discamnt,
        ten99amnt,
        vndchknm,
        cntrltyp,
        bktpuram,
        taxschid,
        tax_date,
        electronic,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
