with

source as (

    select {{ convert_columns('tnm_dbo', 'pop30110') }}
    from {{ source('tnm_dbo', 'pop30110') }}

),

renamed as (

    select
        brkfld1,
        ord,
        ponumber,
        currnidx,
        itemdesc,
        landed_cost_group_id,
        noninven,
        itemnmbr,
        polneary_7,
        polneary_4,
        city,
        polneary_1,
        source_document_number,
        releasebydate,
        origprmdate,
        taxamnt,
        phone2,
        odecplcu,
        product_indicator,
        dex_row_ts,
        address3,
        country,
        vendorid,
        invindx,
        orextcst,
        flags,
        linenumber,
        costcatid,
        commntid,
        reqdate,
        polnesta,
        state,
        costtype,
        qtycance,
        unitcost,
        phone3,
        vnditdsc,
        potype,
        polneary_5,
        obtaxamt,
        fax,
        uofm,
        fstrcptdt,
        prmdate,
        cmpnynam,
        shipmthd,
        ortaxamt,
        polneary_6,
        freeonboard,
        adrscode,
        ccode,
        vctnmthd,
        extdcost,
        purchase_item_tax_schedu,
        doctype,
        umqtyinb,
        release,
        reqstdby,
        lineorigin,
        purchase_iv_item_taxable,
        address1,
        qtyorder,
        polneary_8,
        costcode,
        dex_row_id,
        decplcur,
        purchase_site_tax_schedu,
        decplqty,
        address2,
        prmshpdte,
        source_document_line_num,
        polneary_2,
        oruntcst,
        released_date,
        projnum,
        bcktxamt,
        purchsitetxschsrc,
        locncode,
        jobnumbr,
        addrsource,
        vnditnum,
        itmtrkop,
        lstrcptdt,
        polneary_9,
        zipcode,
        bsivcttl,
        print_phone_numbergb,
        contact,
        phone1,
        polneary_3,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'FALSE') = 'FALSE'
