with source as (

    select * from {{ source('tnm_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        vndclsid,
        noteindx,
        vndchknm,
        acpuridx,
        pmdavidx,
        cbvat,
        modifdt,
        purpvidx,
        pmdtkidx,
        vadcdpad,
        dxvarnum,
        kptrxhst,
        comment1,
        chekbkid,
        taxinvrecvd,
        freeonboard,
        prspayee,
        comment2,
        trddisct,
        city,
        minpydlr,
        vadcdtro,
        credtlmt,
        crtexpdt,
        pmmschix,
        kgldsths,
        writeoff,
        rtobutkn,
        vadcd1099,
        pmrtngix,
        workflow_status,
        userlang,
        address3,
        address2,
        pymntpri,
        state,
        userdef1,
        taxfilenummode,
        ptcshacf,
        vaddcdpr,
        taxschid,
        crtcomdt,
        txrgnnum,
        vendshnm,
        vndcntct,
        withholdingformtype,
        ratetpid,
        creatddt,
        workflow_priority,
        userdef2,
        pmapindx,
        maxindlr,
        minpypct,
        duegrper,
        country,
        onepaypervendinv,
        address1,
        workflow_approval_status,
        dex_row_ts,
        disgrper,
        curncyid,
        crlmtdlr,
        withholdingtype,
        revalue_vendor,
        ccode,
        laborpmttype,
        vendname,
        phnumbr1,
        minorder,
        mxiafvnd,
        xpdtoblg,
        kpcalhst,
        vendstts,
        withholdingentitytype,
        parvenid,
        vadcdsfr,
        brthdate,
        ten99type,
        pmwrtidx,
        ppstaxrt,
        acnmvndr,
        docfmtid,
        kperhist,
        faxnumbr,
        shipmthd,
        pmcshidx,
        pmfinidx,
        phnumbr2,
        pmprchix,
        pmtaxidx,
        phone3,
        declid,
        hold,
        govindid,
        zipcode,
        govcrpid,
        pymtrmid,
        post_results_to,
        sbppsded,
        mxwofamt,
        upszone,
        txidnmbr,
        pmtdscix,
        pmfrtidx,
        dex_row_id,
        ten99boxnumber,
        venddba,
        minpytyp,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
