with source as (

    select * from {{ source('tnm_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        docdate,
        costamnt,
        dex_row_id,
        cheknmbr,
        lstedtdt,
        cbkidcrd,
        cshrctyp,
        delete1,
        tax_date,
        saledate,
        lstusred,
        simplifd,
        cashamnt,
        backouttradedisc,
        trxsorce,
        agngbukt,
        slsamnt,
        aplywith,
        ppsamded,
        voidstts,
        comdlram,
        pstusrid,
        wrofamnt,
        factoring,
        trdisamt,
        gstdsamt,
        dinvpdof,
        curtrxam,
        distknam,
        slstercd,
        bktslsam,
        cspornbr,
        adrscode,
        trxdscrn,
        curncyid,
        bktmscam,
        ectrx,
        electronic,
        postdate,
        mscschid,
        discdate,
        cprcstnm,
        shipmthd,
        bktfrtam,
        disavamt,
        cbkidchk,
        duedate,
        dscdlram,
        frtamnt,
        frtschid,
        eftflag,
        ortrxamt,
        pymtrmid,
        voiddate,
        corrctn,
        taxamnt,
        noteindx,
        bachnumb,
        cbkidcsh,
        taxschid,
        dex_row_ts,
        glpostdt,
        disavtkn,
        bchsourc,
        discrtnd,
        miscamnt,
        dscpctam,
        slprsnid,
        directdebit,
        slschdid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
