with source as (

    select * from {{ source('tnm_dbo', 'pop30300') }}

),

renamed as (

    select
        frtamnt,
        bchsourc,
        withhamt,
        poplnerr,
        curncyid,
        invoiceexpected,
        orsubtot,
        poptype,
        duedate,
        or1099am,
        disavtkn,
        ortaxamt,
        taxschid,
        dscpctam,
        shipmthd,
        ppstaxrt,
        disavamt,
        subtotal,
        creatddt,
        actlship,
        vendname,
        distknam,
        txrgnnum,
        rcptnote_4,
        invoicereceiptdate,
        frttxamt,
        rcptnote_2,
        currnidx,
        bcktxamt,
        ectrx,
        exchdate,
        exgtblid,
        purchase_misc_taxable,
        revaltrxsource,
        receiptdate,
        ormsctax,
        trxsorce,
        revaljrnentry,
        workflow_status,
        tax_date,
        pop_hdr_errors_4,
        vnddocnm,
        bachnumb,
        aplywith,
        prepaymentamount,
        replacegoods,
        backoutfreighttaxamt,
        rcptnote_1,
        vadcdtro,
        mscschid,
        vchrnmbr,
        pophdr2,
        ptdusrid,
        trdpctpr,
        msctxamt,
        pophdr1,
        glpostdt,
        orfrtamt,
        denxrate,
        orfrttax,
        ordavamt,
        obtaxamt,
        rcptnote_6,
        ten99boxnumber,
        ortdisam,
        bsivcttl,
        total_landed_cost_amount,
        miscamnt,
        frtschid,
        taxinvrecvd,
        taxinvreqd,
        taxamnt,
        ormiscamt,
        rcptnote_3,
        purchase_freight_taxable,
        dex_row_id,
        voidstts,
        origbackoutmisctaxamt,
        modifdt,
        xchgrate,
        rcptnote_8,
        rcptnote_5,
        originatingprepaymentamt,
        ratetpid,
        simplifd,
        discdate,
        trdisamt,
        mctrxstt,
        ten99type,
        pymtrmid,
        origbackoutfreighttaxamt,
        dscdlram,
        refrence,
        user2ent,
        backoutmisctaxamt,
        time1,
        ten99amnt,
        orddlrat,
        posteddt,
        ordatkn,
        ratecalc,
        cbvat,
        rcptnote_7,
        ordistkn,
        _fivetran_deleted,
        _fivetran_synced,
        upper(trim(poprctnm)) as poprctnm,
        upper(trim(vendorid)) as vendorid

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
