with

source as (

    select * from {{ source('tnm_dbo', 'pm10000') }}

),

renamed as (

    select
        bachnumb,
        bchsourc,
        vchnumwk,
        ten99type,
        tax_date,
        printed,
        pchschid,
        apdstkam,
        vendorid,
        electronic,
        taxschid,
        crcrdamt,
        chamcbid,
        ictrx,
        campynbr,
        ppsamded,
        dex_row_id,
        bktmscam,
        vaddcdpr,
        camtdate,
        cdocnmbr,
        curncyid,
        posteddt,
        distknam,
        ppstaxrt,
        dex_row_ts,
        frtamnt,
        simplifd,
        vchrncor,
        ten99amnt,
        chekdate,
        pymtrmid,
        pstgdate,
        taxamnt,
        frtschid,
        doctype,
        cntrltyp,
        cardname,
        docprinted,
        chekbkid,
        sourcdoc,
        pmwrkms2,
        trxdscrn,
        vchrnmbr,
        chekamnt,
        pmwrkmsg,
        chrgamnt,
        bktpuram,
        discdate,
        taxinvreqd,
        ccrctnum,
        shipmthd,
        campmtnm,
        pmicmsgs,
        mscschid,
        bktfrtam,
        noteindx,
        docnumbr,
        prchamnt,
        docdate,
        dscdlram,
        vadcdtro,
        backouttradedisc,
        ccampynm,
        prctdisc,
        pordnmbr,
        camcbkid,
        trdisamt,
        mdfusrid,
        modifdt,
        ectrx,
        ptdusrid,
        invoicereceiptdate,
        duedate,
        cbvat,
        aplywith,
        corrctn,
        icdists,
        pgramsbj,
        cheknmbr,
        posted,
        ten99boxnumber,
        gstdsamt,
        docamnt,
        prchdate,
        disamtav,
        txengcld,
        corrnxst,
        retnagam,
        crcarddt,
        pmdstmsg,
        pstgstus,
        curtrxam,
        workflow_status,
        cashamnt,
        un1099am,
        mscchamt,
        bnkrcamt,
        lngdesc,
        wrofamnt,
        appldamt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, 'false') = 'false'
