with source as (

    select * from {{ source('fast_bi_dwh_dbo', 'faglflext') }}

),

renamed as (

    select

        ryear,
        osl03,
        msl15,
        msl07,
        activ,
        hsl11,
        hsl14,
        scntr,
        tsl04,
        msl11,
        hsl06,
        ksl13,
        ksl07,
        rldnr,
        objnr03,
        hslvt,
        kokrs,
        tsl08,
        rcntr,
        ksl03,
        tsl09,
        cost_elem,
        tsl05,
        ksl10,
        hsl04,
        tsl16,
        msl02,
        tsl11,
        rbusa,
        rmvct,
        osl05,
        tsl14,
        segment,
        objnr07,
        tsl10,
        objnr06,
        msl04,
        tsl13,
        ksl06,
        msl16,
        sfarea,
        osl14,
        mslvt,
        msl13,
        objnr04,
        msl03,
        rrcty,
        prctr,
        rtcur,
        osl04,
        faglflextid,
        ksl05,
        drcrk,
        msl10,
        timestamp,
        msl06,
        objnr00,
        kslvt,
        ksl14,
        tsl02,
        awtyp,
        hsl15,
        objnr05,
        hsl09,
        tsl12,
        objnr08,
        msl01,
        osl11,
        ksl11,
        objnr01,
        osl15,
        rfarea,
        ksl01,
        osl01,
        ksl12,
        racct,
        hsl10,
        sbusa,
        rassc,
        ksl02,
        tslvt,
        tsl03,
        hsl08,
        rclnt,
        osl06,
        hsl16,
        osl07,
        msl08,
        osl12,
        tsl01,
        tsl15,
        hsl05,
        tsl06,
        pprctr,
        rpmax,
        ksl08,
        hsl02,
        msl05,
        runit,
        ksl15,
        hsl01,
        psegment,
        osl09,
        tsl07,
        rbukrs,
        ksl04,
        msl12,
        rvers,
        hsl12,
        ksl16,
        osl02,
        hsl03,
        oslvt,
        logsys,
        osl13,
        hsl07,
        osl10,
        ksl09,
        osl16,
        msl09,
        hsl13,
        objnr02,
        osl08,
        msl14,
        _fivetran_synced,
        _fivetran_deleted

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
