with source as (

    select * from {{ source('inspec_fbd', 'QcFBDLineTemperatures') }}

),

filtered as (

    select * from source
    where coalesce(_fivetran_deleted, false) = false

),

renamed as (

    select
        {{ adapter.quote("_ID") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_LOTSUBFORM_LOT") }},
        {{ adapter.quote("TOTAL_SCORE") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_PINBONING_UOM") }},
        {{ adapter.quote("OFFICIALTIME") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_PORTIONS_UOM") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_WIPINTHEVACOOLER_UOM") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_MAINPROCESSINGPINBONELINE_UOM") }},
        {{ adapter.quote("WALLTIME") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_PORTIONTRAYPACKROOM") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_MAINPROCESSINGDEHEADING_UOM") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_RECEIVING") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_ZONEA") }},
        {{ adapter.quote("STATUS_CREATEDBY") }},
        {{ adapter.quote("FORMID") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_VACOOLER_UOM") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_PINBONING") }},
        {{ adapter.quote("STATUSOVERRIDEREASON") }},
        {{ adapter.quote("STATUS_LASTMODIFIEDBY") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_FROZENAREA") }},
        {{ adapter.quote("NEWADDITION_PRODUCTINNEWADDITONFRESH_UOM") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_MAINPROCESSINGPINBONELINE") }},
        {{ adapter.quote("FORMPASSFAIL") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_RECEIVING1") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_PORTIONS") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_FROZENROOM_UOM") }},
        {{ adapter.quote("CONTEXT_ENTERPRISE") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_TRIMMING") }},
        {{ adapter.quote("APPROVAL_DATETIME") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_RECEIVING") }},
        {{ adapter.quote("NEWADDITION_PRODUCTINNEWADDITIONFROZEN_UOM") }},
        {{ adapter.quote("STATUS_WORKFLOW") }},
        {{ adapter.quote("STATUS_LASTMODIFIED") }},
        {{ adapter.quote("NEWADDITION_NEWADDITIONROOMTEMPERATURE") }},
        {{ adapter.quote("NEWADDITION_PRODUCTINNEWADDITIONFROZEN") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_MAINPROCESSINGDEHEADING") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_DEWATERINGTANK2_UOM") }},
        {{ adapter.quote("COMMENTS_0") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_ZONEA_UOM") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_RECEIVING_UOM") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_ZONEB") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_MAINPROCESSINGPACKAGINGAREA_UOM") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_DEWATERINGTANK2") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_DAWATERINGTANK_UOM") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_ZONEB_UOM") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_PORTIONTRAYPACKROOM_UOM") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_GRADING_UOM") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_VACOOLER") }},
        {{ adapter.quote("NEWADDITION_PRODUCTINNEWADDITONFRESH") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_GRADING") }},
        {{ adapter.quote("APPROVAL_USER") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_LOT") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_SHIPPINGCOOLER_UOM") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_COLDSTORAGE_UOM") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_TRIMMING_UOM") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_SHIPPINGCOOLER") }},
        {{ adapter.quote("NEWADDITION_NEWADDITIONROOMTEMPERATURE_UOM") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_DAWATERINGTANK") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_COLDSTORAGE") }},
        {{ adapter.quote("APPROVAL_STATUS") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_HEADCUTTING_UOM") }},
        {{ adapter.quote("CONTEXT_PLANT") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_DAWATERINGTANK1") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_WIPINTHEVACOOLER") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_MAINPROCESSINGPACKAGINGAREA") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_HEADCUTTING") }},
        {{ adapter.quote("COMMENTS") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_RECEIVING_UOM") }},
        {{ adapter.quote("CONTEXT") }},
        {{ adapter.quote("_FIVETRAN_DELETED") }},
        {{ adapter.quote("_FIVETRAN_SYNCED") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_RECEIVINGLINE1") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_RECEIVINGLINE2") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_TRIMMINGLINE2") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_PINBONINGLINE1") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_PINBONINGLINE2") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_TRIMMINGLINE1") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_GRADINGLINE2_UOM") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_TRAYPACK_UOM") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_PINBONINGLINE2_UOM") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_TRIMMINGLINE2_UOM") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_GRADINGLINE1") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_TRAYPACK") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_GRADINGLINE2") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_DEWATERINGTANK1") }},
        {{ adapter.quote("PRODUCTIONTEMPERATURES_RECEIVINGLINE2_UOM") }},
        {{ adapter.quote("PRODUCTINFORMATION_CONTAINERTYPE") }},
        {{ adapter.quote("PRODUCTINFORMATION_LOT_LOT") }},
        {{ adapter.quote("PRODUCTINFORMATION_LOT") }},
        {{ adapter.quote("PROCESSINGROOMTEMPERATURES_BLASTFREEZER") }}

    from filtered
)

select * from renamed
