with source as (

    select * from {{ source('avch_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        minorder,
        crlmtdlr,
        upszone,
        pmfinidx,
        zipcode,
        cbvat,
        state,
        pmtaxidx,
        minpytyp,
        pmprchix,
        declid,
        crtcomdt,
        pmwrtidx,
        pymntpri,
        govcrpid,
        workflow_priority,
        ten99boxnumber,
        ptcshacf,
        creatddt,
        faxnumbr,
        kpcalhst,
        userlang,
        pmdtkidx,
        kptrxhst,
        pmmschix,
        taxinvrecvd,
        comment1,
        maxindlr,
        pmfrtidx,
        address2,
        vadcdsfr,
        mxwofamt,
        writeoff,
        workflow_status,
        acpuridx,
        freeonboard,
        userdef1,
        taxfilenummode,
        vendname,
        withholdingformtype,
        pmdavidx,
        prspayee,
        curncyid,
        brthdate,
        rtobutkn,
        mxiafvnd,
        vendshnm,
        vndclsid,
        vadcd1099,
        userdef2,
        pmcshidx,
        dex_row_id,
        pmtdscix,
        ratetpid,
        laborpmttype,
        vndcntct,
        address1,
        txrgnnum,
        workflow_approval_status,
        minpypct,
        taxschid,
        disgrper,
        comment2,
        onepaypervendinv,
        minpydlr,
        vendstts,
        vaddcdpr,
        address3,
        chekbkid,
        withholdingentitytype,
        ten99type,
        kperhist,
        duegrper,
        acnmvndr,
        city,
        noteindx,
        modifdt,
        withholdingtype,
        shipmthd,
        vadcdpad,
        vadcdtro,
        kgldsths,
        vndchknm,
        parvenid,
        dex_row_ts,
        govindid,
        ppstaxrt,
        crtexpdt,
        hold,
        ccode,
        trddisct,
        phone3,
        pymtrmid,
        dxvarnum,
        xpdtoblg,
        docfmtid,
        phnumbr1,
        credtlmt,
        purpvidx,
        phnumbr2,
        post_results_to,
        revalue_vendor,
        country,
        pmrtngix,
        venddba,
        sbppsded,
        pmapindx,
        txidnmbr,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
