with source as (

    select * from {{ source('avch_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        custpriority,
        frstindt,
        mxwoftyp,
        custclas,
        fnchatyp,
        comment1,
        crcardid,
        txrgnnum,
        address2,
        rmcosacc,
        crlmtpam,
        custdisc,
        taxexmt2,
        gpsfointegrationid,
        curncyid,
        rmfcgacc,
        kpcalhst,
        salsterr,
        slprsnid,
        govindid,
        phone2,
        fnchpcnt,
        bankname,
        rmsoracc,
        modifdt,
        state,
        pymtrmid,
        crlmttyp,
        kptrxhst,
        rmavacc,
        duegrper,
        minpydlr,
        phone1,
        taxschid,
        dex_row_id,
        rmtakacc,
        inactive,
        crlmtper,
        cprcstnm,
        custname,
        crlmtamt,
        kperhist,
        city,
        upszone,
        disgrper,
        mxwrofam,
        ratetpid,
        finchid,
        cbvat,
        shipmthd,
        userlang,
        taxexmt1,
        orderfulfilldefault,
        dex_row_ts,
        userdef1,
        rmivacc,
        declid,
        stmtname,
        docfmtid,
        send_email_statements,
        phone3,
        staddrcd,
        crcrdnum,
        kpdsthst,
        integrationid,
        balnctyp,
        shipcomplete,
        defcacty,
        creatddt,
        cntcprsn,
        stmtcycl,
        comment2,
        prstadcd,
        address1,
        rmslsacc,
        rmwracc,
        hold,
        rmovrpymtwrtoffacctidx,
        bnkbrnch,
        integrationsource,
        minpytyp,
        post_results_to,
        rmaracc,
        zip,
        noteindx,
        userdef2,
        rmcshacc,
        country,
        finchdlr,
        govcrpid,
        prclevel,
        address3,
        chekbkid,
        ccode,
        prbtadcd,
        ccrdxpdt,
        revalue_customer,
        minpypct,
        fax,
        includeindp,
        adrscode,
        shrtname,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
