with source as (

    select * from {{ source('nb601_dbo', 'rm00101') }}

),

renamed as (

    select
        custnmbr,
        city,
        salsterr,
        chekbkid,
        txrgnnum,
        userdef1,
        custdisc,
        zip,
        rmtakacc,
        kptrxhst,
        rmcosacc,
        crlmttyp,
        adrscode,
        address1,
        balnctyp,
        integrationsource,
        rmfcgacc,
        modifdt,
        rmaracc,
        finchdlr,
        ccrdxpdt,
        slprsnid,
        inactive,
        post_results_to,
        taxexmt2,
        rmivacc,
        phone3,
        dex_row_id,
        gpsfointegrationid,
        prbtadcd,
        custclas,
        staddrcd,
        comment2,
        kperhist,
        rmslsacc,
        minpypct,
        kpcalhst,
        govcrpid,
        crlmtpam,
        mxwoftyp,
        govindid,
        rmsoracc,
        cprcstnm,
        fax,
        minpydlr,
        ratetpid,
        declid,
        crlmtper,
        minpytyp,
        duegrper,
        address3,
        crcardid,
        shipcomplete,
        hold,
        crcrdnum,
        taxexmt1,
        cbvat,
        state,
        phone2,
        disgrper,
        mxwrofam,
        rmwracc,
        shrtname,
        comment1,
        rmovrpymtwrtoffacctidx,
        pymtrmid,
        bankname,
        integrationid,
        curncyid,
        includeindp,
        defcacty,
        docfmtid,
        rmavacc,
        custname,
        crlmtamt,
        userlang,
        ccode,
        prstadcd,
        taxschid,
        userdef2,
        cntcprsn,
        stmtname,
        fnchpcnt,
        finchid,
        noteindx,
        address2,
        shipmthd,
        rmcshacc,
        kpdsthst,
        stmtcycl,
        revalue_customer,
        phone1,
        orderfulfilldefault,
        bnkbrnch,
        fnchatyp,
        dex_row_ts,
        prclevel,
        custpriority,
        upszone,
        country,
        creatddt,
        frstindt,
        send_email_statements,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
