with source as (

    select * from {{ source('nb601_dbo', 'rm20101') }}

),

renamed as (

    select
        custnmbr,
        docnumbr,
        rmdtypal,
        curtrxam,
        pstusrid,
        distknam,
        bktslsam,
        bktmscam,
        pymtrmid,
        slsamnt,
        voidstts,
        cbkidcsh,
        agngbukt,
        saledate,
        tax_date,
        bachnumb,
        costamnt,
        trdisamt,
        eftflag,
        taxschid,
        cashamnt,
        directdebit,
        discdate,
        shipmthd,
        lstedtdt,
        corrctn,
        taxamnt,
        voiddate,
        dex_row_ts,
        noteindx,
        dscpctam,
        dscdlram,
        cheknmbr,
        bktfrtam,
        lstusred,
        curncyid,
        dex_row_id,
        trxdscrn,
        cprcstnm,
        miscamnt,
        glpostdt,
        slprsnid,
        frtamnt,
        disavamt,
        duedate,
        factoring,
        ectrx,
        cbkidchk,
        delete1,
        ppsamded,
        docdate,
        trxsorce,
        backouttradedisc,
        gstdsamt,
        adrscode,
        postdate,
        simplifd,
        comdlram,
        bchsourc,
        ortrxamt,
        disavtkn,
        cbkidcrd,
        wrofamnt,
        dinvpdof,
        electronic,
        cshrctyp,
        mscschid,
        discrtnd,
        slstercd,
        frtschid,
        aplywith,
        slschdid,
        cspornbr,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
