with source as (

    select * from {{ source('nb601_dbo', 'pop30300') }}

),

renamed as (

    select
        aplywith,
        dscdlram,
        purchase_freight_taxable,
        ten99boxnumber,
        simplifd,
        cbvat,
        xchgrate,
        distknam,
        total_landed_cost_amount,
        ordavamt,
        bchsourc,
        glpostdt,
        ormsctax,
        frtamnt,
        poplnerr,
        disavtkn,
        ortdisam,
        rcptnote_3,
        posteddt,
        subtotal,
        user2ent,
        frttxamt,
        bsivcttl,
        frtschid,
        or1099am,
        ppstaxrt,
        rcptnote_6,
        pophdr1,
        workflow_status,
        poptype,
        origbackoutfreighttaxamt,
        replacegoods,
        ordatkn,
        shipmthd,
        receiptdate,
        backoutmisctaxamt,
        ortaxamt,
        exgtblid,
        revaljrnentry,
        originatingprepaymentamt,
        trdisamt,
        currnidx,
        refrence,
        purchase_misc_taxable,
        taxinvrecvd,
        discdate,
        mscschid,
        prepaymentamount,
        taxinvreqd,
        rcptnote_2,
        actlship,
        ectrx,
        ordistkn,
        revaltrxsource,
        bcktxamt,
        denxrate,
        rcptnote_5,
        backoutfreighttaxamt,
        trxsorce,
        ratecalc,
        duedate,
        poprctnm,
        ten99type,
        ten99amnt,
        origbackoutmisctaxamt,
        ormiscamt,
        voidstts,
        dscpctam,
        vendorid,
        mctrxstt,
        withhamt,
        rcptnote_8,
        msctxamt,
        miscamnt,
        time1,
        txrgnnum,
        orddlrat,
        ptdusrid,
        vnddocnm,
        vadcdtro,
        exchdate,
        obtaxamt,
        tax_date,
        taxamnt,
        rcptnote_1,
        pop_hdr_errors_4,
        orsubtot,
        curncyid,
        creatddt,
        vendname,
        ratetpid,
        dex_row_id,
        vchrnmbr,
        trdpctpr,
        pymtrmid,
        bachnumb,
        rcptnote_4,
        invoiceexpected,
        modifdt,
        orfrtamt,
        invoicereceiptdate,
        disavamt,
        rcptnote_7,
        orfrttax,
        pophdr2,
        taxschid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
