with source as (

    select * from {{ source('nb601_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        writeoff,
        zipcode,
        pmtaxidx,
        vndclsid,
        sbppsded,
        pmfinidx,
        venddba,
        laborpmttype,
        pmcshidx,
        phnumbr2,
        withholdingtype,
        creatddt,
        mxiafvnd,
        post_results_to,
        pmfrtidx,
        address3,
        vadcdtro,
        declid,
        prspayee,
        xpdtoblg,
        maxindlr,
        purpvidx,
        disgrper,
        txrgnnum,
        pmdavidx,
        chekbkid,
        pmapindx,
        trddisct,
        pmrtngix,
        crtcomdt,
        vendstts,
        workflow_priority,
        phone3,
        vndcntct,
        pmwrtidx,
        noteindx,
        dxvarnum,
        duegrper,
        pmmschix,
        phnumbr1,
        vendname,
        govindid,
        address2,
        userdef2,
        brthdate,
        revalue_vendor,
        comment2,
        kgldsths,
        pymntpri,
        pmdtkidx,
        pmtdscix,
        ten99type,
        crtexpdt,
        minorder,
        faxnumbr,
        crlmtdlr,
        country,
        vndchknm,
        vendshnm,
        ppstaxrt,
        upszone,
        userdef1,
        address1,
        city,
        docfmtid,
        ptcshacf,
        comment1,
        cbvat,
        acpuridx,
        state,
        onepaypervendinv,
        mxwofamt,
        workflow_status,
        rtobutkn,
        kptrxhst,
        parvenid,
        withholdingentitytype,
        curncyid,
        hold,
        taxinvrecvd,
        freeonboard,
        vadcdpad,
        taxfilenummode,
        ccode,
        ten99boxnumber,
        pymtrmid,
        vadcdsfr,
        dex_row_id,
        acnmvndr,
        userlang,
        govcrpid,
        workflow_approval_status,
        credtlmt,
        pmprchix,
        txidnmbr,
        kperhist,
        taxschid,
        ratetpid,
        modifdt,
        vadcd1099,
        minpytyp,
        dex_row_ts,
        withholdingformtype,
        vaddcdpr,
        minpypct,
        shipmthd,
        minpydlr,
        kpcalhst,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
