with source as (

    select * from {{ source('nb601_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        prchamnt,
        gstdsamt,
        duedate,
        bchsourc,
        docprinted,
        docamnt,
        pchschid,
        ten99amnt,
        pgramsbj,
        disamtav,
        taxinvreqd,
        prctdisc,
        ten99type,
        lngdesc,
        electronic,
        discdate,
        docnumbr,
        un1099am,
        voided,
        mdfusrid,
        taxschid,
        cardname,
        bachnumb,
        chekbkid,
        dex_row_id,
        ptdusrid,
        ten99boxnumber,
        dex_row_ts,
        vndchknm,
        noteindx,
        bktfrtam,
        pymtrmid,
        distknam,
        frtschid,
        ttlpymts,
        voidpdate,
        pstgdate,
        ppsamded,
        invoicereceiptdate,
        trxdscrn,
        trxsorce,
        docdate,
        hold,
        dscdlram,
        dinvpdof,
        taxamnt,
        vendorid,
        prchdate,
        frtamnt,
        ponumber,
        ectrx,
        pyenttyp,
        backouttradedisc,
        corrctn,
        posteddt,
        bktmscam,
        ppstaxrt,
        curncyid,
        discamnt,
        ictrx,
        cbvat,
        aplywith,
        mscschid,
        trdisamt,
        workflow_status,
        simplifd,
        retnagam,
        pordnmbr,
        modifdt,
        shipmthd,
        curtrxam,
        tax_date,
        disavtkn,
        vadcdtro,
        mscchamt,
        cntrltyp,
        bktpuram,
        wrofamnt,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
