with source as (

    select * from {{ source('nb601_dbo', 'pm20000') }}

),

renamed as (

    select
        ttlpymts,
        pstgdate,
        modifdt,
        ppsamded,
        pordnmbr,
        invoicereceiptdate,
        disavtkn,
        tax_date,
        curtrxam,
        docdate,
        cntrltyp,
        bktpuram,
        dscdlram,
        prchamnt,
        vendorid,
        gstdsamt,
        frtamnt,
        ponumber,
        ectrx,
        duedate,
        backouttradedisc,
        bktmscam,
        corrctn,
        posteddt,
        bchsourc,
        ppstaxrt,
        docamnt,
        curncyid,
        ten99amnt,
        discamnt,
        doctype,
        pgramsbj,
        disamtav,
        ictrx,
        prctdisc,
        aplywith,
        trdisamt,
        workflow_status,
        voided,
        mdfusrid,
        simplifd,
        taxschid,
        retnagam,
        bachnumb,
        vchrnmbr,
        shipmthd,
        vadcdtro,
        mscchamt,
        ptdusrid,
        ten99boxnumber,
        wrofamnt,
        bktfrtam,
        pymtrmid,
        distknam,
        frtschid,
        docprinted,
        trxdscrn,
        trxsorce,
        pchschid,
        taxinvreqd,
        hold,
        ten99type,
        dinvpdof,
        prchdate,
        lngdesc,
        taxamnt,
        un1099am,
        docnumbr,
        electronic,
        discdate,
        pyenttyp,
        cardname,
        chekbkid,
        dex_row_id,
        bnkrcamt,
        cbvat,
        vndchknm,
        dex_row_ts,
        noteindx,
        mscschid,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
