with source as (

    select * from {{ source('gcags_dbo', 'pm20000') }}

),

renamed as (

    select
        distknam,
        aplywith,
        docdate,
        trxdscrn,
        bktpuram,
        pgramsbj,
        vchrnmbr,
        trdisamt,
        simplifd,
        ppsamded,
        posteddt,
        frtschid,
        ten99boxnumber,
        ptdusrid,
        ppstaxrt,
        pstgdate,
        lngdesc,
        trxsorce,
        wrofamnt,
        cntrltyp,
        bnkrcamt,
        retnagam,
        doctype,
        prctdisc,
        pchschid,
        hold,
        prchdate,
        disamtav,
        voided,
        un1099am,
        vadcdtro,
        bachnumb,
        prchamnt,
        docprinted,
        mscchamt,
        backouttradedisc,
        invoicereceiptdate,
        disavtkn,
        discamnt,
        ten99amnt,
        pymtrmid,
        ectrx,
        bktmscam,
        electronic,
        pordnmbr,
        ten99type,
        pyenttyp,
        chekbkid,
        ictrx,
        dex_row_ts,
        bchsourc,
        gstdsamt,
        taxamnt,
        curncyid,
        workflow_status,
        mdfusrid,
        corrctn,
        shipmthd,
        noteindx,
        vndchknm,
        taxschid,
        bktfrtam,
        discdate,
        mscschid,
        curtrxam,
        dex_row_id,
        vendorid,
        duedate,
        taxinvreqd,
        dinvpdof,
        dscdlram,
        cardname,
        docamnt,
        frtamnt,
        tax_date,
        cbvat,
        ponumber,
        modifdt,
        docnumbr,
        ttlpymts,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
