with source as (

    select * from {{ source('gcags_dbo', 'pm00200') }}

),

renamed as (

    select
        vendorid,
        taxinvrecvd,
        kptrxhst,
        chekbkid,
        workflow_priority,
        cbvat,
        vndcntct,
        comment2,
        creatddt,
        txidnmbr,
        taxschid,
        dex_row_id,
        shipmthd,
        txrgnnum,
        city,
        venddba,
        vadcdtro,
        mxwofamt,
        ratetpid,
        minpytyp,
        userlang,
        acnmvndr,
        pmapindx,
        prspayee,
        brthdate,
        kpcalhst,
        userdef1,
        pmrtngix,
        pmtdscix,
        phnumbr1,
        ptcshacf,
        freeonboard,
        workflow_status,
        vadcdpad,
        withholdingformtype,
        taxfilenummode,
        parvenid,
        country,
        govindid,
        pmdavidx,
        vadcdsfr,
        modifdt,
        laborpmttype,
        phone3,
        crlmtdlr,
        docfmtid,
        crtcomdt,
        purpvidx,
        pymtrmid,
        writeoff,
        govcrpid,
        mxiafvnd,
        minorder,
        ccode,
        declid,
        pmdtkidx,
        pymntpri,
        zipcode,
        workflow_approval_status,
        pmtaxidx,
        pmprchix,
        phnumbr2,
        ten99type,
        minpypct,
        vadcd1099,
        userdef2,
        upszone,
        duegrper,
        onepaypervendinv,
        withholdingentitytype,
        vendstts,
        crtexpdt,
        kgldsths,
        pmwrtidx,
        address1,
        faxnumbr,
        rtobutkn,
        revalue_vendor,
        curncyid,
        disgrper,
        state,
        xpdtoblg,
        pmfrtidx,
        vendname,
        pmcshidx,
        withholdingtype,
        dxvarnum,
        hold,
        address2,
        comment1,
        maxindlr,
        vndchknm,
        vendshnm,
        ten99boxnumber,
        ppstaxrt,
        sbppsded,
        post_results_to,
        credtlmt,
        noteindx,
        trddisct,
        vndclsid,
        vaddcdpr,
        minpydlr,
        pmmschix,
        acpuridx,
        pmfinidx,
        address3,
        dex_row_ts,
        kperhist,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
