with source as (

    select * from {{ source('gcags_dbo', 'pm30200') }}

),

renamed as (

    select
        doctype,
        vchrnmbr,
        prctdisc,
        hold,
        pchschid,
        taxinvreqd,
        retnagam,
        vndchknm,
        ictrx,
        vendorid,
        pordnmbr,
        vadcdtro,
        chekbkid,
        modifdt,
        electronic,
        ectrx,
        ten99boxnumber,
        backouttradedisc,
        frtamnt,
        dscdlram,
        duedate,
        disamtav,
        discamnt,
        ten99amnt,
        bktpuram,
        bktmscam,
        ten99type,
        distknam,
        dex_row_ts,
        ptdusrid,
        tax_date,
        shipmthd,
        mscchamt,
        docprinted,
        disavtkn,
        noteindx,
        trxsorce,
        prchdate,
        pymtrmid,
        cntrltyp,
        pstgdate,
        corrctn,
        voided,
        invoicereceiptdate,
        lngdesc,
        pyenttyp,
        prchamnt,
        bachnumb,
        ttlpymts,
        bktfrtam,
        simplifd,
        trxdscrn,
        pgramsbj,
        ppstaxrt,
        voidpdate,
        trdisamt,
        mscschid,
        discdate,
        frtschid,
        un1099am,
        curtrxam,
        cardname,
        ponumber,
        wrofamnt,
        docdate,
        docnumbr,
        ppsamded,
        taxamnt,
        gstdsamt,
        taxschid,
        aplywith,
        mdfusrid,
        cbvat,
        bchsourc,
        docamnt,
        dinvpdof,
        workflow_status,
        posteddt,
        curncyid,
        dex_row_id,
        _fivetran_deleted,
        _fivetran_synced

    from source

)

select * from renamed
where coalesce(_fivetran_deleted, false) = false
